import type{Metrics,PathRow,Portfolio}from'./portfolio';
import{isApiOffer}from'./affiliate-source-dimensions';
import{assessUnit}from'./decision-engine';
export type RecommendationAction='SKALIEREN'|'WEITERLAUFEN'|'WEITER TESTEN'|'BEOBACHTEN'|'AUSSCHALTEN';export type AffiliateVariant={key:string;offerId:string;offer:string;offerUrlId:string;offerUrl:string;trafficType:'Direkt';trafficMode:'api'|'tracked';days30:Metrics;efficiency:{label:'Profit je Klick'|'Profit je SOI';days30:number};recommendation:{action:RecommendationAction;severity:'positive'|'neutral'|'warning'|'critical';reason:string;evidence:string[]}};export type AffiliateAnalysis={affiliateId:string;affiliate:string;variants:AffiliateVariant[];totals30:Metrics;bestVariantKey:string;summary:string};
const blank=():Metrics=>({clicks:0,sois:0,cvr:0,firstSales:0,firstSaleRate:0,rebills:0,coinSpend:0,payout:0,revenue:0,profit:0,profitEpc:0});
const add=(a:Metrics,b:Metrics)=>{for(const k of['clicks','sois','firstSales','rebills','coinSpend','payout','revenue','profit']as const)a[k]+=b[k];return finish(a)};const finish=(x:Metrics)=>{x.cvr=x.clicks?100*x.sois/x.clicks:0;x.firstSaleRate=x.sois?100*x.firstSales/x.sois:0;x.profitEpc=x.clicks?x.profit/x.clicks:0;return x};
const direct=(p:Portfolio)=>p.paths.filter(x=>x.trafficType==='Direkt'&&x.campaignId==='0');const key=(p:PathRow)=>`${p.affiliateId}|${p.offerId}|${p.offerUrlId}`;const map=(p:Portfolio)=>new Map(direct(p).map(x=>[key(x),x]));
function recommendation(m:Metrics,medianRate:number,api=false){const efficiency=api?(m.sois?m.profit/m.sois:0):(m.clicks?m.profitEpc:(m.sois?m.profit/m.sois:0)),unit=api||!m.clicks?'Profit je SOI':'Profit je Klick';const verdict=assessUnit({clicks:m.clicks,sois:m.sois,firstSales:m.firstSales,rebills:m.rebills,profit:m.profit},{api,benchmarkRate:medianRate>0?medianRate/100:undefined});return{action:verdict.action,severity:verdict.severity,reason:verdict.reason,evidence:[...verdict.evidence,`${efficiency.toFixed(3)} € ${unit}`]}}
export function analyzeAffiliateTraffic(portfolio:Portfolio):AffiliateAnalysis[]{const m30=map(portfolio),groups=new Map<string,PathRow[]>();for(const p of direct(portfolio)){if(!(p.clicks||p.sois||p.payout||p.revenue))continue;const g=groups.get(p.affiliateId)||[];g.push(p);groups.set(p.affiliateId,g)}const out:AffiliateAnalysis[]=[];for(const paths of groups.values()){if(paths.length<2)continue;const rates=paths.filter(x=>x.sois>=10&&x.firstSaleRate>0).map(x=>x.firstSaleRate).sort((a,b)=>a-b),median=rates.length?rates[Math.floor(rates.length/2)]:0;const variants=paths.map(p=>{const k=key(p),c=m30.get(k)||blank(),api=isApiOffer(p.offer),cEfficiency=api?(c.sois?c.profit/c.sois:0):(c.clicks?c.profitEpc:(c.sois?c.profit/c.sois:0)),efficiency={label:(api||!c.clicks?'Profit je SOI':'Profit je Klick') as 'Profit je Klick'|'Profit je SOI',days30:cEfficiency};return{key:k,offerId:p.offerId,offer:p.offer,offerUrlId:p.offerUrlId,offerUrl:p.offerUrl,trafficType:'Direkt' as const,trafficMode:api?'api' as const:'tracked' as const,days30:c,efficiency,recommendation:recommendation(c,median,api)}});const order:Record<RecommendationAction,number>={SKALIEREN:0,WEITERLAUFEN:1,'WEITER TESTEN':2,BEOBACHTEN:3,AUSSCHALTEN:4};variants.sort((a,b)=>order[a.recommendation.action]-order[b.recommendation.action]||b.days30.profit-a.days30.profit);const totals=paths.reduce((a,p)=>add(a,{...p}),blank()),best=variants[0];out.push({affiliateId:paths[0].affiliateId,affiliate:paths[0].affiliate,variants,totals30:totals,bestVariantKey:best.key,summary:`${variants.length} direkte Offer-/URL-Varianten · ${variants.filter(x=>x.recommendation.action==='AUSSCHALTEN').length} Ausschaltkandidaten · ${variants.filter(x=>x.recommendation.action==='SKALIEREN').length} Skalierungskandidaten`})}return out.sort((a,b)=>b.totals30.profit-a.totals30.profit)}
export type AffiliateOfferGroup={offerId:string;offer:string;variants:AffiliateVariant[];totals30:Metrics;stopCount:number;scaleCount:number;testCount:number;immediateSaving:number};
export function groupAffiliateOffers(analysis:AffiliateAnalysis):AffiliateOfferGroup[]{const groups=new Map<string,AffiliateOfferGroup>();for(const variant of analysis.variants){let group=groups.get(variant.offerId);if(!group){group={offerId:variant.offerId,offer:variant.offer,variants:[],totals30:blank(),stopCount:0,scaleCount:0,testCount:0,immediateSaving:0};groups.set(variant.offerId,group)}group.variants.push(variant);add(group.totals30,{...variant.days30});if(variant.recommendation.action==='AUSSCHALTEN'){group.stopCount++;group.immediateSaving+=Math.max(0,-variant.days30.profit)}if(variant.recommendation.action==='SKALIEREN')group.scaleCount++;if(variant.recommendation.action==='WEITER TESTEN')group.testCount++}const priority=(g:AffiliateOfferGroup)=>g.stopCount?0:g.totals30.profit<0?1:g.scaleCount?2:3;return[...groups.values()].sort((a,b)=>priority(a)-priority(b)||b.immediateSaving-a.immediateSaving||a.totals30.profit-b.totals30.profit)}
