import type{ReportingPeriod}from'./supabase-reporting';
export type AffiliatePeriod='today'|'7d'|'30d'|'90d'|'12m'|'all'|'calendar'|'custom';
export type AffiliatePeriodQuery={period?:string;from?:string;to?:string;calendarYear?:string;calendarMonth?:string};
const day=(date:Date)=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).map(x=>[x.type,x.value]));return`${p.year}-${p.month}-${p.day}`};
const shift=(iso:string,days:number)=>new Date(Date.parse(`${iso}T12:00:00Z`)+days*86400000).toISOString().slice(0,10);
const valid=(value?:string)=>{if(!value||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(`${value}T12:00:00Z`);return!Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===value};
const calendarRange=(year:string|undefined,month:string|undefined,today:string)=>{if(!year||!/^\d{4}$/.test(year)||!(month==='all'||/^(0[1-9]|1[0-2])$/.test(month||'')))return null;const y=Number(year),m=month==='all'?null:Number(month),from=m===null?`${year}-01-01`:`${year}-${month}-01`,last=m===null?`${year}-12-31`:`${year}-${month}-${String(new Date(Date.UTC(y,m,0)).getUTCDate()).padStart(2,'0')}`;if(from>today)return null;return{from,to:last>today?today:last}};
export function resolveAffiliatePeriod(query:AffiliatePeriodQuery,now=new Date()){const today=day(now),allowed:AffiliatePeriod[]=['today','7d','30d','90d','12m','all','calendar','custom'];let period=(allowed.includes(query.period as AffiliatePeriod)?query.period:'30d')as AffiliatePeriod,from:string,to=today,error:string|null=null;if(period==='calendar'){const range=calendarRange(query.calendarYear,query.calendarMonth,today);if(range){from=range.from;to=range.to}else{error='Bitte ein gültiges Jahr und einen nicht zukünftigen Monat auswählen.';period='30d';from=shift(today,-29)}}else if(period==='custom'){if(!valid(query.from)||!valid(query.to))error='Bitte ein gültiges Von- und Bis-Datum auswählen.';from=query.from||today;to=query.to||today;if(!error&&from>to)error='Das Von-Datum muss vor oder am Bis-Datum liegen.';if(!error&&to>today)error='Zukünftige Datumswerte sind nicht erlaubt.';if(error){period='30d';from=shift(today,-29);to=today}}else if(period==='today')from=today;else if(period==='7d')from=shift(today,-6);else if(period==='30d')from=shift(today,-29);else if(period==='90d')from=shift(today,-89);else if(period==='12m'||period==='all')from=shift(today,-364);else from=shift(today,-29);const label=`${from.split('-').reverse().join('.')}–${to.split('-').reverse().join('.')}`;const bounded=period==='custom'||period==='all'||period==='calendar',servicePeriod:ReportingPeriod=bounded?'custom':period as ReportingPeriod;return{period,servicePeriod,custom:bounded?{from,to}:undefined,from,to,maxDate:today,label,includesToday:to===today,error,timezone:'Europe/Berlin',timezoneId:80}}
export type ResolvedAffiliatePeriod=ReturnType<typeof resolveAffiliatePeriod>;
export const AFFILIATE_PERIODS:[AffiliatePeriod,string][]=[['today','Heute'],['7d','7 Tage'],['30d','30 Tage'],['90d','90 Tage'],['12m','12 Monate'],['all','365 Tage'],['custom','Individuell']];
