const BASE='https://api.eflow.team/v1';
type Fetcher=typeof fetch;
type RawOffer={network_offer_id:number;name?:string;offer_name?:string;offer_status?:string};
type RawOfferUrl={network_offer_url_id:number;network_offer_id:number;name?:string;url_name?:string;url_status?:string;destination_url?:string;preview_url?:string};
async function json<T>(fetcher:Fetcher,url:string,init:RequestInit={}){const response=await fetcher(url,{...init,signal:init.signal||AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`Everflow Inventar HTTP ${response.status}`);return response.json()as Promise<T>}
const headers=(key:string)=>({'X-Eflow-API-Key':key,'Content-Type':'application/json'});
export type AutomationOfferSearchItem={offerId:number;name:string;status:string};
export type AutomationLandingpageInventory={offerUrlId:number;name:string;status:string;destinationUrl?:string;previewUrl?:string};
export async function searchAutomationOffers(term:string,apiKey:string,fetcher:Fetcher=fetch):Promise<AutomationOfferSearchItem[]>{if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const data=await json<{offers?:RawOffer[]}>(fetcher,`${BASE}/networks/offers`,{headers:headers(apiKey)}),q=term.trim().toLowerCase(),exact=/^\d+$/.test(q)?Number(q):null;return(data.offers||[]).filter(offer=>exact!==null?offer.network_offer_id===exact:(offer.name||offer.offer_name||'').toLowerCase().includes(q)).map(offer=>({offerId:offer.network_offer_id,name:offer.name||offer.offer_name||`Offer #${offer.network_offer_id}`,status:offer.offer_status||'unknown'})).sort((a,b)=>(a.status==='active'?0:1)-(b.status==='active'?0:1)||a.offerId-b.offerId).slice(0,100)}
async function allOfferUrls(apiKey:string,fetcher:Fetcher,pageSize:number){const load=(page:number)=>json<{urls?:RawOfferUrl[];paging?:{total_count?:number}}>(fetcher,`${BASE}/networks/offerurls?page=${page}&page_size=${pageSize}`,{headers:headers(apiKey)}),first=await load(1),total=Number(first.paging?.total_count||first.urls?.length||0),pages=Math.max(1,Math.ceil(total/pageSize)),rows=[...(first.urls||[])];for(let start=2;start<=pages;start+=6){const batch=await Promise.all(Array.from({length:Math.min(6,pages-start+1)},(_,index)=>load(start+index)));for(const item of batch)rows.push(...(item.urls||[]))}if(rows.length<Math.min(total,pageSize))throw new Error('Everflow Offer-URL-Pagination unvollständig');return rows}
function visibleToAffiliate(value:unknown,affiliateId:number){if(!value||typeof value!=='object')return false;const payload=value as{network_affiliate_ids?:unknown;network_affiliate_visible_ids?:unknown;set_type?:unknown},raw=Array.isArray(payload.network_affiliate_ids)?payload.network_affiliate_ids:Array.isArray(payload.network_affiliate_visible_ids)?payload.network_affiliate_visible_ids:null;if(!raw)return false;const ids=raw.map(Number).filter(Number.isSafeInteger),setType=typeof payload.set_type==='string'?payload.set_type:'visible';return setType==='hidden'?!ids.includes(affiliateId):ids.includes(affiliateId)}
export async function loadAutomationOfferLandingpages(offerIds:number[],affiliateId:number,apiKey:string,fetcher:Fetcher=fetch,pageSize=500){if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const ids=[...new Set(offerIds.filter(id=>Number.isSafeInteger(id)&&id>0))];if(!Number.isSafeInteger(affiliateId)||affiliateId<=0)throw new Error('Affiliate-ID ungültig');const urls=await allOfferUrls(apiKey,fetcher,pageSize),visibility=await Promise.all(ids.map(id=>json<unknown>(fetcher,`${BASE}/networks/offers/${id}/visibility`,{headers:headers(apiKey)})));return ids.map((offerId,index)=>({offerId,visible:visibleToAffiliate(visibility[index],affiliateId),landingpages:urls.filter(row=>row.network_offer_id===offerId&&row.url_status==='active').map(row=>({offerUrlId:row.network_offer_url_id,name:row.name||row.url_name||`LP #${row.network_offer_url_id}`,status:row.url_status||'unknown',...(row.destination_url?{destinationUrl:row.destination_url}:{}),...(row.preview_url?{previewUrl:row.preview_url}:{})})).sort((a,b)=>a.offerUrlId-b.offerUrlId)}))}
