import{loadCampaignAffiliateRowsFromCache}from'./cached-smartlinks';
import{validateAutomationDraft,type AutomationConfiguration}from'./automation-config';
import{loadAutomationOfferLandingpages,searchAutomationOffers,type AutomationOfferSearchItem}from'./automation-inventory';
import{readAutomationCampaignBaseline,type AutomationCampaign}from'./everflow-automation';
type LandingpageResult=Awaited<ReturnType<typeof loadAutomationOfferLandingpages>>;
type Deps={readBaseline:(campaignId:number,affiliateId:number,apiKey:string)=>Promise<{campaign:AutomationCampaign;fingerprint:string}>;searchOffers:(term:string,apiKey:string)=>Promise<AutomationOfferSearchItem[]>;loadLandingpages:(offerIds:number[],affiliateId:number,apiKey:string)=>Promise<LandingpageResult>};
const defaults:Deps={readBaseline:readAutomationCampaignBaseline,searchOffers:searchAutomationOffers,loadLandingpages:loadAutomationOfferLandingpages};
export async function assertAutomationCampaignAffiliateMapping(campaignId:number,affiliateId:number){const rows=await loadCampaignAffiliateRowsFromCache();if(!rows.some(row=>row.columns.some(column=>column.column_type==='campaign'&&column.id===String(campaignId))&&row.columns.some(column=>column.column_type==='affiliate'&&column.id===String(affiliateId))))throw new Error(`Campaign #${campaignId} ist Affiliate #${affiliateId} nicht kanonisch zugeordnet.`)}
export async function runAutomationPreflight(config:AutomationConfiguration,apiKey:string,deps:Deps=defaults){const blockers=validateAutomationDraft(config);if(blockers.length)return{verified:false,fingerprint:null,blockers};if(deps===defaults)try{await assertAutomationCampaignAffiliateMapping(config.campaignId,config.affiliateId)}catch(error){blockers.push(error instanceof Error?error.message:'Campaign-Affiliate-Zuordnung fehlt.')}let baseline:{campaign:AutomationCampaign;fingerprint:string};try{baseline=await deps.readBaseline(config.campaignId,config.affiliateId,apiKey)}catch(error){return{verified:false,fingerprint:null,blockers:[error instanceof Error?error.message:'Campaign-Baseline konnte nicht gelesen werden.']}}if(baseline.campaign.campaign_status!=='active')blockers.push(`Campaign #${config.campaignId} ist nicht aktiv.`);if(baseline.campaign.redirect_routing_type!=='weight')blockers.push(`Campaign #${config.campaignId} verwendet kein gewichtetes Routing.`);const ids=config.offers.map(offer=>offer.offerId),offerRows=(await Promise.all(ids.map(id=>deps.searchOffers(String(id),apiKey)))).flat(),inventory=await deps.loadLandingpages(ids,config.affiliateId,apiKey);for(const offer of config.offers){const current=offerRows.find(row=>row.offerId===offer.offerId);if(!current)blockers.push(`Offer #${offer.offerId} wurde in Everflow nicht gefunden.`);else if(current.status!=='active')blockers.push(`Offer #${offer.offerId} ist nicht aktiv.`);const item=inventory.find(row=>row.offerId===offer.offerId);if(!item?.visible)blockers.push(`Offer #${offer.offerId} ist für Affiliate #${config.affiliateId} nicht sichtbar.`);for(const lp of offer.landingpages.filter(value=>value.selection!=='excluded'))if(!item?.landingpages.some(value=>value.offerUrlId===lp.offerUrlId&&value.status==='active'))blockers.push(`Offer-URL #${lp.offerUrlId} ist im aktiven Everflow-Inventar nicht vorhanden.`)}return{verified:blockers.length===0,fingerprint:blockers.length?null:baseline.fingerprint,blockers:[...new Set(blockers)]}}
