import {describe,expect,it} from 'vitest';
import {automationScopeAllowed,filterAutomationOffersByScope,mayConfigureAutomation,mayRunLiveAutomation} from './automation-policy';
import {parseAccessMetadata} from './rbac';
describe('automation access policy',()=>{
 it('requires explicit automation permission and excludes partners',()=>{expect(mayConfigureAutomation(parseAccessMetadata({role:'partner',grants:['automations.manage']}))).toBe(false);expect(mayConfigureAutomation(parseAccessMetadata({role:'employee',grants:['automations.manage','campaigns.edit']}))).toBe(true);expect(mayRunLiveAutomation(parseAccessMetadata({role:'employee',grants:['automations.manage','campaigns.edit']}))).toBe(false);expect(mayRunLiveAutomation(parseAccessMetadata({role:'super_admin'}))).toBe(true)});
 it('enforces every populated resource scope for non-partner delegated roles too',()=>{const scoped=parseAccessMetadata({role:'employee',grants:['automations.manage'],scopes:{affiliate:['436'],campaign:['146'],offer:['57','50']}});expect(automationScopeAllowed(scoped,{affiliateId:436,campaignId:146,offerIds:[57,50]})).toBe(true);expect(automationScopeAllowed(scoped,{affiliateId:436,campaignId:2,offerIds:[57]})).toBe(false);expect(automationScopeAllowed(scoped,{affiliateId:436,campaignId:146,offerIds:[8]})).toBe(false)});
 it('filters offer search results before disclosure for offer-scoped users',()=>{const scoped=parseAccessMetadata({role:'employee',scopes:{offer:['57']}}),offers=[{offerId:57,name:'Allowed'},{offerId:99,name:'Secret'}];expect(filterAutomationOffersByScope(scoped,offers)).toEqual([{offerId:57,name:'Allowed'}]);expect(filterAutomationOffersByScope(parseAccessMetadata({role:'admin'}),offers)).toEqual(offers)});
 it('allows unscoped admins but fails closed for empty partner scopes',()=>{expect(automationScopeAllowed(parseAccessMetadata({role:'admin'}),{affiliateId:436,campaignId:146,offerIds:[57]})).toBe(true);expect(automationScopeAllowed(parseAccessMetadata({role:'partner',grants:['automations.manage'],scopes:{}}),{affiliateId:436,campaignId:146,offerIds:[57]})).toBe(false)});
});
