import type {SecurityLease,SecurityStore} from './security';
import {withSecurityLock} from './security';
import {validateAutomationDraft,type AutomationConfiguration} from './automation-config';

const PREFIX='automation:config:v1:',RUN_PREFIX='automation:run:v1:';
export const automationLockName=(id:string)=>`automation:${id}`;
export type AutomationRun={runId:string;startedAt:string;completedAt:string;mode:'dry_run'|'live';decision:string;writesPerformed:number;verified:boolean;summary:string};
export type AutomationIncident={incidentId:string;at:string;runId:string;message:string;providerMutated:boolean;compensation:'not_needed'|'verified'|'failed'|'uncertain'};
export type StoredAutomationConfiguration=AutomationConfiguration&{updatedBy:string;acceptedBaselineFingerprint?:string;runs:AutomationRun[];lastIncident?:AutomationIncident};
type StoredRecord=Omit<StoredAutomationConfiguration,'runs'> & {lastFailedRun?:AutomationRun};
type Transition='dry_run'|'request_live'|'activate_live'|'pause'|'resume'|'hold'|'complete';
const isConfig=(value:unknown):value is StoredRecord=>Boolean(value)&&typeof value==='object'&&(value as StoredRecord).schemaVersion===1&&typeof (value as StoredRecord).id==='string';
const configKey=(id:string)=>`${PREFIX}${id}`;
const runPrefix=(id:string)=>`${RUN_PREFIX}${id}:`;
async function runs(store:SecurityStore,id:string){return(await store.list(runPrefix(id))).map(x=>x.value).filter((x):x is AutomationRun=>Boolean(x)&&typeof x==='object'&&typeof(x as AutomationRun).runId==='string').sort((a,b)=>b.startedAt.localeCompare(a.startedAt));}
async function attach(store:SecurityStore,record:StoredRecord):Promise<StoredAutomationConfiguration>{const persisted=await runs(store,record.id),merged=record.lastFailedRun&&!persisted.some(run=>run.runId===record.lastFailedRun?.runId)?[record.lastFailedRun,...persisted]:persisted,configuration=Object.fromEntries(Object.entries(record).filter(([key])=>key!=='lastFailedRun')) as Omit<StoredRecord,'lastFailedRun'>;return{...configuration,runs:merged}}
export async function getAutomationConfiguration(store:SecurityStore,id:string){const raw=await store.get(configKey(id));return isConfig(raw)?attach(store,raw):null}
export async function listAutomationConfigurations(store:SecurityStore){const items=(await store.list(PREFIX)).map(x=>x.value).filter(isConfig).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return Promise.all(items.map(item=>attach(store,item)))}
export function withAutomationLock<T>(store:SecurityStore,id:string,operation:(lease:SecurityLease)=>Promise<T>){return withSecurityLock(store,automationLockName(id),operation,{leaseMs:60_000})}
async function underAutomationLock<T>(store:SecurityStore,id:string,lease:SecurityLease|undefined,operation:()=>Promise<T>){if(lease){if(lease.name!==automationLockName(id))throw new Error('Falsche Automationssperre.');await lease.assertOwned();return operation()}return withAutomationLock(store,id,async()=>operation())}
export async function createAutomationConfiguration(store:SecurityStore,configuration:AutomationConfiguration,actorId:string,lease?:SecurityLease){const errors=validateAutomationDraft(configuration);if(errors.length)throw new Error(errors.join(' '));return underAutomationLock(store,configuration.id,lease,async()=>{const key=configKey(configuration.id);if(await store.get(key))throw new Error('Automation existiert bereits.');const record:StoredRecord={...configuration,status:'draft',writeEnabled:false,version:1,updatedBy:actorId};await store.set(key,record);return attach(store,record)})}
export async function updateAutomationConfiguration(store:SecurityStore,configuration:AutomationConfiguration,expectedVersion:number,actorId:string,lease?:SecurityLease){const errors=validateAutomationDraft(configuration);if(errors.length)throw new Error(errors.join(' '));return underAutomationLock(store,configuration.id,lease,async()=>{const raw=await store.get(configKey(configuration.id));if(!isConfig(raw))throw new Error('Automation nicht gefunden.');if(raw.version!==expectedVersion)throw new Error('Automation wurde zwischenzeitlich geändert.');if(raw.status==='active')throw new Error('Aktive Automationen müssen vor Änderungen pausiert werden.');const now=new Date().toISOString(),record:StoredRecord={...configuration,status:raw.status,writeEnabled:false,version:raw.version+1,createdAt:raw.createdAt,updatedAt:now,updatedBy:actorId,...(raw.acceptedBaselineFingerprint?{acceptedBaselineFingerprint:raw.acceptedBaselineFingerprint}:{})};await store.set(configKey(record.id),record);return attach(store,record)})}
export async function updateAutomationConfigurationAuthorized(store:SecurityStore,configuration:AutomationConfiguration,expectedVersion:number,actorId:string,authorize:(candidate:AutomationConfiguration,current:StoredAutomationConfiguration)=>Promise<void>,afterPersist?:(updated:StoredAutomationConfiguration,current:StoredAutomationConfiguration)=>Promise<void>){return withAutomationLock(store,configuration.id,async lease=>{const current=await getAutomationConfiguration(store,configuration.id);if(!current)throw new Error('Automation nicht gefunden.');if(current.version!==expectedVersion)throw new Error('Automation wurde zwischenzeitlich geändert.');await authorize(configuration,current);const updated=await updateAutomationConfiguration(store,configuration,expectedVersion,actorId,lease);if(afterPersist)await afterPersist(updated,current);return updated})}
const nextState=(current:StoredRecord,transition:Transition,preflightVerified:boolean)=>{
 if(transition==='dry_run'&&['draft','dry_run','paused','hold'].includes(current.status))return{status:'dry_run' as const,writeEnabled:false};
 if(transition==='request_live'&&current.status==='draft')throw new Error('Vor der Live-Anfrage muss mindestens ein Dry Run abgeschlossen sein.');
 if(transition==='request_live'&&['dry_run','paused','hold'].includes(current.status))return{status:'awaiting_live' as const,writeEnabled:false};
 if(transition==='activate_live'&&current.status==='awaiting_live'){if(!preflightVerified)throw new Error('Live-Aktivierung benötigt einen verifizierten Preflight.');return{status:'active' as const,writeEnabled:true};}
 if(transition==='pause'&&current.status==='active')return{status:'paused' as const,writeEnabled:false};
 if(transition==='resume'&&['paused','hold'].includes(current.status)){if(!preflightVerified)throw new Error('Fortsetzen benötigt einen verifizierten Preflight.');return{status:'active' as const,writeEnabled:true};}
 if(transition==='hold'&&['active','dry_run','awaiting_live'].includes(current.status))return{status:'hold' as const,writeEnabled:false};
 if(transition==='complete'&&current.status!=='completed')return{status:'completed' as const,writeEnabled:false};
 throw new Error('Ungültiger Automations-Statuswechsel.');
};
export async function transitionAutomation(store:SecurityStore,id:string,expectedVersion:number,transition:Transition,actorId:string,options:{preflightVerified?:boolean;baselineFingerprint?:string}={},lease?:SecurityLease){return underAutomationLock(store,id,lease,async()=>{const raw=await store.get(configKey(id));if(!isConfig(raw))throw new Error('Automation nicht gefunden.');if(raw.version!==expectedVersion)throw new Error('Automation wurde zwischenzeitlich geändert.');const state=nextState(raw,transition,options.preflightVerified===true);if(state.writeEnabled&&(!options.baselineFingerprint||!options.baselineFingerprint.startsWith('sha256:')))throw new Error('Verifizierter Campaign-Baseline-Fingerprint fehlt.');const record:StoredRecord={...raw,...state,version:raw.version+1,updatedAt:new Date().toISOString(),updatedBy:actorId,...(options.baselineFingerprint?{acceptedBaselineFingerprint:options.baselineFingerprint}:{})};await store.set(configKey(id),record);return attach(store,record)})}
export async function commitAutomationTarget(store:SecurityStore,id:string,expectedVersion:number,targetSlots:AutomationConfiguration['slots'],verifiedFingerprint:string,actorId:string,lease?:SecurityLease){if(!verifiedFingerprint.startsWith('sha256:'))throw new Error('Verifizierter Campaign-Fingerprint fehlt.');return underAutomationLock(store,id,lease,async()=>{const raw=await store.get(configKey(id));if(!isConfig(raw))throw new Error('Automation nicht gefunden.');if(raw.version!==expectedVersion)throw new Error('Automation wurde zwischenzeitlich geändert.');if(raw.status!=='active'||!raw.writeEnabled)throw new Error('Nur aktive Live-Automationen dürfen Routingzustand übernehmen.');const known=new Set(raw.offers.flatMap(offer=>offer.landingpages.filter(lp=>lp.selection!=='excluded').map(lp=>`${offer.offerId}:${lp.offerUrlId}`))),targetIds=new Set<number>();for(const slot of targetSlots){if(!known.has(`${slot.offerId}:${slot.offerUrlId}`))throw new Error(`Unbekannte oder ausgeschlossene Ziel-LP #${slot.offerUrlId}.`);if(targetIds.has(slot.offerUrlId))throw new Error('Doppelte Ziel-LP.');targetIds.add(slot.offerUrlId)}if(Math.abs(targetSlots.reduce((sum,slot)=>sum+slot.weight,0)-100)>0.01)throw new Error('Zielgewichte ergeben nicht 100 %.');const previousActive=new Set(raw.slots.map(slot=>slot.offerUrlId)),offers=raw.offers.map(offer=>({...offer,landingpages:offer.landingpages.map(lp=>({...lp,selection:targetIds.has(lp.offerUrlId)?'active' as const:previousActive.has(lp.offerUrlId)?'excluded' as const:lp.selection}))})),record:StoredRecord={...raw,offers,slots:targetSlots,acceptedBaselineFingerprint:verifiedFingerprint,version:raw.version+1,updatedAt:new Date().toISOString(),updatedBy:actorId};await store.set(configKey(id),record);return attach(store,record)})}
export async function recordAutomationRun(store:SecurityStore,id:string,run:AutomationRun,lease?:SecurityLease){return underAutomationLock(store,id,lease,async()=>{if(!await store.get(configKey(id)))throw new Error('Automation nicht gefunden.');if(!run.runId||!Number.isSafeInteger(run.writesPerformed)||run.writesPerformed<0)throw new Error('Ungültiger Automationslauf.');if(!await store.setIfAbsent(`${runPrefix(id)}${run.startedAt}:${run.runId}`,run))throw new Error('Automationslauf existiert bereits.');})}
export async function holdAutomationAfterFailure(store:SecurityStore,id:string,actorId:string,run:AutomationRun,incident:AutomationIncident,restore:StoredAutomationConfiguration,lease:SecurityLease){return underAutomationLock(store,id,lease,async()=>{const raw=await store.get(configKey(id));if(!isConfig(raw))throw new Error('Automation nicht gefunden.');const record:StoredRecord={...raw,status:'hold',writeEnabled:false,slots:restore.slots,offers:restore.offers,acceptedBaselineFingerprint:restore.acceptedBaselineFingerprint,lastFailedRun:run,lastIncident:incident,version:raw.version+1,updatedAt:new Date().toISOString(),updatedBy:actorId};await store.set(configKey(id),record);return attach(store,record)})}
