import {describe,expect,it,vi} from 'vitest';
import {MemorySecurityStore} from './security';
import {createAutomationConfiguration,getAutomationConfiguration,recordAutomationRun,transitionAutomation} from './automation-store';
import {AutomationNotDueError,executeAutomationRun} from './automation-runner';
import {normalizeAutomationDraft} from './automation-config';
const make=()=>normalizeAutomationDraft({name:'Test',affiliateId:436,campaignId:146,testMode:'single_offer',strategy:'equal_slots',objective:'sale_first',offers:[{offerId:57,offerName:'Singles69',landingpages:[{familyKey:'a',familyName:'A',offerUrlId:1,offerUrlName:'A',status:'active'},{familyKey:'b',familyName:'B',offerUrlId:2,offerUrlName:'B',status:'active'},{familyKey:'c',familyName:'C',offerUrlId:3,offerUrlName:'C',status:'active',selection:'candidate'}]}],schedule:{intervalMinutes:120},thresholds:{targetSois:50,minClicks:500,minAgeHours:24,maxAgeHours:336,maturityHours:168,minIndependentFirstSales:3,minIndependentPayers:3},weights:{mode:'equal'}});
const metrics=[{offerUrlId:1,clicks:5000,sois:55,cvr:.011,firstSales:0,rebills:0,revenue:100,payout:165,profit:-65,independentPayers:2,top1RevenueShare:.6,ageHours:200,mature:true},{offerUrlId:2,clicks:5000,sois:55,cvr:.011,firstSales:4,rebills:1,revenue:300,payout:165,profit:135,independentPayers:4,top1RevenueShare:.4,ageHours:200,mature:true}];
const deps=(overrides={})=>({loadMetrics:vi.fn().mockResolvedValue(metrics),preflight:vi.fn().mockResolvedValue({verified:true,fingerprint:'sha256:before',blockers:[]}),applyRouting:vi.fn().mockResolvedValue({verified:true,writesPerformed:1,afterFingerprint:'sha256:after'}),authorize:vi.fn().mockResolvedValue(undefined),beforeWrite:vi.fn().mockResolvedValue(undefined),...overrides});
describe('automation runner',()=>{
 it('runs a complete dry run and performs zero provider writes',async()=>{const store=new MemorySecurityStore(),created=await createAutomationConfiguration(store,make(),'a'),d=deps();const result=await executeAutomationRun(store,created.id,'dry_run','a',d);expect(result.evaluation.action.type).toBe('replace_slot');expect(result.writesPerformed).toBe(0);expect(d.applyRouting).not.toHaveBeenCalled();expect(result.configuration.runs[0].mode).toBe('dry_run')});
 it('requires an active write-enabled state for live runs',async()=>{const store=new MemorySecurityStore(),created=await createAutomationConfiguration(store,make(),'a'),d=deps();await expect(executeAutomationRun(store,created.id,'live','a',d)).rejects.toThrow('nicht live freigegeben');expect(d.applyRouting).not.toHaveBeenCalled()});
 it('puts live automation into a durable evidenced hold when preflight sees foreign state',async()=>{const store=new MemorySecurityStore(),created=await createAutomationConfiguration(store,make(),'a'),dry=await transitionAutomation(store,created.id,1,'dry_run','a'),awaiting=await transitionAutomation(store,created.id,dry.version,'request_live','a'),active=await transitionAutomation(store,created.id,awaiting.version,'activate_live','a',{preflightVerified:true,baselineFingerprint:'sha256:before'}),d=deps({preflight:vi.fn().mockResolvedValue({verified:true,fingerprint:'sha256:foreign',blockers:[]})});await expect(executeAutomationRun(store,active.id,'live','a',d)).rejects.toThrow('Baseline');expect(d.beforeWrite).not.toHaveBeenCalled();expect(d.applyRouting).not.toHaveBeenCalled();const held=await getAutomationConfiguration(store,active.id);expect(held).toMatchObject({status:'hold',writeEnabled:false,lastIncident:{providerMutated:false,compensation:'not_needed'}});expect(held?.runs[0]).toMatchObject({mode:'live',verified:false,writesPerformed:0})});
 it('compensates a verified provider mutation and durably holds with run and incident evidence when run persistence fails',async()=>{class FailingRunStore extends MemorySecurityStore{failed=false;override async setIfAbsent(key:string,value:unknown){if(key.startsWith('automation:run:')&&!this.failed){this.failed=true;throw new Error('run store unavailable')}return super.setIfAbsent(key,value)}}const store=new FailingRunStore(),created=await createAutomationConfiguration(store,make(),'a'),dry=await transitionAutomation(store,created.id,1,'dry_run','a'),awaiting=await transitionAutomation(store,created.id,dry.version,'request_live','a'),active=await transitionAutomation(store,created.id,awaiting.version,'activate_live','a',{preflightVerified:true,baselineFingerprint:'sha256:before'}),compensateRouting=vi.fn().mockResolvedValue({verified:true,writesPerformed:1,afterFingerprint:'sha256:before'}),d=deps({compensateRouting});await expect(executeAutomationRun(store,active.id,'live','a',d)).rejects.toThrow('run store unavailable');expect(d.applyRouting).toHaveBeenCalledTimes(1);expect(compensateRouting).toHaveBeenCalledWith({config:expect.objectContaining({slots:active.slots}),expectedFingerprint:'sha256:after'});const held=await getAutomationConfiguration(store,active.id);expect(held).toMatchObject({status:'hold',writeEnabled:false,slots:active.slots,acceptedBaselineFingerprint:'sha256:before',lastIncident:{providerMutated:true,compensation:'verified'}});expect(held?.runs[0]).toMatchObject({verified:false,writesPerformed:1})});
 it('rechecks scheduler due state after acquiring the automation lease',async()=>{const store=new MemorySecurityStore(),created=await createAutomationConfiguration(store,make(),'a'),dry=await transitionAutomation(store,created.id,1,'dry_run','a'),awaiting=await transitionAutomation(store,created.id,dry.version,'request_live','a'),active=await transitionAutomation(store,created.id,awaiting.version,'activate_live','a',{preflightVerified:true,baselineFingerprint:'sha256:before'});await recordAutomationRun(store,active.id,{runId:'recent',startedAt:'2026-07-30T11:00:00Z',completedAt:'2026-07-30T11:01:00Z',mode:'live',decision:'hold',writesPerformed:0,verified:true,summary:'recent'});const d=deps();await expect(executeAutomationRun(store,active.id,'live','scheduler',d,{requireDueAt:new Date('2026-07-30T12:00:00Z')})).rejects.toBeInstanceOf(AutomationNotDueError);expect(d.loadMetrics).not.toHaveBeenCalled()});
 it('authorizes the freshly loaded config and excludes updates with the same automation lease',async()=>{const store=new MemorySecurityStore(),created=await createAutomationConfiguration(store,make(),'a'),updated=await (await import('./automation-store')).updateAutomationConfiguration(store,{...created,name:'Fresh'},created.version,'editor');let release!:()=>void,entered!:()=>void;const wait=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>entered=resolve),d=deps({authorize:vi.fn(async(config)=>{expect(config.name).toBe('Fresh')}),loadMetrics:vi.fn(async()=>{entered();await wait;return metrics})});const running=executeAutomationRun(store,updated.id,'dry_run','a',d);await started;await expect((await import('./automation-store')).updateAutomationConfiguration(store,{...updated,name:'Overlap'},updated.version,'editor')).rejects.toThrow(/läuft/);release();await running});
 it('reauthorizes inside the lock, audits before write, verifies and commits the target',async()=>{const store=new MemorySecurityStore(),created=await createAutomationConfiguration(store,make(),'a'),dry=await transitionAutomation(store,created.id,1,'dry_run','a'),awaiting=await transitionAutomation(store,created.id,dry.version,'request_live','a'),active=await transitionAutomation(store,created.id,awaiting.version,'activate_live','a',{preflightVerified:true,baselineFingerprint:'sha256:before'}),order:string[]=[],d=deps({authorize:vi.fn(async()=>{order.push('authorize')}),beforeWrite:vi.fn(async()=>{order.push('audit')}),applyRouting:vi.fn(async()=>{order.push('write');return{verified:true,writesPerformed:1,afterFingerprint:'sha256:after'}})});const result=await executeAutomationRun(store,active.id,'live','a',d);expect(order).toEqual(['authorize','audit','write']);expect(result.configuration.slots.map(x=>x.offerUrlId)).toEqual([3,2]);expect(result.configuration.acceptedBaselineFingerprint).toBe('sha256:after');expect(result.writesPerformed).toBe(1)});
});
