import {describe,expect,it,vi} from 'vitest';
import {createEverflowHistorySource} from './everflow-history';
import {refreshHistoryRange,type ReportRow,type SyncStore} from './history-cache';
const day='2025-07-23';
const columns=[['affiliate','6','Partner'],['offer','20','API Offer'],['campaign','0','Direct'],['offer_url','0','API'],['source_id','',''],['sub1','',''],['adv1','origin','origin'],['adv2','segment','segment']].map(([column_type,id,label])=>({column_type,id,label}));
const base:ReportRow={columns,reporting:{total_click:0,cv:10,revenue:100,payout:25}};
const event=(label:string,count:number,extra:Partial<ReportRow>={}):ReportRow=>({columns:[...columns,{column_type:'event_name',id:label,label}],reporting:{event:count,revenue:100,payout:25},...extra});
function fixture(response:(events:boolean)=>Response){const fetcher=vi.fn<typeof fetch>(async(_url,init)=>response(JSON.parse(String(init?.body)).columns.some((item:{column:string})=>item.column==='event_name'))),writes=vi.fn(),replace=vi.fn(),store:SyncStore={getState:async()=>null,setState:async()=>{},upsertConversions:writes,upsertMetrics:async()=>{},replaceMetrics:replace};return{fetcher,writes,replace,run:()=>{const source=createEverflowHistorySource('fixture',fetcher);return refreshHistoryRange({store,from:day,to:day,includeConversions:false,...source})}}}
describe('older Berlin days use complete aggregate reporting',()=>{
 it('retains clickless API money and all event counts without fetching expired conversions',async()=>{const f=fixture(events=>Response.json({table:events?[event('Sale',2),event('Rebill',3),event('Coin Spend',4)]:[base]}));const result=await f.run();expect(result.metrics).toHaveLength(1);expect(result.metrics[0]).toMatchObject({metric_date:day,clicks:0,sois:10,first_sales:2,rebills:3,coin_spend:4,revenue:100,payout:25,profit:75,raw:{adv1:'origin',adv2:'segment',traffic_mode:'api'}});expect(f.replace).toHaveBeenCalledWith(day,day,result.metrics);expect(f.fetcher).toHaveBeenCalledTimes(2);for(const [url,init] of f.fetcher.mock.calls){expect(String(url)).toContain('/entity/table');expect(JSON.parse(String(init?.body))).toMatchObject({timezone_id:56,from:day,to:day})}});
 it('retains event-only dimensions missing from the base response',async()=>{const f=fixture(events=>Response.json({table:events?[event('Rebill',3,{reporting:{event:3,revenue:30,payout:5}})]:[]}));expect((await f.run()).metrics[0]).toMatchObject({rebills:3,revenue:30,payout:5,profit:25})});
 it('does not replace a day when the separate event report fails',async()=>{const f=fixture(events=>events?new Response('failed',{status:500}):Response.json({table:[base]}));await expect(f.run()).rejects.toThrow('Everflow 500');expect(f.writes).not.toHaveBeenCalled();expect(f.replace).not.toHaveBeenCalled()});
 it.each([false,true])('rejects an explicitly incomplete %s report before writing',async flaggedEvents=>{const f=fixture(events=>Response.json({table:events?[event('Rebill',3)]:[base],incomplete_results:events===flaggedEvents}));await expect(f.run()).rejects.toThrow('incomplete_results');expect(f.replace).not.toHaveBeenCalled()});
 it('rejects missing table data instead of publishing an empty full day',async()=>{const f=fixture(()=>Response.json({}));await expect(f.run()).rejects.toThrow('missing table');expect(f.replace).not.toHaveBeenCalled()});
});
