import 'server-only';
import {getSupabaseAdmin} from './supabase';
import {buildSmartlinkInsight,type SmartlinkReportRow} from './smartlink';
import{attachSmartlinkSourceBreakdowns,buildSelectedRangeAttribution,filterSmartlinkSourceFactsAfterDay,groupSmartlinkSources,summarizeSmartlinkRows,type SmartlinkSourceFact}from'./smartlink-transparency';
import {loadCampaignShapesFromCache} from './campaign-snapshots';
import{loadAffiliateSourceRowsRangeFromCache}from'./cached-evaluations';
type MetricRow=SmartlinkSourceFact&{metric_date:string;affiliate_id:string;affiliate_name:string;campaign_id:string;campaign_name:string;offer_url_name:string};
const n=(value:number|string)=>Number(value||0);
const dimId=(row:SmartlinkReportRow,type:string)=>row.columns.find(column=>column.column_type===type)?.id||'';
const berlinDay=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
const shift=(day:string,count:number)=>new Date(Date.parse(`${day}T12:00:00Z`)+count*86_400_000).toISOString().slice(0,10);

const dimensions=(row:MetricRow)=>[
  {column_type:'date',id:row.metric_date,label:row.metric_date},{column_type:'hour',id:String(Date.parse(`${row.metric_date}T00:00:00Z`)/1000),label:String(Date.parse(`${row.metric_date}T00:00:00Z`)/1000)},
  {column_type:'affiliate',id:row.affiliate_id,label:row.affiliate_name},{column_type:'offer',id:row.offer_id,label:row.offer_name},
  {column_type:'campaign',id:row.campaign_id,label:row.campaign_name},{column_type:'offer_url',id:row.offer_url_id,label:row.offer_url_name},
];
function reports(rows:MetricRow[]){const base:SmartlinkReportRow[]=[],events:SmartlinkReportRow[]=[];for(const row of rows){const columns=dimensions(row);base.push({columns,reporting:{total_click:n(row.clicks),cv:n(row.sois),payout:n(row.payout),revenue:n(row.revenue),profit:n(row.profit)}});for(const[label,value]of[['Sale',row.first_sales],['Rebill',row.rebills],['Coin Spend',row.coin_spend]]as const)if(n(value))events.push({columns:[...columns,{column_type:'event_name',id:label,label}],reporting:{event:n(value)}})}return{base,events}}
async function metricRange(campaignIds:number[],from:string,to:string,affiliateId?:string){const{data,error}=await getSupabaseAdmin().rpc('smartlink_metric_rows',{p_from:from,p_to:to,p_campaign_ids:campaignIds.map(String),p_affiliate_id:affiliateId||null});if(error)throw new Error(`Supabase smartlink_metric_rows: ${error.message}`);return reports((data||[])as MetricRow[])}
async function metrics(campaignIds:number[],now:Date,affiliateId?:string){const to=berlinDay(now);return metricRange(campaignIds,shift(to,-13),to,affiliateId)}
function sourceFact(row:SmartlinkReportRow):SmartlinkSourceFact{const mode=dimId(row,'traffic_mode')==='api'?'api':'tracked',source=dimId(row,'source_id'),subSource=dimId(row,'sub1'),offer=dimId(row,'offer');return{metric_date:dimId(row,'date'),offer_url_id:dimId(row,'offer_url'),offer_id:offer,offer_name:row.columns.find(column=>column.column_type==='offer')?.label||`Offer #${offer}`,source_id:source,sub_source:subSource,clicks:n(row.reporting.total_click||0),sois:n(row.reporting.cv||0),first_sales:n(row.reporting.first_sales||0),rebills:n(row.reporting.rebills||0),coin_spend:n(row.reporting.coin_spend||0),payout:n(row.reporting.payout||0),revenue:n(row.reporting.revenue||0),profit:n(row.reporting.profit||0),raw:{traffic_mode:mode,adv1:mode==='api'?source:'',adv2:mode==='api'?subSource:''}}}
export async function loadSmartlinkInsightFromCache(campaignId:number,now=new Date()){const[shapes,rows]=await Promise.all([loadCampaignShapesFromCache([campaignId]),metrics([campaignId],now)]);if(!shapes[0])throw new Error(`Campaign #${campaignId}: synchronisierte Metadaten fehlen`);return buildSmartlinkInsight(shapes[0],rows.base,rows.events,now)}
export async function loadAffiliateSmartlinkInsightsFromCache(affiliateId:string,campaignIds:number[],now=new Date(),selectedRange?:{from:string;to:string}){const ids=Array.from(new Set(campaignIds));if(!ids.length)return[];const to=berlinDay(now),sourceRange={from:shift(to,-13),to},range=selectedRange||sourceRange,[shapes,rows,selectedRows,sourceRows]=await Promise.all([loadCampaignShapesFromCache(ids),metrics(ids,now,affiliateId),metricRange(ids,range.from,range.to,affiliateId),loadAffiliateSourceRowsRangeFromCache(sourceRange,affiliateId)]);if(shapes.length!==ids.length){const found=new Set(shapes.map(shape=>shape.network_campaign_id)),missing=ids.filter(id=>!found.has(id));throw new Error(`Campaign-Metadaten fehlen: ${missing.join(', ')}`)}return shapes.map(shape=>{const campaignId=String(shape.network_campaign_id),campaignBase=rows.base.filter(row=>dimId(row,'campaign')===campaignId),campaignEvents=rows.events.filter(row=>dimId(row,'campaign')===campaignId),insight=buildSmartlinkInsight(shape,campaignBase,campaignEvents,now,{affiliateId:Number(affiliateId),affiliate:rows.base[0]?.columns.find(x=>x.column_type==='affiliate')?.label||`Affiliate #${affiliateId}`}),selectedBase=selectedRows.base.filter(row=>dimId(row,'campaign')===campaignId),selectedEvents=selectedRows.events.filter(row=>dimId(row,'campaign')===campaignId),attribution=buildSelectedRangeAttribution({total:summarizeSmartlinkRows(selectedBase,selectedEvents),base:selectedBase,events:selectedEvents,currentSlotIds:new Set(insight.currentSlots.map(slot=>slot.id)),rotationStartEpoch:insight.rotationStartEpoch}),sourceFacts=sourceRows.filter(row=>dimId(row,'campaign')===campaignId).map(sourceFact),rotationDay=insight.rotationStartEpoch?berlinDay(new Date(insight.rotationStartEpoch*1000)):null,currentByUrl=groupSmartlinkSources(filterSmartlinkSourceFactsAfterDay(sourceFacts,rotationDay)),legacyByUrl=groupSmartlinkSources(sourceFacts),sourceSlots=attachSmartlinkSourceBreakdowns(insight.currentSlots,insight.legacySlots,currentByUrl,legacyByUrl);return{...insight,windows:{...insight.windows,source:insight.windows.maturity,sourceLegacy:`Letzte 14 Kalendertage · ${sourceRange.from}–${sourceRange.to}`},currentSlots:sourceSlots.currentSlots,legacySlots:sourceSlots.legacySlots,selectedRange:{...range,attribution}}})}
async function campaignAffiliateMetricRows(from:string,to:string):Promise<MetricRow[]>{
 const days:string[]=[];for(let day=from;day<=to;day=shift(day,1))days.push(day);
 const markerPrefix='campaign_affiliate_day_generation:',markersResult=await getSupabaseAdmin().from('sync_state').select('value').gte('key',`${markerPrefix}${from}`).lte('key',`${markerPrefix}${to}`).order('key');if(markersResult.error)throw new Error(`Supabase campaign markers: ${markersResult.error.message}`);const markers=new Map((markersResult.data||[]).map(item=>{const value=item.value as{date?:string;generation?:string};return[value.date||'',value.generation||'']}));
 if(days.every(day=>markers.get(day))){
  const keys=days.map(day=>`campaign_affiliate_day:${day}:${markers.get(day)}`),rows:MetricRow[]=[],snapshotBatches:string[][]=[];
  for(let start=0;start<keys.length;start+=50)snapshotBatches.push(keys.slice(start,start+50));
  const results=await Promise.all(snapshotBatches.map(async batch=>{const{data,error}=await getSupabaseAdmin().from('sync_state').select('value').in('key',batch);if(error)throw new Error(`Supabase campaign snapshots: ${error.message}`);return data||[]}));
  let found=0;for(const data of results)for(const item of data){const value=item.value as{rows?:MetricRow[]};if(Array.isArray(value.rows)){found++;rows.push(...value.rows)}}if(found===days.length)return rows
 }
 const rows:MetricRow[]=[];for(let start=0;;start+=1000){const{data,error}=await getSupabaseAdmin().from('daily_metrics').select('metric_date,affiliate_id,affiliate_name,offer_id,offer_name,campaign_id,campaign_name,offer_url_id,offer_url_name,clicks,sois,first_sales,rebills,coin_spend,payout,revenue,profit').gte('metric_date',from).lte('metric_date',to).neq('campaign_id','0').order('metric_date').order('id').range(start,start+999);if(error)throw new Error(`Supabase campaign fallback: ${error.message}`);const batch=(data||[])as MetricRow[];rows.push(...batch);if(batch.length<1000)break}return rows
}
export async function loadCampaignAffiliateRowsFromCache(range?:{from:string;to:string},now=new Date()):Promise<SmartlinkReportRow[]>{const to=range?.to||berlinDay(now),from=range?.from||shift(to,-29),data=await campaignAffiliateMetricRows(from,to),grouped=new Map<string,MetricRow>();for(const row of data){const key=`${row.affiliate_id}\u0000${row.campaign_id}`,current=grouped.get(key)||{...row,clicks:0,sois:0,first_sales:0,rebills:0,coin_spend:0,payout:0,revenue:0,profit:0};for(const metric of['clicks','sois','first_sales','rebills','coin_spend','payout','revenue','profit']as const)current[metric]=n(current[metric])+n(row[metric]);grouped.set(key,current)}return Array.from(grouped.values()).map(row=>({columns:[{column_type:'campaign',id:row.campaign_id,label:row.campaign_name},{column_type:'affiliate',id:row.affiliate_id,label:row.affiliate_name}],reporting:{total_click:n(row.clicks),cv:n(row.sois),payout:n(row.payout),revenue:n(row.revenue),profit:n(row.profit)}}))}
