import{describe,expect,it}from'vitest';
import{readFileSync}from'node:fs';
import{join}from'node:path';
import{paginateLtvCohorts,revenuePerRegistration}from'./cohort-pagination';
import type{LtvCohort}from'./cohorts';
const row=(month:string,source:string,sub:string,registrations:number,revenue:number):LtvCohort=>({registration_month:month,affiliate_id:'a',offer_id:'o',campaign_id:'c',source_id:source,sub_source:sub,registrations,revenue_30d:revenue,revenue_60d:revenue,revenue_90d:revenue,revenue_180d:revenue,revenue_365d:revenue});
describe('cohort result pagination',()=>{
 it('keeps affiliate, offer, and campaign dimensions instead of folding them into the source',()=>{const result=paginateLtvCohorts([row('2026-07-01','s','sub',2,3),{...row('2026-07-01','s','sub',4,5),affiliate_id:'b',offer_id:'x'}],1,100);expect(result.total).toBe(2);expect(result.rows[0]).toMatchObject({affiliate_id:'b',offer_id:'x',campaign_id:'c',registrations:4,revenue_30d:5});expect(result.rows[1]).toMatchObject({affiliate_id:'a',offer_id:'o',campaign_id:'c',registrations:2,revenue_30d:3})});
 it('does not merge two affiliates that share the same source and sub-source',()=>{const result=paginateLtvCohorts([row('2026-07-01','s','sub',2,3),{...row('2026-07-01','s','sub',2,3),affiliate_id:'b'}],1,100);expect(result.total).toBe(2);expect(result.rows.map(r=>r.affiliate_id).sort()).toEqual(['a','b'])});
 it('sums only true duplicates of the full dimension key',()=>{const result=paginateLtvCohorts([row('2026-07-01','s','sub',2,3),row('2026-07-01','s','sub',4,5)],1,100);expect(result.total).toBe(1);expect(result.rows[0]).toMatchObject({registrations:6,revenue_30d:8,revenue_365d:8})});
 it('sorts by month descending then registrations descending',()=>{const result=paginateLtvCohorts([row('2026-06-01','s','',9,0),row('2026-07-01','s','',1,0),{...row('2026-07-01','t','',5,0),affiliate_id:'z'}],1,100);expect(result.rows.map(r=>`${r.registration_month}:${r.registrations}`)).toEqual(['2026-07-01:5','2026-07-01:1','2026-06-01:9'])});
 it('filters by exact affiliate id when requested',()=>{const input=[row('2026-07-01','s','sub',2,3),{...row('2026-07-01','s','sub',4,5),affiliate_id:'b'},{...row('2026-07-01','s','sub',4,5),affiliate_id:'ab'}];expect(paginateLtvCohorts(input,1,100,{affiliate:'b'}).rows.map(r=>r.affiliate_id)).toEqual(['b']);expect(paginateLtvCohorts(input,1,100,{affiliate:' b '}).total).toBe(1);expect(paginateLtvCohorts(input,1,100,{affiliate:''}).total).toBe(3);expect(paginateLtvCohorts(input,1,100,{affiliate:'zzz'}).total).toBe(0)});
 it('computes revenue per registration over 90 days and returns null without registrations',()=>{expect(revenuePerRegistration(row('2026-07-01','s','',4,10))).toBe(2.5);expect(revenuePerRegistration({...row('2026-07-01','s','',3,0),revenue_90d:1})).toBeCloseTo(1/3);expect(revenuePerRegistration(row('2026-07-01','s','',0,10))).toBeNull()});
 it('returns only one bounded page and clamps invalid page numbers',()=>{const rows=Array.from({length:235},(_,i)=>row(`2026-${String(12-Math.floor(i/20)).padStart(2,'0')}-01`,`s${i}`,'',i+1,i));const result=paginateLtvCohorts(rows,99,100);expect(result.pages).toBe(3);expect(result.page).toBe(3);expect(result.rows).toHaveLength(35);expect(result.rows[0].registration_month>=result.rows.at(-1)!.registration_month).toBe(true)});
});
describe('cohort page dimension columns',()=>{
 const source=readFileSync(join(process.cwd(),'src/app/cohorts/page.tsx'),'utf8');
 it('renders affiliate, offer, and campaign columns before the source column with mobile labels',()=>{const order=['<th>Monat</th>','<th>Affiliate</th>','<th>Offer</th>','<th>Campaign</th>','<th>Source / Sub-Source</th>','<th>Registrierungen</th>','<th>Umsatz je Registrierung (90 Tage)</th>'].map(marker=>source.indexOf(marker));expect(order.every(i=>i>=0)).toBe(true);expect([...order].sort((a,b)=>a-b)).toEqual(order);for(const label of['data-label="Affiliate"','data-label="Offer"','data-label="Campaign"','data-label="Umsatz je Registrierung (90 Tage)"'])expect(source).toContain(label)});
 it('labels campaign 0 as direct traffic and offers an exact affiliate filter',()=>{expect(source).toMatch(/campaign_id==='0'\?'Direkt'/);expect(source).toContain('name="affiliate"');expect(source).toContain('Affiliate-ID');expect(source).toMatch(/paginateLtvCohorts\(allRows,.*?\{affiliate:filters\.affiliate\}\)/);expect(source).toContain("params.set('affiliate',filters.affiliate)");expect(source).toContain('revenuePerRegistration(row)')});
});
