import {readFileSync,readdirSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
const root=new URL('../../',import.meta.url),read=(name:string)=>readFileSync(new URL(name,root),'utf8');
describe('production operations and normalized access model',()=>{
 it('documents every required server setting and safe defaults',()=>{const env=read('.env.example');for(const key of ['APP_ORIGIN','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','EVERFLOW_API_KEY','CRON_SECRET','MFA_ENCRYPTION_KEY','ALLOW_LEGACY_ADMIN'])expect(env).toContain(`${key}=`);expect(env).not.toContain('SUPABASE_ANON_KEY');expect(env).toContain('ALLOW_LEGACY_ADMIN=false')});
 it('configures the authenticated staggered hourly cron',()=>{const vercel=JSON.parse(read('vercel.json'));expect(vercel.crons).toContainEqual({path:'/api/sync',schedule:'17 * * * *'})});
 it('ships a future-safe normalized RLS migration',()=>{const dir=new URL('supabase/migrations/',root),sql=readdirSync(dir).filter(x=>x.endsWith('.sql')).sort().map(name=>readFileSync(new URL(name,dir),'utf8')).join('\n').toLowerCase();for(const table of ['app_roles','app_role_permissions','app_user_roles','app_user_scopes','app_sessions','app_audit_events','app_mfa_factors']){expect(sql).toContain(`create table if not exists public.${table}`);expect(sql).toContain(`alter table public.${table} enable row level security`)}});
 it('ships atomic normalized Postgres primitives and documents the active persistent safeguards',()=>{const sql=read('supabase/migrations/20260727071000_atomic_security_primitives.sql').toLowerCase();for(const object of['app_rate_limits','app_validate_session','app_revoke_session','app_revoke_user_sessions','app_record_rate_limit_failure','app_reset_rate_limit','app_mutate_user_role'])expect(sql).toContain(object);expect(sql).toMatch(/create or replace function public\.app_revoke_session\s*\(/);expect(sql).toMatch(/app_validate_session[\s\S]*for update[\s\S]*update public\.app_sessions/);expect(sql).toMatch(/app_record_rate_limit_failure[\s\S]*on conflict\s*\(identifier_hash\) do update/);expect(sql).toMatch(/app_mutate_user_role[\s\S]*pg_advisory_xact_lock[\s\S]*metadata_version=p_expected_version/);expect(sql).toContain('alter table public.app_rate_limits enable row level security');expect(sql).toMatch(/revoke all on function[\s\S]*from public/);expect(sql).toMatch(/grant execute on function[\s\S]*to service_role/);const docs=read('README.md');for(const safeguard of['Unique-Key','Widerrufsmarkern','fail-closed Owner-Locks','Incident-Recovery'])expect(docs).toContain(safeguard)});
 it('documents setup, RBAC invariants, MFA, exports, cron, and all release gates',()=>{const docs=read('README.md');for(const text of ['RBAC','MFA','/api/exports','CRON_SECRET','npm audit','npx tsc --noEmit','APP_ORIGIN'])expect(docs).toContain(text)});
 it('pins patched Next, PostCSS, and Sharp releases',()=>{const pkg=JSON.parse(read('package.json'));expect(pkg.dependencies.next).toBe('16.2.12');expect(pkg.dependencies.postcss).toMatch(/^8\.5\.(1[89]|[2-9]\d)$/);expect(pkg.dependencies.sharp).toMatch(/^0\.(35|[4-9]\d)\./)});
});
