import{readFileSync}from'node:fs';import{join}from'node:path';import{describe,expect,it}from'vitest';
import{translations}from'./i18n-translations';
const read=(path:string)=>readFileSync(join(process.cwd(),path),'utf8');
/** Quelltext-Vertrag der Etappe-3-Review (U): Vorzeichen nur über das Reife-Gate, Zustandsfamilie „Gesperrt“, Zeitraum bleibt erhalten, Schwellentext mit D3, Ladefeedback und Mobile-Ziele. */
const THRESHOLD_FRAGMENTS=['Ausschalten ab','Klicks ohne SOI, oder ab','SOIs ohne First-Sale bei negativem Profit, oder ab','SOIs bei negativem Profit und belegter Unterperformance (First-Sale-Rate auch optimistisch unter','% des Vergleichswerts) – beide SOI-Regeln erst mit mindestens','reifen SOIs (typische Wartezeit des Partners erreicht). Skalieren ab','SOIs mit mindestens','First-Sales und positivem Profit.'];
describe('Etappe-3-Review (U)',()=>{
 it('colours every sign of the partner page and the source list through signTone/toneClass (Abnahme E: 0 Fälle)',()=>{const page=read('src/app/affiliates/page.tsx'),list=read('src/app/sources/SourceCandidateList.tsx');expect(page).toContain('import { signTone } from "@/lib/verdict-vocabulary"');expect(page).toContain('import { toneClass } from "@/lib/verdict-trust"');expect(page.match(/toneClass\(signTone\(/g)?.length).toBeGreaterThanOrEqual(11);expect(page).not.toMatch(/\?\s*"up"\s*:\s*"down"/);expect(list).toContain('className={toneClass(signTone(row.profit??0,row))}');expect(list).not.toContain("'negative':'positive'");expect(read('src/app/globals.css')).toContain('.sourcesTable td.up b{color:var(--positive)}.sourcesTable td.down b{color:var(--negative)}')});
 it('takes the product-wide block action word from ACTION_WORDS',()=>{const button=read('src/app/affiliates/SourceBlockButton.tsx');expect(button.match(/ACTION_WORDS\.blockAcrossOffersScoped\(controlScope\)/g)).toHaveLength(2);expect(button).toContain('ACTION_WORDS.blockAcrossOffersConfirm(controlScope)');expect(button).not.toContain('überall sperren')});
 it('names the blocked state family consistently in sidebar, audit page and dictionary',()=>{expect(read('src/app/components/AdminSidebar.tsx')).toContain('label:"Gesperrte Quellen"');expect(read('src/app/source-blocks/page.tsx')).toContain("block.status==='active'?'GESPERRT'");expect(translations['Gesperrte Quellen']).toBe('Blocked sources');expect(translations['GESPERRT']).toBe('BLOCKED');expect(translations['Ausgeschaltete Quellen']).toBeDefined()});
 it('uses the verdict word in the engine prose instead of Abschaltung',()=>{const engine=read('src/lib/decision-engine.ts');expect(engine).not.toMatch(/reason: [`"][^`"]*Abschalt/);expect(engine).not.toMatch(/"[^"\n]*abschalten[^"\n]*",/);for(const sentence of['Ausschalten erst nach geprüfter Wartezeit.','Ausschalten erst ab ${KILL_MATURITY_SOIS} reifen SOIs.','Ausschalten nur bei belegter Unterperformance.','vor dem Ausschalten mehr Evidenz sammeln.'])expect(engine).toContain(sentence)});
 it('carries the global period into the /sources range switch and explains the 30-day mapping',()=>{const page=read('src/app/sources/page.tsx'),list=read('src/app/sources/SourceCandidateList.tsx');expect(page).toContain('withGlobalPeriod(`/sources?range=${item}`,current)');expect(page).toContain("for(const key of['period','from','to'] as const)if(params[key])current.set(key,params[key]!)");expect(page).toContain("mappedPeriod=isReportingPeriod(params.period)&&params.period!=='7d'&&params.period!=='30d'&&range==='30d'");expect(page).toContain('Quellenliste: 30 Tage (Rollup-Zeitraum)');expect(list).toContain('withGlobalPeriod(`${window.location.pathname}?${query}`,window.location.search)')});
 it('shows one maturity statement per source row – the gate when the snapshot carries one',()=>{expect(read('src/lib/source-candidate-view.ts')).toContain('gate:VerdictGate|null|undefined=m.gate');expect(read('src/app/sources/SourceCandidateList.tsx').match(/maturityLabel\(row\)/g)).toHaveLength(2)});
 it('keeps the trust line short (latency only as badge) and explains tracker dashes on source level',()=>{const trend=read('src/app/affiliates/TrendList.tsx');expect(trend).toContain('withoutLatency(trust.text)');expect(trend).toContain('const SOURCE_NO_PREVIOUS = "keine Vorperiode auf Quellen-Ebene"');expect(trend).toContain('item.kind === "source" && !item.previous ?');expect(trend).not.toContain('sparklineEmpty')});
 it('states the D3 condition in the threshold footer with numbers interpolated from the engine constants',()=>{const breakdown=read('src/app/affiliates/SourceBreakdown.tsx');expect(breakdown).not.toContain('Ausschalten ab ${');expect(breakdown).toContain('KILL_MATURITY_SOIS, " reifen SOIs');expect(breakdown).toContain('{thresholdText(apiMode)}');for(const fragment of THRESHOLD_FRAGMENTS){expect(breakdown).toContain(fragment);expect(translations).toHaveProperty(fragment);expect(/\d/.test(fragment)).toBe(false)}});
 it('puts Δ CVR in percentage points on the SOI/CVR tile and marks the partial last sparkline point',()=>{const kpis=read('src/lib/home-kpis.ts'),home=read('src/app/page.tsx');expect(kpis).toContain("unit:' pp'");expect(kpis).toContain("deltaLabel:'Δ First-Sales'");expect(kpis).not.toContain("deltaLabel:'Δ CVR'");expect(home).toContain('sparklinePartialNote(dataStatus)');expect(home).toContain("(data.daily?.length??0)>1&&data.range.to===reportingRange('today').to?");expect(home.indexOf('kpiPartialDay')).toBeGreaterThan(home.indexOf('<section className="kpis">'))});
 it('gives the compact period control loading feedback and error text, with 44 px targets and single-column source editors on phones',()=>{const controls=read('src/app/components/PeriodControls.tsx'),css=read('src/app/globals.css');expect(controls).toContain("compactPeriodControls${pending?' pending':''}");expect(controls).toMatch(/if\(compact\)return <div[^\n]*\{feedback\}<\/div>/);expect(controls.indexOf('const feedback=')).toBeLessThan(controls.indexOf('if(compact)return'));expect(css).toContain('@media(max-width:759px){.compactPeriodControls .affiliatePresetButtons button{min-height:44px');expect(css).toContain('.sourcePeriodControls .dashboardCustomPeriod{grid-template-columns:1fr}');expect(css).toContain('.compactPeriodControls.pending .affiliatePresetButtons button{opacity:.6}')});
 it('passes partners no money on the home page: tiles without finance carry counts only',()=>{const home=read('src/app/page.tsx');expect(home).toContain('<Sparkline points={tile.points}');expect(home).toContain("finance=can(user.access,'finance.view')");expect(home).toContain('{finance&&<section className="portfolioCopyBar">');expect(home).toContain("user.access.role!=='partner'&&<LeitstandSection")});
 it('translates the visible Etappe-3 terms',()=>{for(const key of['belastbar','unsicher','Latenz hoch','Latenz nicht geprüft','Konfidenz: nicht berechnet','Trauen oder nicht, und warum','Was zuerst zu tun ist','keine Vorperiode','keine Vorperiode auf Quellen-Ebene','unter Reifeschwelle (≥ 100 Klicks oder ≥ 20 SOIs)','Tagesreihe nur bei Fenstern bis 45 Tage','Heute','7 Tage','30 Tage','90 Tage','12 Monate','365 Tage','ZEITRAUM','letzter Punkt: Teiltag bis Sync-Zeit','Δ First-Sales','Δ Vorperiode','Profit je Tag','SOIs je Tag','Zeitraum wird geladen …'])expect(translations).toHaveProperty(key);const en=Object.values(translations) as string[];for(const value of['Blocked sources','BLOCKED','reliable','uncertain','PERIOD'])expect(en.filter(item=>item===value)).toHaveLength(1)});
});
