const BASE='https://api.eflow.team/v1';
type Fetcher=typeof fetch;
export type CampaignStatus='active'|'paused';
type Redirect={redirect_network_offer_id:number;redirect_network_offer_url_id:number;routing_value:number;ruleset?:unknown};
type Relationship={redirects?:Redirect[]|{entries?:Redirect[]};labels?:string[]|{entries?:string[]}};
type EverflowCampaign={network_campaign_id:number;campaign_name:string;campaign_status:string;network_tracking_domain_id:number;redirect_routing_type:string;catch_all_network_offer_id?:number;data_collection_threshold?:unknown;data_lookback_window?:unknown;is_open_to_affiliates?:boolean;is_use_secure_link?:boolean;metric?:unknown;optimization_goal?:unknown;run_frequency?:unknown;conversion_method?:unknown;is_whitelist_check_enabled?:unknown;relationship?:Relationship};
const headers=(apiKey:string)=>({'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'});
async function json<T>(fetcher:Fetcher,url:string,init:RequestInit){const response=await fetcher(url,{...init,signal:init.signal||AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`Everflow Campaign API HTTP ${response.status}`);return response.json() as Promise<T>}
const entries=<T>(value:T[]|{entries?:T[]}|undefined)=>Array.isArray(value)?value:(value?.entries||[]);
const safeId=(value:unknown)=>Number.isSafeInteger(value)&&Number(value)>=0;
const enumValue=(value:unknown,allowed:readonly string[])=>typeof value==='string'&&allowed.includes(value);
const RUN_FREQUENCIES=['unknown','12_hours','24_hours','6_hours','3_hours','1_hours'] as const;
const METRICS=['unknown','profit','cvr','evr','conversions','payout','revenue','rpc','cpc','epc'] as const;
const LOOKBACK_WINDOWS=['unknown','12_hours','24_hours','48_hours'] as const;
const CONVERSION_METHODS=['server_postback','pixel_tracking'] as const;
function assertCompleteCampaign(campaign:EverflowCampaign,id?:number){
 if(id!==undefined&&campaign.network_campaign_id!==id)throw new Error('Everflow lieferte eine andere Campaign-ID');
 if(!safeId(campaign.network_campaign_id)||typeof campaign.campaign_name!=='string'||!campaign.campaign_name.trim())throw new Error('Everflow lieferte keinen vollständigen Campaign-Snapshot');
 if(!['active','paused','deleted'].includes(campaign.campaign_status)||!safeId(campaign.network_tracking_domain_id)||!['priority','weight','kpi'].includes(campaign.redirect_routing_type))throw new Error('Everflow lieferte keinen vollständigen Campaign-Snapshot');
 if(typeof campaign.is_use_secure_link!=='boolean'||typeof campaign.is_open_to_affiliates!=='boolean'||!campaign.relationship||campaign.relationship.redirects===undefined||campaign.relationship.labels===undefined)throw new Error('Everflow lieferte keinen vollständigen Campaign-Snapshot');
 const redirectRows=entries(campaign.relationship.redirects),labelRows=entries(campaign.relationship.labels);
 if(!redirectRows.every(row=>safeId(row.redirect_network_offer_id)&&safeId(row.redirect_network_offer_url_id)&&Number.isFinite(row.routing_value))||!labelRows.every(label=>typeof label==='string'))throw new Error('Everflow lieferte ungültige Routingdaten');
 if(campaign.catch_all_network_offer_id!==undefined&&!safeId(campaign.catch_all_network_offer_id))throw new Error('Everflow lieferte einen ungültigen Campaign-Snapshot');
 if(campaign.run_frequency!==undefined&&!enumValue(campaign.run_frequency,RUN_FREQUENCIES)||campaign.metric!==undefined&&!enumValue(campaign.metric,METRICS)||campaign.data_lookback_window!==undefined&&!enumValue(campaign.data_lookback_window,LOOKBACK_WINDOWS))throw new Error('Everflow lieferte einen ungültigen Campaign-Snapshot');
 if(campaign.optimization_goal!==undefined&&(typeof campaign.optimization_goal!=='number'||!Number.isFinite(campaign.optimization_goal))||campaign.data_collection_threshold!==undefined&&(!Number.isSafeInteger(campaign.data_collection_threshold)||Number(campaign.data_collection_threshold)<0))throw new Error('Everflow lieferte einen ungültigen Campaign-Snapshot');
 if(campaign.conversion_method!==undefined&&!enumValue(campaign.conversion_method,CONVERSION_METHODS)||campaign.is_whitelist_check_enabled!==undefined&&typeof campaign.is_whitelist_check_enabled!=='boolean')throw new Error('Everflow lieferte einen ungültigen Campaign-Snapshot');
 if(campaign.redirect_routing_type==='kpi'&&(campaign.run_frequency===undefined||campaign.metric===undefined||campaign.optimization_goal===undefined||campaign.data_lookback_window===undefined||campaign.data_collection_threshold===undefined))throw new Error('Everflow lieferte unvollständige KPI-Routingdaten');
}
const redirects=(campaign:EverflowCampaign)=>entries(campaign.relationship?.redirects).map(item=>({redirect_network_offer_id:item.redirect_network_offer_id,redirect_network_offer_url_id:item.redirect_network_offer_url_id,routing_value:item.routing_value,...(item.ruleset!==undefined?{ruleset:item.ruleset}:{})}));
const labels=(campaign:EverflowCampaign)=>entries(campaign.relationship?.labels);
export function buildCampaignStatusPayload(campaign:EverflowCampaign,status:CampaignStatus){assertCompleteCampaign(campaign);return{campaign_name:campaign.campaign_name,campaign_status:status,network_tracking_domain_id:campaign.network_tracking_domain_id,is_use_secure_link:campaign.is_use_secure_link,redirect_routing_type:campaign.redirect_routing_type,is_open_to_affiliates:campaign.is_open_to_affiliates,redirects:redirects(campaign),labels:labels(campaign),...(campaign.catch_all_network_offer_id!==undefined?{catch_all_network_offer_id:campaign.catch_all_network_offer_id}:{}),...(campaign.data_collection_threshold!==undefined?{data_collection_threshold:campaign.data_collection_threshold}:{}),...(campaign.data_lookback_window!==undefined?{data_lookback_window:campaign.data_lookback_window}:{}),...(campaign.metric!==undefined?{metric:campaign.metric}:{}),...(campaign.optimization_goal!==undefined?{optimization_goal:campaign.optimization_goal}:{}),...(campaign.run_frequency!==undefined?{run_frequency:campaign.run_frequency}:{}),...(campaign.conversion_method!==undefined?{conversion_method:campaign.conversion_method}:{}),...(campaign.is_whitelist_check_enabled!==undefined?{is_whitelist_check_enabled:campaign.is_whitelist_check_enabled}:{})}}
const configurationFingerprint=(campaign:EverflowCampaign)=>JSON.stringify({...buildCampaignStatusPayload(campaign,'active'),campaign_status:'*'});
async function readCampaign(id:number,apiKey:string,fetcher:Fetcher){/* Everflow documents redirects as a repeatable relationship; labels are part of the returned SmartLink relationship schema and have no separate query enum. */const result=await json<EverflowCampaign>(fetcher,`${BASE}/networks/campaigns/${id}?relationship=redirects`,{headers:headers(apiKey)});assertCompleteCampaign(result,id);return result}
export async function readEverflowCampaignStatus(campaignId:number,apiKey:string,fetcher:Fetcher=fetch){if(!Number.isSafeInteger(campaignId)||campaignId<=0)throw new Error('Campaign-ID ungültig');if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const campaign=await readCampaign(campaignId,apiKey,fetcher);return{campaignId,status:campaign.campaign_status as CampaignStatus|'deleted',name:campaign.campaign_name}}
export async function setEverflowCampaignStatus(campaignId:number,status:CampaignStatus,apiKey:string,fetcher:Fetcher=fetch){if(!Number.isSafeInteger(campaignId)||campaignId<=0)throw new Error('Campaign-ID ungültig');if(status!=='active'&&status!=='paused')throw new Error('Campaign-Status ungültig');if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const before=await readCampaign(campaignId,apiKey,fetcher);if(before.campaign_status==='deleted')throw new Error('Gelöschte Campaigns werden nicht automatisch reaktiviert');if(before.campaign_status===status)return{campaignId,status,changed:false,name:before.campaign_name};const fingerprint=configurationFingerprint(before),payload=buildCampaignStatusPayload(before,status);await json(fetcher,`${BASE}/networks/campaigns/${campaignId}`,{method:'PUT',headers:headers(apiKey),body:JSON.stringify(payload)});const after=await readCampaign(campaignId,apiKey,fetcher);if(after.campaign_status!==status||configurationFingerprint(after)!==fingerprint){const rollback=buildCampaignStatusPayload(before,before.campaign_status as CampaignStatus),rollbackResponse=await fetcher(`${BASE}/networks/campaigns/${campaignId}`,{method:'PUT',headers:headers(apiKey),body:JSON.stringify(rollback),signal:AbortSignal.timeout(30_000)});if(!rollbackResponse.ok)throw new Error(`Campaign-Verifikation und Rollback fehlgeschlagen: HTTP ${rollbackResponse.status}`);const restored=await readCampaign(campaignId,apiKey,fetcher);if(restored.campaign_status!==before.campaign_status||configurationFingerprint(restored)!==fingerprint)throw new Error('Campaign-Verifikation und Rollback-Verifikation fehlgeschlagen');throw new Error('Campaign-Verifikation fehlgeschlagen; die ursprüngliche Konfiguration wurde wiederhergestellt und verifiziert')}return{campaignId,status,changed:true,name:after.campaign_name}}
