import {describe,expect,it,vi} from 'vitest';
import {buildCampaignStatusPayload,setEverflowCampaignStatus} from './everflow-campaign-status';

const campaign={network_campaign_id:135,campaign_name:'WLX',campaign_status:'active',network_tracking_domain_id:4931,redirect_routing_type:'weight',catch_all_network_offer_id:0,data_collection_threshold:100,data_lookback_window:'24_hours',is_open_to_affiliates:false,is_use_secure_link:false,metric:'revenue',optimization_goal:1,run_frequency:'24_hours',relationship:{redirects:{entries:[{redirect_network_offer_id:57,redirect_network_offer_url_id:2750,routing_value:50,ruleset:{countries:[]}}]},labels:{entries:[]}}};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});

describe('Everflow campaign status writer',()=>{
 it('preserves the complete routing contract while changing only campaign status',()=>{expect(buildCampaignStatusPayload(campaign,'paused')).toMatchObject({campaign_name:'WLX',campaign_status:'paused',network_tracking_domain_id:4931,is_use_secure_link:false,is_open_to_affiliates:false,labels:[],redirect_routing_type:'weight',redirects:[{redirect_network_offer_id:57,redirect_network_offer_url_id:2750,routing_value:50,ruleset:{countries:[]}}]})});
 it('GETs, writes and read-back verifies status without changing redirects',async()=>{let state=campaign;const fetcher=vi.fn(async(_url:string|URL|Request,init?:RequestInit)=>{if(init?.method==='PUT'){state={...state,...JSON.parse(String(init.body))};return response({ok:true})}return response(state)});await expect(setEverflowCampaignStatus(135,'paused','secret',fetcher)).resolves.toMatchObject({campaignId:135,status:'paused'});expect(fetcher.mock.calls.map(call=>call[1]?.method||'GET')).toEqual(['GET','PUT','GET']);expect(state.relationship.redirects.entries).toEqual(campaign.relationship.redirects.entries)});
 it('requests documented redirects and rejects incomplete required PUT fields',async()=>{const fetcher=vi.fn(async(url:string|URL|Request)=>{String(url);return response({...campaign,is_use_secure_link:undefined})});await expect(setEverflowCampaignStatus(135,'paused','secret',fetcher)).rejects.toThrow('vollständigen Campaign-Snapshot');expect(String(fetcher.mock.calls[0][0])).toContain('/135?relationship=redirects');expect(fetcher).toHaveBeenCalledTimes(1)});
 it.each([
  ['metric',{bad:true}],['run_frequency',17],['data_lookback_window','bogus'],['optimization_goal',null],['data_collection_threshold',null],['conversion_method',42],['is_whitelist_check_enabled','yes'],
 ] as const)('rejects an invalid documented optional field %s before PUT',(field,value)=>{const kpi={...campaign,redirect_routing_type:'kpi',metric:'profit',run_frequency:'24_hours',data_lookback_window:'24_hours',optimization_goal:1,data_collection_threshold:100,[field]:value};expect(()=>buildCampaignStatusPayload(kpi,'paused')).toThrow('Campaign-Snapshot')});
 it('fails closed and restores the exact original payload when read-back changes routing',async()=>{let state=campaign,puts=0;const fetcher=vi.fn(async(_url:string|URL|Request,init?:RequestInit)=>{if(init?.method==='PUT'){puts++;const body=JSON.parse(String(init.body));state=puts===1?{...campaign,campaign_status:'paused',relationship:{...campaign.relationship,redirects:{entries:[{...campaign.relationship.redirects.entries[0],routing_value:100}]}}}:{...campaign,campaign_status:body.campaign_status};return response({ok:true})}return response(state)});await expect(setEverflowCampaignStatus(135,'paused','secret',fetcher)).rejects.toThrow('wiederhergestellt');const putBodies=fetcher.mock.calls.filter(call=>call[1]?.method==='PUT').map(call=>JSON.parse(String(call[1]?.body)));expect(putBodies).toHaveLength(2);expect(putBodies[1]).toEqual(buildCampaignStatusPayload(campaign,'active'))});
 it('never revives a deleted Campaign',async()=>{const fetcher=vi.fn(async()=>response({...campaign,campaign_status:'deleted'}));await expect(setEverflowCampaignStatus(135,'active','secret',fetcher)).rejects.toThrow('Gelöschte');expect(fetcher).toHaveBeenCalledTimes(1)});
});