import { aggregateDashboard, berlinDateRange, type DashboardData, type Period, type Redirect } from './dashboard';
import { aggregatePortfolio, type Portfolio } from './portfolio';
import { buildSmartlinkInsight, type CampaignShape } from './smartlink';
import{normalizeAffiliateSourceDimensions}from'./affiliate-source-dimensions';
const BASE='https://api.eflow.team/v1';
type Fetcher=typeof fetch;
type ReportRow={columns:{column_type:string;id:string;label:string}[];reporting:Record<string,number>};
async function json(fetcher:Fetcher,url:string,init:RequestInit){const response=await fetcher(url,init);if(!response.ok)throw new Error(`Everflow HTTP ${response.status}: ${(await response.text()).slice(0,250)}`);return response.json();}
export async function loadDashboard(period:Period,apiKey:string,fetcher:Fetcher=fetch,now=new Date()):Promise<DashboardData>{
 if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'};
 const campaign=await json(fetcher,`${BASE}/networks/campaigns/169?relationship=redirects`,{headers}) as {network_campaign_id:number;relationship?:{redirects?:{entries?:Array<{redirect_network_offer_id:number;redirect_network_offer_url_id:number;routing_value:number;relationship?:{offer_url?:{name?:string;url_status?:string}}}>}}};
 if(campaign.network_campaign_id!==169)throw new Error('Unerwartete Campaign');
 const redirects:Redirect[]=(campaign.relationship?.redirects?.entries||[]).filter(r=>r.redirect_network_offer_id===57).map(r=>({urlId:String(r.redirect_network_offer_url_id),name:r.relationship?.offer_url?.name||`LP #${r.redirect_network_offer_url_id}`,weight:Number(r.routing_value),status:r.relationship?.offer_url?.url_status||'unknown'}));
 const range=berlinDateRange(period,now);const filters=[{resource_type:'offer',filter_id_value:'57'},{resource_type:'campaign',filter_id_value:'169'}];
 const body=(events:boolean)=>({from:range.from,to:range.to,timezone_id:80,currency_id:'EUR',columns:['campaign','offer','offer_url',...(events?['event_name']:[])].map(column=>({column})),query:{filters,search_terms:[]}});
 const [baseResponse,eventResponse]=await Promise.all([false,true].map(events=>json(fetcher,`${BASE}/networks/reporting/entity/table`,{method:'POST',headers,body:JSON.stringify(body(events))}))) as [{table?:ReportRow[]},{table?:ReportRow[]}];
 const validate=(rows:ReportRow[])=>{for(const row of rows){const ids=Object.fromEntries(row.columns.map(c=>[c.column_type,String(c.id)]));if(ids.campaign!=='169'||ids.offer!=='57')throw new Error('Everflow-Filter wurde ignoriert');}return rows;};
 return aggregateDashboard(redirects,validate(baseResponse.table||[]),validate(eventResponse.table||[]),range);
}

export async function loadPortfolio(period:Period,apiKey:string,fetcher:Fetcher=fetch,now=new Date()):Promise<Portfolio>{
 if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');
 const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'};
 const range=berlinDateRange(period,now);
 const body=(events:boolean)=>({from:range.from,to:range.to,timezone_id:80,currency_id:'EUR',columns:['affiliate','offer','campaign','offer_url',...(events?['event_name']:[])].map(column=>({column})),query:{filters:[],search_terms:[]}});
 const [baseResponse,eventResponse]=await Promise.all([false,true].map(events=>json(fetcher,`${BASE}/networks/reporting/entity/table`,{method:'POST',headers,body:JSON.stringify(body(events))}))) as [{table?:ReportRow[]},{table?:ReportRow[]}];
 return aggregatePortfolio(baseResponse.table||[],eventResponse.table||[],range);
}
export async function loadAffiliateSourceRows(period:Period,affiliateId:string,apiKey:string,fetcher:Fetcher=fetch,now=new Date()):Promise<ReportRow[]>{return loadAffiliateSourceRowsRange(berlinDateRange(period,now),affiliateId,apiKey,fetcher)}
export async function loadAffiliateSourceRowsRange(range:{from:string;to:string},affiliateId:string,apiKey:string,fetcher:Fetcher=fetch):Promise<ReportRow[]>{
 if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');if(!/^\d+$/.test(affiliateId))throw new Error('Ungültige Affiliate-ID');const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'},body={from:range.from,to:range.to,timezone_id:80,currency_id:'EUR',columns:['affiliate','offer','campaign','offer_url','source_id','sub1','adv1','adv2'].map(column=>({column})),query:{filters:[{resource_type:'affiliate',filter_id_value:affiliateId},{resource_type:'campaign',filter_id_value:'0'}],search_terms:[]}},response=await json(fetcher,`${BASE}/networks/reporting/entity/table`,{method:'POST',headers,body:JSON.stringify(body)})as{table?:ReportRow[]};for(const row of response.table||[]){const affiliate=row.columns.find(c=>c.column_type==='affiliate');if(affiliate&&String(affiliate.id)!==affiliateId)throw new Error('Everflow Affiliate-Filter wurde ignoriert')}return(response.table||[]).map(row=>normalizeAffiliateSourceDimensions(row))
}

export type ConversionRow={transaction_id:string;event:string;is_event:boolean;conversion_unix_timestamp:number;source_id?:string;sub1?:string;relationship?:{affiliate?:{network_affiliate_id:number;name?:string};offer?:{network_offer_id:number;name?:string};offer_url?:{network_offer_url_id:number;name?:string};campaign?:{network_campaign_id:number}}};
export async function loadAffiliateConversions(affiliateId:string,apiKey:string,lookbackDays=90,fetcher:Fetcher=fetch,now=new Date()):Promise<ConversionRow[]>{if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');if(!/^\d+$/.test(affiliateId))throw new Error('Ungültige Affiliate-ID');const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'},to=berlinDay(now),from=berlinDay(new Date(now.getTime()-(lookbackDays-1)*86400000)),body={from,to,timezone_id:80,currency_id:'EUR',show_conversions:true,show_events:true,query:{filters:[{resource_type:'affiliate',filter_id_value:affiliateId},{resource_type:'campaign',filter_id_value:'0'}],search_terms:[]}},pageSize=2000,load=(page:number)=>json(fetcher,`${BASE}/networks/reporting/conversions?page=${page}&page_size=${pageSize}`,{method:'POST',headers,body:JSON.stringify(body)})as Promise<{conversions?:ConversionRow[];paging?:{total_count?:number}}>;const first=await load(1),total=Number(first.paging?.total_count||first.conversions?.length||0),pages=Math.max(1,Math.ceil(total/pageSize)),all=[...(first.conversions||[])];for(let start=2;start<=pages;start+=6){const batch=await Promise.all(Array.from({length:Math.min(6,pages-start+1)},(_,i)=>load(start+i)));for(const result of batch)all.push(...(result.conversions||[]))}for(const row of all){const id=row.relationship?.affiliate?.network_affiliate_id;if(id!==undefined&&String(id)!==affiliateId)throw new Error('Everflow Affiliate-Filter wurde ignoriert')}return all}

function berlinDay(now:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
export async function loadCampaignAffiliateRows(apiKey:string,fetcher:Fetcher=fetch,now=new Date()){if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'},range=berlinDateRange('30d',now),body={from:range.from,to:range.to,timezone_id:80,currency_id:'EUR',columns:['campaign','affiliate'].map(column=>({column})),query:{filters:[],search_terms:[]}},response=await json(fetcher,`${BASE}/networks/reporting/entity/table`,{method:'POST',headers,body:JSON.stringify(body)})as{table?:ReportRow[]};return response.table||[]}
export async function loadAffiliateSmartlinkInsights(affiliateId:string,campaignIds:number[],apiKey:string,fetcher:Fetcher=fetch,now=new Date()){if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');if(!/^\d+$/.test(affiliateId))throw new Error('Ungültige Affiliate-ID');const ids=[...new Set(campaignIds.filter(x=>Number.isInteger(x)&&x>0))];if(!ids.length)return[];const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'},to=berlinDay(now),end=Date.parse(`${to}T00:00:00Z`),from=new Date(end-14*86400000).toISOString().slice(0,10),filters=[{resource_type:'affiliate',filter_id_value:affiliateId}],body=(events:boolean)=>({from,to,timezone_id:80,currency_id:'EUR',columns:['campaign','affiliate','offer','offer_url','hour',...(events?['event_name']:[])].map(column=>({column})),query:{filters,search_terms:[]}});const [campaigns,baseResponse,eventResponse]=await Promise.all([Promise.all(ids.map(id=>json(fetcher,`${BASE}/networks/campaigns/${id}?relationship=redirects`,{headers})as Promise<CampaignShape>)),...([false,true].map(events=>json(fetcher,`${BASE}/networks/reporting/entity/table`,{method:'POST',headers,body:JSON.stringify(body(events))})))])as[CampaignShape[],{table?:ReportRow[]},{table?:ReportRow[]}],allowed=new Set(ids.map(String)),filterRows=(rows:ReportRow[])=>(rows||[]).filter(row=>{const affiliate=row.columns.find(c=>c.column_type==='affiliate'),campaign=row.columns.find(c=>c.column_type==='campaign');if(affiliate&&String(affiliate.id)!==affiliateId)throw new Error('Everflow Affiliate-Filter wurde ignoriert');return campaign&&allowed.has(String(campaign.id))});const base=filterRows(baseResponse.table||[]),events=filterRows(eventResponse.table||[]),affiliateName=(base[0]||events[0])?.columns.find(c=>c.column_type==='affiliate')?.label||`Affiliate #${affiliateId}`;return campaigns.map(c=>{const id=String(c.network_campaign_id);return buildSmartlinkInsight(c,base.filter(r=>r.columns.find(x=>x.column_type==='campaign')?.id===id),events.filter(r=>r.columns.find(x=>x.column_type==='campaign')?.id===id),now,{affiliateId:Number(affiliateId),affiliate:affiliateName})})}
export async function loadSmartlinkInsight(campaignId:number,apiKey:string,fetcher:Fetcher=fetch,now=new Date()){
 if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');if(!Number.isInteger(campaignId)||campaignId<=0)throw new Error('Ungültige Campaign-ID');const headers={'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'};const to=berlinDay(now),end=Date.parse(`${to}T00:00:00Z`),from=new Date(end-14*86400000).toISOString().slice(0,10);const filter=[{resource_type:'campaign',filter_id_value:String(campaignId)}];const body=(events:boolean)=>({from,to,timezone_id:80,currency_id:'EUR',columns:['campaign','affiliate','offer','offer_url','hour',...(events?['event_name']:[])].map(column=>({column})),query:{filters:filter,search_terms:[]}});
 const [campaign,baseResponse,eventResponse]=await Promise.all([json(fetcher,`${BASE}/networks/campaigns/${campaignId}?relationship=redirects`,{headers}),...([false,true].map(events=>json(fetcher,`${BASE}/networks/reporting/entity/table`,{method:'POST',headers,body:JSON.stringify(body(events))})))]) as [CampaignShape,{table?:ReportRow[]},{table?:ReportRow[]}];
 if(Number(campaign.network_campaign_id)!==campaignId)throw new Error('Unerwartete Campaign');return buildSmartlinkInsight(campaign,baseResponse.table||[],eventResponse.table||[],now);
}
export type CampaignSearchItem={network_campaign_id:number;campaign_name:string;campaign_status:string};
export async function searchCampaigns(term:string,apiKey:string,fetcher:Fetcher=fetch):Promise<CampaignSearchItem[]>{if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');const data=await json(fetcher,`${BASE}/networks/campaigns`,{headers:{'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'}}) as {campaigns?:CampaignSearchItem[]};const q=term.trim().toLowerCase(),exact=/^\d+$/.test(q)?Number(q):null;const matches=(data.campaigns||[]).filter(c=>exact!==null?c.network_campaign_id===exact:c.campaign_name.toLowerCase().includes(q)).sort((a,b)=>(a.campaign_status==='active'?0:1)-(b.campaign_status==='active'?0:1)||a.network_campaign_id-b.network_campaign_id);return q?matches.slice(0,20):matches}
