import{SourceBlockActivationCompensatedError,type NormalizedSourceBlock,type EverflowBlockVariable}from'./source-blocks';
const BASE='https://api.eflow.team/v1';
type Fetcher=typeof fetch;
type EverflowPayload=ReturnType<typeof buildEverflowBlockPayload>;
type SettingSummary={network_custom_payout_revenue_setting_id:number;network_affiliate_ids?:number[];network_offer_id:number;name?:string;custom_setting_status?:string;is_custom_payout_enabled?:boolean;payout_amount?:number;is_postback_disabled?:boolean};
type EverflowRuleset=Record<string,unknown>;
type SettingDetail=SettingSummary&EverflowPayload&{relationship?:{variables?:{entries?:Array<EverflowBlockVariable&Record<string,unknown>>};ruleset?:EverflowRuleset}};
const headers=(apiKey:string)=>({'X-Eflow-API-Key':apiKey,'Content-Type':'application/json'});
async function json<T>(fetcher:Fetcher,url:string,init:RequestInit,expected:number[]=[200]){const response=await fetcher(url,{...init,signal:AbortSignal.timeout(30_000)});const text=await response.text();if(!expected.includes(response.status))throw new Error(`Everflow HTTP ${response.status}: ${text.slice(0,250)}`);return(text?JSON.parse(text):{})as T}
const emptyRuleset={platforms:[],device_types:[],os_versions:[],browsers:[],languages:[],countries:[],regions:[],cities:[],dmas:[],mobile_carriers:[],connection_types:[],ips:[],isps:[],brands:[],postal_codes:[],is_block_proxy:false,is_use_day_parting:false,day_parting_apply_to:'null_value',day_parting_timezone_id:0,days_parting:[]};
const safeName=(value:string)=>value.replace(/[\r\n]/g,' ').slice(0,120);
export function buildEverflowBlockPayload(block:NormalizedSourceBlock,dashboardId:string,ruleset:EverflowRuleset=emptyRuleset){return{network_offer_payout_revenue_id:0,network_offer_id:block.offerId,name:safeName(`[Dashboard-Sperre] ${dashboardId} · ${block.level==='sub_source'?(block.subValue||'Unterquelle'):(block.mainValue||'ohne Hauptquelle')}`),custom_setting_status:'active',is_apply_all_affiliates:false,network_affiliate_ids:[block.affiliateId],is_custom_payout_enabled:true,payout_type:'cpa',payout_amount:0,payout_percentage:0,is_custom_revenue_enabled:false,revenue_type:'blank',revenue_amount:0,revenue_percentage:0,is_postback_disabled:true,description:safeName(`Dashboard-Sperre: ${block.reason||'Partner wurde über Abschaltung informiert'}`),public_description:'',date_valid_from:'',date_valid_to:'',is_apply_specific_offer_urls:false,network_offer_url_ids:[],ruleset,variables:block.variables}}
const normalizedVariables=(items:Array<EverflowBlockVariable&Record<string,unknown>>=[])=>items.map(item=>({variable:item.variable,variable_value:item.variable_value,variable_secondary_value:item.variable_secondary_value||'',comparison_method:item.comparison_method})).sort((a,b)=>`${a.variable}\0${a.variable_value}`.localeCompare(`${b.variable}\0${b.variable_value}`));
const variablesEqual=(left:Array<EverflowBlockVariable&Record<string,unknown>>|undefined,right:EverflowBlockVariable[])=>JSON.stringify(normalizedVariables(left))===JSON.stringify(normalizedVariables(right));
const cleanRuleset=(value:EverflowRuleset|undefined):EverflowRuleset=>Object.fromEntries(Object.entries(emptyRuleset).map(([key,fallback])=>{const raw=value?.[key];if(!Array.isArray(fallback))return[key,raw??fallback];const entries=Array.isArray(raw)?raw:[];return[key,entries.map(entry=>{if(!entry||typeof entry!=='object')return entry;return Object.fromEntries(Object.entries(entry).filter(([field])=>!field.startsWith('network_')&&!field.startsWith('time_')&&field!=='label'&&field!=='country_code').sort(([left],[right])=>left.localeCompare(right)))}).sort((left,right)=>JSON.stringify(left).localeCompare(JSON.stringify(right)))]}));
const rulesetSignature=(value:EverflowRuleset|undefined)=>JSON.stringify(cleanRuleset(value));
const isDangerousGeneralSetting=(detail:SettingDetail)=>detail.network_offer_payout_revenue_id===0&&detail.custom_setting_status==='active'&&!normalizedVariables(detail.relationship?.variables?.entries).length&&(Number(detail.payout_amount)>0||Number(detail.payout_percentage)>0||detail.is_postback_disabled!==true);
const priorityRuleset=(details:SettingDetail[])=>{const dangerous=details.filter(isDangerousGeneralSetting),bySignature=new Map(dangerous.map(detail=>[rulesetSignature(detail.relationship?.ruleset),cleanRuleset(detail.relationship?.ruleset)]));if(bySignature.size>1)throw new Error('Mehrere vergütete Everflow-Targetingsegmente können mit einer einzelnen Quellen-Sperre nicht sicher übersteuert werden. Keine Änderung durchgeführt.');return bySignature.values().next().value??cleanRuleset(emptyRuleset)};
async function setting(fetcher:Fetcher,id:number,apiKey:string){return json<SettingDetail>(fetcher,`${BASE}/networks/custom/payoutrevenue/${id}?relationship=all`,{headers:headers(apiKey)})}
async function deleteSettingVerified(fetcher:Fetcher,id:number,apiKey:string){await json(fetcher,`${BASE}/networks/custom/payoutrevenue/${id}`,{method:'DELETE',headers:headers(apiKey)});const check=await fetcher(`${BASE}/networks/custom/payoutrevenue/${id}?relationship=all`,{headers:headers(apiKey),signal:AbortSignal.timeout(30_000)});if(check.status!==404)throw new Error(`Everflow-Regel ${id} ist nach DELETE weiterhin vorhanden (HTTP ${check.status})`)}
async function exactSettings(block:NormalizedSourceBlock,apiKey:string,fetcher:Fetcher){const rows:SettingSummary[]=[];for(let page=1;;page++){const result=await json<{custom_payout_revenue_settings?:SettingSummary[];paging?:{total_count?:number}}>(fetcher,`${BASE}/networks/custom/payoutrevenuetable?page=${page}&page_size=100&relationship=all`,{method:'POST',headers:headers(apiKey),body:JSON.stringify({search_terms:[],filters:{network_affiliate_ids:[block.affiliateId],network_offer_ids:[block.offerId]}})}),batch=(result.custom_payout_revenue_settings||[]).filter(row=>row.network_offer_id===block.offerId&&(row.network_affiliate_ids||[]).includes(block.affiliateId));rows.push(...batch);if((result.custom_payout_revenue_settings||[]).length<100||rows.length>=Number(result.paging?.total_count||0))break}return rows}
function exactBlockScope(detail:SettingDetail,block:NormalizedSourceBlock){const affiliates=detail.network_affiliate_ids||[],offerUrls=detail.network_offer_url_ids||[];return detail.is_apply_all_affiliates===false&&affiliates.length===1&&affiliates[0]===block.affiliateId&&detail.is_apply_specific_offer_urls===false&&offerUrls.length===0&&!String(detail.date_valid_from??'').trim()&&!String(detail.date_valid_to??'').trim()}
function verify(detail:SettingDetail,block:NormalizedSourceBlock){return detail.network_offer_id===block.offerId&&exactBlockScope(detail,block)&&detail.network_offer_payout_revenue_id===0&&detail.custom_setting_status==='active'&&detail.is_custom_payout_enabled===true&&detail.payout_type==='cpa'&&Number(detail.payout_amount)===0&&Number(detail.payout_percentage)===0&&detail.is_postback_disabled===true&&variablesEqual(detail.relationship?.variables?.entries,block.variables)}
export async function activateEverflowSourceBlock(block:NormalizedSourceBlock,dashboardId:string,apiKey:string,fetcher:Fetcher=fetch){
 if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');
 const matches=await exactSettings(block,apiKey,fetcher),details:SettingDetail[]=[];
 for(const summary of matches)details.push(await setting(fetcher,summary.network_custom_payout_revenue_setting_id,apiKey));
 const baseDetails=details.filter(detail=>detail.network_offer_payout_revenue_id===0),matching=baseDetails.filter(detail=>variablesEqual(detail.relationship?.variables?.entries,block.variables)),matchingIds=new Set(matching.map(detail=>detail.network_custom_payout_revenue_setting_id)),requiredRuleset=priorityRuleset(baseDetails.filter(detail=>!matchingIds.has(detail.network_custom_payout_revenue_setting_id)));
 if(matching.length){
  const allConsistent=matching.every(detail=>verify(detail,block)&&rulesetSignature(detail.relationship?.ruleset)===rulesetSignature(requiredRuleset));
  if(!allConsistent)throw new Error('Für diese Quellenkombination existiert bereits eine widersprüchliche Everflow-Regel. Keine Änderung durchgeführt.');
  const existing=[...matching].sort((left,right)=>left.network_custom_payout_revenue_setting_id-right.network_custom_payout_revenue_setting_id)[0];
  return{settingId:existing.network_custom_payout_revenue_setting_id,created:false};
 }
 const payload=buildEverflowBlockPayload(block,dashboardId,requiredRuleset),created=await json<{network_custom_payout_revenue_setting_id?:number}>(fetcher,`${BASE}/networks/custom/payoutrevenue`,{method:'POST',headers:headers(apiKey),body:JSON.stringify(payload)}),id=Number(created.network_custom_payout_revenue_setting_id);
 if(!Number.isSafeInteger(id)||id<=0)throw new Error('Everflow hat keine gültige Setting-ID zurückgegeben');
 try{
  const detail=await setting(fetcher,id,apiKey);
  if(!verify(detail,block)||rulesetSignature(detail.relationship?.ruleset)!==rulesetSignature(requiredRuleset))throw new Error('Everflow-Verifikation der Quellen-Sperre fehlgeschlagen');
  let tableVerified=false;
  for(let attempt=0;attempt<3&&!tableVerified;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,300*attempt));const visible=await exactSettings(block,apiKey,fetcher);tableVerified=visible.some(item=>item.network_custom_payout_revenue_setting_id===id)}
  if(!tableVerified)throw new Error('Everflow-Tabellenverifikation der Quellen-Sperre fehlgeschlagen');
  return{settingId:id,created:true};
 }catch(error){
  try{await deleteSettingVerified(fetcher,id,apiKey)}catch(rollbackError){throw new Error(`Quellen-Sperre fehlgeschlagen; Zustand unklar: ${rollbackError instanceof Error?rollbackError.message:'Rollback konnte nicht verifiziert werden'}`,{cause:error})}
  throw new SourceBlockActivationCompensatedError(error instanceof Error?error.message:'Everflow-Aktivierung fehlgeschlagen und wurde zurückgerollt',{cause:error});
 }
}
export async function deactivateEverflowSourceBlock(settingId:number,apiKey:string,fetcher:Fetcher=fetch){if(!Number.isSafeInteger(settingId)||settingId<=0)throw new Error('Ungültige Everflow-Setting-ID');if(!apiKey)throw new Error('EVERFLOW_API_KEY fehlt');await deleteSettingVerified(fetcher,settingId,apiKey);return{deleted:true}}
