import {createCipheriv,createDecipheriv,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
import {withSecurityLock,type SecurityStore} from './security';
type MfaRecord={state:'pending'|'enabled';ciphertext:string;iv:string;tag:string;lastCounter:number;createdAt:number};
const BASE32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',storeKey=(userId:string)=>`rbac:mfa:${userId}`;
const encryptionKey=(value:string)=>{let key:Buffer;try{key=/^[a-f\d]{64}$/i.test(value)?Buffer.from(value,'hex'):Buffer.from(value,'base64')}catch{key=Buffer.alloc(0)}if(key.length!==32)throw new Error('MFA_ENCRYPTION_KEY muss 32 Byte (Base64 oder Hex) enthalten');return key};
const base32Encode=(input:Buffer)=>{let bits=0,value=0,out='';for(const byte of input){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=BASE32[(value>>>(bits-5))&31];bits-=5}}if(bits)out+=BASE32[(value<<(5-bits))&31];return out};
const base32Decode=(input:string)=>{let bits=0,value=0;const out:number[]=[];for(const char of input.replace(/=+$/,'').toUpperCase()){const index=BASE32.indexOf(char);if(index<0)throw new Error('Ungültiges TOTP-Secret');value=(value<<5)|index;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}}return Buffer.from(out)};
const encrypt=(secret:string,keyText:string,userId:string):Pick<MfaRecord,'ciphertext'|'iv'|'tag'>=>{const key=encryptionKey(keyText),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from(userId));const ciphertext=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return{ciphertext:ciphertext.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64')}};
const decrypt=(record:MfaRecord,keyText:string,userId:string)=>{const decipher=createDecipheriv('aes-256-gcm',encryptionKey(keyText),Buffer.from(record.iv,'base64'));decipher.setAAD(Buffer.from(userId));decipher.setAuthTag(Buffer.from(record.tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(record.ciphertext,'base64')),decipher.final()]).toString('utf8')};
const record=(v:unknown):v is MfaRecord=>Boolean(v)&&typeof v==='object'&&((v as MfaRecord).state==='pending'||(v as MfaRecord).state==='enabled')&&typeof (v as MfaRecord).ciphertext==='string';
export function totpCode(secret:string,epochSeconds=Math.floor(Date.now()/1000),digits=6){const counter=Math.floor(epochSeconds/30),message=Buffer.alloc(8);message.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',base32Decode(secret)).update(message).digest(),offset=digest[digest.length-1]&15,value=(digest.readUInt32BE(offset)&0x7fffffff)%10**digits;return String(value).padStart(digits,'0')}
const matches=(secret:string,code:string,now:number,lastCounter=-1)=>{if(!/^\d{6}$/.test(code))return null;for(let drift=-1;drift<=1;drift++){const at=now+drift*30,counter=Math.floor(at/30),expected=Buffer.from(totpCode(secret,at));const supplied=Buffer.from(code);if(counter>lastCounter&&expected.length===supplied.length&&timingSafeEqual(expected,supplied))return counter}return null};
export async function beginMfaEnrollment(store:SecurityStore,userId:string,keyText:string,now=Math.floor(Date.now()/1000)){encryptionKey(keyText);const existing=await store.get(storeKey(userId));if(record(existing)&&existing.state==='enabled')throw new Error('Ein aktiver MFA-Faktor darf nicht überschrieben werden');const secret=base32Encode(randomBytes(20)),sealed=encrypt(secret,keyText,userId);await store.set(storeKey(userId),{state:'pending',...sealed,lastCounter:-1,createdAt:now} satisfies MfaRecord);return{secret,otpauth:`otpauth://totp/WLX:${encodeURIComponent(userId)}?secret=${secret}&issuer=WLX&algorithm=SHA1&digits=6&period=30`};}
export async function confirmMfaEnrollment(store:SecurityStore,userId:string,code:string,keyText:string,now=Math.floor(Date.now()/1000)){const raw=await store.get(storeKey(userId));if(!record(raw)||raw.state!=='pending')return false;const counter=matches(decrypt(raw,keyText,userId),code,now);if(counter===null)return false;await store.set(storeKey(userId),{...raw,state:'enabled',lastCounter:counter});return true;}
export async function verifyMfaChallenge(store:SecurityStore,userId:string,code:string,keyText:string,now=Math.floor(Date.now()/1000)){try{return await withSecurityLock(store,`mfa-challenge:${userId}`,async()=>{const raw=await store.get(storeKey(userId));if(!record(raw)||raw.state!=='enabled')return false;const counter=matches(decrypt(raw,keyText,userId),code,now,raw.lastCounter);if(counter===null)return false;await store.set(storeKey(userId),{...raw,lastCounter:counter});return true})}catch{return false}}
export async function disableMfa(store:SecurityStore,userId:string,code:string,keyText:string,now=Math.floor(Date.now()/1000)){if(!await verifyMfaChallenge(store,userId,code,keyText,now))return false;await store.delete(storeKey(userId));return true;}
/** Administrative recovery path. Authorization, hierarchy checks, audit, and session revocation belong to the caller. */
export async function resetMfa(store:SecurityStore,userId:string){await store.delete(storeKey(userId));}
export async function hasMfa(store:SecurityStore,userId:string){const raw=await store.get(storeKey(userId));return record(raw)&&raw.state==='enabled';}
