import 'server-only';
import{safeNotificationPath}from'./push-notifications';

const ENDPOINT='https://api.onesignal.com/notifications',MAX_RESPONSE_BYTES=16_384;
type OneSignalInput={userId:string;title:string;body:string;path?:string};
type PublicConfig={appId:string;origin:string};
type RuntimeConfig=PublicConfig&{enabled:boolean;restApiKey:string;fetch?:typeof fetch};
const bounded=(value:string,max:number,label:string)=>{if(!value||value.length>max||/[\u0000-\u001f\u007f]/.test(value))throw new Error(`Ungültiges OneSignal-${label}`);return value};
const validAppId=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const validRestKey=(value:unknown):value is string=>typeof value==='string'&&value===value.trim()&&/^\S{32,512}$/.test(value);
function canonicalOrigin(value:string){let url:URL;try{url=new URL(value)}catch{throw new Error('Ungültiger OneSignal-Origin')}if(url.protocol!=='https:'||url.pathname!=='/'||url.search||url.hash||url.username||url.password)throw new Error('Ungültiger OneSignal-Origin');return url.origin}
async function boundedResponse(response:Response){const declared=response.headers.get('content-length');if(declared!==null&&(!/^(0|[1-9]\d*)$/.test(declared)||Number(declared)>MAX_RESPONSE_BYTES))return null;if(!response.body)return'';const reader=response.body.getReader(),chunks:Uint8Array[]=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>MAX_RESPONSE_BYTES){await reader.cancel();return null}chunks.push(value)}}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{try{await reader.cancel()}catch{}return null}}
export function oneSignalConfigured(config:Partial<RuntimeConfig>={enabled:process.env.ONESIGNAL_ENABLED==='true',appId:process.env.ONESIGNAL_APP_ID,restApiKey:process.env.ONESIGNAL_REST_API_KEY,origin:process.env.APP_ORIGIN,fetch:globalThis.fetch}){try{return Boolean(config.enabled===true&&validAppId(config.appId)&&validRestKey(config.restApiKey)&&config.origin&&canonicalOrigin(config.origin))}catch{return false}}
export function buildOneSignalMessage(input:OneSignalInput,config:PublicConfig){if(!validAppId(config.appId))throw new Error('Ungültige OneSignal-App-ID');const userId=bounded(input.userId,128,'Empfänger'),title=bounded(input.title,100,'Titel'),body=bounded(input.body,240,'Inhalt'),origin=canonicalOrigin(config.origin),requested=input.path||'/',path=safeNotificationPath(requested);if(path!==requested)throw new Error('Ungültiger OneSignal-Pfad');return{app_id:config.appId,target_channel:'push' as const,include_aliases:{external_id:[userId]},headings:{de:title},contents:{de:body},url:new URL(path,origin).toString()}}
export async function sendOneSignalPush(input:OneSignalInput,config:RuntimeConfig={enabled:process.env.ONESIGNAL_ENABLED==='true',appId:process.env.ONESIGNAL_APP_ID||'',restApiKey:process.env.ONESIGNAL_REST_API_KEY||'',origin:process.env.APP_ORIGIN||'',fetch:globalThis.fetch}){if(!oneSignalConfigured(config))throw new Error('OneSignal ist nicht konfiguriert');const request=config.fetch||globalThis.fetch;try{const response=await request(ENDPOINT,{method:'POST',headers:{Authorization:`Key ${config.restApiKey}`,'Content-Type':'application/json'},body:JSON.stringify(buildOneSignalMessage(input,config)),signal:AbortSignal.timeout(10_000)});if(!response.ok)return{ok:false as const,status:response.status};const text=await boundedResponse(response);if(text===null)return{ok:false as const,status:502};let value:unknown;try{value=JSON.parse(text)}catch{return{ok:false as const,status:502}}const id=value&&typeof value==='object'&&'id'in value&&typeof value.id==='string'?value.id:null;return id?{ok:true as const,id}:{ok:false as const,status:502}}catch{return{ok:false as const,status:503}}}
