import{describe,expect,it,vi}from'vitest';
import{bindOneSignalIdentity,detachOneSignalIdentity}from'./onesignal-browser';

describe('OneSignal shared-browser identity lifecycle',()=>{
 it('detaches the previous external_id before binding another account',async()=>{const calls:string[]=[],sdk={logout:vi.fn(async()=>{calls.push('logout')}),login:vi.fn(async(id:string)=>{calls.push(`login:${id}`)})};await bindOneSignalIdentity(sdk,{previousBinding:'app:user-a',desiredBinding:'app:user-b',externalId:'user-b'});expect(calls).toEqual(['logout','login:user-b'])});
 it('detaches a provider identity after reload even when volatile binding state was lost',async()=>{const calls:string[]=[],sdk={logout:vi.fn(async()=>{calls.push('logout')}),login:vi.fn(async(id:string)=>{calls.push(`login:${id}`)})};await bindOneSignalIdentity(sdk,{desiredBinding:'app:user-b',externalId:'user-b'});expect(calls).toEqual(['logout','login:user-b'])});
 it('clears the local binding only after provider logout succeeds',async()=>{const state:{__wlxOneSignalBinding?:string}={__wlxOneSignalBinding:'app:user-a'},sdk={logout:vi.fn(async()=>{})};await detachOneSignalIdentity(sdk,state);expect(sdk.logout).toHaveBeenCalledOnce();expect(state.__wlxOneSignalBinding).toBeUndefined()});
 it('logs out the provider even when no volatile binding marker exists',async()=>{const state:Record<string,never>={},sdk={logout:vi.fn(async()=>{})};await detachOneSignalIdentity(sdk,state);expect(sdk.logout).toHaveBeenCalledOnce()});
 it('detaches a durable provider identity when an authenticated session expires before another login',async()=>{const calls:string[]=[],sdk={logout:vi.fn(async()=>{calls.push('logout')}),login:vi.fn(async(id:string)=>{calls.push(`login:${id}`)})},state:{__wlxOneSignalBinding?:string}={};await bindOneSignalIdentity(sdk,{desiredBinding:'app:user-a',externalId:'user-a'});state.__wlxOneSignalBinding='app:user-a';await detachOneSignalIdentity(sdk,state);expect(calls).toEqual(['logout','login:user-a','logout']);expect(state.__wlxOneSignalBinding).toBeUndefined()});
});
