import 'server-only';
import{createHash,ECDH,randomUUID}from'node:crypto';
import webpush from'web-push';
import{securityStore,type SyncStateSecurityStore}from'./access-store';
import{automationScopeAllowed,mayConfigureAutomation}from'./automation-policy';
import{resolveStoredAccessFromStore,resolveStoredAccessMetadata,type AccessMetadata}from'./rbac';
import{withSecurityLock}from'./security';
import{getSupabaseAdmin}from'./supabase';

export type PushSubscriptionRecord={endpoint:string;expirationTime:number|null;keys:{p256dh:string;auth:string}};
type EndpointOwner={version:2;userId:string;subscription:PushSubscriptionRecord;createdAt:string;userAgent:string};
type StoredPushSubscription=EndpointOwner;
type PushAudience={affiliateId:number;campaignId:number;offerIds:number[]};
type PushPayload={title:string;body:string;path?:string;tag?:string};
type PushOutboxRecord={version:1;dedupeId:string;payload:PushPayload;audience:PushAudience;createdAt:string;attempts:number;cursor:string|null};
type PushOutboxDelivered={version:2;createdAt:string;deliveredAt:string};
type PushOutboxDeadLetter={version:3;dedupeId:string;payload:PushPayload;audience:PushAudience;createdAt:string;failedAt:string;attempts:number};
type PushOutboxQuarantined={version:4;quarantinedAt:string;reason:'malformed'};
export type PushDispatchDependencies={ensureTransport:()=>void;loadAccess:(userId:string,store:SyncStateSecurityStore)=>Promise<AccessMetadata|null>;deliver:(userId:string,record:StoredPushSubscription,payload:PushPayload,store:SyncStateSecurityStore)=>Promise<{ok:true}|{ok:false;status?:number}>};
const PREFIX='push:subscription:v2:',ENDPOINT_OWNER_PREFIX='push:endpoint-owner:v2:',OUTBOX_PREFIX='push:outbox:v1:',MAX_DEVICES=5;
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const userPrefix=(userId:string)=>`${PREFIX}${hash(userId)}:`;
const endpointOwnerKey=(endpoint:string)=>`${ENDPOINT_OWNER_PREFIX}${hash(endpoint)}`;

export function normalizePushSubscription(input:unknown):PushSubscriptionRecord{
 if(!input||typeof input!=='object')throw new Error('Ungültige Push-Subscription');
 const value=input as{endpoint?:unknown;expirationTime?:unknown;keys?:{p256dh?:unknown;auth?:unknown}};
 if(typeof value.endpoint!=='string'||value.endpoint.length>2048)throw new Error('Ungültiger Push-Endpunkt');
 let url:URL;try{url=new URL(value.endpoint)}catch{throw new Error('Ungültiger Push-Endpunkt')}
 if(url.protocol!=='https:')throw new Error('Push-Endpunkt muss HTTPS verwenden');
 if(url.username||url.password||url.hash||(url.port&&url.port!=='443'))throw new Error('Ungültiger Push-Endpunkt');
 const host=url.hostname.toLowerCase(),trusted=host==='fcm.googleapis.com'||host.endsWith('.push.services.mozilla.com')||host==='push.services.mozilla.com'||host.endsWith('.push.apple.com')||host==='push.apple.com'||host.endsWith('.notify.windows.com')||host==='notify.windows.com';
 if(!trusted)throw new Error('Unbekannter Push-Dienst');
 const p256dh=value.keys?.p256dh,auth=value.keys?.auth;
 const decode=(key:string)=>Buffer.from(key.replace(/-/g,'+').replace(/_/g,'/').replace(/=+$/,''),'base64'),decodedP256dh=typeof p256dh==='string'?decode(p256dh):Buffer.alloc(0),decodedAuth=typeof auth==='string'?decode(auth):Buffer.alloc(0);
 if(typeof p256dh!=='string'||typeof auth!=='string'||!/^[-_A-Za-z0-9]+=*$/.test(p256dh)||!/^[-_A-Za-z0-9]+=*$/.test(auth)||decodedP256dh.length!==65||decodedAuth.length!==16||decodedP256dh[0]!==4)throw new Error('Ungültige Push-Schlüssel');
 try{ECDH.convertKey(decodedP256dh,'prime256v1')}catch{throw new Error('Ungültige Push-Schlüssel')}
 let expirationTime:number|null=null;
 if(value.expirationTime!==undefined&&value.expirationTime!==null){if(typeof value.expirationTime!=='number'||!Number.isSafeInteger(value.expirationTime)||value.expirationTime<=Date.now()||value.expirationTime>Date.now()+10*365*24*60*60_000)throw new Error('Ungültiger Ablaufzeitpunkt');expirationTime=value.expirationTime}
 return{endpoint:url.toString(),expirationTime,keys:{p256dh,auth}};
}
export function pushSubscriptionKey(userId:string,endpoint:string){return`${userPrefix(userId)}${hash(endpoint)}`}
export function safeNotificationPath(path:unknown){return typeof path==='string'&&path.startsWith('/')&&!path.startsWith('//')&&!path.includes('\\')&&!/[\u0000-\u001f\u007f]/.test(path)&&!/%(?:2f|5c)/i.test(path)?path:'/'}
function vapid(){const subject=process.env.VAPID_SUBJECT||'mailto:admin@me-media.com',publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY||'',privateKey=process.env.VAPID_PRIVATE_KEY||'';if(!publicKey||!privateKey)throw new Error('Push-Benachrichtigungen sind nicht konfiguriert');webpush.setVapidDetails(subject,publicKey,privateKey);return publicKey}
export function publicVapidKey(){return vapid()}

export async function listSyncStatePrefix<T>(prefix:string){const rows:Array<{key:string;value:T}>=[],client=getSupabaseAdmin();let cursor='';for(;;){let query=client.from('sync_state').select('key,value').like('key',`${prefix}%`).order('key').limit(500);if(cursor)query=query.gt('key',cursor);const{data,error}=await query;if(error)throw new Error('Push-Status nicht verfügbar');const batch=(data||[])as Array<{key:string;value:T}>;rows.push(...batch);if(batch.length<500)break;cursor=batch[batch.length-1].key}return rows}
async function listSyncStatePage<T>(prefix:string,afterKey:string|null,limit:number){const client=getSupabaseAdmin();let query=client.from('sync_state').select('key,value').like('key',`${prefix}%`).order('key').limit(limit);if(afterKey)query=query.gt('key',afterKey);const{data,error}=await query;if(error)throw new Error('Push-Status nicht verfügbar');return(data||[])as Array<{key:string;value:T}>}
async function ownerRows(userId:string,store:SyncStateSecurityStore){if(store!==securityStore())return(await store.list(ENDPOINT_OWNER_PREFIX)as Array<{key:string;value:StoredPushSubscription}>).filter(row=>row.value?.version===2&&row.value.userId===userId);const rows:Array<{key:string;value:StoredPushSubscription}>=[],client=getSupabaseAdmin();let cursor='';for(;;){let query=client.from('sync_state').select('key,value').like('key',`${ENDPOINT_OWNER_PREFIX}%`).eq('value->>userId',userId).order('key').limit(100);if(cursor)query=query.gt('key',cursor);const{data,error}=await query;if(error)throw new Error('Push-Status nicht verfügbar');const batch=(data||[])as Array<{key:string;value:StoredPushSubscription}>;rows.push(...batch);if(batch.length<100)break;cursor=batch[batch.length-1].key}return rows}
export async function listPushSubscriptions(userId:string,store:SyncStateSecurityStore=securityStore()){return ownerRows(userId,store)}
const userBoundary=(userId:string,store:SyncStateSecurityStore,operation:()=>Promise<unknown>)=>withSecurityLock(store,`push-subscriptions:${hash(userId)}`,operation,{leaseMs:30_000});
export async function savePushSubscription(userId:string,input:unknown,userAgent:string,store:SyncStateSecurityStore=securityStore(),authorize:()=>Promise<boolean>=async()=>true){const subscription=normalizePushSubscription(input),ownerKey=endpointOwnerKey(subscription.endpoint);return userBoundary(userId,store,async()=>{if(!await authorize())throw new Error('Push-Aktion ist nicht mehr autorisiert');const rows=await listPushSubscriptions(userId,store),existing=rows.some(row=>row.key===ownerKey);if(!existing&&rows.length>=MAX_DEVICES)throw new Error(`Maximal ${MAX_DEVICES} Geräte erlaubt`);return withSecurityLock(store,`push-endpoint:${hash(subscription.endpoint)}`,async()=>{if(!await authorize())throw new Error('Push-Aktion ist nicht mehr autorisiert');const record:StoredPushSubscription={version:2,userId,subscription,createdAt:new Date().toISOString(),userAgent:userAgent.slice(0,300)};await store.set(ownerKey,record);return record},{leaseMs:15_000})}) as Promise<StoredPushSubscription>}
export async function reconcilePushSubscription(userId:string,input:unknown,userAgent:string,store:SyncStateSecurityStore=securityStore(),authorize:()=>Promise<boolean>=async()=>true){return savePushSubscription(userId,input,userAgent,store,authorize)}
async function removePushSubscriptionUnlocked(userId:string,endpoint:string,store:SyncStateSecurityStore){return withSecurityLock(store,`push-endpoint:${hash(endpoint)}`,async()=>{const ownerKey=endpointOwnerKey(endpoint),owner=await store.get(ownerKey)as EndpointOwner|null;if(owner?.version!==2||owner.userId!==userId)return false;await store.delete(ownerKey);return true},{leaseMs:15_000})}
export async function removePushSubscription(userId:string,endpoint:string,store:SyncStateSecurityStore=securityStore()){return userBoundary(userId,store,()=>removePushSubscriptionUnlocked(userId,endpoint,store)) as Promise<boolean>}
export async function ownsPushEndpoint(userId:string,endpoint:string,store:SyncStateSecurityStore=securityStore()){return withSecurityLock(store,`push-endpoint:${hash(endpoint)}`,async()=>{const owner=await store.get(endpointOwnerKey(endpoint))as EndpointOwner|null;return owner?.version===2&&owner.userId===userId},{leaseMs:15_000})}
async function removeAllUnlocked(userId:string,store:SyncStateSecurityStore){const rows=await listPushSubscriptions(userId,store);for(const row of rows)await removePushSubscriptionUnlocked(userId,row.value.subscription.endpoint,store);return rows.length}
export async function removeAllPushSubscriptions(userId:string,store:SyncStateSecurityStore=securityStore()){return userBoundary(userId,store,()=>removeAllUnlocked(userId,store)) as Promise<number>}
export async function withPushLogoutBoundary<T>(userId:string,operation:()=>Promise<T>,store:SyncStateSecurityStore=securityStore()){return userBoundary(userId,store,async()=>{await removeAllUnlocked(userId,store);return operation()}) as Promise<T>}
export async function rateLimitPushTest(userId:string,channel:'webpush'|'onesignal'='webpush',store:SyncStateSecurityStore=securityStore()){const now=Date.now();if(!await store.tryAcquireLease(`push:test-rate:v2:${hash(userId)}:${channel}`,randomUUID(),now+60_000,now))throw new Error('Bitte eine Minute bis zum nächsten Test warten')}
export async function rateLimitPushMutation(userId:string,action:string,store:SyncStateSecurityStore=securityStore()){const now=Date.now();if(!await store.tryAcquireLease(`push:mutation-rate:v1:${hash(userId)}:${hash(action)}`,randomUUID(),now+5_000,now))throw new Error('Bitte kurz bis zur nächsten Geräteänderung warten')}

function message(payload:PushPayload){return JSON.stringify({title:payload.title.slice(0,100),body:payload.body.slice(0,240),path:safeNotificationPath(payload.path),tag:(payload.tag||'wlx-alert').slice(0,80)})}
async function deliver(record:StoredPushSubscription,payload:PushPayload){try{await webpush.sendNotification(record.subscription,message(payload),{TTL:300,urgency:'high',timeout:10_000});return{ok:true as const}}catch(error){return{ok:false as const,status:(error as{statusCode?:number}).statusCode}}}
async function deliverOwned(userId:string,record:StoredPushSubscription,payload:PushPayload,store:SyncStateSecurityStore){const endpoint=record.subscription.endpoint;try{return await withSecurityLock(store,`push-endpoint:${hash(endpoint)}`,async()=>{const ownerKey=endpointOwnerKey(endpoint),current=await store.get(ownerKey)as EndpointOwner|null;if(current?.version!==2||current.userId!==userId)return{ok:false as const,status:404};const result=await deliver(current,payload);if(!result.ok&&(result.status===404||result.status===410))await store.delete(ownerKey);return result},{leaseMs:30_000})}catch{return{ok:false as const,status:undefined}}}
export async function sendPushToEndpoint(userId:string,endpoint:string,payload:PushPayload,store:SyncStateSecurityStore=securityStore()){vapid();const record=await store.get(endpointOwnerKey(endpoint))as StoredPushSubscription|null;if(record?.version!==2||record.userId!==userId)return{ok:false as const,status:404};return deliverOwned(userId,record,payload,store)}
export async function sendPushToUser(userId:string,payload:PushPayload,store:SyncStateSecurityStore=securityStore()){vapid();const rows=await listPushSubscriptions(userId,store);return Promise.all(rows.map(row=>deliverOwned(userId,row.value,payload,store)))}

export const resolveStoredPushAccess=resolveStoredAccessMetadata;
async function currentPushAccess(userId:string,store:SyncStateSecurityStore){const{data,error}=await getSupabaseAdmin().auth.admin.getUserById(userId);if(error||!data.user)return null;const bannedUntil=Date.parse(data.user.banned_until||'');if(Number.isFinite(bannedUntil)&&bannedUntil>Date.now())return null;return resolveStoredAccessFromStore(data.user.app_metadata,store)}
function normalizeOutbox(dedupeId:string,payload:PushPayload,audience:PushAudience){if(!dedupeId||dedupeId.length>200||/[\u0000-\u001f\u007f]/.test(dedupeId))throw new Error('Ungültige Push-Dedupe-ID');const text=(value:unknown,max:number,label:string)=>{if(typeof value!=='string'||!value||value.length>max||/[\u0000-\u001f\u007f]/.test(value))throw new Error(`Ungültiger Push-${label}`);return value},requested=payload.path||'/',path=safeNotificationPath(requested);if(path!==requested)throw new Error('Ungültiger Push-Pfad');const integer=(value:unknown)=>typeof value==='number'&&Number.isSafeInteger(value)&&value>0;if(!integer(audience.affiliateId)||!integer(audience.campaignId)||!Array.isArray(audience.offerIds)||audience.offerIds.length>100||audience.offerIds.some(value=>!integer(value)))throw new Error('Ungültige Push-Audience');return{dedupeId,payload:{title:text(payload.title,100,'Titel'),body:text(payload.body,240,'Inhalt'),path,tag:payload.tag===undefined?'wlx-alert':text(payload.tag,80,'Tag')},audience:{affiliateId:audience.affiliateId,campaignId:audience.campaignId,offerIds:[...new Set(audience.offerIds)]}}}
const exactObject=(value:unknown,keys:string[]):value is Record<string,unknown>=>{if(value===null||typeof value!=='object'||Array.isArray(value))return false;const record=value as Record<string,unknown>;return Object.keys(record).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(record,key))};
function parsePendingOutbox(value:unknown):PushOutboxRecord|null{
 if(!exactObject(value,['version','dedupeId','payload','audience','createdAt','attempts','cursor'])||value.version!==1||typeof value.dedupeId!=='string'||!exactObject(value.payload,['title','body','path','tag'])||!exactObject(value.audience,['affiliateId','campaignId','offerIds']))return null;
 const payload=value.payload,audience=value.audience,offerIds=audience.offerIds;
 if(!Array.isArray(offerIds))return null;
 let normalized;
 try{normalized=normalizeOutbox(value.dedupeId,payload as PushPayload,audience as PushAudience)}catch{return null}
 if(normalized.payload.title!==payload.title||normalized.payload.body!==payload.body||normalized.payload.path!==payload.path||normalized.payload.tag!==payload.tag||normalized.audience.affiliateId!==audience.affiliateId||normalized.audience.campaignId!==audience.campaignId||normalized.audience.offerIds.length!==offerIds.length||normalized.audience.offerIds.some((item,index)=>item!==offerIds[index]))return null;
 const createdAt=typeof value.createdAt==='string'?Date.parse(value.createdAt):NaN;
 if(!Number.isFinite(createdAt)||new Date(createdAt).toISOString()!==value.createdAt||createdAt<Date.UTC(2020,0,1)||createdAt>Date.now()+3_600_000||!Number.isSafeInteger(value.attempts)||Number(value.attempts)<0||Number(value.attempts)>2)return null;
 const cursor=value.cursor;
 if(cursor!==null&&(typeof cursor!=='string'||!new RegExp(`^${ENDPOINT_OWNER_PREFIX}[0-9a-f]{64}$`).test(cursor)))return null;
 return{version:1,...normalized,createdAt:value.createdAt,attempts:Number(value.attempts),cursor:cursor as string|null};
}
export async function enqueuePushAlert(dedupeId:string,payload:PushPayload,audience:PushAudience,store:SyncStateSecurityStore=securityStore()){const normalized=normalizeOutbox(dedupeId,payload,audience),now=Date.now(),key=`${OUTBOX_PREFIX}${hash(normalized.dedupeId)}`;return withSecurityLock(store,`push-outbox-enqueue:${hash(normalized.dedupeId)}`,async()=>{const current=await store.get(key)as PushOutboxRecord|PushOutboxDelivered|PushOutboxDeadLetter|null;if(current?.version===1||current?.version===3&&Date.parse(current.failedAt)>now-60*60_000||current?.version===2&&Date.parse(current.deliveredAt)>now-60*60_000)return false;const record:PushOutboxRecord={version:1,...normalized,createdAt:new Date(now).toISOString(),attempts:0,cursor:null};await store.set(key,record);return true},{leaseMs:5_000})}
async function listSubscriptionPage(store:SyncStateSecurityStore,afterKey:string|null,limit:number){if(store===securityStore())return listSyncStatePage<StoredPushSubscription>(ENDPOINT_OWNER_PREFIX,afterKey,limit);return(await store.list(ENDPOINT_OWNER_PREFIX)as Array<{key:string;value:StoredPushSubscription}>).filter(row=>!afterKey||row.key>afterKey).sort((a,b)=>a.key.localeCompare(b.key)).slice(0,limit)}
async function sendPushAlertPage(record:PushOutboxRecord,store:SyncStateSecurityStore,deps:PushDispatchDependencies){deps.ensureTransport();const rows=await listSubscriptionPage(store,record.cursor,50),access=new Map<string,ReturnType<PushDispatchDependencies['loadAccess']>>();let sent=0,failed=0;for(let start=0;start<rows.length;start+=5){const batch=await Promise.all(rows.slice(start,start+5).map(async row=>{const subscription=row.value;if(subscription?.version!==2)return{sent:0,failed:0};let current=access.get(subscription.userId);if(!current){current=deps.loadAccess(subscription.userId,store);access.set(subscription.userId,current)}const userAccess=await current;if(!userAccess||!mayConfigureAutomation(userAccess)||!automationScopeAllowed(userAccess,record.audience))return{sent:0,failed:0};const result=await deps.deliver(subscription.userId,subscription,record.payload,store);return result.ok?{sent:1,failed:0}:result.status===404||result.status===410?{sent:0,failed:0}:{sent:0,failed:1}}));sent+=batch.reduce((sum,value)=>sum+value.sent,0);failed+=batch.reduce((sum,value)=>sum+value.failed,0)}return{sent,failed,done:rows.length<50,cursor:rows.at(-1)?.key||record.cursor}}
async function nextPendingOutbox(store:SyncStateSecurityStore){if(store!==securityStore())return(await store.list(OUTBOX_PREFIX)).find(item=>(item.value as{version?:unknown})?.version===1)as{key:string;value:PushOutboxRecord}|undefined;const{data,error}=await getSupabaseAdmin().from('sync_state').select('key,value').like('key',`${OUTBOX_PREFIX}%`).eq('value->>version','1').order('key').limit(1).maybeSingle();if(error)throw new Error('Push-Outbox nicht verfügbar');return data as{key:string;value:PushOutboxRecord}|null}
export async function dispatchPushOutbox(store:SyncStateSecurityStore=securityStore(),overrides:Partial<PushDispatchDependencies>={}){const deps:PushDispatchDependencies={ensureTransport:vapid,loadAccess:currentPushAccess,deliver:deliverOwned,...overrides};const row=await nextPendingOutbox(store);if(!row)return[];const fail=async(current:PushOutboxRecord)=>{if(current.attempts<2){await store.set(row.key,{...current,attempts:current.attempts+1});return}const failedAt=new Date().toISOString(),dead:PushOutboxDeadLetter={version:3,dedupeId:current.dedupeId,payload:current.payload,audience:current.audience,createdAt:current.createdAt,failedAt,attempts:current.attempts+1};await store.set(row.key,dead)};try{return await withSecurityLock(store,`push-outbox:${hash(row.key)}`,async()=>{const raw=await store.get(row.key) as unknown;if(raw===null||typeof raw!=='object'||Array.isArray(raw)||!Object.prototype.hasOwnProperty.call(raw,'version')||(raw as{version?:unknown}).version!==1)return[{key:row.key,sent:0,ok:false}];const current=parsePendingOutbox(raw);if(!current){const quarantine:PushOutboxQuarantined={version:4,quarantinedAt:new Date().toISOString(),reason:'malformed'};await store.set(row.key,quarantine);return[{key:row.key,sent:0,ok:false}]}try{const delivery=await sendPushAlertPage(current,store,deps),result={key:row.key,sent:delivery.sent,ok:delivery.failed===0};if(delivery.failed){await fail(current);return[result]}if(delivery.done)await store.set(row.key,{version:2,createdAt:current.createdAt,deliveredAt:new Date().toISOString()} satisfies PushOutboxDelivered);else await store.set(row.key,{...current,cursor:delivery.cursor,attempts:0});return[result]}catch{await fail(current);return[{key:row.key,sent:0,ok:false}]}},{leaseMs:240_000})}catch{return[{key:row.key,sent:0,ok:false}]}}
