export type RebillEvent={type:'first_sale'|'rebill';customerId:string|null;convertedAt:string;campaignId:string;offerId:string;offerUrlId:string};
export type RebillScope={campaignId?:string;offerId?:string;offerUrlId?:string};
export type RebillConcentrationStatus='none'|'broad'|'slight'|'strong'|'critical'|'unavailable';
export type RebillSample='none'|'very_low'|'provisional'|'stable';
export type RebillCustomerShare={customer:string;rebills:number;share:number};
export type RebillConcentration={firstSales:number;firstSaleCustomers:number;totalRebills:number;rebillCustomers:number;averagePerFirstSale:number|null;averagePerRebillCustomer:number|null;topCustomers:RebillCustomerShare[];topOneShare:number;topTwoShare:number;hhi:number;effectiveCustomers:number;status:RebillConcentrationStatus;sample:RebillSample;coverageComplete:boolean;firstSaleCoverageComplete:boolean;customerAverageComplete:boolean};
const round=(value:number,digits=2)=>Number(value.toFixed(digits));
const BERLIN_DAY_FORMATTER=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'});
const berlinDay=(value:string)=>BERLIN_DAY_FORMATTER.format(new Date(value));
type CustomerBuckets={byCampaign:Map<string,Array<string|null>>;byPath:Map<string,Array<string|null>>};
export type RebillCustomerIndex={rebills:CustomerBuckets;firstSales:CustomerBuckets};
const emptyBuckets=():CustomerBuckets=>({byCampaign:new Map(),byPath:new Map()});
const add=(buckets:CustomerBuckets,event:RebillEvent)=>{const campaign=buckets.byCampaign.get(event.campaignId)||[];campaign.push(event.customerId);buckets.byCampaign.set(event.campaignId,campaign);const key=`${event.campaignId}|${event.offerId}|${event.offerUrlId}`,path=buckets.byPath.get(key)||[];path.push(event.customerId);buckets.byPath.set(key,path)};
export function buildRebillCustomerIndex(events:RebillEvent[],range:{from:string;to:string}):RebillCustomerIndex{const index={rebills:emptyBuckets(),firstSales:emptyBuckets()};for(const event of events){const day=berlinDay(event.convertedAt);if(day<range.from||day>range.to)continue;add(event.type==='rebill'?index.rebills:index.firstSales,event)}return index}
const idsForScope=(buckets:CustomerBuckets,scope:RebillScope)=>scope.offerId||scope.offerUrlId?buckets.byPath.get(`${scope.campaignId||'0'}|${scope.offerId||'0'}|${scope.offerUrlId||'0'}`)||[]:scope.campaignId?buckets.byCampaign.get(scope.campaignId)||[]:[];
export function rebillCustomerIdsFromIndex(index:RebillCustomerIndex,scope:RebillScope){return idsForScope(index.rebills,scope)}
export function firstSaleCustomerIdsFromIndex(index:RebillCustomerIndex,scope:RebillScope){return idsForScope(index.firstSales,scope)}
export function rebillCustomerIdsForScope(events:RebillEvent[],range:{from:string;to:string},scope:RebillScope){return rebillCustomerIdsFromIndex(buildRebillCustomerIndex(events,range),scope)}
export function analyzeRebillConcentration(input:{firstSales:number;totalRebills:number;customerIds:Array<string|null|undefined>;firstSaleCustomerIds?:Array<string|null|undefined>}):RebillConcentration{
 const firstSales=Math.max(0,Number(input.firstSales)||0),totalRebills=Math.max(0,Number(input.totalRebills)||0),valid=input.customerIds.filter((id):id is string=>typeof id==='string'&&id.trim().length>0),coverageComplete=valid.length===totalRebills;
 const validFirstSales=(input.firstSaleCustomerIds||[]).filter((id):id is string=>typeof id==='string'&&id.trim().length>0),firstSaleSet=new Set(validFirstSales),firstSaleCustomers=firstSaleSet.size,firstSaleCoverageComplete=validFirstSales.length===firstSales&&firstSaleCustomers===firstSales,customerAverageComplete=coverageComplete&&firstSaleCoverageComplete&&valid.every(id=>firstSaleSet.has(id));
 const counts=new Map<string,number>();for(const id of valid)counts.set(id,(counts.get(id)||0)+1);
 const rankedCounts=[...counts.values()].sort((a,b)=>b-a),topCustomers=rankedCounts.map((rebills,index)=>({customer:`Kunde #${index+1}`,rebills,share:totalRebills?round(100*rebills/totalRebills):0})),rebillCustomers=counts.size,topOneShare=topCustomers[0]?.share||0,topTwoShare=round(100*((topCustomers[0]?.rebills||0)+(topCustomers[1]?.rebills||0))/(totalRebills||1));
 let status:RebillConcentrationStatus='none';if(!coverageComplete)status='unavailable';else if(totalRebills){if(topOneShare>=60||topTwoShare>=80)status='critical';else if(topOneShare>=40||topTwoShare>=60)status='strong';else if(topOneShare>=25||topTwoShare>=40)status='slight';else status='broad'}
 const sample:RebillSample=!totalRebills?'none':rebillCustomers<3?'very_low':firstSaleCustomers<5?'provisional':'stable',hhi=totalRebills?round(rankedCounts.reduce((sum,count)=>sum+(count/totalRebills)**2,0),4):0,effectiveCustomers=hhi?round(1/hhi,2):0;
 return{firstSales,firstSaleCustomers,totalRebills,rebillCustomers:coverageComplete?rebillCustomers:0,averagePerFirstSale:customerAverageComplete&&firstSaleCustomers?round(totalRebills/firstSaleCustomers):null,averagePerRebillCustomer:coverageComplete&&rebillCustomers?round(totalRebills/rebillCustomers):null,topCustomers:coverageComplete?topCustomers.slice(0,5):[],topOneShare:coverageComplete?topOneShare:0,topTwoShare:coverageComplete?topTwoShare:0,hhi:coverageComplete?hhi:0,effectiveCustomers:coverageComplete?effectiveCustomers:0,status,sample,coverageComplete,firstSaleCoverageComplete,customerAverageComplete}
}
