import type{RebillEvent}from'./rebill-concentration';
import type{ConversionCacheRow}from'./history-cache';
const DAY=86_400_000,shift=(day:string,count:number)=>new Date(Date.parse(`${day}T00:00:00Z`)+count*DAY).toISOString().slice(0,10),days=(from:string,to:string)=>{const result:string[]=[];for(let day=from;day<=to;day=shift(day,1))result.push(day);return result};
type SnapshotEvent={i:string;t:'first_sale'|'rebill';l:string;d:string;c:string;o:string;u:string;s:string;ss:string};
export type RebillDaySnapshot={version:1;affiliateId:string;date:string;events:SnapshotEvent[]};
export type RebillDaySnapshotRecord={key:string;value:RebillDaySnapshot};
const key=(affiliateId:string,date:string)=>`rebill_day_v1:${affiliateId}:${date}`;
export const clampRebillSnapshotRange=(range:{from:string;to:string},availableThrough:string)=>({...range,to:range.to<availableThrough?range.to:availableThrough});
export function buildRebillDaySnapshots(rows:ConversionCacheRow[],range:{from:string;to:string},affiliateId:string):RebillDaySnapshotRecord[]{const byDay=new Map<string,SnapshotEvent[]>();for(const row of rows){if(row.affiliate_id!==affiliateId||(row.type!=='first_sale'&&row.type!=='rebill')||(row.status!==null&&row.status!=='approved'))continue;const date=row.converted_at.slice(0,10);if(date<range.from||date>range.to)continue;const events=byDay.get(date)||[];events.push({i:row.id,t:row.type,l:row.lead_id,d:row.converted_at,c:row.campaign_id||'0',o:row.offer_id||'0',u:row.offer_url_id||'0',s:row.source_id?.trim()||'',ss:row.sub_source?.trim()||''});byDay.set(date,events)}return days(range.from,range.to).map(date=>({key:key(affiliateId,date),value:{version:1,affiliateId,date,events:byDay.get(date)||[]}}))}
export function decodeCompleteRebillDaySnapshots(records:RebillDaySnapshotRecord[],affiliateId:string,range:{from:string;to:string}):{complete:boolean;events:RebillEvent[]}{const byDate=new Map(records.filter(record=>record.value?.version===1&&record.value.affiliateId===affiliateId).map(record=>[record.value.date,record.value]));if(days(range.from,range.to).some(date=>!byDate.has(date)))return{complete:false,events:[]};const seen=new Set<string>(),events:RebillEvent[]=[];for(const date of days(range.from,range.to))for(const event of byDate.get(date)?.events||[]){if(seen.has(event.i))continue;seen.add(event.i);events.push({type:event.t,customerId:event.l?.trim()||null,convertedAt:event.d,campaignId:event.c,offerId:event.o,offerUrlId:event.u,sourceId:event.s,subSource:event.ss})}return{complete:true,events:events.sort((a,b)=>a.convertedAt.localeCompare(b.convertedAt))}}
export const rebillDaySnapshotKeyRange=(affiliateId:string,range:{from:string;to:string})=>({from:key(affiliateId,range.from),to:key(affiliateId,range.to)});
