import {beforeEach,describe,expect,it,vi} from 'vitest';
import type {ConversionCacheRow} from './history-cache';
import {createSupabaseSyncStore} from './supabase';
import {publishRebillDaySnapshots,loadCompleteRebillDaySnapshot} from './rebill-event-snapshot-store';
import {rebillQueryEnvelope} from './rebill-concentration-query';

const memory=vi.hoisted(()=>({states:new Map<string,unknown>(),conversions:[] as Array<Record<string,unknown>>,failDelete:false,writes:0}));
vi.mock('@supabase/supabase-js',()=>({createClient:()=>({from:(table:string)=>{
 const filters:Array<(row:Record<string,unknown>)=>boolean>=[];let offset=0,end=999,deleting=false;
 const field=(row:Record<string,unknown>,key:string)=>key==='value->>date'?(row.value as {date?:string})?.date:row[key];
 const execute=()=>{const data=(table==='sync_state'?[...memory.states].map(([key,value])=>({key,value})):memory.conversions).filter(row=>filters.every(test=>test(row))).slice(offset,end+1);if(deleting){if(memory.failDelete)return{data:null,error:{message:'invalidation unavailable'}};for(const row of data)memory.states.delete(String(row.key))}return{data,error:null}};
 const q={select:()=>q,delete:()=>{deleting=true;end=Infinity;return q},order:()=>q,eq:(key:string,value:unknown)=>{filters.push(row=>field(row,key)===value);return q},gte:(key:string,value:string)=>{filters.push(row=>String(field(row,key))>=value);return q},lte:(key:string,value:string)=>{filters.push(row=>String(field(row,key))<=value);return q},lt:(key:string,value:string)=>{filters.push(row=>String(field(row,key))<value);return q},or:()=>q,range:(from:number,to:number)=>{offset=from;end=to;return Promise.resolve(execute())},then:(resolve:(value:unknown)=>unknown)=>Promise.resolve(execute()).then(resolve),upsert:async(records:Array<Record<string,unknown>>)=>{if(table==='conversions'){memory.writes++;for(const record of records){memory.conversions=memory.conversions.filter(row=>row.id!==record.id);memory.conversions.push(record)}}else for(const record of records)memory.states.set(String(record.key),record.value);return{error:null}}};return q;
},rpc:async(_name:string,args:{p_rows:unknown[]})=>{memory.writes++;return{data:args.p_rows.length,error:null}}})}));
const event=(id:string,time:string)=>({id,type:'rebill',converted_at:time,affiliate_id:'6',lead_id:`lead-${id}`,status:'approved',traffic_mode:'tracked_direct',source_id:'source',sub_source:'sub',offer_id:'8',offer_url_id:'1',campaign_id:'0'}) as ConversionCacheRow;
const load=()=>loadCompleteRebillDaySnapshot('6',rebillQueryEnvelope({from:'2026-07-02',to:'2026-07-02'}),new Date('2026-07-10T12:00Z'));
beforeEach(()=>{vi.stubEnv('SUPABASE_URL','https://example.invalid');vi.stubEnv('SUPABASE_SERVICE_ROLE_KEY','fixture');memory.states.clear();memory.conversions=[];memory.failDelete=false;memory.writes=0;for(let day=1;day<=5;day++){const date=`2026-07-0${day}`;memory.states.set(`portfolio_day_generation:${date}`,{version:5,timezoneId:56,date,generation:`initial-${day}`})}});
async function seed(){memory.conversions=[event('initial','2026-07-02T12:00:00.000Z') as unknown as Record<string,unknown>];await publishRebillDaySnapshots(memory.conversions as unknown as ConversionCacheRow[],{from:'2026-07-01',to:'2026-07-05'},'6');expect((await load()).complete).toBe(true)}
describe('conversion writes invalidate Rebill fast paths',()=>{
 it('rejects a previously complete cache after one Berlin day adds an event',async()=>{await seed();const rows=[event('new','2026-07-02T14:00:00.000Z')];await createSupabaseSyncStore().upsertConversions(rows);await publishRebillDaySnapshots(rows,{from:'2026-07-02',to:'2026-07-02'},'6');expect(await load()).toEqual({complete:false,events:[]})});
 it('invalidates both UTC edges of an empty Berlin replacement',async()=>{await seed();await createSupabaseSyncStore().replaceConversions!('2026-07-02','2026-07-02',[]);expect(memory.states.has('rebill_day_berlin_v4:6:2026-07-01')).toBe(false);expect(memory.states.has('rebill_day_berlin_v4:6:2026-07-02')).toBe(false);expect(memory.states.has('rebill_day_berlin_v4:6:2026-07-03')).toBe(true)});
 it('does not write conversions when invalidation fails',async()=>{await seed();memory.failDelete=true;await expect(createSupabaseSyncStore().upsertConversions([event('new','2026-07-02T14:00:00.000Z')])).rejects.toThrow('invalidation unavailable');expect(memory.writes).toBe(0)});
 it('can publish fresh complete UTC buckets after a wider successful import',async()=>{await seed();const rows=[event('new','2026-07-02T14:00:00.000Z')];await createSupabaseSyncStore().upsertConversions(rows);await publishRebillDaySnapshots(rows,{from:'2026-07-01',to:'2026-07-03'},'6');const result=await load();expect(result.complete).toBe(true);expect(result.events.map(row=>row.customerId).sort()).toEqual(['lead-initial','lead-new'])});
});
