import'server-only';
import{unstable_cache}from'next/cache';
import{getSupabaseAdmin}from'./supabase';
import type{AccessMetadata}from'./rbac';
import type{RebillEvent}from'./rebill-concentration';
import{mapStoredRebillEvent,rebillEventsForAccess,rebillQueryChunks,rebillQueryEnvelope,type StoredRebillEvent}from'./rebill-concentration-query';
async function loadChunk(affiliateId:string,chunk:{from:string;toExclusive:string}){const events:RebillEvent[]=[];for(let start=0;;start+=1000){const{data,error}=await getSupabaseAdmin().from('conversions').select('type,lead_id,converted_at,campaign_id,offer_id,offer_url_id,source_id,sub_source,status').eq('affiliate_id',affiliateId).in('type',['first_sale','rebill']).gte('converted_at',chunk.from).lt('converted_at',chunk.toExclusive).or('status.eq.approved,status.is.null').order('converted_at').order('id').range(start,start+999);if(error)throw new Error(`Supabase Rebill-Verteilung: ${error.message}`);const rows=(data||[])as StoredRebillEvent[];events.push(...rows.map(mapStoredRebillEvent).filter((row):row is RebillEvent=>row!==null));if(rows.length<1000)break}return events}
async function loadAffiliateRebillEvents(affiliateId:string,range:{from:string;to:string}){if(!/^\d+$/.test(affiliateId))throw new Error('Ungültige Affiliate-ID');const chunks=rebillQueryChunks(rebillQueryEnvelope(range)),events:RebillEvent[]=[];for(let start=0;start<chunks.length;start+=4){const batches=await Promise.all(chunks.slice(start,start+4).map(chunk=>loadChunk(affiliateId,chunk)));for(const batch of batches)events.push(...batch)}return events}
const cachedAffiliateRebillEvents=(affiliateId:string,range:{from:string;to:string})=>unstable_cache(()=>loadAffiliateRebillEvents(affiliateId,range),['affiliate-rebill-events-v3',affiliateId,range.from,range.to],{revalidate:300,tags:[`affiliate-rebills-${affiliateId}`]})();
export async function getAffiliateRebillEvents(affiliateId:string,range:{from:string;to:string},access:AccessMetadata){return rebillEventsForAccess(await cachedAffiliateRebillEvents(affiliateId,range),affiliateId,access)}
