import'server-only';
import{unstable_cache}from'next/cache';
import{getSupabaseAdmin}from'./supabase';
import type{AccessMetadata}from'./rbac';
import type{RebillEvent}from'./rebill-concentration';
import{mapStoredRebillEvent,rebillEventsForAccess,rebillQueryEnvelope,rebillQuerySegments,type StoredRebillEvent}from'./rebill-concentration-query';
import{loadCompleteRebillDaySnapshot}from'./rebill-event-snapshot-store';
async function loadSegment(affiliateId:string,segment:{from:string;toExclusive:string;type:'first_sale'|'rebill'}){const events:RebillEvent[]=[];for(let start=0;;start+=1000){const{data,error}=await getSupabaseAdmin().from('conversions').select('type,lead_id,converted_at,campaign_id,offer_id,offer_url_id,traffic_mode,source_id,sub_source,status').eq('affiliate_id',affiliateId).eq('type',segment.type).gte('converted_at',segment.from).lt('converted_at',segment.toExclusive).or('status.eq.approved,status.is.null').order('converted_at').order('id').range(start,start+999);if(error)throw new Error(`Supabase Rebill-Verteilung: ${error.message}`);const rows=(data||[])as StoredRebillEvent[];events.push(...rows.map(mapStoredRebillEvent).filter((row):row is RebillEvent=>row!==null));if(rows.length<1000)break}return events}
async function loadAffiliateRebillEvents(affiliateId:string,range:{from:string;to:string}){if(!/^\d+$/.test(affiliateId))throw new Error('Ungültige Affiliate-ID');const envelope=rebillQueryEnvelope(range),snapshot=await loadCompleteRebillDaySnapshot(affiliateId,envelope);if(snapshot.complete)return snapshot.events;const segments=rebillQuerySegments(envelope),events:RebillEvent[]=[];for(let start=0;start<segments.length;start+=4){const batches=await Promise.all(segments.slice(start,start+4).map(segment=>loadSegment(affiliateId,segment)));for(const batch of batches)events.push(...batch)}return events.sort((a,b)=>a.convertedAt.localeCompare(b.convertedAt))}
const cachedAffiliateRebillEvents=(affiliateId:string,range:{from:string;to:string})=>unstable_cache(()=>loadAffiliateRebillEvents(affiliateId,range),['affiliate-rebill-events-v5',affiliateId,range.from,range.to],{revalidate:3600,tags:[`affiliate-rebills-${affiliateId}`]})();
export async function getAffiliateRebillEvents(affiliateId:string,range:{from:string;to:string},access:AccessMetadata){return rebillEventsForAccess(await cachedAffiliateRebillEvents(affiliateId,range),affiliateId,access)}
