import {assertBerlinReportingRange} from './berlin-reporting-contract';
import'server-only';
import{getSupabaseAdmin}from'./supabase';
import{buildRebillDaySnapshots,completeUtcDaysWithinBerlinRange,clampRebillSnapshotRange,decodeCompleteRebillDaySnapshots,rebillDaySnapshotKeyRange,type RebillDaySnapshotRecord}from'./rebill-event-snapshots';
import type{ConversionCacheRow}from'./history-cache';
const shift=(day:string,count:number)=>new Date(Date.parse(`${day}T00:00:00Z`)+count*86_400_000).toISOString().slice(0,10);
const eventFields='id,type,converted_at,offer_url_id,source_id,sub_source,lead_id,status,affiliate_id,offer_id,campaign_id,traffic_mode';
async function canonicalRows(affiliateId:string,range:{from:string;to:string}){const rows:ConversionCacheRow[]=[],toExclusive=shift(range.to,1);for(const type of ['first_sale','rebill']as const)for(let start=0;;start+=1000){const{data,error}=await getSupabaseAdmin().from('conversions').select(eventFields).eq('affiliate_id',affiliateId).eq('type',type).gte('converted_at',`${range.from}T00:00:00Z`).lt('converted_at',`${toExclusive}T00:00:00Z`).or('status.is.null,status.eq.approved').order('converted_at').order('id').range(start,start+999);if(error)throw new Error(`Supabase Rebill-Tagescache: ${error.message}`);const batch=(data||[])as unknown as ConversionCacheRow[];rows.push(...batch.map(row=>({...row,raw:{},cost:0,revenue:0,payout:0,affiliate_name:null,offer_name:null,offer_url_name:null,campaign_name:null})));if(batch.length<1000)break}return rows}
export async function publishRebillDaySnapshots(rows:ConversionCacheRow[],range:{from:string;to:string},affiliateId?:string){const complete=completeUtcDaysWithinBerlinRange(range);if(!complete)return{affiliates:0,days:0};range=complete;const proofs=await assertBerlinReportingRange(getSupabaseAdmin(),{from:range.from,to:shift(range.to,1)});const proof=(date:string)=>JSON.stringify([proofs.get(date)?.generation,proofs.get(shift(date,1))?.generation]);const affiliateIds=affiliateId?[affiliateId]:[...new Set(rows.map(row=>row.affiliate_id).filter((id):id is string=>Boolean(id)))];let days=0;for(const id of affiliateIds){const records=buildRebillDaySnapshots(await canonicalRows(id,range),range,id).map(record=>({...record,value:{...record.value,proof:proof(record.value.date)}}));if(records.length>31)throw new Error('Rebill-Tagescache darf höchstens 31 Tage atomar veröffentlichen');const{error}=await getSupabaseAdmin().from('sync_state').upsert(records);if(error)throw new Error(`Supabase Rebill-Tagescache: ${error.message}`);days+=records.length}return{affiliates:affiliateIds.length,days}}
export async function loadCompleteRebillDaySnapshot(affiliateId:string,envelope:{from:string;toExclusive:string},now=new Date()){const range=clampRebillSnapshotRange({from:envelope.from.slice(0,10),to:shift(envelope.toExclusive.slice(0,10),-1)},now.toISOString().slice(0,10)),keys=rebillDaySnapshotKeyRange(affiliateId,range),{data,error}=await getSupabaseAdmin().from('sync_state').select('key,value').gte('key',keys.from).lte('key',keys.to).order('key');if(error)throw new Error(`Supabase Rebill-Tagescache: ${error.message}`);let proofs;try{proofs=await assertBerlinReportingRange(getSupabaseAdmin(),{from:range.from,to:shift(range.to,1)})}catch{return{complete:false,events:[]}}const records=((data||[])as RebillDaySnapshotRecord[]).filter(record=>record.value?.proof===JSON.stringify([proofs.get(record.value.date)?.generation,proofs.get(shift(record.value.date,1))?.generation]));return decodeCompleteRebillDaySnapshots(records,affiliateId,range)}
