import {randomBytes,createHash} from 'node:crypto';
export const COOKIE_NAME='wlx_session';
export const IDLE_SECONDS=1_800,ABSOLUTE_SECONDS=43_200;
export const SESSION_SECURITY_VERSION=2;
export const MAX_ACTIVE_SESSIONS=10;
export type SessionRecord={userId:string;actorId?:string;metadataVersion:number;mfaSetupOnly?:boolean;securityVersion:number;createdAt:number;lastSeenAt:number;expiresAt:number;userRevocationVersion?:string;actorRevocationVersion?:string};
export interface SecurityStore{get(key:string):Promise<unknown|null>;set(key:string,value:unknown):Promise<void>;setIfAbsent(key:string,value:unknown):Promise<boolean>;tryAcquireLease(key:string,owner:string,expiresAt:number,now:number):Promise<boolean>;renewLease(key:string,owner:string,expiresAt:number,now:number):Promise<boolean>;deleteIfOwner(key:string,owner:string):Promise<boolean>;delete(key:string):Promise<void>;list(prefix:string):Promise<Array<{key:string;value:unknown}>>;listBefore(prefix:string,beforeKey:string,limit:number):Promise<Array<{key:string;value:unknown}>>}
export class MemorySecurityStore implements SecurityStore{values=new Map<string,unknown>();async get(k:string){return this.values.get(k)??null}async set(k:string,v:unknown){this.values.set(k,v)}async setIfAbsent(k:string,v:unknown){if(this.values.has(k))return false;this.values.set(k,v);return true}async tryAcquireLease(k:string,owner:string,expiresAt:number,now:number){const current=this.values.get(k)as{expiresAt?:number}|undefined;if(current&&Number(current.expiresAt)>now)return false;this.values.set(k,{owner,expiresAt});return true}async renewLease(k:string,owner:string,expiresAt:number,now:number){const current=this.values.get(k)as{owner?:string;expiresAt?:number}|undefined;if(current?.owner!==owner||Number(current.expiresAt)<=now)return false;this.values.set(k,{owner,expiresAt});return true}async deleteIfOwner(k:string,owner:string){const current=this.values.get(k) as {owner?:string}|undefined;if(current?.owner!==owner)return false;this.values.delete(k);return true}async delete(k:string){this.values.delete(k)}async list(prefix:string){return [...this.values].filter(([k])=>k.startsWith(prefix)).map(([key,value])=>({key,value}))}async listBefore(prefix:string,beforeKey:string,limit:number){return(await this.list(prefix)).filter(row=>row.key<beforeKey).sort((a,b)=>a.key.localeCompare(b.key)).slice(0,limit)}}
const hash=(token:string)=>createHash('sha256').update(token).digest('hex');
const sessionKey=(token:string)=>`rbac:session:${hash(token)}`;
const sessionCleanupKey=(token:string)=>`rbac:session-cleanup:${hash(token)}`;
const revokedSessionKey=(token:string)=>`rbac:session-revoked:${hash(token)}`;
const SESSION_CLEANUP_EXPIRY_PREFIX='rbac:session-cleanup-expiry:';
const cleanupExpiryKey=(token:string,cleanupUntil:number)=>`${SESSION_CLEANUP_EXPIRY_PREFIX}${String(cleanupUntil).padStart(12,'0')}:${hash(token)}`;
type SessionCleanupExpiry={cleanupKey:string;cleanupUntil:number};
type SessionCleanupIdentity={userId:string;actorId:string;cleanupUntil:number};
const CLEANUP_RETENTION_SECONDS=30*24*60*60;
const cleanupIdentityKeyFromExpiryIndex=(key:string)=>{const match=key.match(/^rbac:session-cleanup-expiry:\d{12}:([a-f0-9]{64})$/);return match?`rbac:session-cleanup:${match[1]}`:null};
export async function pruneExpiredSessionCleanupIdentities(store:SecurityStore,now=Math.floor(Date.now()/1000),limit=100){const before=`${SESSION_CLEANUP_EXPIRY_PREFIX}${String(now).padStart(12,'0')}:`;const rows=await store.listBefore(SESSION_CLEANUP_EXPIRY_PREFIX,before,Math.max(1,Math.min(100,limit)));for(const row of rows){const cleanupKey=cleanupIdentityKeyFromExpiryIndex(row.key);if(!cleanupKey)continue;await store.delete(cleanupKey);await store.delete(row.key)}return rows.length}
const userRevocationKey=(userId:string)=>`rbac:user-revocation:${hash(userId)}`;
type SessionIndex={sessionKey:string;createdAt:number};
const userSessionPrefix=(userId:string)=>`rbac:user-session:${hash(userId)}:`;
const userSessionKey=(userId:string,storedKey:string)=>`${userSessionPrefix(userId)}${storedKey.slice('rbac:session:'.length)}`;
const isIndex=(value:unknown):value is SessionIndex=>Boolean(value)&&typeof value==='object'&&typeof (value as SessionIndex).sessionKey==='string';
async function deleteStoredSession(store:SecurityStore,key:string,record?:SessionRecord){const raw=record??await store.get(key);await store.delete(key);if(isRecord(raw)){await store.delete(userSessionKey(raw.userId,key));if(raw.actorId)await store.delete(userSessionKey(raw.actorId,key));}}
export async function createOpaqueSession(store:SecurityStore,input:{userId:string;actorId?:string;metadataVersion:number;mfaSetupOnly?:boolean;absoluteSeconds?:number},now=Math.floor(Date.now()/1000)){const token=randomBytes(32).toString('base64url'),storedKey=sessionKey(token),userRevocationVersion=String(await store.get(userRevocationKey(input.userId))??''),actorRevocationVersion=input.actorId?String(await store.get(userRevocationKey(input.actorId))??''):undefined,{absoluteSeconds=ABSOLUTE_SECONDS,...identity}=input,lifetime=Math.min(ABSOLUTE_SECONDS,Math.max(60,absoluteSeconds)),record:SessionRecord={...identity,securityVersion:SESSION_SECURITY_VERSION,createdAt:now,lastSeenAt:now,expiresAt:now+lifetime,userRevocationVersion,actorRevocationVersion},cleanupIdentity:SessionCleanupIdentity={userId:input.userId,actorId:input.actorId||input.userId,cleanupUntil:now+lifetime+CLEANUP_RETENTION_SECONDS},cleanupKey=sessionCleanupKey(token);await pruneExpiredSessionCleanupIdentities(store,now);await store.set(cleanupExpiryKey(token,cleanupIdentity.cleanupUntil),{cleanupKey,cleanupUntil:cleanupIdentity.cleanupUntil} satisfies SessionCleanupExpiry);await store.set(cleanupKey,cleanupIdentity);await store.set(storedKey,record);await store.set(userSessionKey(input.userId,storedKey),{sessionKey:storedKey,createdAt:now} satisfies SessionIndex);if(input.actorId)await store.set(userSessionKey(input.actorId,storedKey),{sessionKey:storedKey,createdAt:now} satisfies SessionIndex);const active=(await store.list(userSessionPrefix(input.userId))).filter(item=>isIndex(item.value)).sort((a,b)=>(a.value as SessionIndex).createdAt-(b.value as SessionIndex).createdAt);for(const item of active.slice(0,Math.max(0,active.length-MAX_ACTIVE_SESSIONS))){const indexed=item.value as SessionIndex;await deleteStoredSession(store,indexed.sessionKey);await store.delete(item.key)}return {token,record};}
const isRecord=(v:unknown):v is SessionRecord=>Boolean(v)&&typeof v==='object'&&typeof (v as SessionRecord).userId==='string'&&Number.isFinite((v as SessionRecord).lastSeenAt);
export async function validateOpaqueSession(store:SecurityStore,token:string|undefined,now=Math.floor(Date.now()/1000)){if(!token||token.length>200)return null;const key=sessionKey(token),revokedKey=revokedSessionKey(token);if(await store.get(revokedKey))return null;const raw=await store.get(key);if(!isRecord(raw))return null;if(raw.securityVersion!==SESSION_SECURITY_VERSION){await deleteStoredSession(store,key,raw);return null}const userVersion=String(await store.get(userRevocationKey(raw.userId))??''),actorVersion=raw.actorId?String(await store.get(userRevocationKey(raw.actorId))??''):undefined;if(userVersion!==(raw.userRevocationVersion??'')||actorVersion!==(raw.actorRevocationVersion??undefined)){await deleteStoredSession(store,key,raw);return null}if(now>raw.expiresAt||now-raw.lastSeenAt>IDLE_SECONDS){await deleteStoredSession(store,key,raw);return null;}const updated={...raw,lastSeenAt:now};await store.set(key,updated);const revokedAfter=await store.get(revokedKey),userAfter=String(await store.get(userRevocationKey(raw.userId))??''),actorAfter=raw.actorId?String(await store.get(userRevocationKey(raw.actorId))??''):undefined;if(revokedAfter||userAfter!==(raw.userRevocationVersion??'')||actorAfter!==(raw.actorRevocationVersion??undefined)){await deleteStoredSession(store,key,updated);return null}return updated;}
export async function revokeSession(store:SecurityStore,token:string|undefined){if(token){await store.set(revokedSessionKey(token),randomBytes(16).toString('hex'));await deleteStoredSession(store,sessionKey(token));}}
export async function resolveSessionCleanupIdentity(store:SecurityStore,token:string|undefined,now=Math.floor(Date.now()/1000)){if(!token||token.length>200)return null;const key=sessionCleanupKey(token),value=await store.get(key) as SessionCleanupIdentity|null;if(!value||typeof value.userId!=='string'||typeof value.actorId!=='string'||!Number.isFinite(value.cleanupUntil)){await store.delete(key);return null}if(now>value.cleanupUntil){await store.delete(key);await store.delete(cleanupExpiryKey(token,value.cleanupUntil));return null}return value}
export async function forgetSessionCleanupIdentity(store:SecurityStore,token:string|undefined){if(!token)return;const key=sessionCleanupKey(token),value=await store.get(key) as SessionCleanupIdentity|null;if(value&&Number.isFinite(value.cleanupUntil))await store.delete(cleanupExpiryKey(token,value.cleanupUntil));await store.delete(key)}
export async function revokeUserSessions(store:SecurityStore,userId:string){await store.set(userRevocationKey(userId),randomBytes(16).toString('hex'));for(const item of await store.list(userSessionPrefix(userId))){if(isIndex(item.value))await deleteStoredSession(store,item.value.sessionKey);await store.delete(item.key);}}
export function checkCsrf(request:Request,canonicalOrigin:string){if(['GET','HEAD','OPTIONS'].includes(request.method))return true;const site=request.headers.get('sec-fetch-site');if(site&&site!=='same-origin'&&site!=='same-site'&&site!=='none')return false;try{return new URL(request.headers.get('origin')||request.url).origin===new URL(canonicalOrigin).origin}catch{return false;}}
const rateGenerationKey=(id:string)=>`rbac:rate-generation:${hash(id)}`;
const ratePrefix=async(store:SecurityStore,id:string,now:number,windowSeconds:number)=>{const generation=String(await store.get(rateGenerationKey(id))??'0'),bucket=Math.floor(now/windowSeconds);return {prefix:`rbac:rate-slot:${hash(id)}:${generation}:${bucket}:`,bucket};};
/** Atomically reserves one of a small fixed number of slots before credential verification. A successful login resets the generation, so only failed attempts remain consumed. */
export async function consumeRateLimit(store:SecurityStore,id:string,now:number,limit=5,windowSeconds=900){const {prefix,bucket}=await ratePrefix(store,id,now,windowSeconds);for(let slot=0;slot<limit;slot++)if(await store.setIfAbsent(`${prefix}${slot}`,{at:now}))return {allowed:true,retryAfter:0};return {allowed:false,retryAfter:Math.max(1,(bucket+1)*windowSeconds-now)};}
export type RateLimitSpec={id:string;limit?:number;windowSeconds?:number};
/** Reserves every bucket or compensates this request's partial reservations. */
export async function consumeRateLimitsAtomically(store:SecurityStore,specs:RateLimitSpec[],now:number){
 const owner=randomBytes(16).toString('hex'),reservations:string[]=[];
 const rollback=async()=>{const keys=reservations.splice(0);let failed=false;for(const key of keys)if(!await store.deleteIfOwner(key,owner))failed=true;if(failed)throw new Error('Rate-Limit-Reservierung konnte nicht vollständig zurückgerollt werden')};
 try{
  for(const spec of specs){
   const limit=spec.limit??5,windowSeconds=spec.windowSeconds??900,{prefix,bucket}=await ratePrefix(store,spec.id,now,windowSeconds);let reserved=false;
   for(let slot=0;slot<limit;slot++){const key=`${prefix}${slot}`;if(await store.setIfAbsent(key,{at:now,owner})){reservations.push(key);reserved=true;break}}
   if(!reserved){await rollback();return{allowed:false,retryAfter:Math.max(1,(bucket+1)*windowSeconds-now)}}
  }
  return{allowed:true,retryAfter:0};
 }catch(error){if(reservations.length)await rollback();throw error}
}
export async function recordRateLimitFailure(store:SecurityStore,id:string,now:number,limit=5,windowSeconds=900){const {prefix}=await ratePrefix(store,id,now,windowSeconds);return Math.min((await store.list(prefix)).length,limit);}
export async function resetRateLimit(store:SecurityStore,id:string){await store.set(rateGenerationKey(id),randomBytes(16).toString('hex'));}
export type SecurityLease={owner:string;name:string;assertOwned:()=>Promise<void>;renew:()=>Promise<boolean>;release:()=>Promise<boolean>};
type LeaseOptions={leaseMs?:number;now?:()=>number};
export async function acquireSecurityLease(store:SecurityStore,name:string,options:LeaseOptions={}):Promise<SecurityLease|null>{
 const key=`rbac:lock:${hash(name)}`,owner=randomBytes(16).toString('hex'),leaseMs=Math.max(1000,options.leaseMs??30_000),now=options.now??Date.now;
 if(!await store.tryAcquireLease(key,owner,now()+leaseMs,now()))return null;
 const renew=()=>{const current=now();return store.renewLease(key,owner,current+leaseMs,current)};
 return{owner,name,renew,release:()=>store.deleteIfOwner(key,owner),assertOwned:async()=>{if(!await renew())throw new Error('Sicherheitskritische Sperre wurde verloren.')}};
}
export async function withSecurityLock<T>(store:SecurityStore,name:string,operation:(lease:SecurityLease)=>Promise<T>,options:LeaseOptions={}):Promise<T>{
 const lease=await acquireSecurityLease(store,name,options);if(!lease)throw new Error('Eine sicherheitskritische Änderung läuft bereits.');
 const leaseMs=Math.max(1000,options.leaseMs??30_000);let lost=false,renewing=false;
 const timer=setInterval(()=>{if(renewing)return;renewing=true;void lease.renew().then(ok=>{if(!ok)lost=true}).catch(()=>{lost=true}).finally(()=>{renewing=false})},Math.max(250,Math.floor(leaseMs/3)));
 try{const result=await operation(lease);if(lost)throw new Error('Sicherheitskritische Sperre wurde verloren.');await lease.assertOwned();return result}finally{clearInterval(timer);await lease.release()}
}
export function canonicalOrigin(configured:string|undefined,nodeEnv:string|undefined,requestUrl:string){if(configured){const parsed=new URL(configured);if(parsed.pathname!=='/'||parsed.search||parsed.hash)throw new Error('APP_ORIGIN muss ein Origin ohne Pfad sein');return parsed.origin;}if(nodeEnv==='production')throw new Error('APP_ORIGIN ist in Produktion erforderlich');return new URL(requestUrl).origin;}
export async function parseBoundedJson(request:Request,maxBytes=32_768){const header=request.headers.get('content-length');if(header!==null&&(!/^\d+$/.test(header)||Number(header)>maxBytes))throw new Error('Anfrage zu groß');const text=await request.text();if(Buffer.byteLength(text,'utf8')>maxBytes)throw new Error('Anfrage zu groß');let value:unknown;try{value=JSON.parse(text)}catch{throw new Error('Ungültiges JSON')}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Ungültiges JSON');return value as Record<string,unknown>;}
export const securityHeaders={'Cache-Control':'private, no-store','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'Strict-Transport-Security':'max-age=31536000; includeSubDomains','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()'} as const;
