import{isApiOffer}from'./affiliate-source-dimensions';
import type{SmartMetrics,SmartlinkReportRow,SmartlinkSourceBreakdown}from'./smartlink';

const blank=():SmartMetrics=>({clicks:0,sois:0,cvr:0,firstSales:0,firstSaleRate:0,rebills:0,coinSpend:0,revenue:0,payout:0,profit:0,profitEpc:0});
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;
const round=(value:number,digits=2)=>Number(value.toFixed(digits));
const finish=(metric:SmartMetrics):SmartMetrics=>({...metric,cvr:metric.clicks?round(100*metric.sois/metric.clicks):0,firstSaleRate:metric.sois?round(100*metric.firstSales/metric.sois):0,revenue:round(metric.revenue),payout:round(metric.payout),profit:round(metric.profit),profitEpc:metric.clicks?round(metric.profit/metric.clicks,3):0});
const add=(target:SmartMetrics,value:SmartMetrics)=>{for(const key of['clicks','sois','firstSales','rebills','coinSpend','revenue','payout','profit']as const)target[key]+=value[key];return target};
const subtract=(total:SmartMetrics,used:SmartMetrics)=>finish({...blank(),clicks:total.clicks-used.clicks,sois:total.sois-used.sois,firstSales:total.firstSales-used.firstSales,rebills:total.rebills-used.rebills,coinSpend:total.coinSpend-used.coinSpend,revenue:total.revenue-used.revenue,payout:total.payout-used.payout,profit:total.profit-used.profit});
const dim=(row:SmartlinkReportRow,type:string)=>row.columns.find(column=>column.column_type===type);
const rowMetric=(row:SmartlinkReportRow)=>{const metric=blank(),event=dim(row,'event_name')?.label,value=number(row.reporting.event);if(event==='Sale')metric.firstSales=value;else if(event==='Rebill')metric.rebills=value;else if(event==='Coin Spend')metric.coinSpend=value;else{metric.clicks=number(row.reporting.total_click);metric.sois=number(row.reporting.cv);metric.revenue=number(row.reporting.revenue);metric.payout=number(row.reporting.payout);metric.profit=number(row.reporting.profit??metric.revenue-metric.payout)}return metric};
export function summarizeSmartlinkRows(base:SmartlinkReportRow[],events:SmartlinkReportRow[]){return finish([...base,...events].reduce((sum,row)=>add(sum,rowMetric(row)),blank()))}
const berlinDay=(epoch:number)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(epoch*1000));
const rowDay=(row:SmartlinkReportRow)=>dim(row,'date')?.id||(()=>{const epoch=number(dim(row,'hour')?.id);return epoch?berlinDay(epoch):''})();

export type SelectedRangeAttribution={total:SmartMetrics;current:SmartMetrics;legacy:SmartMetrics;beforeRotation:SmartMetrics;transitionDay:SmartMetrics;unassigned:SmartMetrics;rotationDay:string|null;reconciled:boolean};
export function buildSelectedRangeAttribution({total,base,events,currentSlotIds,rotationStartEpoch}:{total:SmartMetrics;base:SmartlinkReportRow[];events:SmartlinkReportRow[];currentSlotIds:Set<string>;rotationStartEpoch:number|null}):SelectedRangeAttribution{
 const current=blank(),legacy=blank(),beforeRotation=blank(),transitionDay=blank(),unknown=blank(),rotationDay=rotationStartEpoch?berlinDay(rotationStartEpoch):null;
 for(const row of[...base,...events]){const metric=rowMetric(row),day=rowDay(row),url=dim(row,'offer_url')?.id||'';if(!rotationDay||!day){add(unknown,metric);continue}if(day<rotationDay)add(beforeRotation,metric);else if(day===rotationDay)add(transitionDay,metric);else if(currentSlotIds.has(url))add(current,metric);else if(url&&url!=='0')add(legacy,metric);else add(unknown,metric)}
 const known=finish([current,legacy,beforeRotation,transitionDay,unknown].reduce((sum,value)=>add(sum,value),blank())),difference=subtract(total,known),unassigned=finish(add(unknown,difference)),parts=finish([current,legacy,beforeRotation,transitionDay,unassigned].reduce((sum,value)=>add(sum,value),blank())),close=(a:number,b:number)=>Math.abs(a-b)<0.011;
 return{total:finish(total),current:finish(current),legacy:finish(legacy),beforeRotation:finish(beforeRotation),transitionDay:finish(transitionDay),unassigned,rotationDay,reconciled:(['clicks','sois','firstSales','rebills','coinSpend','revenue','payout','profit']as const).every(key=>close(parts[key],total[key]))}
}
export function reconcileSelectedRangeHeadline(attribution:SelectedRangeAttribution,headline:Partial<Pick<SmartMetrics,'clicks'|'sois'|'firstSales'|'rebills'|'coinSpend'|'revenue'|'payout'|'profit'>>){const total=finish({...attribution.total,...headline}),difference=subtract(total,attribution.total),unassigned=finish(add({...attribution.unassigned},difference)),parts=finish([attribution.current,attribution.legacy,attribution.beforeRotation,attribution.transitionDay,unassigned].reduce((sum,value)=>add(sum,value),blank())),close=(a:number,b:number)=>Math.abs(a-b)<0.011;return{...attribution,total,unassigned,reconciled:(['clicks','sois','firstSales','rebills','coinSpend','revenue','payout','profit']as const).every(key=>close(parts[key],total[key]))}}

export type SmartlinkSourceFact={metric_date?:string;offer_url_id:string;offer_id:string;offer_name:string;source_id:string;sub_source:string;clicks:number|string;sois:number|string;first_sales:number|string;rebills:number|string;coin_spend:number|string;payout:number|string;revenue:number|string;profit:number|string;raw?:{traffic_mode?:'api'|'tracked';adv1?:string;adv2?:string}|null};
const text=(value:unknown)=>{const result=String(value??'').trim();return result&&result.toUpperCase()!=='N/A'?result:'Nicht übermittelt'};
export function filterSmartlinkSourceFactsAfterDay<T extends{metric_date?:string}>(facts:T[],day:string|null){return day?facts.filter(fact=>Boolean(fact.metric_date&&fact.metric_date>day)):facts}
export function groupSmartlinkSources(facts:SmartlinkSourceFact[]){const grouped=new Map<string,Map<string,SmartlinkSourceBreakdown>>();for(const fact of facts){const mode=fact.raw?.traffic_mode||(isApiOffer(fact.offer_name)?'api':'tracked'),source=text(mode==='api'?fact.raw?.adv1:fact.source_id),subSource=text(mode==='api'?fact.raw?.adv2:fact.sub_source),bySource=grouped.get(fact.offer_url_id)||new Map<string,SmartlinkSourceBreakdown>(),key=`${mode}\u0000${source}\u0000${subSource}`,current=bySource.get(key)||{mode,source,subSource,clicks:0,sois:0,cvr:mode==='api'?null:0,firstSales:0,rebills:0,coinSpend:0,payout:0,revenue:0,profit:0};current.clicks+=number(fact.clicks);current.sois+=number(fact.sois);current.firstSales+=number(fact.first_sales);current.rebills+=number(fact.rebills);current.coinSpend+=number(fact.coin_spend);current.payout+=number(fact.payout);current.revenue+=number(fact.revenue);current.profit+=number(fact.profit);bySource.set(key,current);grouped.set(fact.offer_url_id,bySource)}const result=new Map<string,SmartlinkSourceBreakdown[]>();for(const[url,items]of grouped){result.set(url,[...items.values()].map(item=>({...item,cvr:item.mode==='api'?null:item.clicks?round(100*item.sois/item.clicks):0,payout:round(item.payout),revenue:round(item.revenue),profit:round(item.profit)})).sort((a,b)=>a.profit-b.profit||b.sois-a.sois||b.coinSpend-a.coinSpend||a.source.localeCompare(b.source)))}return result}
export function attachSmartlinkSourceBreakdowns<C extends{id:string},L extends{id:string}>(currentSlots:C[],legacySlots:L[],currentByUrl:Map<string,SmartlinkSourceBreakdown[]>,legacyByUrl=currentByUrl){return{currentSlots:currentSlots.map(slot=>({...slot,sourceBreakdown:currentByUrl.get(slot.id)||[]})),legacySlots:legacySlots.map(slot=>({...slot,sourceBreakdown:legacyByUrl.get(slot.id)||[]}))}}
