import{describe,expect,it}from'vitest';import{existsSync,readFileSync}from'node:fs';import{join}from'node:path';
import{nextAnalysisTab,smartlinkInstanceKey,sortSmartlinkSlots,type SmartlinkSort}from'./smartlink-presentation';
import type{SmartMetrics,SmartSlot}from'./smartlink';
const metrics=(profit:number,cvr:number,sois:number):SmartMetrics=>({clicks:100,sois,cvr,firstSales:0,firstSaleRate:0,rebills:0,coinSpend:0,revenue:0,payout:0,profit,profitEpc:0});
const slot=(id:string,profit:number,cvr:number,sois:number):SmartSlot=>({id,name:id,offerId:'8',weight:33.3,status:'active',metrics24:metrics(0,cvr,sois),metrics72:metrics(0,0,0),metrics14:metrics(profit,0,sois),hoursTo50Sois:null});
describe('Smartlink LP presentation sorting',()=>{const slots=[slot('A',10,0.4,20),slot('B',-3,1.2,40),slot('C',30,0.8,10)];it.each<[SmartlinkSort,string[]]>([['rotation',['A','B','C']],['profit',['C','A','B']],['cvr',['B','C','A']],['sois',['B','A','C']]])('sorts by %s without changing live rotation data',(sort,ids)=>{const before=slots.map(x=>x.id);expect(sortSmartlinkSlots(slots,sort).map(x=>x.id)).toEqual(ids);expect(slots.map(x=>x.id)).toEqual(before)})});
describe('Smartlink analysis tabs',()=>{it('moves between both tabs with arrows, Home and End',()=>{expect(nextAnalysisTab('overview','ArrowRight')).toBe('sources');expect(nextAnalysisTab('sources','ArrowLeft')).toBe('overview');expect(nextAnalysisTab('sources','Home')).toBe('overview');expect(nextAnalysisTab('overview','End')).toBe('sources');expect(nextAnalysisTab('overview','Enter')).toBe(null)});it('isolates repeated LP IDs by campaign',()=>{expect(smartlinkInstanceKey('146','2673')).toBe('146-2673');expect(smartlinkInstanceKey('147','2673')).not.toBe(smartlinkInstanceKey('146','2673'))})});
describe('shared Smartlink presentation system',()=>{it('keeps the canonical LP cards in the central Affiliate Optimizer',()=>{const root=join(process.cwd(),'src/app'),component=join(root,'components/SmartlinkPresentation.tsx');expect(existsSync(component)).toBe(true);const shared=readFileSync(component,'utf8'),partner=readFileSync(join(root,'affiliates/AffiliateSmartlinks.tsx'),'utf8'),legacy=readFileSync(join(root,'smartlinks/page.tsx'),'utf8');for(const name of['KpiValue','RecommendationBanner','TimeWindowSection','SmartlinkRotationCards'])expect(shared).toContain(`export function ${name}`);expect(partner).toContain("from'../components/SmartlinkPresentation'");expect(partner).toContain('<SmartlinkRotationCards');expect(legacy).toContain('redirect(');expect(legacy).not.toContain('<SmartlinkRotationCards')})});
describe('shared Smartlink visual hierarchy',()=>{it('styles primary KPIs, comparison sorting, accessible badges and mobile cards',()=>{const css=readFileSync(join(process.cwd(),'src/app/globals.css'),'utf8');expect(css).toMatch(/\.sharedLpCard\{/);expect(css).toMatch(/\.primaryKpis\{/);expect(css).toMatch(/\.rotationSort\{/);expect(css).toMatch(/\.sharedStatusBadge:focus/);expect(css).toMatch(/@media\(max-width:600px\)[^{]*\{[^}]*\.sharedLpGrid/);expect(css).toMatch(/\.size-l>strong\{[^}]*font-size/)});});
