export type SmartlinkReportRow={columns:{column_type:string;id:string;label:string}[];reporting:Record<string,number>};
export type CampaignShape={network_campaign_id:number;campaign_name:string;campaign_status:string;redirect_routing_type:string;time_saved?:number;relationship?:{redirects?:{entries?:Array<{redirect_network_offer_id:number;redirect_network_offer_url_id:number;routing_value:number;relationship?:{offer_url?:{name?:string;url_status?:string}}}>}}};
export type SmartMetrics={clicks:number;sois:number;cvr:number;firstSales:number;firstSaleRate:number;rebills:number;coinSpend:number;revenue:number;payout:number;profit:number;profitEpc:number};
export type SmartSlot={id:string;name:string;offerId:string;weight:number;status:string;metrics24:SmartMetrics;metrics72:SmartMetrics;metrics14:SmartMetrics;hoursTo50Sois:number|null};
export type SlotRecommendation={slotId:string;action:'stop'|'rotate'|'scale'|'protect'|'hold';severity:'critical'|'warning'|'positive'|'neutral';reasonCode:string;title:string;detail:string};
const blank=():SmartMetrics=>({clicks:0,sois:0,cvr:0,firstSales:0,firstSaleRate:0,rebills:0,coinSpend:0,revenue:0,payout:0,profit:0,profitEpc:0});
const round=(n:number,d=2)=>Number(n.toFixed(d));
const finish=(m:SmartMetrics)=>({...m,cvr:m.clicks?round(100*m.sois/m.clicks):0,firstSaleRate:m.sois?round(100*m.firstSales/m.sois):0,revenue:round(m.revenue),payout:round(m.payout),profit:round(m.profit),profitEpc:m.clicks?round(m.profit/m.clicks,3):0});
const add=(a:SmartMetrics,b:SmartMetrics)=>{for(const k of ['clicks','sois','firstSales','rebills','coinSpend','revenue','payout','profit'] as const)a[k]+=b[k]};
const dim=(r:SmartlinkReportRow|undefined,type:string)=>r?.columns.find(c=>c.column_type===type)||{id:'0',label:'N/A',column_type:type};
const rowHour=(r:SmartlinkReportRow)=>{const value=Number(dim(r,'hour').id||dim(r,'hour').label);return Number.isFinite(value)?value:0};
const baseMetric=(r:SmartlinkReportRow):SmartMetrics=>{const q=r.reporting;return{...blank(),clicks:Number(q.total_click||0),sois:Number(q.cv||0),revenue:Number(q.revenue||0),payout:Number(q.payout||0),profit:Number(q.profit??(Number(q.revenue||0)-Number(q.payout||0)))}};
const eventMetric=(r:SmartlinkReportRow):SmartMetrics=>{const m=blank(),n=Number(r.reporting.event||0),label=dim(r,'event_name').label;if(label==='Sale')m.firstSales=n;else if(label==='Rebill')m.rebills=n;else if(label==='Coin Spend')m.coinSpend=n;return m};
function aggregate(base:SmartlinkReportRow[],events:SmartlinkReportRow[],fromEpoch:number,ids?:Set<string>){const m=blank();for(const r of base){if(rowHour(r)<fromEpoch||ids&&!ids.has(dim(r,'offer_url').id))continue;add(m,baseMetric(r))}for(const r of events){if(rowHour(r)<fromEpoch||ids&&!ids.has(dim(r,'offer_url').id))continue;add(m,eventMetric(r))}return finish(m)}
export function buildSmartlinkInsight(campaign:CampaignShape,base:SmartlinkReportRow[],events:SmartlinkReportRow[],now=new Date()){
 const requested=String(campaign.network_campaign_id);for(const row of [...base,...events]){const id=dim(row,'campaign').id;if(id&&id!=='0'&&id!==requested)throw new Error('Everflow campaign filter was ignored')}
 const nowEpoch=Math.floor(now.getTime()/1000),from24=nowEpoch-24*3600,from72=nowEpoch-72*3600,from14=nowEpoch-14*86400;const saved=Number(campaign.time_saved),rotationStartEpoch=Number.isFinite(saved)&&saved>from14&&saved<=nowEpoch?saved:null,slotFrom14=rotationStartEpoch||from14,slotFrom72=Math.max(from72,slotFrom14),slotFrom24=Math.max(from24,slotFrom14);const redirects=campaign.relationship?.redirects?.entries||[],currentIds=new Set(redirects.map(r=>String(r.redirect_network_offer_url_id))),legacyIds=new Set([...new Set(base.map(r=>dim(r,'offer_url').id))].filter(id=>!currentIds.has(id)));const totalWeight=redirects.reduce((s,r)=>s+Number(r.routing_value||0),0)||1;
 const identityRow=base[0]||events[0];const currentSlots:SmartSlot[]=redirects.map(r=>{const id=String(r.redirect_network_offer_url_id),ids=new Set([id]),metrics24=aggregate(base,events,slotFrom24,ids),observedHours=Math.max(1,Math.min(24,(nowEpoch-slotFrom24)/3600)),rate=metrics24.sois/observedHours;return{id,name:r.relationship?.offer_url?.name||`LP #${id}`,offerId:String(r.redirect_network_offer_id),weight:round(100*Number(r.routing_value||0)/totalWeight,1),status:r.relationship?.offer_url?.url_status||'unknown',metrics24,metrics72:aggregate(base,events,slotFrom72,ids),metrics14:aggregate(base,events,slotFrom14,ids),hoursTo50Sois:rate>0?round(Math.max(0,50-metrics24.sois)/rate,1):null}});
 const startHour=Math.floor(nowEpoch/3600)*3600-23*3600;const hourly24=Array.from({length:24},(_,i)=>{const epoch=startHour+i*3600,m=blank();for(const r of base)if(rowHour(r)===epoch)add(m,baseMetric(r));for(const r of events)if(rowHour(r)===epoch)add(m,eventMetric(r));return{epoch,...finish(m)}});
 const identity={campaignId:campaign.network_campaign_id,name:campaign.campaign_name,status:campaign.campaign_status,affiliateId:Number(dim(identityRow,'affiliate').id||0),affiliate:dim(identityRow,'affiliate').label,offerIds:[...new Set(redirects.map(r=>String(r.redirect_network_offer_id)))]};
 const traffic24=aggregate(base,events,from24),money72=aggregate(base,events,from72),mature14=aggregate(base,events,from14),legacy14=aggregate(base,events,from14,legacyIds);const recommendations=recommendSlots({affiliateId:identity.affiliateId,campaignId:identity.campaignId,blendCvr24:traffic24.cvr/100,slots:currentSlots});
 return{identity,traffic24,money72,mature14,legacy14,currentSlots,recommendations,hourly24,rotationStartEpoch,generatedAt:now.toISOString(),windows:{traffic:'24h rollierend',economics:'72h rollierend',maturity:'14 Tage rollierend'}};
}
type RecSlot={id:string;weight:number;metrics24:Pick<SmartMetrics,'clicks'|'sois'|'cvr'>;metrics14:Pick<SmartMetrics,'sois'|'firstSales'|'firstSaleRate'|'rebills'|'profit'>};
export function recommendSlots(input:{affiliateId:number;campaignId:number;blendCvr24:number;slots:RecSlot[]}):SlotRecommendation[]{const rates=input.slots.map(s=>s.metrics14.firstSaleRate).sort((a,b)=>a-b),median=rates.length?rates[Math.floor(rates.length/2)]:0;return input.slots.map(slot=>{const a=slot.metrics24,m=slot.metrics14;if(a.clicks>=500&&a.cvr<0.3)return{slotId:slot.id,action:'stop',severity:'critical',reasonCode:'catastrophic_cvr',title:'Sofort stoppen',detail:`${a.clicks} Klicks in 24h bei nur ${a.cvr.toFixed(2)} % CVR.`};if(input.affiliateId===436){const winner=m.sois>=50&&m.firstSales>=3&&m.firstSaleRate>=1.5*Math.max(median,0.01)&&m.profit>0;if(winner)return{slotId:slot.id,action:'scale',severity:'positive',reasonCode:'sale_outlier',title:'Skalierung prüfen',detail:`${m.firstSales} First-Sales, ${m.firstSaleRate.toFixed(2)} % First-Sale-Rate und profitabel.`};if(m.sois>=50)return{slotId:slot.id,action:'rotate',severity:'critical',reasonCode:'test_quota_without_outlier',title:'Austausch empfohlen',detail:`Testziel ${m.sois} SOIs erreicht, aber kein robuster Sale-Ausreißer.`};return{slotId:slot.id,action:'hold',severity:'neutral',reasonCode:'test_running',title:'Test weiterlaufen lassen',detail:`Noch ${Math.max(0,50-m.sois)} SOIs bis zum Testziel.`}}if(input.affiliateId===6&&input.campaignId===2&&input.blendCvr24<0.01)return{slotId:slot.id,action:'protect',severity:'warning',reasonCode:'cvr_floor',title:'1-%-CVR schützen',detail:'Smartlink liegt unter der TrafficPartner-Leitplanke; CVR-starke Slots nicht reduzieren.'};if(m.sois>=50&&m.firstSales===0&&m.rebills===0&&m.profit<0)return{slotId:slot.id,action:'rotate',severity:'critical',reasonCode:'no_monetization',title:'Austausch prüfen',detail:`${m.sois} SOIs ohne First-Sale oder Rebill.`};if(m.sois>=50&&m.firstSales>=3&&m.profit>0&&m.firstSaleRate>=1.5*Math.max(median,0.01))return{slotId:slot.id,action:'scale',severity:'positive',reasonCode:'profitable_outlier',title:'Skalierung prüfen',detail:'Profitabler Sale-Ausreißer mit ausreichendem Volumen.'};return{slotId:slot.id,action:'hold',severity:'neutral',reasonCode:'insufficient_evidence',title:'Beobachten',detail:'Noch keine belastbare Stop- oder Scale-Evidenz.'}})}
