import{DEFAULT_DEAL_RULES,resolveDealRule,type DealRule}from'./deal-register';
export type SmartlinkReportRow={columns:{column_type:string;id:string;label:string}[];reporting:Record<string,number>};
export type CampaignShape={network_campaign_id:number;campaign_name:string;campaign_status:string;redirect_routing_type:string;network_tracking_domain_id?:number;time_saved?:number;relationship?:{redirects?:{entries?:Array<{redirect_network_offer_id:number;redirect_network_offer_url_id:number;routing_value:number;relationship?:{offer_url?:{name?:string;url_status?:string}}}>}}};
export type SmartMetrics={clicks:number;sois:number;cvr:number;firstSales:number;firstSaleRate:number;rebills:number;coinSpend:number;revenue:number;payout:number;profit:number;profitEpc:number};
export type SmartlinkSourceBreakdown={mode:'api'|'tracked';source:string;subSource:string;mainValue?:string|null;subValue?:string|null;clicks:number;sois:number;cvr:number|null;firstSales:number;rebills:number;coinSpend:number;payout:number;revenue:number;profit:number;lastLeadDate?:string|null;activityAsOf?:string;activityCoverageComplete?:boolean;activityLookbackDays?:number};
export type SmartlinkSourceCoverage={from:string;to:string;acceptedFrom:string|null;acceptedTo:string|null;acceptedDays:number;expectedDays:number;missingDays:string[]};
export type SmartSlot={id:string;name:string;offerId:string;weight:number;status:string;metrics24:SmartMetrics;metrics72:SmartMetrics;metrics14:SmartMetrics;hoursTo50Sois:number|null;sourceBreakdown?:SmartlinkSourceBreakdown[];sourceCoverage?:SmartlinkSourceCoverage};
export type LegacySlot={id:string;name:string;offerId:string;metrics72?:SmartMetrics;metrics14:SmartMetrics;sourceBreakdown?:SmartlinkSourceBreakdown[];sourceCoverage?:SmartlinkSourceCoverage};
export type SlotRecommendation={slotId:string;action:'stop'|'rotate'|'scale'|'protect'|'hold';severity:'critical'|'warning'|'positive'|'neutral';reasonCode:string;title:string;detail:string};
export type SmartlinkDailyPoint={date:string;clicks:number;sois:number;cvr:number;profit:number;partial:boolean};
const blank=():SmartMetrics=>({clicks:0,sois:0,cvr:0,firstSales:0,firstSaleRate:0,rebills:0,coinSpend:0,revenue:0,payout:0,profit:0,profitEpc:0});
const round=(n:number,d=2)=>Number(n.toFixed(d));
const berlinDay=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
const shiftDay=(day:string,count:number)=>new Date(Date.parse(`${day}T12:00:00Z`)+count*86_400_000).toISOString().slice(0,10);
const displayDay=(day:string,year=true)=>new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',...(year?{year:'numeric'}:{})}).format(new Date(`${day}T12:00:00Z`));
const finish=(m:SmartMetrics)=>({...m,cvr:m.clicks?round(100*m.sois/m.clicks):0,firstSaleRate:m.sois?round(100*m.firstSales/m.sois):0,revenue:round(m.revenue),payout:round(m.payout),profit:round(m.profit),profitEpc:m.clicks?round(m.profit/m.clicks,3):0});
const add=(a:SmartMetrics,b:SmartMetrics)=>{for(const k of ['clicks','sois','firstSales','rebills','coinSpend','revenue','payout','profit'] as const)a[k]+=b[k]};
const dim=(r:SmartlinkReportRow|undefined,type:string)=>r?.columns.find(c=>c.column_type===type)||{id:'0',label:'N/A',column_type:type};
const rowHour=(r:SmartlinkReportRow)=>{const value=Number(dim(r,'hour').id||dim(r,'hour').label);return Number.isFinite(value)?value:0};
const baseMetric=(r:SmartlinkReportRow):SmartMetrics=>{const q=r.reporting;return{...blank(),clicks:Number(q.total_click||0),sois:Number(q.cv||0),revenue:Number(q.revenue||0),payout:Number(q.payout||0),profit:Number(q.profit??(Number(q.revenue||0)-Number(q.payout||0)))}};
const eventMetric=(r:SmartlinkReportRow):SmartMetrics=>{const m=blank(),n=Number(r.reporting.event||0),label=dim(r,'event_name').label;if(label==='Sale')m.firstSales=n;else if(label==='Rebill')m.rebills=n;else if(label==='Coin Spend')m.coinSpend=n;return m};
function aggregate(base:SmartlinkReportRow[],events:SmartlinkReportRow[],fromEpoch:number,ids?:Set<string>){const m=blank();for(const r of base){if(rowHour(r)<fromEpoch||ids&&!ids.has(dim(r,'offer_url').id))continue;add(m,baseMetric(r))}for(const r of events){if(rowHour(r)<fromEpoch||ids&&!ids.has(dim(r,'offer_url').id))continue;add(m,eventMetric(r))}return finish(m)}
export function buildSmartlinkInsight(campaign:CampaignShape,base:SmartlinkReportRow[],events:SmartlinkReportRow[],now=new Date(),identityOverride?:{affiliateId:number;affiliate:string},deals:readonly DealRule[]=DEFAULT_DEAL_RULES){
 const requested=String(campaign.network_campaign_id);for(const row of [...base,...events]){const id=dim(row,'campaign').id;if(id&&id!=='0'&&id!==requested)throw new Error('Everflow campaign filter was ignored')}
 const nowEpoch=Math.floor(now.getTime()/1000),from24=nowEpoch-24*3600,from72=nowEpoch-72*3600,from14=nowEpoch-14*86400,rotationRetentionFrom=nowEpoch-15*86400;const saved=Number(campaign.time_saved),rotationStartEpoch=Number.isFinite(saved)&&saved>=rotationRetentionFrom&&saved<=nowEpoch?saved:null,slotFrom14=rotationStartEpoch||from14,slotFrom72=Math.max(from72,slotFrom14),slotFrom24=Math.max(from24,slotFrom14);const redirects=campaign.relationship?.redirects?.entries||[],currentIds=new Set(redirects.map(r=>String(r.redirect_network_offer_url_id))),allRows=[...base,...events],legacyIds=new Set([...new Set(allRows.map(r=>dim(r,'offer_url').id))].filter(id=>id&&id!=='0'&&!currentIds.has(id)));const totalWeight=redirects.reduce((s,r)=>s+Number(r.routing_value||0),0)||1;
 const identityRow=base[0]||events[0];const currentSlots:SmartSlot[]=redirects.map(r=>{const id=String(r.redirect_network_offer_url_id),ids=new Set([id]),metrics24=aggregate(base,events,slotFrom24,ids),observedHours=Math.max(1,Math.min(24,(nowEpoch-slotFrom24)/3600)),rate=metrics24.sois/observedHours;return{id,name:r.relationship?.offer_url?.name||`LP #${id}`,offerId:String(r.redirect_network_offer_id),weight:round(100*Number(r.routing_value||0)/totalWeight,1),status:r.relationship?.offer_url?.url_status||'unknown',metrics24,metrics72:aggregate(base,events,slotFrom72,ids),metrics14:aggregate(base,events,slotFrom14,ids),hoursTo50Sois:rate>0?round(Math.max(0,50-metrics24.sois)/rate,1):null}});const legacySlots:LegacySlot[]=[...legacyIds].map(id=>{const row=allRows.find(x=>dim(x,'offer_url').id===id),ids=new Set([id]);return{id,name:dim(row,'offer_url').label||`LP #${id}`,offerId:dim(row,'offer').id,metrics72:aggregate(base,events,from72,ids),metrics14:aggregate(base,events,from14,ids)}}).sort((a,b)=>b.metrics72.revenue-a.metrics72.revenue||b.metrics72.firstSales+b.metrics72.rebills-a.metrics72.firstSales-a.metrics72.rebills||b.metrics14.profit-a.metrics14.profit);
 const startHour=Math.floor(nowEpoch/3600)*3600-23*3600;const hourly24=Array.from({length:24},(_,i)=>{const epoch=startHour+i*3600,m=blank();for(const r of base)if(rowHour(r)===epoch)add(m,baseMetric(r));for(const r of events)if(rowHour(r)===epoch)add(m,eventMetric(r));return{epoch,...finish(m)}});
 const rowDay=(r:SmartlinkReportRow)=>{const d=dim(r,'date').id;return d&&d!=='0'?d:berlinDay(new Date(rowHour(r)*1000))},chartToday=berlinDay(now),dailyTotals=new Map<string,SmartMetrics>();for(const r of base){const d=rowDay(r),m=dailyTotals.get(d)||blank();add(m,baseMetric(r));dailyTotals.set(d,m)}const daily14:SmartlinkDailyPoint[]=Array.from({length:14},(_,i)=>{const date=shiftDay(chartToday,i-13),m=finish(dailyTotals.get(date)||blank());return{date,clicks:m.clicks,sois:m.sois,cvr:m.cvr,profit:m.profit,partial:date===chartToday}});
 const identity={campaignId:campaign.network_campaign_id,name:campaign.campaign_name,status:campaign.campaign_status,affiliateId:identityOverride?.affiliateId??Number(dim(identityRow,'affiliate').id||0),affiliate:identityOverride?.affiliate??dim(identityRow,'affiliate').label,offerIds:[...new Set(redirects.map(r=>String(r.redirect_network_offer_id)))]};
 const traffic24=aggregate(base,events,from24),money72=aggregate(base,events,from72),mature14=aggregate(base,events,from14),legacy14=aggregate(base,events,from14,legacyIds);const recommendations=recommendSlots({affiliateId:identity.affiliateId,campaignId:identity.campaignId,blendCvr24:traffic24.cvr/100,slots:currentSlots},deals);
 const dailyResolution=allRows.some(row=>Boolean(dim(row,'date').id)),today=berlinDay(now),economicsFrom=shiftDay(today,-2),rotationDay=rotationStartEpoch?berlinDay(new Date(rotationStartEpoch*1000)):null,maturityFrom=rotationDay?shiftDay(rotationDay,1):shiftDay(today,-13),maturityLabel=maturityFrom>today?`Reifefenster · noch kein vollständiger Kalendertag nach Campaign-Speichertag`:`Reifefenster · ${displayDay(maturityFrom,false)}–${displayDay(today)} · ${rotationDay?'vollständige Kalendertage nach Campaign-Speichertag':'letzte 14 Kalendertage'}`,windows=dailyResolution?{traffic:`Heute · ${displayDay(today)} · bis Datenstand`,economics:`Kurztrend · ${displayDay(economicsFrom,false)}–${displayDay(today)} · Teilmenge des Kampagnenzeitraums · heute bis Datenstand`,maturity:maturityLabel,granularity:'daily' as const}:{traffic:'24h rollierend',economics:'Kurztrend · 72h rollierend · anderer Zeitraum',maturity:'Reifefenster · 14 Tage rollierend',granularity:'hourly' as const};
 return{identity,traffic24,money72,mature14,legacy14,currentSlots,legacySlots,recommendations,hourly24,daily14,rotationStartEpoch,generatedAt:now.toISOString(),windows};
}
type RecSlot={id:string;weight:number;metrics24:Pick<SmartMetrics,'clicks'|'sois'|'cvr'>;metrics14:Pick<SmartMetrics,'sois'|'firstSales'|'firstSaleRate'|'rebills'|'profit'>};
const pct=(value:number)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(value);
/** Sonderdeals kommen ausschließlich aus dem Deal-Register (D9); ohne Übergabe gelten die bisherigen Konstanten. */
export function recommendSlots(input:{affiliateId:number;campaignId:number;blendCvr24:number;slots:RecSlot[]},deals:readonly DealRule[]=DEFAULT_DEAL_RULES):SlotRecommendation[]{const rates=input.slots.map(s=>s.metrics14.firstSaleRate).sort((a,b)=>a-b),median=rates.length?rates[Math.floor(rates.length/2)]:0,deal=resolveDealRule(deals,input.affiliateId,input.campaignId),quota=deal?.testQuotaSois,cvrFloor=deal?.cvrFloorPct;return input.slots.map(slot=>{const a=slot.metrics24,m=slot.metrics14;if(a.clicks>=500&&a.cvr<0.3)return{slotId:slot.id,action:'stop',severity:'critical',reasonCode:'catastrophic_cvr',title:'Sofort stoppen',detail:`${a.clicks} Klicks in 24h bei nur ${a.cvr.toFixed(2)} % CVR.`};if(quota!==undefined){const winner=m.sois>=quota&&m.firstSales>=3&&m.firstSaleRate>=1.5*Math.max(median,0.01)&&m.profit>0;if(winner)return{slotId:slot.id,action:'scale',severity:'positive',reasonCode:'sale_outlier',title:'Skalierung prüfen',detail:`${m.firstSales} First-Sales, ${m.firstSaleRate.toFixed(2)} % First-Sale-Rate und profitabel.`};if(m.sois>=quota)return{slotId:slot.id,action:'rotate',severity:'critical',reasonCode:'test_quota_without_outlier',title:'Austausch empfohlen',detail:`Testziel ${m.sois} SOIs erreicht, aber kein robuster Sale-Ausreißer.`};return{slotId:slot.id,action:'hold',severity:'neutral',reasonCode:'test_running',title:'Test weiterlaufen lassen',detail:`Noch ${Math.max(0,quota-m.sois)} SOIs bis zum Testziel.`}}if(cvrFloor!==undefined&&input.blendCvr24<cvrFloor/100)return{slotId:slot.id,action:'protect',severity:'warning',reasonCode:'cvr_floor',title:`${pct(cvrFloor)}-%-CVR schützen`,detail:'Smartlink liegt unter der TrafficPartner-Leitplanke; CVR-starke Slots nicht reduzieren.'};if(m.sois>=50&&m.firstSales===0&&m.rebills===0&&m.profit<0)return{slotId:slot.id,action:'rotate',severity:'critical',reasonCode:'no_monetization',title:'Austausch prüfen',detail:`${m.sois} SOIs ohne First-Sale oder Rebill.`};if(m.sois>=50&&m.firstSales>=3&&m.profit>0&&m.firstSaleRate>=1.5*Math.max(median,0.01))return{slotId:slot.id,action:'scale',severity:'positive',reasonCode:'profitable_outlier',title:'Skalierung prüfen',detail:'Profitabler Sale-Ausreißer mit ausreichendem Volumen.'};return{slotId:slot.id,action:'hold',severity:'neutral',reasonCode:'insufficient_evidence',title:'Beobachten',detail:'Noch keine belastbare Stop- oder Scale-Evidenz.'}})}
type DealAwareInsight={identity:{affiliateId:number;campaignId:number};traffic24:{cvr:number};currentSlots:RecSlot[];recommendations:SlotRecommendation[]};
/** Rechnet die Slot-Empfehlungen eines (ggf. gecachten) Insights mit dem aktuellen Deal-Register neu; unvollständige Insights bleiben unverändert. */
export function applyDealRules<T extends Partial<DealAwareInsight>>(insight:T,deals:readonly DealRule[]):T{if(!insight||!insight.identity||!insight.traffic24||!Array.isArray(insight.currentSlots))return insight;return{...insight,recommendations:recommendSlots({affiliateId:insight.identity.affiliateId,campaignId:insight.identity.campaignId,blendCvr24:insight.traffic24.cvr/100,slots:insight.currentSlots},deals)}}
