import {describe,expect,it} from 'vitest';
import {buildSmartlinkInsight,recommendSlots,type CampaignShape,type SmartlinkReportRow} from './smartlink';
const now=new Date('2026-07-22T12:00:00Z');
const hour=(hoursAgo:number)=>String(Math.floor((now.getTime()-hoursAgo*3600000)/1000));
const cols=(url:string,name:string,hoursAgo:number,event?:string)=>[
 {column_type:'campaign',id:'146',label:'Global - TrafficCompany'},{column_type:'affiliate',id:'436',label:'Traffic Company'},{column_type:'offer',id:'57',label:'Singles69'},{column_type:'offer_url',id:url,label:name},{column_type:'hour',id:hour(hoursAgo),label:hour(hoursAgo)},...(event?[{column_type:'event_name',id:event,label:event}]:[])
];
const row=(url:string,name:string,hoursAgo:number,reporting:Record<string,number>,event?:string):SmartlinkReportRow=>({columns:cols(url,name,hoursAgo,event),reporting});
const campaign:CampaignShape={network_campaign_id:146,campaign_name:'Global - TrafficCompany',campaign_status:'active',redirect_routing_type:'weight',relationship:{redirects:{entries:[{redirect_network_offer_id:57,redirect_network_offer_url_id:10,routing_value:1,relationship:{offer_url:{name:'LP A',url_status:'active'}}},{redirect_network_offer_id:57,redirect_network_offer_url_id:20,routing_value:1,relationship:{offer_url:{name:'LP B',url_status:'active'}}}]}}};
describe('buildSmartlinkInsight',()=>{it('separates rolling 24h traffic, 72h economics, 14d maturity and legacy LPs',()=>{const base=[row('10','LP A',2,{total_click:100,cv:10,payout:30,revenue:60,profit:30}),row('10','LP A',50,{total_click:50,cv:5,payout:15,revenue:0,profit:-15}),row('20','LP B',3,{total_click:80,cv:8,payout:24,revenue:0,profit:-24}),row('99','Legacy',4,{total_click:10,cv:1,payout:3,revenue:20,profit:17})];const events=[row('10','LP A',2,{event:2},'Sale'),row('10','LP A',50,{event:3},'Rebill'),row('20','LP B',3,{event:4},'Coin Spend'),row('99','Legacy',4,{event:1},'Sale')];const result=buildSmartlinkInsight(campaign,base,events,now);expect(result.identity).toMatchObject({campaignId:146,affiliateId:436});expect(result.traffic24).toMatchObject({clicks:190,sois:19});expect(result.money72).toMatchObject({profit:8,firstSales:3,rebills:3,coinSpend:4});expect(result.currentSlots).toHaveLength(2);expect(result.currentSlots[0].weight).toBe(50);expect(result.legacy14).toMatchObject({clicks:10,firstSales:1,profit:17});expect(result.legacySlots).toEqual([expect.objectContaining({id:'99',name:'Legacy',offerId:'57',metrics72:expect.objectContaining({clicks:10,firstSales:1,profit:17}),metrics14:expect.objectContaining({clicks:10,firstSales:1,profit:17})})]);expect(result.hourly24).toHaveLength(24);});it('uses the Campaign save timestamp as a conservative current-rotation test start',()=>{const changed=Math.floor(now.getTime()/1000)-24*3600;const saved={...campaign,time_saved:changed};const base=[row('10','LP A',50,{total_click:100,cv:60,payout:180,revenue:0,profit:-180}),row('10','LP A',2,{total_click:20,cv:4,payout:12,revenue:0,profit:-12})];const result=buildSmartlinkInsight(saved,base,[],now);expect(result.currentSlots[0].metrics14.sois).toBe(4);expect(result.mature14.sois).toBe(64);expect(result.rotationStartEpoch).toBe(changed);});});
describe('recommendSlots',()=>{it('rotates a Traffic Company LP after 50 SOIs unless it is a robust Sale outlier',()=>{const recommendations=recommendSlots({affiliateId:436,campaignId:146,blendCvr24:0.12,slots:[{id:'10',weight:33.3,metrics24:{clicks:100,sois:12,cvr:12},metrics14:{sois:60,firstSales:0,firstSaleRate:0,rebills:0,profit:-180}},{id:'20',weight:33.3,metrics24:{clicks:100,sois:10,cvr:10},metrics14:{sois:60,firstSales:4,firstSaleRate:6.67,rebills:2,profit:80}},{id:'30',weight:33.3,metrics24:{clicks:100,sois:11,cvr:11},metrics14:{sois:40,firstSales:1,firstSaleRate:2.5,rebills:0,profit:-80}}]});expect(recommendations.find(x=>x.slotId==='10')).toMatchObject({action:'rotate',severity:'critical'});expect(recommendations.find(x=>x.slotId==='20')).toMatchObject({action:'scale',severity:'positive'});});it('flags catastrophic 24h CVR before economic recommendations',()=>{const r=recommendSlots({affiliateId:1,campaignId:9,blendCvr24:0.002,slots:[{id:'1',weight:100,metrics24:{clicks:600,sois:1,cvr:0.167},metrics14:{sois:1,firstSales:0,firstSaleRate:0,rebills:0,profit:-3}}]});expect(r[0]).toMatchObject({action:'stop',reasonCode:'catastrophic_cvr'});});});
