export type RevenueOriginFact={type:'soi'|'first_sale'|'rebill'|'coin_spend';convertedAt:string;offerUrlId:string|null;revenue:number;payout:number};
export type RevenueOriginEntry={count:number;revenue:number;payout:number};
export type RevenueOriginBreakdown={soi:RevenueOriginEntry;firstSale:RevenueOriginEntry;rebill:RevenueOriginEntry;coinSpend:RevenueOriginEntry;unattributedRevenue:number;unattributedPayout:number};
type MetricMoney={revenue:number;payout:number};
export type RevenueOriginSections={total:RevenueOriginBreakdown;current:RevenueOriginBreakdown;legacy:RevenueOriginBreakdown;beforeRotation:RevenueOriginBreakdown;transitionDay:RevenueOriginBreakdown;unassigned:RevenueOriginBreakdown};
const keys=['total','current','legacy','beforeRotation','transitionDay','unassigned']as const;
type Section=typeof keys[number];
const entry=():RevenueOriginEntry=>({count:0,revenue:0,payout:0});
const blank=():RevenueOriginBreakdown=>({soi:entry(),firstSale:entry(),rebill:entry(),coinSpend:entry(),unattributedRevenue:0,unattributedPayout:0});
const round=(value:number)=>Math.abs(value)<0.005?0:Number(value.toFixed(2));
const berlinDay=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const originKey=(type:RevenueOriginFact['type'])=>type==='first_sale'?'firstSale':type==='coin_spend'?'coinSpend':type;
const sectionFor=(fact:RevenueOriginFact,current:Set<string>,rotationDay:string|null):Exclude<Section,'total'>=>{const day=berlinDay(fact.convertedAt),url=fact.offerUrlId||'';if(!rotationDay)return'unassigned';if(day<rotationDay)return'beforeRotation';if(day===rotationDay)return'transitionDay';if(current.has(url))return'current';return url&&url!=='0'?'legacy':'unassigned'};
const finalize=(origin:RevenueOriginBreakdown,metric:MetricMoney)=>{for(const key of['soi','firstSale','rebill','coinSpend']as const){origin[key].revenue=round(origin[key].revenue);origin[key].payout=round(origin[key].payout)}const knownRevenue=origin.soi.revenue+origin.firstSale.revenue+origin.rebill.revenue+origin.coinSpend.revenue,knownPayout=origin.soi.payout+origin.firstSale.payout+origin.rebill.payout+origin.coinSpend.payout;origin.unattributedRevenue=round(metric.revenue-knownRevenue);origin.unattributedPayout=round(metric.payout-knownPayout);return origin};
export function alignRevenueOriginSections(origins:RevenueOriginSections,metrics:Record<Section,MetricMoney>):RevenueOriginSections{const result={}as RevenueOriginSections;for(const key of keys){const source=origins[key],copy:RevenueOriginBreakdown={soi:{...source.soi},firstSale:{...source.firstSale},rebill:{...source.rebill},coinSpend:{...source.coinSpend},unattributedRevenue:0,unattributedPayout:0};result[key]=finalize(copy,metrics[key])}return result}
export function buildSelectedRevenueOrigins(input:{facts:RevenueOriginFact[];currentSlotIds:Set<string>;rotationDay:string|null;metrics:Record<Section,MetricMoney>}):RevenueOriginSections{const result=Object.fromEntries(keys.map(key=>[key,blank()]))as RevenueOriginSections;for(const fact of input.facts){const section=sectionFor(fact,input.currentSlotIds,input.rotationDay),key=originKey(fact.type);for(const target of[result.total,result[section]]){target[key].count++;target[key].revenue+=Number(fact.revenue||0);target[key].payout+=Number(fact.payout||0)}}return alignRevenueOriginSections(result,input.metrics)}
