import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {LandingpageSourceBreakdown,SmartlinkRotationCards} from '../app/components/SmartlinkPresentation';
import type {SmartSlot} from './smartlink';

const metrics={clicks:120,sois:12,cvr:10,firstSales:2,firstSaleRate:16.67,rebills:1,coinSpend:7,revenue:50,payout:96,profit:-46,profitEpc:-0.383};
const metrics72={...metrics,revenue:72,payout:33,profit:39};
const slot:SmartSlot={id:'2673',name:'Test LP',offerId:'8',weight:33.3,status:'active',metrics24:metrics,metrics72,metrics14:metrics,hoursTo50Sois:12,sourceBreakdown:[{mode:'tracked',source:'CD_DE_ZERO',subSource:'45',clicks:120,sois:10,cvr:8.33,firstSales:1,rebills:1,coinSpend:4,revenue:25,payout:80,profit:-55,lastLeadDate:'2026-07-06',activityAsOf:'2026-07-27',activityCoverageComplete:true,activityLookbackDays:365},{mode:'api',source:'campaign-a',subSource:'creative-b',clicks:0,sois:2,cvr:null,firstSales:1,rebills:0,coinSpend:3,revenue:25,payout:16,profit:9,lastLeadDate:'2026-07-27',activityAsOf:'2026-07-27',activityCoverageComplete:true,activityLookbackDays:365}],sourceCoverage:{from:'2026-07-27',to:'2026-07-27',acceptedFrom:'2026-07-27',acceptedTo:'2026-07-27',acceptedDays:1,expectedDays:1,missingDays:[]}};
const renderCards=(value:SmartSlot=slot)=>renderToStaticMarkup(<SmartlinkRotationCards slots={[value]} recommendations={[]} rotationLabel="Campaign-Speichertag als Referenz" windows={{traffic:'Heute',economics:'Kurztrend · 27.07.–29.07.2026 · Teilmenge des Kampagnenzeitraums',maturity:'Reifefenster · 16.07.–29.07.2026',source:'Reifefenster · 16.07.–29.07.2026'}} affiliateId="436" affiliateName="Traffic Company" campaignId="146" canManage/>);

describe('SmartlinkRotationCards visual hierarchy',()=>{
 it('shows the strongest and weakest source pairing directly on each LP master',()=>{const html=renderCards();expect(html).toContain('2 Quellenkombinationen');expect(html).toContain('Stärkste Quelle');expect(html).toContain('campaign-a');expect(html).toContain('Schwächste Quelle');expect(html).toContain('CD_DE_ZERO')});

 it('compares one source across all affected landingpages factually and preserves the Offer per cell',()=>{const second={...slot,id:'2674',name:'Second LP',offerId:'50',metrics14:{...slot.metrics14,sois:8},sourceBreakdown:[{...slot.sourceBreakdown![1],sois:8,firstSales:0,revenue:0,payout:64,profit:-64}]},html=renderToStaticMarkup(<SmartlinkRotationCards slots={[slot,second]} recommendations={[]} rotationLabel="Referenz" campaignId="146"/>);for(const text of['Landingpages','Sources über Landingpages','Source × Landingpage','campaign-a','2 Landingpages','Auf LP #2673 profitabler beobachtet','LP #2673 · Offer #8','LP #2674 · Offer #50','First-Sales','Rebills','Umsatz','Payout','Profit'])expect(html).toContain(text);expect(html).toContain('role="tablist"');expect(html).toContain('Beobachtung · keine automatische Traffic-Steuerung');expect(html).toContain('EIGENES SOURCE-FENSTER');expect(html).toContain('Diese Summe erklärt nicht automatisch die Campaign-Bilanz');expect(html).not.toMatch(/bevorzugen|umleiten/i)});

 it('keeps every existing KPI but makes the LP window subordinate and unmistakable',()=>{const html=renderCards();expect(html).toContain('LP #2673 · Sales und Nachzahlungen');expect(html).toContain('LP #2673 · Woher kommen die Leads?');expect(html).toContain('LP #2673 · Kosten, Umsatz und Prognose');for(const text of['LP-Profit','Anderer Zeitraum als der Campaign-Profit','Anmelderate (CVR)','SOIs','First-Sales','Anteil SOI → First-Sale','Rebills','Coin-Spend-Events','Profit je Klick','Umsatz · Kurztrend','Payout · Kurztrend','Geschätzte Zeit bis 50 SOIs'])expect(html).toContain(text);expect(html).toContain('72,00');expect(html).toContain('33,00')});

 it('renders recommendations as clearly labelled read-only status instead of an action button',()=>{const html=renderCards();expect(html).toContain('Empfehlung: Halten');expect(html).toContain('role="status"');expect(html).toContain('class="sharedStatusBadge neutral"');expect(html).not.toContain('<button type="button" class="sharedStatusBadge')});

 it('preserves all source dimensions, API labels, shares and the visible control total',()=>{const html=renderCards(),apiHtml=renderToStaticMarkup(<LandingpageSourceBreakdown rows={[slot.sourceBreakdown![1]]} scope="Reifefenster" totalSois={2} landingpageId="2673"/>);expect(html).toContain('2 Source-Kombinationen');expect(html).toContain('12 von 12 SOIs nach Herkunft zugeordnet');expect(html).toContain('10 SOIs · 83,3 %');expect(html).toContain('16,7 %');for(const text of['Source','Sub1','Reifefenster · 16.07.–29.07.2026','Lead-Herkunft für LP #2673'])expect(html).toContain(text);for(const text of['ADV1','ADV2','n/a – clickless','2 SOIs · 100,0 %'])expect(apiHtml).toContain(text);for(const label of['Source CD_DE_ZERO kopieren','Sub1 45 kopieren','Source + Sub1 kopieren'])expect(html).toContain(label);for(const label of['ADV1 campaign-a kopieren','ADV2 creative-b kopieren','ADV1 + ADV2 kopieren'])expect(apiHtml).toContain(label)});

 it('promotes Sub1 when Everflow did not receive a Source-ID without inventing a source',()=>{const missingParent={...slot.sourceBreakdown![0],source:'Nicht übermittelt',subSource:'FERTIG_CH',mainValue:null,subValue:'FERTIG_CH'},missingSlot={...slot,metrics14:{...slot.metrics14,sois:10},sourceBreakdown:[missingParent]},html=renderCards(missingSlot);expect(html).toContain('FERTIG_CH');expect(html).toContain('Source-ID nicht übermittelt');expect(html).toContain('Sub1 FERTIG_CH kopieren');expect(html).not.toContain('Source Nicht übermittelt kopieren');expect(html).not.toContain('Nicht übermittelt / FERTIG_CH')});

 it('uses a searchable economic ranking with one selected source detail and keeps safe source actions',()=>{const html=renderCards();expect(html).toContain('Source, Sub1, ADV1 oder ADV2 suchen');expect(html).toContain('class="lpSourceRanking"');expect(html).toContain('class="lpSourceDetail"');for(const label of['Letzter Lead','Klicks','SOIs · Anteil','CVR','First-Sales · Rate','Rebills','Coin-Spend · Eventquote','Umsatz','Payout','Profit'])expect(html).toContain(label);expect(html).toContain('4 · 40,0 %');expect(html).toContain('Eventquote, keine Kundenquote');expect(html).toContain('Ausschalten');expect(html).toContain('Source CD_DE_ZERO ausschalten');expect(html).toContain('Sub1 45 ausschalten');expect(html).toContain('Vergütung und Partner-Postback');expect(html).toContain('06.07.2026');expect(html).toContain('Seit 21 Tagen keine neuen Leads')});

 it('offers reversible low-to-high and high-to-low sorting for every numeric source value',()=>{const html=renderCards();for(const label of['Klicks','SOIs','CVR','First-Sales','Rebills','Coin-Spend','Umsatz','Payout','Profit'])expect(html).toContain(`aria-label="Nach ${label} sortieren`);expect(html).toContain('aria-label="Nach Profit sortieren: derzeit niedrigste zuerst; klicken für höchste zuerst"');expect(html).toContain('Profit ↑')});

 it('reduces the LP detail to campaign-scoped overview and source-analysis modes with complete keyboard tabs while keeping costs beside results',()=>{const html=renderCards(),shared=readFileSync(join(process.cwd(),'src/app/components/SmartlinkPresentation.tsx'),'utf8');expect(html).toContain('role="tablist"');expect(html).toContain('Übersicht');expect(html).toContain('Quellenanalyse');expect(html).toContain('id="lp-detail-146-2673"');expect(html).toContain('id="lp-overview-tab-146-2673"');expect(html).toContain('data-source-search="landingpage-146-2673"');expect(shared).toContain('smartlinkInstanceKey(campaignId,slot.id)');expect(shared).toContain('key={smartlinkInstanceKey(campaignId,selectedSlot.id)}');expect(shared).toContain('lpDetailTabs');expect(shared).toContain('nextAnalysisTab(mode,event.key)');expect(shared).toContain("tabIndex={mode==='overview'?0:-1}");expect(shared).toContain("tabIndex={mode==='sources'?0:-1}");expect(shared).not.toContain('>Ergebnis<');expect(shared).not.toContain('>Kosten<')});

 it('shows non-computable rates as n/a instead of a measured zero',()=>{const zero={...slot,metrics14:{...slot.metrics14,sois:0,firstSales:0},sourceBreakdown:[{...slot.sourceBreakdown![0],sois:0,firstSales:0,coinSpend:3}]},html=renderCards(zero);expect(html).toContain('0 · n/a');expect(html).toContain('3 · n/a');expect(html).not.toContain('0 · 0,0 %')});

 it('never claims inactivity when the Smartlink activity history is incomplete',()=>{const uncertain={...slot,sourceBreakdown:[{...slot.sourceBreakdown![0],activityCoverageComplete:false}]},html=renderCards(uncertain);expect(html).toContain('Status unbekannt');expect(html).toContain('Letzter bekannter Lead');expect(html).not.toContain('Seit 21 Tagen keine neuen Leads');expect(html).not.toContain('Vermutlich inaktiv')});

 it('uses the LP total as share denominator when source assignment is incomplete',()=>{const partial={...slot,sourceBreakdown:[slot.sourceBreakdown![0]]},html=renderCards(partial);expect(html).toContain('10 von 12 SOIs nach Herkunft zugeordnet');expect(html).toContain('10 SOIs · 83,3 %');expect(html).toContain('Abweichung prüfen');expect(html).not.toContain('10 SOIs · 100,0 %')});

 it('shows source rebills, revenue and the exact missing snapshot days without declaring source winners',()=>{const partial={...slot,sourceCoverage:{from:'2026-07-31',to:'2026-08-06',acceptedFrom:'2026-08-02',acceptedTo:'2026-08-06',acceptedDays:5,expectedDays:7,missingDays:['2026-07-31','2026-08-01']}},html=renderCards(partial),css=readFileSync(join(process.cwd(),'src/app/globals.css'),'utf8');expect(html).toContain('Rebills');expect(html).toContain('Umsatz');expect(html).toContain('Quellen unvollständig');expect(html).not.toContain('Stärkste Quelle');expect(html).toContain('Datenabdeckung Quellenanalyse: 5 von 7 Tagen');expect(html).toContain('02.08.–06.08.2026');expect(html).toContain('Fehlende Tage: 31.07.2026, 01.08.2026');expect(css).toContain('.lpSourceCoverage{');expect(css).toContain('grid-template-columns:repeat(6,minmax(0,1fr))')});

 it('uses compact LP masters and one broad selected detail instead of nested wide cards',()=>{const css=readFileSync(join(process.cwd(),'src/app/globals.css'),'utf8'),shared=readFileSync(join(process.cwd(),'src/app/components/SmartlinkPresentation.tsx'),'utf8');for(const marker of['lpOverviewCard','lpDetailRegion','lpOverviewGrid','lpSourceRanking','lpSourceDetail'])expect(shared).toContain(marker);expect(shared).toContain('aria-pressed={selected}');expect(css).toContain('.lpOverviewGrid{');expect(css).toContain('.lpDetailRegion{');expect(css).toContain('.lpSourceRanking{');expect(css).toContain('.lpSourceDetail{');expect(shared).not.toContain('<table className="lpSourceTable"')});

 it('uses distinct restrained accents for sales, source and economics sections',()=>{const css=readFileSync(join(process.cwd(),'src/app/globals.css'),'utf8');expect(css).toContain('--lp-sales:');expect(css).toContain('--lp-source:');expect(css).toContain('--lp-economics:');expect(css).toContain('.lpEvidenceStrip{');expect(css).toContain('.lpSourceBreakdown[open]');expect(css).toContain('.lpDiagnostics[open]')});

 it('places the same contextual lead-origin disclosure on former landingpages',()=>{const affiliate=readFileSync(join(process.cwd(),'src/app/affiliates/AffiliateSmartlinks.tsx'),'utf8'),cache=readFileSync(join(process.cwd(),'src/lib/cached-smartlinks.ts'),'utf8');expect(affiliate).toContain('LandingpageSourceBreakdown');expect(affiliate).toContain('landingpageId={slot.id}');expect(cache).toContain('attachSmartlinkSourceBreakdowns')});
});
