import type{ReportRow}from'./portfolio';
export const MIN_DECISION_CLICKS=100,MIN_SCALE_SOIS=20,NO_SOURCE='Ohne Source-ID',NO_SUB_SOURCE='Ohne Sub-Source';
export type ConversionMetric={clicks:number;sois:number;cvr:number;payout:number;revenue:number;profit:number};
export type SourceBreakdownRow={pathKey:string;offerId:string;affiliateId:string;offerUrlId:string;sourceId:string;subSource:string;today:ConversionMetric;days7:ConversionMetric;days30:ConversionMetric};
export type BreakdownWindow='today'|'days7'|'days30';export type BreakdownSort='sois'|'cvr';export type TrafficAction='SKALIEREN'|'ABSCHALTEN'|'BEOBACHTEN';export type SourceAction=TrafficAction|'TEILWEISE SKALIEREN'|'TEILWEISE ABSCHALTEN';
export type TrafficAssessment={action:TrafficAction;severity:'positive'|'critical'|'neutral';reason:string};
export type TrafficLeaf={sourceId:string;subSource:string|null;metric:ConversionMetric;assessment:TrafficAssessment};
export type SourceGroup={sourceId:string;metric:ConversionMetric;leaves:TrafficLeaf[];hasSubSources:boolean;action:SourceAction;actionReason:string};
export type ActionCandidate=TrafficLeaf&{pathKey:string;offerId:string;offerUrlId:string};
const dim=(r:ReportRow,type:string)=>r.columns.find(c=>c.column_type===type)||{id:'N/A',label:'N/A',column_type:type};
const blank=():ConversionMetric=>({clicks:0,sois:0,cvr:0,payout:0,revenue:0,profit:0});
const add=(a:ConversionMetric,b:ConversionMetric)=>{a.clicks+=b.clicks;a.sois+=b.sois;a.payout+=b.payout;a.revenue+=b.revenue;a.profit+=b.profit;return a};
const finish=(m:ConversionMetric)=>({...m,cvr:m.clicks?100*m.sois/m.clicks:0});
export function assessTraffic(m:ConversionMetric):TrafficAssessment{const mature=m.clicks>=MIN_DECISION_CLICKS||m.sois>=MIN_SCALE_SOIS;if(m.clicks>=MIN_DECISION_CLICKS&&m.sois===0)return{action:'ABSCHALTEN',severity:'critical',reason:`${m.clicks} Klicks ohne SOI`};if(mature&&m.profit<0)return{action:'ABSCHALTEN',severity:'critical',reason:`${m.profit.toFixed(2)} € Profit bei reifer Datenbasis`};if(m.sois>=MIN_SCALE_SOIS&&m.profit>0)return{action:'SKALIEREN',severity:'positive',reason:`${m.sois} SOIs und ${m.profit.toFixed(2)} € Profit`};return{action:'BEOBACHTEN',severity:'neutral',reason:mature?'Noch kein belastbarer positiver oder negativer Economics-Entscheid':'Unter 100 Klicks und 20 SOIs'}}
export function aggregateSourceRows(rows:ReportRow[]){const map=new Map<string,{pathKey:string;offerId:string;affiliateId:string;offerUrlId:string;sourceId:string;subSource:string;metric:ConversionMetric}>();for(const row of rows){const campaign=dim(row,'campaign');if(campaign.id!=='0')continue;const offer=dim(row,'offer'),affiliate=dim(row,'affiliate'),url=dim(row,'offer_url'),source=dim(row,'source_id'),sub=dim(row,'sub1'),pathKey=`${offer.id}|${affiliate.id}|0|${url.id}`,sourceId=source.id==='N/A'?NO_SOURCE:source.label,subSource=sub.id==='N/A'?NO_SUB_SOURCE:sub.label,key=`${pathKey}|${sourceId}|${subSource}`,current=map.get(key)||{pathKey,offerId:offer.id,affiliateId:affiliate.id,offerUrlId:url.id,sourceId,subSource,metric:blank()},r=row.reporting;add(current.metric,{clicks:Number(r.total_click||0),sois:Number(r.cv||0),cvr:0,payout:Number(r.payout||0),revenue:Number(r.revenue||0),profit:Number(r.profit||0)});map.set(key,current)}return[...map.values()].map(x=>({...x,metric:finish(x.metric)}))}
export function mergeSourceWindows(today:ReportRow[],days7:ReportRow[],days30:ReportRow[]):SourceBreakdownRow[]{const windows=[aggregateSourceRows(today),aggregateSourceRows(days7),aggregateSourceRows(days30)],keys=new Set(windows.flatMap(x=>x.map(y=>`${y.pathKey}|${y.sourceId}|${y.subSource}`)));return[...keys].map(key=>{const found=windows.map(rows=>rows.find(x=>`${x.pathKey}|${x.sourceId}|${x.subSource}`===key)),identity=found.find(Boolean)!;return{pathKey:identity.pathKey,offerId:identity.offerId,affiliateId:identity.affiliateId,offerUrlId:identity.offerUrlId,sourceId:identity.sourceId,subSource:identity.subSource,today:found[0]?.metric||blank(),days7:found[1]?.metric||blank(),days30:found[2]?.metric||blank()}})}
const derive=(leaves:TrafficLeaf[]):{action:SourceAction;actionReason:string}=>{const scale=leaves.filter(x=>x.assessment.action==='SKALIEREN'),stop=leaves.filter(x=>x.assessment.action==='ABSCHALTEN'),watch=leaves.filter(x=>x.assessment.action==='BEOBACHTEN');if(scale.length===leaves.length)return{action:'SKALIEREN',actionReason:`Alle ${leaves.length} tiefsten Einheiten skalieren`};if(stop.length===leaves.length)return{action:'ABSCHALTEN',actionReason:`Alle ${leaves.length} tiefsten Einheiten abschalten`};if(watch.length===leaves.length)return{action:'BEOBACHTEN',actionReason:`Alle ${leaves.length} Einheiten noch unreif`};if(scale.length)return{action:'TEILWEISE SKALIEREN',actionReason:`${scale.length} skalieren · ${stop.length} abschalten · ${watch.length} beobachten`};return{action:'TEILWEISE ABSCHALTEN',actionReason:`${stop.length} abschalten · ${watch.length} beobachten`}};
const groupsFor=(rows:SourceBreakdownRow[],window:BreakdownWindow)=>{const map=new Map<string,{sourceId:string;metric:ConversionMetric;rows:SourceBreakdownRow[]}>();for(const row of rows){const g=map.get(row.sourceId)||{sourceId:row.sourceId,metric:blank(),rows:[]};add(g.metric,row[window]);g.rows.push(row);map.set(row.sourceId,g)}return[...map.values()].map(g=>{g.metric=finish(g.metric);const hasSubSources=g.rows.some(row=>row.subSource!==NO_SUB_SOURCE),leaves:TrafficLeaf[]=hasSubSources?g.rows.map(row=>({sourceId:g.sourceId,subSource:row.subSource,metric:row[window],assessment:assessTraffic(row[window])})):[{sourceId:g.sourceId,subSource:null,metric:g.metric,assessment:assessTraffic(g.metric)}];return{...g,hasSubSources,leaves,...derive(leaves)}})};
export function groupSources(rows:SourceBreakdownRow[],window:BreakdownWindow,sort:BreakdownSort):SourceGroup[]{const score=(m:ConversionMetric)=>sort==='sois'?m.sois:m.cvr;return groupsFor(rows,window).map(g=>({...g,leaves:g.leaves.sort((a,b)=>score(b.metric)-score(a.metric)||b.metric.sois-a.metric.sois)})).sort((a,b)=>score(b.metric)-score(a.metric)||b.metric.sois-a.metric.sois)}
export function buildActionCandidates(rows:SourceBreakdownRow[],window:BreakdownWindow):ActionCandidate[]{const paths=new Map<string,SourceBreakdownRow[]>();for(const row of rows){const key=`${row.pathKey}|${row.sourceId}`,group=paths.get(key)||[];group.push(row);paths.set(key,group)}return[...paths.values()].flatMap(group=>groupsFor(group,window)[0].leaves.map(leaf=>({...leaf,pathKey:group[0].pathKey,offerId:group[0].offerId,offerUrlId:group[0].offerUrlId}))).sort((a,b)=>a.metric.profit-b.metric.profit)}
