import type{SecurityStore}from'./security';
import{withSecurityLock}from'./security';
import{normalizeSourceBlockInput,sourceBlockStoreKey,type NormalizedSourceBlock,type SourceBlockInput,type SourceBlockRecord}from'./source-blocks';
const PREFIX='source-block:v1:';
type Writer={actorId:string;activate:(block:NormalizedSourceBlock,dashboardId:string)=>Promise<{settingId:number;created:boolean}>;deactivate:(settingId:number)=>Promise<{deleted:boolean}>};
const isRecord=(value:unknown):value is SourceBlockRecord=>Boolean(value)&&typeof value==='object'&&typeof(value as SourceBlockRecord).id==='string'&&typeof(value as SourceBlockRecord).offerId==='number';
export async function listSourceBlocks(store:SecurityStore){return(await store.list(PREFIX)).map(item=>item.value).filter(isRecord).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
export async function activateSourceBlock(store:SecurityStore,input:SourceBlockInput,writer:Writer){const block=normalizeSourceBlockInput(input),key=sourceBlockStoreKey(block);return withSecurityLock(store,`source-block:${key}`,async()=>{const existing=await store.get(key);if(isRecord(existing)&&existing.status==='active'&&existing.everflowSettingId)return existing;const now=new Date().toISOString(),id=isRecord(existing)?existing.id:crypto.randomUUID(),pending:SourceBlockRecord={...block,id,status:'pending',effectiveAt:now,createdAt:isRecord(existing)?existing.createdAt:now,createdBy:isRecord(existing)?existing.createdBy:writer.actorId,updatedAt:now,updatedBy:writer.actorId,everflowSettingId:null,lastVerifiedAt:null,error:null};await store.set(key,pending);const external=await writer.activate(block,id),active:SourceBlockRecord={...pending,status:'active',everflowSettingId:external.settingId,lastVerifiedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};try{await store.set(key,active);return active}catch(error){if(external.created)await writer.deactivate(external.settingId).catch(()=>undefined);throw error}})}
export async function deactivateSourceBlock(store:SecurityStore,id:string,writer:Writer){const match=(await listSourceBlocks(store)).find(item=>item.id===id);if(!match)throw new Error('Quellen-Sperre nicht gefunden');const key=sourceBlockStoreKey(match);return withSecurityLock(store,`source-block:${key}`,async()=>{const fresh=await store.get(key);if(!isRecord(fresh))throw new Error('Quellen-Sperre nicht gefunden');if(fresh.status==='inactive')return fresh;if(!fresh.everflowSettingId)throw new Error('Everflow-Setting der Sperre fehlt');const pending:SourceBlockRecord={...fresh,status:'pending',updatedAt:new Date().toISOString(),updatedBy:writer.actorId,error:'Reaktivierung läuft'};await store.set(key,pending);await writer.deactivate(fresh.everflowSettingId);const inactive:SourceBlockRecord={...pending,status:'inactive',everflowSettingId:null,lastVerifiedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),error:null};try{await store.set(key,inactive);return inactive}catch(error){try{const restored=await writer.activate(fresh,fresh.id);await store.set(key,{...fresh,status:'active',everflowSettingId:restored.settingId,lastVerifiedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),error:'Reaktivierung wegen Speicherfehler zurückgerollt'})}catch{}throw error}})}
