import{readFileSync}from'node:fs';import{join}from'node:path';import{describe,expect,it}from'vitest';
const read=(path:string)=>readFileSync(join(process.cwd(),path),'utf8');
describe('source block mutation boundary',()=>{
 it('requires compound admin-grade permissions and rejects partner access',()=>{const route=read('src/app/api/source-blocks/route.ts');expect(route).toContain("access.role!=='partner'");expect(route).toContain("can(access,'landingpages.manage')");expect(route).toContain("can(access,'api.manage')")});
 it('validates CSRF and verifies the requested tuple against server-side dashboard data',()=>{const route=read('src/app/api/source-blocks/route.ts'),model=read('src/lib/source-blocks.ts');expect(route).toContain('checkCsrf(request,origin)');expect(route).toContain('assertVisibleSource');expect(route).toContain('sourceBlockVisibleInSnapshotRows');expect(model).toContain("snapshotDimension(row,'offer')?.id===String(block.offerId)");expect(model).toContain("snapshotDimension(row,'campaign')?.id===String(block.originCampaignId)");expect(route).toContain("'Cache-Control':'private, no-store'")});
 it('never accepts browser-controlled Everflow variable names or payout fields',()=>{const route=read('src/app/api/source-blocks/route.ts');expect(route).not.toContain('input.variables');expect(route).not.toContain('input.payout_amount');const model=read('src/lib/source-blocks.ts');expect(model).toContain("input.trafficMode==='api'?'adv1':'source_id'");expect(model).toContain("input.trafficMode==='api'?'adv2':'sub1'")});
 it('discovers product-wide offer scope server-side and requires exact confirmation',()=>{const route=read('src/app/api/source-blocks/route.ts');expect(route).toContain('resolveProductWideInputs');expect(route).toContain("input.action==='activate_across_offers'");expect(route).toContain('sourceBlockRequiredConfirmation');expect(route).toContain('activateSourceBlocksAtomically')});
 it('uses the coverage-checked source snapshot scope without caching the large raw history or calling full smartlink RPCs',()=>{const route=read('src/app/api/source-blocks/route.ts'),service=read('src/lib/affiliate-optimizer-service.ts'),start=service.indexOf('export async function getAffiliateSourceScopeRows'),end=service.indexOf('export async function getAffiliateSourceFreshness',start),scope=service.slice(start,end);expect(route).toContain('getAffiliateSourceScopeRows');expect(route).not.toContain('getAffiliateSmartlinks');expect(route).not.toContain('getCampaignAffiliateMappings');expect(route).not.toContain('getAffiliateSourceBreakdown');expect(scope).toContain('loadAffiliateSourceRowsRangeFromCache');expect(scope).toContain('sourceRowsForAccess');expect(scope).not.toContain('sourceWindow(');expect(service).toContain('sourceScopeCoverageComplete');expect(service).toContain('Source-Historie ist unvollständig')});
 it('passes fresh uncached authorization into the service mutation lock',()=>{const route=read('src/app/api/source-blocks/route.ts'),service=read('src/lib/source-block-service.ts');expect(route).toContain('resolveCurrentUserUncached');expect(route).toContain('authorize:async');expect(service).toMatch(/withSecurityLock[\s\S]*await writer\.authorize\?\.\(\)/)});
 it('receives activation and deactivation audit before-state from inside the service lock',()=>{const route=read('src/app/api/source-blocks/route.ts');expect(route).toContain('async (after,before)=>audit');expect(route).not.toContain('const before=await listSourceBlocks(store)')});
 it('audits the canonical position-aligned before-state for product-wide activation',()=>{const route=read('src/app/api/source-blocks/route.ts');expect(route).toContain("action:'source_block.activate_across_offers'");expect(route).toContain('before:{blocks:before}')});
 it('audits failed activation and deactivation attempts without changing the error response',()=>{const route=read('src/app/api/source-blocks/route.ts'),failure=route.indexOf("console.error('Source block mutation failed'"),failedAudit=route.indexOf('source_block.activate_failed',failure),response=route.indexOf('return json({error:error instanceof Error?error.message:',failedAudit);expect(route).toContain("action:input.action==='deactivate'?'source_block.deactivate_failed':'source_block.activate_failed'");expect(route).toContain('after:{error:message}');expect(route).toContain('failedTargetId=input.action');expect(failedAudit).toBeGreaterThan(failure);expect(response).toBeGreaterThan(failedAudit);expect(route.slice(failedAudit,response)).toContain('.catch(()=>{})')});
});

describe('source block lifecycle contract (Etappe 2, F2)',()=>{
 const route=()=>read('src/app/api/source-blocks/route.ts');
 it('validates the reason category for activation and rejects a missing one since Phase B (Etappe 2)',()=>{const source=route();expect(source).toContain('const REASON_CATEGORY_REQUIRED=true');expect(source).not.toContain('const REASON_CATEGORY_REQUIRED=false');expect(source).toContain('isSourceBlockReasonCategory(raw)');expect(source).toContain('throw new SourceBlockRequestError(REASON_CATEGORY_ERROR)');expect(source).toContain("missing?(required?'sonstiges':undefined)");expect(source).toContain('Begründung ist zu lang (max. 500 Zeichen)');expect(source).toContain('return json({error:error.message},400)')});
 it('passes reason category and reason into the persisted record for both activation paths',()=>{const source=route(),model=read('src/lib/source-blocks.ts'),service=read('src/lib/source-block-service.ts');expect(source.split('const requested={...input,reasonCategory,reason} as unknown as SourceBlockInput')).toHaveLength(3);expect(model).toContain('reasonCategory?:SourceBlockReasonCategory}');expect(service).toContain('...(reasonCategory ? { reasonCategory } : {})')});
 it('records append-only history on success inside the audited commit and on failure after the failure audit',()=>{const source=route(),failure=source.indexOf("console.error('Source block mutation failed'"),failedAudit=source.indexOf('source_block.activate_failed',failure),failedHistory=source.indexOf("action:input.action==='deactivate'?'deactivate_failed':'activate_failed'",failedAudit),response=source.indexOf('return json({error:error instanceof Error?error.message:',failedHistory);expect(source).toContain("then(()=>history('activate',after,before))");expect(source).toContain("history('activate_across_offers',record,before?.[index]??null)");expect(source).toContain("then(()=>history('deactivate',after,before))");expect(source).toContain('resolveFailedBlock(input,failedTargetId,store)');expect(failedHistory).toBeGreaterThan(failedAudit);expect(response).toBeGreaterThan(failedHistory);const history=read('src/lib/source-block-history.ts');expect(history).toContain('setIfAbsent(key,record)');expect(history).toContain("catch(error){console.error('Source block history could not be recorded'");expect(history).toContain('source_block_history:')});
 it('serves history, product-wide preview sums with block state and optional effects only behind the manage gate',()=>{const source=route(),gate=source.indexOf('export async function GET'),manage=source.indexOf('if(!mayManage(auth.user.access))',gate);expect(manage).toBeGreaterThan(gate);expect(source).toContain('offers=sourceBlockOfferSummariesFromSnapshotRows(rows,block)');for(const marker of ["action==='history'","listSourceBlockHistory(id,store)","action==='preview_across_offers'",'resolveProductWideOffers(input,auth.user.access)','loadBlockIndex(store)',"?.status==='active'","url.searchParams.get('effects')==='1'",'loadBlockEffects({from,to}',"json(stripFinance({blocks,effects},can(auth.user.access,'finance.view')))","json(stripFinance({offers:"])expect(source.indexOf(marker,manage)).toBeGreaterThan(manage)});
 it('expires the block effect cache after every mutation outcome without new Everflow write paths',()=>{const source=route();expect(source.split('expireBlockCaches();')).toHaveLength(5);expect(source).toContain("revalidateTag(BLOCK_EFFECTS_CACHE_TAG,{expire:0})");expect(read('src/lib/block-effects.ts')).toContain("BLOCK_EFFECTS_CACHE_TAG='source-blocks'");expect(source).not.toContain('input.variables');expect(source).not.toContain('input.payout_amount')});
});
