import{assessUnit,projectSourceAction,type LeadMaturityInput,type VerdictGate}from'./decision-engine';
import{guardMaturityCoverage,leadMaturityFor,leadMaturityFromReport,leafMaturityKey,maturityCoverage,sumLeadMaturity,type LeadMaturityIndex}from'./lead-maturity';
import{canonicalTrackedSub}from'./click-id-sub-source';
import type{ReportRow}from'./portfolio';
import{sourceRowBlockKeys}from'./source-block-markers';
export const MIN_DECISION_CLICKS=100,MIN_SCALE_SOIS=20,NO_SOURCE='Ohne Source-ID',NO_SUB_SOURCE='Ohne Sub-Source';
export type ConversionMetric={clicks:number;sois:number;cvr:number;firstSales:number;firstSaleRate:number;rebills:number;coinSpend:number;payout:number;revenue:number;profit:number;profitPerSoi:number};
export type LeadActivity={lastLeadDate:string|null;asOf:string;coverageComplete:boolean;lookbackDays:number};
export type LeadActivityStatus={label:string;detail:string;tone:'active'|'recent'|'stale'|'unknown'};
export type SourceBreakdownRow={pathKey:string;offerId:string;affiliateId:string;offerUrlId:string;sourceId:string;subSource:string;trafficMode:'api'|'tracked';mainValue:string|null;subValue:string|null;today:ConversionMetric;days7:ConversionMetric;days30:ConversionMetric;activity:LeadActivity;/** Reife der SOIs dieses Blatts (Etappe 3, attachSourceMaturity); fehlt sie, bleibt das Verdikt ungekoppelt. */maturity?:LeadMaturityInput};
export type BreakdownWindow='today'|'days7'|'days30';export type BreakdownSort='sois'|'cvr';export type TrafficAction='SKALIEREN'|'AUSSCHALTEN'|'BEOBACHTEN';export type SourceAction=TrafficAction|'TEILWEISE SKALIEREN'|'TEILWEISE AUSSCHALTEN';
export type TrafficAssessment={action:TrafficAction;severity:'positive'|'critical'|'neutral';reason:string;gate?:VerdictGate};
export type TrafficLeaf={sourceId:string;subSource:string|null;metric:ConversionMetric;assessment:TrafficAssessment;activity:LeadActivity};
export type SourceGroup={sourceId:string;metric:ConversionMetric;leaves:TrafficLeaf[];hasSubSources:boolean;action:SourceAction;actionReason:string;activity:LeadActivity};
export type ActionCandidate=TrafficLeaf&{pathKey:string;offerId:string;offerUrlId:string;affiliateId:string;trafficMode:'api'|'tracked';mainValue:string|null;subValue:string|null};
const dim=(r:ReportRow,type:string)=>r.columns.find(c=>c.column_type===type)||{id:'N/A',label:'N/A',column_type:type};
const blank=():ConversionMetric=>({clicks:0,sois:0,cvr:0,firstSales:0,firstSaleRate:0,rebills:0,coinSpend:0,payout:0,revenue:0,profit:0,profitPerSoi:0});
const add=(a:ConversionMetric,b:ConversionMetric)=>{a.clicks+=b.clicks;a.sois+=b.sois;a.firstSales+=b.firstSales;a.rebills+=b.rebills;a.coinSpend+=b.coinSpend;a.payout+=b.payout;a.revenue+=b.revenue;a.profit+=b.profit;return a};
const finish=(m:ConversionMetric)=>({...m,cvr:m.clicks?100*m.sois/m.clicks:0,firstSaleRate:m.sois?100*m.firstSales/m.sois:0,profitPerSoi:m.sois?m.profit/m.sois:0});
const unknownActivity:LeadActivity={lastLeadDate:null,asOf:'',coverageComplete:false,lookbackDays:365};
const activityOf=(row:SourceBreakdownRow)=>row.activity;
const activityLatest=(items:LeadActivity[]):LeadActivity=>({lastLeadDate:items.map(x=>x.lastLeadDate).filter((x):x is string=>Boolean(x)).sort().at(-1)||null,asOf:items.map(x=>x.asOf).filter(Boolean).sort().at(-1)||'',coverageComplete:items.every(x=>x.coverageComplete),lookbackDays:Math.max(...items.map(x=>x.lookbackDays),365)});
const calendarDays=(from:string,to:string)=>Math.max(0,Math.round((Date.parse(`${to}T12:00:00Z`)-Date.parse(`${from}T12:00:00Z`))/86_400_000));
export function leadActivityStatus(activity:LeadActivity):LeadActivityStatus{if(!activity.coverageComplete)return{label:'Status unbekannt',detail:activity.lastLeadDate?`Letzter bekannter Lead: ${activity.lastLeadDate.split('-').reverse().join('.')}`:`Historie unvollständig`,tone:'unknown'};if(!activity.lastLeadDate)return{label:'Kein Lead gefunden',detail:`Kein Lead in ${activity.lookbackDays} Tagen`,tone:'stale'};const days=calendarDays(activity.lastLeadDate,activity.asOf),date=activity.lastLeadDate.split('-').reverse().join('.');if(days===0)return{label:'Heute aktiv',detail:`Letzter Lead: heute`,tone:'active'};if(days===1)return{label:'Kürzlich aktiv',detail:`Letzter Lead: gestern (${date})`,tone:'recent'};if(days===2)return{label:'Kürzlich aktiv',detail:`Letzter Lead: ${date} · vor 2 Tagen`,tone:'recent'};return{label:days>=7?'Vermutlich inaktiv':'Keine neuen Leads',detail:`Seit ${days} Tagen keine neuen Leads`,tone:'stale'}}
/** maturity = Index-Eintrag des Blatts (Conversions-Zählung); die Reife gegen die Berichtszeile ergibt sich als SOIs − junge SOIs (leadMaturityFromReport). */
export function assessTraffic(m:ConversionMetric,benchmarkRate?:number,maturity?:LeadMaturityInput):TrafficAssessment{
 const leadMaturity=maturity?leadMaturityFromReport(maturity,maturity,m.sois):undefined;
 const verdict=assessUnit({clicks:m.clicks,sois:m.sois,firstSales:m.firstSales,rebills:m.rebills,profit:m.profit},{benchmarkRate,leadMaturity});
 const action=projectSourceAction(verdict.action);
 return{action,severity:action==='SKALIEREN'?'positive':action==='AUSSCHALTEN'?'critical':'neutral',reason:verdict.reason,gate:verdict.gate};
}
/** Reife-Index (lead-maturity.ts) an die Zeilen hängen; ohne Index unverändert. */
export function attachSourceMaturity(rows:SourceBreakdownRow[],index:LeadMaturityIndex|undefined):SourceBreakdownRow[]{if(!index)return rows;const guarded=guardMaturityCoverage(index,maturityCoverage(index.byLeaf,rows.map(row=>({key:leafMaturityKey(row),sois:row.days30.sois}))));return rows.map(row=>({...row,maturity:leadMaturityFor(guarded,row)}))}
export type SourceMaturityOptions={maturity?:LeadMaturityIndex};
export function aggregateSourceRows(rows:ReportRow[]){const map=new Map<string,{pathKey:string;offerId:string;affiliateId:string;offerUrlId:string;sourceId:string;subSource:string;trafficMode:'api'|'tracked';mainValue:string|null;subValue:string|null;metric:ConversionMetric}>();for(const row of rows){const campaign=dim(row,'campaign');if(campaign.id!=='0')continue;const offer=dim(row,'offer'),affiliate=dim(row,'affiliate'),url=dim(row,'offer_url'),source=dim(row,'source_id'),subRaw=dim(row,'sub1'),subCanonical=canonicalTrackedSub(subRaw.id==='N/A'?'':subRaw.id,(dim(row,'sub2').id==='N/A'?'':dim(row,'sub2').id)),sub={id:subCanonical.value||'N/A',label:subCanonical.value||'N/A',column_type:'sub1'},mode=dim(row,'traffic_mode').id==='api'?'api' as const:'tracked' as const,mainValue=!source.id||source.id==='N/A'||source.id==='Nicht übermittelt'?null:source.id,subValue=!sub.id||sub.id==='N/A'?null:sub.id,pathKey=`${offer.id}|${affiliate.id}|0|${url.id}`,sourceId=mainValue===null?NO_SOURCE:source.label,subSource=subValue===null?NO_SUB_SOURCE:sub.label,key=`${pathKey}|${mode}|${mainValue||''}|${subValue||''}`,current=map.get(key)||{pathKey,offerId:offer.id,affiliateId:affiliate.id,offerUrlId:url.id,sourceId,subSource,trafficMode:mode,mainValue,subValue,metric:blank()},r=row.reporting;add(current.metric,{clicks:Number(r.total_click||0),sois:Number(r.cv||0),cvr:0,firstSales:Number(r.first_sales||0),firstSaleRate:0,rebills:Number(r.rebills||0),coinSpend:Number(r.coin_spend||0),payout:Number(r.payout||0),revenue:Number(r.revenue||0),profit:Number(r.profit||0),profitPerSoi:0});map.set(key,current)}return[...map.values()].map(x=>({...x,metric:finish(x.metric)}))}
export function mergeSourceWindows(today:ReportRow[],days7:ReportRow[],days30:ReportRow[]):SourceBreakdownRow[]{const windows=[aggregateSourceRows(today),aggregateSourceRows(days7),aggregateSourceRows(days30)],keys=new Set(windows.flatMap(x=>x.map(y=>`${y.pathKey}|${y.trafficMode}|${y.mainValue||''}|${y.subValue||''}`)));return[...keys].map(key=>{const found=windows.map(rows=>rows.find(x=>`${x.pathKey}|${x.trafficMode}|${x.mainValue||''}|${x.subValue||''}`===key)),identity=found.find(Boolean)!;return{pathKey:identity.pathKey,offerId:identity.offerId,affiliateId:identity.affiliateId,offerUrlId:identity.offerUrlId,sourceId:identity.sourceId,subSource:identity.subSource,trafficMode:identity.trafficMode,mainValue:identity.mainValue,subValue:identity.subValue,today:found[0]?.metric||blank(),days7:found[1]?.metric||blank(),days30:found[2]?.metric||blank(),activity:unknownActivity}})}
export type SourceActivityIdentity=Pick<SourceBreakdownRow,'pathKey'|'offerId'|'affiliateId'|'offerUrlId'|'sourceId'|'subSource'|'trafficMode'|'mainValue'|'subValue'>;
export type SourceActivityEntry={identity:SourceActivityIdentity;lastLeadDate:string|null};
/** Kompakter Aktivitäts-Index aus Historienzeilen: je Kombination die Identität und der letzte Lead-Tag. */
export function buildSourceActivityIndex(history:ReportRow[]):SourceActivityEntry[]{const activity=new Map<string,SourceActivityEntry>();for(const row of history){const campaign=dim(row,'campaign');if(campaign.id!=='0')continue;const offer=dim(row,'offer'),affiliate=dim(row,'affiliate'),url=dim(row,'offer_url'),source=dim(row,'source_id'),subRaw=dim(row,'sub1'),subCanonical=canonicalTrackedSub(subRaw.id==='N/A'?'':subRaw.id,(dim(row,'sub2').id==='N/A'?'':dim(row,'sub2').id)),sub={id:subCanonical.value||'N/A',label:subCanonical.value||'N/A',column_type:'sub1'},trafficMode=dim(row,'traffic_mode').id==='api'?'api' as const:'tracked' as const,mainValue=!source.id||source.id==='N/A'||source.id==='Nicht übermittelt'?null:source.id,subValue=!sub.id||sub.id==='N/A'?null:sub.id,identity={pathKey:`${offer.id}|${affiliate.id}|0|${url.id}`,offerId:offer.id,affiliateId:affiliate.id,offerUrlId:url.id,sourceId:mainValue===null?NO_SOURCE:source.label,subSource:subValue===null?NO_SUB_SOURCE:sub.label,trafficMode,mainValue,subValue},key=`${identity.pathKey}|${identity.trafficMode}|${identity.mainValue||''}|${identity.subValue||''}`,day=dim(row,'date').id,current=activity.get(key)||{identity,lastLeadDate:null};if(Number(row.reporting.cv||0)>0&&/^\d{4}-\d{2}-\d{2}$/.test(day)&&(!current.lastLeadDate||day>current.lastLeadDate))current.lastLeadDate=day;activity.set(key,current)}return[...activity.values()]}
export function attachSourceActivityFromIndex(selected:SourceBreakdownRow[],index:SourceActivityEntry[],context:Omit<LeadActivity,'lastLeadDate'>):SourceBreakdownRow[]{const rows=new Map(selected.map(row=>[`${row.pathKey}|${row.trafficMode}|${row.mainValue||''}|${row.subValue||''}`,row]));for(const item of index){const key=`${item.identity.pathKey}|${item.identity.trafficMode}|${item.identity.mainValue||''}|${item.identity.subValue||''}`,existing=rows.get(key);rows.set(key,{...(existing||{...item.identity,today:blank(),days7:blank(),days30:blank(),activity:unknownActivity}),activity:{...context,lastLeadDate:item.lastLeadDate}})}return[...rows.values()].map(row=>({...row,activity:row.activity===unknownActivity?{...context,lastLeadDate:null}:row.activity}))}
export function attachSourceActivity(selected:SourceBreakdownRow[],history:ReportRow[],context:Omit<LeadActivity,'lastLeadDate'>):SourceBreakdownRow[]{return attachSourceActivityFromIndex(selected,buildSourceActivityIndex(history),context)}
const derive=(leaves:TrafficLeaf[]):{action:SourceAction;actionReason:string}=>{const scale=leaves.filter(x=>x.assessment.action==='SKALIEREN'),stop=leaves.filter(x=>x.assessment.action==='AUSSCHALTEN'),watch=leaves.filter(x=>x.assessment.action==='BEOBACHTEN');if(scale.length===leaves.length)return{action:'SKALIEREN',actionReason:`Alle ${leaves.length} tiefsten Einheiten skalieren`};if(stop.length===leaves.length)return{action:'AUSSCHALTEN',actionReason:`Alle ${leaves.length} tiefsten Einheiten abschalten`};if(watch.length===leaves.length)return{action:'BEOBACHTEN',actionReason:`Alle ${leaves.length} Einheiten noch unreif`};if(scale.length)return{action:'TEILWEISE SKALIEREN',actionReason:`${scale.length} skalieren · ${stop.length} abschalten · ${watch.length} beobachten`};return{action:'TEILWEISE AUSSCHALTEN',actionReason:`${stop.length} abschalten · ${watch.length} beobachten`}};
const contextBenchmark=(rows:SourceBreakdownRow[],window:BreakdownWindow)=>{let sois=0,firstSales=0;for(const row of rows){sois+=row[window].sois;firstSales+=row[window].firstSales}return sois>0&&firstSales>0?firstSales/sois:undefined};
const groupsFor=(rows:SourceBreakdownRow[],window:BreakdownWindow)=>{const benchmark=contextBenchmark(rows,window);const map=new Map<string,{sourceId:string;metric:ConversionMetric;rows:SourceBreakdownRow[]}>();for(const row of rows){const g=map.get(row.sourceId)||{sourceId:row.sourceId,metric:blank(),rows:[]};add(g.metric,row[window]);g.rows.push(row);map.set(row.sourceId,g)}return[...map.values()].map(g=>{g.metric=finish(g.metric);const activity=activityLatest(g.rows.map(activityOf)),hasSubSources=g.rows.some(row=>row.subSource!==NO_SUB_SOURCE),leaves:TrafficLeaf[]=hasSubSources?g.rows.map(row=>({sourceId:g.sourceId,subSource:row.subSource,metric:row[window],assessment:assessTraffic(row[window],benchmark,row.maturity),activity:activityOf(row)})):[{sourceId:g.sourceId,subSource:null,metric:g.metric,assessment:assessTraffic(g.metric,benchmark,sumLeadMaturity(g.rows.map(row=>row.maturity))),activity}];return{...g,activity,hasSubSources,leaves,...derive(leaves)}})};
/** options.maturity: Reife-Index für das Gate D3 (sonst zählt eine bereits an den Zeilen hängende maturity). */
export function groupSources(rows:SourceBreakdownRow[],window:BreakdownWindow,sort:BreakdownSort,options?:SourceMaturityOptions):SourceGroup[]{const score=(m:ConversionMetric)=>sort==='sois'?m.sois:m.cvr;return groupsFor(attachSourceMaturity(rows,options?.maturity),window).map(g=>({...g,leaves:g.leaves.sort((a,b)=>score(b.metric)-score(a.metric)||b.metric.sois-a.metric.sois)})).sort((a,b)=>score(b.metric)-score(a.metric)||b.metric.sois-a.metric.sois)}
/** options.blockedKeys (Sperr-Index-Schlüssel, sourceRowBlockKeys): aktiv gesperrte Einheiten werden auf Sperr-Ebene ausgelassen; ohne Option unverändert. */
export function buildActionCandidates(rows:SourceBreakdownRow[],window:BreakdownWindow,options?:{blockedKeys?:Set<string>}&SourceMaturityOptions):ActionCandidate[]{const paths=new Map<string,SourceBreakdownRow[]>();for(const row of attachSourceMaturity(rows,options?.maturity)){const key=`${row.pathKey}|${row.sourceId}`,group=paths.get(key)||[];group.push(row);paths.set(key,group)}const blocked=options?.blockedKeys;return[...paths.values()].flatMap(group=>groupsFor(group,window)[0].leaves.map(leaf=>{const source=leaf.subSource===null?group[0]:group.find(row=>row.subSource===leaf.subSource)||group[0];return{...leaf,pathKey:group[0].pathKey,offerId:group[0].offerId,offerUrlId:group[0].offerUrlId,affiliateId:group[0].affiliateId,trafficMode:group[0].trafficMode,mainValue:group[0].mainValue,subValue:leaf.subSource===null?null:source.subValue}})).filter(candidate=>!blocked?.size||!sourceRowBlockKeys(candidate).some(key=>blocked.has(key))).sort((a,b)=>a.metric.profit-b.metric.profit)}
