import{readFileSync}from'node:fs';import{join}from'node:path';import React from'react';import{renderToStaticMarkup}from'react-dom/server';import{describe,expect,it}from'vitest';import SourceBreakdown from'../app/affiliates/SourceBreakdown';import{sourceRebillKey}from'./source-rebill-key';import{NO_SUB_SOURCE,type ConversionMetric,type SourceBreakdownRow}from'./source-breakdown';
import{analyzeRebillConcentration}from'./rebill-concentration';
const metric:ConversionMetric={clicks:0,sois:3,cvr:0,firstSales:1,firstSaleRate:100/3,rebills:2,coinSpend:0,payout:30,revenue:60,profit:30,profitPerSoi:10};const rows:SourceBreakdownRow[]=[{pathKey:'8|7|0|2673',offerId:'8',affiliateId:'7',offerUrlId:'2673',sourceId:'P-3591625022',subSource:'creative-17',trafficMode:'tracked',mainValue:'P-3591625022',subValue:'creative-17',today:metric,days7:metric,days30:metric,activity:{lastLeadDate:'2026-07-06',asOf:'2026-07-27',coverageComplete:true,lookbackDays:365}}];
describe('SourceBreakdown copy integration',()=>{
 it('renders a copy action for the tracked Source group',()=>{const html=renderToStaticMarkup(<SourceBreakdown rows={rows}/>);expect(html).toContain('Source P-3591625022 kopieren')});
 it('renders a copy action for the clickless ADV1 group',()=>{const html=renderToStaticMarkup(<SourceBreakdown rows={rows} apiMode/>);expect(html).toContain('ADV1 P-3591625022 kopieren')});
 it('uses Sub1 and ADV2 labels for the deepest values and offers one pair-copy action',()=>{const source=readFileSync(join(process.cwd(),'src/app/affiliates/SourceBreakdown.tsx'),'utf8'),html=renderToStaticMarkup(<SourceBreakdown rows={rows}/>);expect(source).toContain("label={apiMode?'ADV2':'Sub1'}");expect(source).toContain('value={leaf.subSource}');expect(html).toContain('Source + Sub1 kopieren')});
 it('shows the last lead date and inactivity duration on source and deepest-level cards',()=>{const html=renderToStaticMarkup(<SourceBreakdown rows={rows}/>);expect(html).toContain('Letzter Lead: 06.07.2026');expect(html).toContain('Seit 21 Tagen keine neuen Leads');expect(html).toContain('Vermutlich inaktiv')});
 it('shows rebills per customer and Top-1/Top-2 concentration on the deepest ADV2 row',()=>{const ids=[...Array(91).fill('a'),...Array(20).fill('b'),...Array(12).fill('c')],analysis=analyzeRebillConcentration({firstSales:17,totalRebills:123,customerIds:ids,firstSaleCustomerIds:['a','b','c',...Array.from({length:14},(_,i)=>`lead-${i}`)]}),html=renderToStaticMarkup(<SourceBreakdown rows={rows} apiMode rebillAnalyses={{'api\u001fP-3591625022\u001fcreative-17':analysis}}/>);expect(html).toContain('7,24 Rebills je gewonnenem Kunden');expect(html).toContain('Top-Kunde');expect(html).toContain('90,2 %')});
 it('uses the same analysis key for a deepest missing Sub-Source leaf and its null aggregate representation',()=>{expect(sourceRebillKey('tracked','source-a',NO_SUB_SOURCE)).toBe(sourceRebillKey('tracked','source-a',null))});
 it('keeps identical tracked and API source tuples in separate rendered analysis keys',()=>{expect(sourceRebillKey('tracked','same','sub')).not.toBe(sourceRebillKey('api','same','sub'))});
 it('renders only the matching traffic-mode analysis for adversarial identical source tuples',()=>{const tracked=analyzeRebillConcentration({firstSales:3,totalRebills:3,customerIds:['t1','t2','t3'],firstSaleCustomerIds:['t1','t2','t3']}),api=analyzeRebillConcentration({firstSales:2,totalRebills:6,customerIds:['a','a','a','b','b','b'],firstSaleCustomerIds:['a','b']}),analyses={[sourceRebillKey('tracked','P-3591625022','creative-17')]:tracked,[sourceRebillKey('api','P-3591625022','creative-17')]:api},trackedHtml=renderToStaticMarkup(<SourceBreakdown rows={rows} rebillAnalyses={analyses}/>),apiHtml=renderToStaticMarkup(<SourceBreakdown rows={rows.map(row=>({...row,trafficMode:'api' as const}))} apiMode rebillAnalyses={analyses}/>);expect(trackedHtml).toContain('1,00 Rebills je gewonnenem Kunden');expect(trackedHtml).not.toContain('3,00 Rebills je gewonnenem Kunden');expect(apiHtml).toContain('3,00 Rebills je gewonnenem Kunden');expect(apiHtml).not.toContain('1,00 Rebills je gewonnenem Kunden')});
 it('keeps source-row buckets traffic-mode specific before rendering',()=>{const page=readFileSync(join(process.cwd(),'src/app/affiliates/page.tsx'),'utf8');expect(page).toContain('`${row.trafficMode}|${row.offerId}|${row.offerUrlId}`');expect(page).toContain('`${v.trafficMode}|${v.offerId}|${v.offerUrlId}`')});
 it('keeps the rebill key helper outside the client component boundary so the server page can call it',()=>{const page=readFileSync(join(process.cwd(),'src/app/affiliates/page.tsx'),'utf8'),component=readFileSync(join(process.cwd(),'src/app/affiliates/SourceBreakdown.tsx'),'utf8');expect(page).toContain('source-rebill-key');expect(page).not.toMatch(/import SourceBreakdown,\s*\{\s*sourceRebillKey\s*\}/);expect(component).not.toContain('export const sourceRebillKey=')});
 it('offers an Offer-URL-scoped source finder in the direct-traffic source view',()=>{const siblingRows=rows.map(row=>({...row,pathKey:'8|7|0|2674',offerUrlId:'2674'})),first=renderToStaticMarkup(<SourceBreakdown rows={rows}/>),second=renderToStaticMarkup(<SourceBreakdown rows={siblingRows}/>);expect(first).toContain('data-source-search="source-breakdown-tracked-2673"');expect(second).toContain('data-source-search="source-breakdown-tracked-2674"')});
});
describe('SourceBreakdown decision thresholds footer',()=>{
 it('derives the thresholds from the decision engine constants instead of hard-coded numbers',()=>{const source=readFileSync(join(process.cwd(),'src/app/affiliates/SourceBreakdown.tsx'),'utf8');for(const name of['KILL_MATURITY_SOIS','DEAD_TRAFFIC_CLICKS','SCALE_MIN_SOIS','SCALE_MIN_FIRST_SALES','UNDERPERFORMANCE_FACTOR'])expect(source).toContain(name);expect(source).toContain('decision-engine');expect(source).not.toContain('100 Klicks');expect(source).not.toContain('20 SOIs');expect(source).not.toContain('Entscheidungsreif ab');const tracked=renderToStaticMarkup(<SourceBreakdown rows={rows}/>),api=renderToStaticMarkup(<SourceBreakdown rows={rows} apiMode/>);expect(tracked).toContain('Abschalten ab 100 Klicks ohne SOI, oder ab 50 SOIs ohne First-Sale bei negativem Profit');expect(tracked).toContain('oder ab 50 SOIs bei negativem Profit und belegter Unterperformance (First-Sale-Rate auch optimistisch unter 50 % des Vergleichswerts)');expect(tracked).not.toContain(', oder bei belegter Unterperformance');expect(tracked).toContain('Skalieren ab 20 SOIs mit mindestens 3 First-Sales und positivem Profit');expect(api).not.toContain('Klicks ohne SOI');expect(api).toContain('ab 50 SOIs ohne First-Sale bei negativem Profit');expect(api).toContain('oder ab 50 SOIs bei negativem Profit und belegter Unterperformance (First-Sale-Rate auch optimistisch unter 50 % des Vergleichswerts)');expect(api).not.toContain(', oder bei belegter Unterperformance');expect(api).toContain('Skalieren ab 20 SOIs mit mindestens 3 First-Sales und positivem Profit')});
});
