import{readFileSync}from'node:fs';import{join}from'node:path';import{describe,expect,it}from'vitest';
const read=(file:string)=>readFileSync(join(process.cwd(),file),'utf8');
describe('local source period UI integration',()=>{
 it('loads source snapshots from an independent resolved range',()=>{const page=read('src/app/affiliates/page.tsx');expect(page).toContain('resolveSourcePeriod(query)');expect(page).toContain("getAffiliateSourceBreakdown(selected.affiliateId,{from:sourcePeriod.from,to:sourcePeriod.to})");expect(page).toContain('rangeLabel={sourcePeriod.label}');expect(page).toContain('sourcePeriod={sourcePeriod}')});
 it('offers calendar-day presets and a bounded custom range with loading feedback',()=>{const controls=read('src/app/affiliates/SourcePeriodControls.tsx');for(const label of['Heute','7 Tage','30 Tage','90 Tage','Individuell'])expect(controls).toContain(label);expect(controls).toContain('buildSourcePeriodQuery');expect(controls).toContain('sourceFrom');expect(controls).toContain('sourceTo');expect(controls).toContain('max={period.maxDate}');expect(controls).toContain('aria-busy={pending}');expect(controls).toContain('Lädt …')});
 it('offers a dedicated year/month picker with a whole-year option',()=>{const controls=read('src/app/affiliates/SourcePeriodControls.tsx');for(const label of['Jahr / Monat','Ganzes Jahr','Jahr auswählen','Monat auswählen'])expect(controls).toContain(label);expect(controls).toContain('buildCalendarSourceRange');expect(controls).toContain("navigate('calendar'");expect(controls).toContain('sourceCalendarPeriod')});
 it('keeps the current source sort in the URL',()=>{const breakdown=read('src/app/affiliates/SourceBreakdown.tsx');expect(breakdown).toContain("params.set('sourceSort',next)");expect(breakdown).toContain("initialSort='sois'")});
 it('preserves the open offer and source disclosures across period navigation',()=>{const controls=read('src/app/affiliates/SourcePeriodControls.tsx'),page=read('src/app/affiliates/page.tsx'),breakdown=read('src/app/affiliates/SourceBreakdown.tsx');expect(controls).toContain('collectOpenSourceDetails');expect(controls).toContain("query.set('sourceOpen'");expect(controls).toContain('anchorId');expect(page).toContain('openSourceDetails');expect(page).toContain('defaultOpen={openSourceDetails.has(`url-${v.offerUrlId}`)}');expect(breakdown).toContain('defaultOpen={openSourceDetails.has(disclosureId)}')});
 it('shows one immediately visible Source coverage notice instead of one alert per lazy landing page',()=>{const page=read('src/app/affiliates/page.tsx');expect(page.match(/<SourceCacheNotice period=/g)).toHaveLength(1);expect(page).not.toContain('sourceError?<section className="sourceCacheError"')});
 it('shows available source rows with an honest partial-data notice instead of blocking them',()=>{const page=read('src/app/affiliates/page.tsx');expect(page).toContain('Vorhandene Quellen werden trotzdem angezeigt');expect(page).toContain('sourceFreshness&&!sourceFreshness.complete');expect(page).toContain('blocked={sourceError}')});
 it('classifies lead activity through the latest consecutive snapshot instead of the pending current day',()=>{const service=read('src/lib/affiliate-optimizer-service.ts');expect(service).toContain('resolveActivityCoverage(activityRange.from,freshness)');expect(service).not.toContain('coverageComplete:freshness.complete')});
});
