import{resolveAffiliatePeriod}from'./affiliate-period';
export type SourcePeriod='today'|'7d'|'30d'|'90d'|'12m'|'calendar'|'custom';
export type SourcePeriodQuery={sourcePeriod?:string;sourceFrom?:string;sourceTo?:string};
export const SOURCE_PERIODS:[SourcePeriod,string][]=[['today','Heute'],['7d','7 Tage'],['30d','30 Tage'],['90d','90 Tage'],['12m','12 Monate'],['calendar','Jahr / Monat'],['custom','Individuell']];
const allowed=new Set<SourcePeriod>(SOURCE_PERIODS.map(([id])=>id));
export function resolveSourcePeriod(query:SourcePeriodQuery,now=new Date()){const requested=allowed.has(query.sourcePeriod as SourcePeriod)?query.sourcePeriod as SourcePeriod:'30d',resolved=resolveAffiliatePeriod({period:requested==='calendar'?'custom':requested,from:query.sourceFrom,to:query.sourceTo},now);return{...resolved,period:requested==='calendar'?'calendar':resolved.period as SourcePeriod}}
export type ResolvedSourcePeriod=ReturnType<typeof resolveSourcePeriod>;
export function buildSourcePeriodQuery(current:string|URLSearchParams,period:SourcePeriod,from?:string,to?:string){const params=new URLSearchParams(current);params.set('sourcePeriod',period);params.delete('sourceFrom');params.delete('sourceTo');if(period==='custom'||period==='calendar'){if(from)params.set('sourceFrom',from);if(to)params.set('sourceTo',to)}return params.toString()}
export function buildCalendarSourceRange(year:string,month:string,maxDate:string){if(!/^\d{4}$/.test(year)||!/^\d{4}-\d{2}-\d{2}$/.test(maxDate)||!(month==='all'||/^(0[1-9]|1[0-2])$/.test(month)))return null;const y=Number(year),m=month==='all'?null:Number(month),from=m===null?`${year}-01-01`:`${year}-${month}-01`,last=m===null?`${year}-12-31`:`${year}-${month}-${String(new Date(Date.UTC(y,m,0)).getUTCDate()).padStart(2,'0')}`;if(from>maxDate)return null;return{from,to:last>maxDate?maxDate:last}}
