import type{ReportRow}from'./portfolio';
export type ConversionMetric={clicks:number;sois:number;cvr:number};
export type SourceBreakdownRow={pathKey:string;offerId:string;affiliateId:string;offerUrlId:string;sourceId:string;subSource:string;today:ConversionMetric;days7:ConversionMetric;days30:ConversionMetric};
export type BreakdownWindow='today'|'days7'|'days30';export type BreakdownSort='sois'|'cvr';
const dim=(r:ReportRow,type:string)=>r.columns.find(c=>c.column_type===type)||{id:'N/A',label:'N/A',column_type:type};
const blank=():ConversionMetric=>({clicks:0,sois:0,cvr:0});const finish=(m:ConversionMetric)=>({...m,cvr:m.clicks?100*m.sois/m.clicks:0});
export function aggregateSourceRows(rows:ReportRow[]){const map=new Map<string,{pathKey:string;offerId:string;affiliateId:string;offerUrlId:string;sourceId:string;subSource:string;metric:ConversionMetric}>();for(const row of rows){const campaign=dim(row,'campaign');if(campaign.id!=='0')continue;const offer=dim(row,'offer'),affiliate=dim(row,'affiliate'),url=dim(row,'offer_url'),source=dim(row,'source_id'),sub=dim(row,'sub1'),pathKey=`${offer.id}|${affiliate.id}|0|${url.id}`,sourceId=source.id==='N/A'?'Ohne Source-ID':source.label,subSource=sub.id==='N/A'?'Ohne Sub-Source':sub.label,key=`${pathKey}|${sourceId}|${subSource}`,current=map.get(key)||{pathKey,offerId:offer.id,affiliateId:affiliate.id,offerUrlId:url.id,sourceId,subSource,metric:blank()};current.metric.clicks+=Number(row.reporting.total_click||0);current.metric.sois+=Number(row.reporting.cv||0);map.set(key,current)}return[...map.values()].map(x=>({...x,metric:finish(x.metric)}))}
export function mergeSourceWindows(today:ReportRow[],days7:ReportRow[],days30:ReportRow[]):SourceBreakdownRow[]{const windows=[aggregateSourceRows(today),aggregateSourceRows(days7),aggregateSourceRows(days30)],keys=new Set(windows.flatMap(x=>x.map(y=>`${y.pathKey}|${y.sourceId}|${y.subSource}`)));return[...keys].map(key=>{const found=windows.map(rows=>rows.find(x=>`${x.pathKey}|${x.sourceId}|${x.subSource}`===key));const identity=found.find(Boolean)!;return{pathKey:identity.pathKey,offerId:identity.offerId,affiliateId:identity.affiliateId,offerUrlId:identity.offerUrlId,sourceId:identity.sourceId,subSource:identity.subSource,today:found[0]?.metric||blank(),days7:found[1]?.metric||blank(),days30:found[2]?.metric||blank()}})}
export function groupSources(rows:SourceBreakdownRow[],window:BreakdownWindow,sort:BreakdownSort){const map=new Map<string,{sourceId:string;metric:ConversionMetric;children:SourceBreakdownRow[]}>();for(const row of rows){const group=map.get(row.sourceId)||{sourceId:row.sourceId,metric:blank(),children:[]};group.metric.clicks+=row[window].clicks;group.metric.sois+=row[window].sois;group.children.push(row);map.set(row.sourceId,group)}const score=(m:ConversionMetric)=>sort==='sois'?m.sois:m.clicks?100*m.sois/m.clicks:0,groups=[...map.values()].map(g=>({...g,metric:finish(g.metric),children:g.children.sort((a,b)=>score(b[window])-score(a[window])||b[window].sois-a[window].sois)}));return groups.sort((a,b)=>score(b.metric)-score(a.metric)||b.metric.sois-a.metric.sois)}
