import{readFileSync}from'node:fs';import{join}from'node:path';import{describe,expect,it}from'vitest';
const read=(path:string)=>readFileSync(join(process.cwd(),path),'utf8');
describe('compact source block control',()=>{
 it('renders the modal through document.body so contained source rows cannot distort it',()=>{const source=read('src/app/affiliates/SourceBlockButton.tsx');expect(source).toContain("import { createPortal } from \"react-dom\"");expect(source).toContain('createPortal(modal, document.body)');expect(source).toContain('className="sourceBlockDialog"');});
 it('names the visible main and sub-source actions by their exact scope',()=>{const source=read('src/app/affiliates/SourceBlockButton.tsx');expect(source).toContain('const controlScope = isSubSource ? fieldSub : fieldMain');expect(source).toContain('{active ? `${controlScope} ausgeschaltet` : `${controlScope} ausschalten`}');expect(source).toContain('{controlScope} überall sperren');expect(source).not.toContain('{active ? "Ausgeschaltet" : "Ausschalten"}');expect(source).not.toContain('>Alle Produkte sperren</button>');});
 it('defines a compact viewport-safe dialog and a clearly outlined action button',()=>{const css=read('src/app/globals.css');expect(css).toContain('.sourceBlockIconButton{');expect(css).toContain('min-height:36px');expect(css).toContain('border:2px solid color-mix(in srgb,var(--negative) 68%,var(--border))');expect(css).toContain('box-shadow:0 1px 0 color-mix(in srgb,var(--negative) 18%,transparent)');expect(css).not.toContain('var(--danger)');expect(css).toContain('width:min(440px,calc(100vw - 32px))');expect(css).toContain('.sourceBlockModal{position:fixed;inset:0');});
 it('keeps the product-wide stop behind a separate scoped button and exact typed confirmation',()=>{const source=read('src/app/affiliates/SourceBlockButton.tsx');expect(source).toContain('{controlScope} überall sperren');expect(source).toContain('activate_across_offers');expect(source).toContain('confirmation !== requiredConfirmation');expect(source).toContain('Betroffene Offers');});
 it('renders unclear and pending records as disabled controls without any activation path',()=>{const source=read('src/app/affiliates/SourceBlockButton.tsx');expect(source).toContain('block.status === "error"');expect(source).toContain('block.status === "pending"');expect(source).toContain('Zustand unklar');expect(source).toContain('Verifizierung läuft');expect(source).toContain('aria-disabled');expect(source).toContain('title={lockedTitle}');expect(source).toContain('uncertain.error || "Zustand unklar"');expect(source).toContain('Kein zweiter Aktivierungsversuch ohne manuelle Prüfung in Everflow.');expect(source).toMatch(/\{!locked && \([\s\S]*überall sperren/);});
 it('labels every source block status truthfully on the audit page and marks unclear states',()=>{const page=read('src/app/source-blocks/page.tsx'),css=read('src/app/globals.css');expect(page).toContain("block.status==='active'?'AKTIV AUSGESCHALTET'");expect(page).toContain("block.status==='pending'?'VERIFIZIERUNG LÄUFT'");expect(page).toContain("block.status==='error'?'ZUSTAND UNKLAR'");expect(page).toContain("'WIEDER AKTIV'");expect(page).toContain("block.status==='error'&&");expect(page).toContain('Zuletzt verifiziert:');expect(page).toContain('Kein zweiter Aktivierungsversuch ohne manuelle Prüfung in Everflow.');expect(css).toContain('.sourceBlockAuditCard.error{border-color:var(--warning)');});
});
