import{readFileSync}from'node:fs';import{join}from'node:path';import React from'react';import{renderToStaticMarkup}from'react-dom/server';import{describe,expect,it}from'vitest';import SourceBreakdown from'../app/affiliates/SourceBreakdown';import{sourceRebillKey}from'./source-rebill-key';import{NO_SUB_SOURCE,type ConversionMetric,type SourceBreakdownRow}from'./source-breakdown';
import{analyzeRebillConcentration}from'./rebill-concentration';
const metric:ConversionMetric={clicks:0,sois:3,cvr:0,firstSales:1,firstSaleRate:100/3,rebills:2,coinSpend:0,payout:30,revenue:60,profit:30,profitPerSoi:10};const rows:SourceBreakdownRow[]=[{pathKey:'8|7|0|2673',offerId:'8',affiliateId:'7',offerUrlId:'2673',sourceId:'P-3591625022',subSource:'creative-17',trafficMode:'tracked',mainValue:'P-3591625022',subValue:'creative-17',today:metric,days7:metric,days30:metric,activity:{lastLeadDate:'2026-07-06',asOf:'2026-07-27',coverageComplete:true,lookbackDays:365}}];
describe('SourceBreakdown copy integration',()=>{
 it('renders a copy action for the tracked Source group',()=>{const html=renderToStaticMarkup(<SourceBreakdown rows={rows}/>);expect(html).toContain('Source P-3591625022 kopieren')});
 it('renders a copy action for the clickless ADV1 group',()=>{const html=renderToStaticMarkup(<SourceBreakdown rows={rows} apiMode/>);expect(html).toContain('ADV1 P-3591625022 kopieren')});
 it('uses Sub1 and ADV2 labels for the deepest values and offers one pair-copy action',()=>{const source=readFileSync(join(process.cwd(),'src/app/affiliates/SourceBreakdown.tsx'),'utf8'),html=renderToStaticMarkup(<SourceBreakdown rows={rows} openSourceDetails={new Set(['source-source-P-3591625022'])}/>);expect(source).toContain("label={apiMode?'ADV2':'Sub1'}");expect(source).toContain('value={leaf.subSource}');expect(html).toContain('Source + Sub1 kopieren')});
 it('shows the last lead date and inactivity duration on source and deepest-level cards',()=>{const html=renderToStaticMarkup(<SourceBreakdown rows={rows}/>);expect(html).toContain('Letzter Lead: 06.07.2026');expect(html).toContain('Seit 21 Tagen keine neuen Leads');expect(html).toContain('Vermutlich inaktiv')});
 it('shows rebills per customer and Top-1/Top-2 concentration on the deepest ADV2 row',()=>{const ids=[...Array(91).fill('a'),...Array(20).fill('b'),...Array(12).fill('c')],analysis=analyzeRebillConcentration({firstSales:17,totalRebills:123,customerIds:ids,firstSaleCustomerIds:['a','b','c',...Array.from({length:14},(_,i)=>`lead-${i}`)]}),html=renderToStaticMarkup(<SourceBreakdown rows={rows} apiMode openSourceDetails={new Set(['source-source-P-3591625022'])} rebillAnalyses={{'P-3591625022\u001fcreative-17':analysis}}/>);expect(html).toContain('7,24 Rebills je gewonnenem Kunden');expect(html).toContain('Top-Kunde');expect(html).toContain('90,2 %')});
 it('uses the same analysis key for a deepest missing Sub-Source leaf and its null aggregate representation',()=>{expect(sourceRebillKey('source-a',NO_SUB_SOURCE)).toBe(sourceRebillKey('source-a',null))});
 it('keeps the rebill key helper outside the client component boundary so the server page can call it',()=>{const page=readFileSync(join(process.cwd(),'src/app/affiliates/page.tsx'),'utf8'),component=readFileSync(join(process.cwd(),'src/app/affiliates/SourceBreakdown.tsx'),'utf8');expect(page).toContain('source-rebill-key');expect(page).not.toMatch(/import SourceBreakdown,\s*\{\s*sourceRebillKey\s*\}/);expect(component).not.toContain('export const sourceRebillKey=')});
 it('offers an Offer-URL-scoped source finder in the direct-traffic source view',()=>{const siblingRows=rows.map(row=>({...row,pathKey:'8|7|0|2674',offerUrlId:'2674'})),first=renderToStaticMarkup(<SourceBreakdown rows={rows}/>),second=renderToStaticMarkup(<SourceBreakdown rows={siblingRows}/>);expect(first).toContain('data-source-search="source-breakdown-tracked-2673"');expect(second).toContain('data-source-search="source-breakdown-tracked-2674"')});
});
