import{readFileSync}from'node:fs';import{join}from'node:path';import{describe,expect,it}from'vitest';
const read=(path:string)=>readFileSync(join(process.cwd(),path),'utf8');
const page=()=>read('src/app/sources/page.tsx'),list=()=>read('src/app/sources/SourceCandidateList.tsx'),bulk=()=>read('src/app/sources/SourceBulkBlockDialog.tsx'),button=()=>read('src/app/affiliates/SourceBlockButton.tsx');
describe('/sources page contract (Etappe 2, Q)',()=>{
 it('gates the page for internal roles with dashboard.view and keeps partners out (D7)',()=>{const source=page();expect(source).toContain("user.access.role==='partner'||!can(user.access,'dashboard.view')");expect(source).toContain('403 · Keine Berechtigung');expect(source).toContain('<AccessDeniedHint permission=');expect(source).toContain("export const dynamic='force-dynamic'")});
 it('reads the cron snapshot for the validated range with the user scope and explains the empty state',()=>{const source=page();expect(source).toContain("isSourceCandidateRange(params.range)?params.range:sourcesRangeFromPeriod(params.period)");expect(source).toContain('reportingRange(range)');expect(source).toContain('loadSourceCandidates({from:period.from!,to:period.to},user.access)');expect(source).toContain('stündlich um Minute 47');expect(read('vercel.json')).toContain('"schedule": "47 * * * *"')});
 it('shows the shared data status, the rollup line and the coverage warning',()=>{const source=page();expect(source).toContain('getDataStatus(),header=headerStatus(dataStatus)');expect(source).toContain('<DataStatusBar status={dataStatus}/>');expect(source).toContain('Rollup vom {berlinDateTime(snapshot.generatedAt)} · {snapshot.affiliatesProcessed} von {snapshot.affiliates} Partnern');expect(source).toContain('rollupStaleWarning(snapshot.generatedAt)');expect(source).toContain('snapshot.rowsTruncated&&');expect(source).toContain('!snapshot.coverageComplete&&');expect(source).toContain('Rollup unvollständig')});
 it('derives the block state through the shared block index and money only with finance.view',()=>{const source=page(),view=read('src/lib/source-candidate-view.ts');expect(source).toContain('loadBlockIndex()');expect(source).toContain("finance=can(user.access,'finance.view')");expect(source).toContain('prepareSourceCandidateRows(snapshot.rows,index,{finance})');expect(view).toContain('block:resolveCandidateBlock(row,index),blockable:isBlockableCandidate(row)');expect(view).toContain('for(const key of sourceCandidateBlockKeys(row))');expect(view).toContain('payout:options.finance?row.payout:null');expect(source).toContain("mayBlock=can(user.access,'landingpages.manage')&&can(user.access,'api.manage')")});
 it('resolves ?open through the shared link contract, marks the row by DOM id and scrolls to it',()=>{const source=page(),client=list();expect(source).toContain('parseSourceCandidateKey(params.open)');expect(source).toContain('openKey=openIdentity?sourceCandidateKey(openIdentity):null');expect(client).toContain('id={row.domId}');expect(read('src/lib/source-candidate-view.ts')).toContain('domId:sourceCandidateDomId(row)');expect(client).toContain("className={isOpen?'sourcesOpenRow':undefined}");expect(client).toContain("document.getElementById(openRow.domId)?.scrollIntoView({block:'center'})");expect(client).toContain('selectSourceCandidates(rows,deferredFilters,sort,limit,openKey)');expect(client).toContain('useDeferredValue(filters)');expect(client).toContain('autoOpen={isOpen}')});
 it('lists the top 50 with a show-more control, filters and default profit sorting (D10)',()=>{const client=list(),view=read('src/lib/source-candidate-view.ts');expect(view).toContain('SOURCE_CANDIDATE_PAGE_SIZE=50');expect(client).toContain('setLimit(current=>current+SOURCE_CANDIDATE_PAGE_SIZE)');expect(client).toContain('Quellen anzeigen</button>');for(const option of['value="AUSSCHALTEN"','value="SKALIEREN"','value="BEOBACHTEN"','value="tracked"','value="api"','value="open"','value="blocked"'])expect(client).toContain(option);expect(view).toContain("sort:isSourceCandidateSort(params.sort)?params.sort:'profit'")});
 it('renders blocked rows as state with a link and without a block action; unblocked rows get the inline button with metrics and 44 px targets',()=>{const client=list(),css=read('src/app/globals.css');expect(client).toContain('Gesperrt seit ${berlinDay(block.effectiveAt)}');expect(client).toContain('NOT_BLOCKABLE_HINT');expect(client).toContain('onFinished={refreshBlocks}');expect(client).toContain('href="/source-blocks"');expect(client).toMatch(/row\.block\?<>[\s\S]*blockLabel\(row\.block\)/);expect(client).toContain("metrics={{payout:row.payout,sois:row.sois,profit:row.profit,clicks:row.clicks,firstSales:row.firstSales,maturity:maturityLabel(row),leadStatus:row.leadStatus,trend:trendLabel(row,finance)??'für diesen Zeitraum nicht berechnet'}}");expect(client).toContain('showMoney={finance}');expect(client).toContain('trend:trendLabel(row,finance)');expect(read('src/app/affiliates/SourceBlockButton.tsx')).toContain('<dt>Trend</dt>');expect(css).toContain('.sourcesRowAction .sourceBlockIconButton{min-height:44px}');expect(css).toContain('.sourcesSelect{display:grid;place-items:center;width:44px;height:44px');expect(css).toContain('.sourcesBulkButton{margin-left:auto;min-height:44px')});
 it('runs the bulk block as one dialog with a shared reason and sequential existing POST activate calls, capped at five',()=>{const client=list(),dialog=bulk(),view=read('src/lib/source-candidate-view.ts');expect(view).toContain('BULK_BLOCK_LIMIT=5');expect(client).toContain('toggleBulkSelection(selected,key,BULK_BLOCK_LIMIT)');expect(client).toContain('Maximal {BULK_BLOCK_LIMIT} Quellen gleichzeitig');expect(client).toContain('Ausgewählte sperren');expect(client).toContain('rows={selectedRows.slice(0,BULK_BLOCK_LIMIT)}');expect(dialog).toContain('for(const row of rows){');expect(dialog).toContain("body:JSON.stringify({action:'activate',affiliateId:row.affiliateId,affiliateName:row.affiliate,offerId:row.offerId,offerName:row.offer,trafficMode:row.trafficMode,level:row.level,mainValue:row.mainValue,subValue:row.subValue,reasonCategory,reason})");expect(dialog).not.toContain('bulk_activate');expect(dialog).not.toContain('activate_across_offers');expect(dialog).toContain("disabled={running||!reasonCategory||!rows.length}");expect(dialog).toContain("status:'error',message:error instanceof Error?error.message");expect(dialog).toContain('onBlocked(row.key,blockStateFromRecord(body.block as SourceBlockRecord))');expect(dialog).toContain('{ok} gesperrt · {failed} fehlgeschlagen')});
 it('keeps the verdict word AUSSCHALTEN on the source level (D13) and shows the API detection note (D21)',()=>{expect(read('src/lib/source-candidate-view.ts')).toContain('export const verdictLabel=(action:SourceCandidateAction)=>action;');expect(read('src/lib/source-candidates.ts')).not.toContain("'AB"+"SCHALTEN'");expect(list()).toContain("'API · aus Offer-Name erkannt'")});
});
describe('source block dialog contract (Etappe 2, Q)',()=>{
 it('shows key figures before confirmation when the caller provides them',()=>{const source=button();expect(source).toContain('export type SourceBlockDialogMetrics');expect(source).toContain('metrics?: SourceBlockDialogMetrics');expect(source).toContain('{metrics && (');expect(source).toContain('aria-label="Kennzahlen vor der Bestätigung"');for(const label of['<dt>Payout</dt>','<dt>SOIs</dt>','<dt>Profit</dt>','<dt>First-Sale-Rate</dt>','<dt>Klicks</dt>','<dt>Reife · Lead-Status</dt>','<dt>Sperrstatus</dt>'])expect(source).toContain(label);expect(source).toContain('STATE_WORDS.blockedSince(day(active.effectiveAt))');expect(source).toContain('showMoney && metrics.payout !== null')});
 it('requires the reason category from the shared list and sends category plus optional reason on both activation paths',()=>{const source=button();expect(source).toContain('SOURCE_BLOCK_REASON_CATEGORIES.map((category) =>');expect(source).toContain('SOURCE_BLOCK_REASON_LABELS[category]');expect(source).toContain('Grundkategorie <span>Pflicht</span>');expect(source).toContain('optional · max. 500 Zeichen');expect(source).toContain('maxLength={500}');expect(source).toContain('(activating && !reasonCategory)');expect(source).toContain('body: JSON.stringify({ action: productWide ? "activate_across_offers" : "activate", ...identity, reasonCategory, reason, confirmation })');expect(source).not.toContain('...props, reason, confirmation');expect(read('src/app/api/source-blocks/route.ts')).toContain('const REASON_CATEGORY_REQUIRED=true')});
 it('previews product-wide blocks with per-offer sums and existing blocks, and lazy-loads the history for existing blocks',()=>{const source=button();expect(source).toContain('action:"preview_across_offers"');expect(source).toContain('{integer(item.sois)} SOIs');expect(source).toContain('item.blocked&&<span className="sourceBlockOfferBlocked">bereits gesperrt</span>');expect(source).toContain('`/api/source-blocks?action=history&id=${encodeURIComponent(existing.id)}`');expect(source).toContain('onClick={loadHistory}');expect(source).toContain('sourceBlockHistoryActionLabel(event.action)');expect(source).toContain('event.reasonCategory ? SOURCE_BLOCK_REASON_LABELS[event.reasonCategory]');expect(source).toContain('<span>{event.actorId}</span>')});
 it('keeps the Etappe-1 states untouched and notifies list callers after activation',()=>{const source=button();expect(source).toContain('const locked = Boolean(pending || (uncertain && !recoverable))');expect(source).toContain('? "Nach Everflow-Prüfung deaktivieren"');expect(source).toContain('onBlocked?: (records: SourceBlockRecord[]) => void');expect(source).toContain('props.onBlocked?.(changed)');for(const caller of['src/app/affiliates/SourceBreakdown.tsx','src/app/source-blocks/page.tsx','src/app/components/SmartlinkPresentation.tsx'])expect(read(caller)).toContain('<SourceBlockButton')});
});
