import{describe,expect,it}from'vitest';
import{readFileSync}from'node:fs';
import{join}from'node:path';

const source=()=>readFileSync(join(process.cwd(),'src/lib/supabase.ts'),'utf8');
describe('Supabase sync lock contract',()=>{
 it('takes unique database locks before replacement and releases only its owner token',()=>{const code=source(),acquire=code.indexOf('const release=await acquireMetricReplaceLock()'),replace=code.indexOf(".rpc('replace_metric_window'",acquire),release=code.indexOf('finally{await release()}',replace);expect(code).toContain("acquireSyncStateLock('daily_metrics_replace_lock'");expect(code).toContain("acquireSyncStateLock('everflow_history_sync_lock'");expect(code).toContain(".insert({key,value:{owner,expires_at:expiresAt}})");expect(code).toContain(".contains('value',{owner})");expect(acquire).toBeGreaterThan(-1);expect(replace).toBeGreaterThan(acquire);expect(release).toBeGreaterThan(replace)});
 it('fails closed on a live competing lock and only steals an expired lock by matching its owner',()=>{const code=source();expect(code).toContain("inserted.error.code!=='23505'");expect(code).toContain('Date.parse(value.expires_at)<Date.now()');expect(code).toContain("contains('value',{owner:value.owner})");expect(code).toContain('läuft bereits')});
 it('bounds abandoned lock recovery close to the five-minute function limit',()=>{const code=source();expect(code).toContain("acquireSyncStateLock('daily_metrics_replace_lock',10*60_000");expect(code).toContain("acquireSyncStateLock('everflow_history_sync_lock',10*60_000")});
 it('holds the route-level lock across scheduled and manual sync workflows',()=>{const route=readFileSync(join(process.cwd(),'src/app/api/sync/route.ts'),'utf8');expect(route.match(/acquireHistorySyncLock\(\)/g)).toHaveLength(2);expect(route.match(/finally\{await release\(\)\}/g)).toHaveLength(2)});
 it('prunes day snapshot generations once per refreshed range instead of issuing per-day cleanup storms',()=>{const code=source(),start=code.indexOf('async function upsertSourceSnapshots'),end=code.indexOf('async function acquireSyncStateLock',start),body=code.slice(start,end);expect(code).toContain('async function pruneDaySnapshotRange');expect(body).not.toContain('await pruneDaySnapshots(day)');expect(body).toContain('await pruneDaySnapshotRange(from,to,activeGenerations)')});
 it('replaces each metric window through a JSON-body RPC instead of URL-sized id filters',()=>{const code=source(),replace=code.slice(code.indexOf('async replaceMetrics'),code.indexOf('async setState'));expect(replace).toContain(".rpc('replace_metric_window'");expect(replace).toContain('p_rows:canonical');expect(replace).not.toContain('existingMetricIds');expect(replace).not.toContain('zeroMetrics');expect(code).not.toContain(".in('id',batch)")});
});
