import{describe,expect,it}from'vitest';
import{readFileSync}from'node:fs';
import{join}from'node:path';
import{boundedPostgrestInBatches,postgrestInFilterBytes}from'./supabase';

const source=()=>readFileSync(join(process.cwd(),'src/lib/supabase.ts'),'utf8');
describe('Supabase sync lock contract',()=>{
 it('takes unique database locks before replacement and releases only its owner token',()=>{const code=source(),acquire=code.indexOf('const release=await acquireMetricReplaceLock()'),scan=code.indexOf('existingMetricIds(from,to)',acquire),release=code.indexOf('finally{await release()}',scan);expect(code).toContain("acquireSyncStateLock('daily_metrics_replace_lock'");expect(code).toContain("acquireSyncStateLock('everflow_history_sync_lock'");expect(code).toContain(".insert({key,value:{owner,expires_at:expiresAt}})");expect(code).toContain(".contains('value',{owner})");expect(acquire).toBeGreaterThan(-1);expect(scan).toBeGreaterThan(acquire);expect(release).toBeGreaterThan(scan)});
 it('fails closed on a live competing lock and only steals an expired lock by matching its owner',()=>{const code=source();expect(code).toContain("inserted.error.code!=='23505'");expect(code).toContain('Date.parse(value.expires_at)<Date.now()');expect(code).toContain("contains('value',{owner:value.owner})");expect(code).toContain('läuft bereits')});
 it('bounds abandoned lock recovery close to the five-minute function limit',()=>{const code=source();expect(code).toContain("acquireSyncStateLock('daily_metrics_replace_lock',10*60_000");expect(code).toContain("acquireSyncStateLock('everflow_history_sync_lock',10*60_000")});
 it('holds the route-level lock across scheduled and manual sync workflows',()=>{const route=readFileSync(join(process.cwd(),'src/app/api/sync/route.ts'),'utf8');expect(route.match(/acquireHistorySyncLock\(\)/g)).toHaveLength(2);expect(route.match(/finally\{await release\(\)\}/g)).toHaveLength(2)});
 it('prunes day snapshot generations once per refreshed range instead of issuing per-day cleanup storms',()=>{const code=source(),start=code.indexOf('async function upsertSourceSnapshots'),end=code.indexOf('async function acquireSyncStateLock',start),body=code.slice(start,end);expect(code).toContain('async function pruneDaySnapshotRange');expect(body).not.toContain('await pruneDaySnapshots(day)');expect(body).toContain('await pruneDaySnapshotRange(from,to,activeGenerations)')});
 it('keeps long stale metric id filters below the PostgREST URL budget',()=>{const ids=Array.from({length:200},(_,index)=>`metric:2026-08-04:32:57:campaign-${index}:${'source-segment-'.repeat(10)}${index}`),budget=5_000,batches=boundedPostgrestInBatches(ids,budget);expect(batches.length).toBeGreaterThan(1);expect(batches.flat()).toEqual(ids);expect(Math.max(...batches.map(postgrestInFilterBytes))).toBeLessThanOrEqual(budget)});
});
