import Link from 'next/link';import {redirect} from 'next/navigation';import {currentUser} from '@/lib/session';import {findCampaigns,getSmartlinkInsight} from '@/lib/smartlink-service';import SmartlinkWatchlist from './SmartlinkWatchlist';
export const dynamic='force-dynamic';const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);const num=(n:number)=>new Intl.NumberFormat('de-DE').format(n);const pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`;const time=(epoch:number)=>new Date(epoch*1000).toLocaleTimeString('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit'});
export default async function SmartlinksPage({searchParams}:{searchParams:Promise<{campaign?:string;q?:string;refresh?:string;ts?:string}>}){if(!await currentUser())redirect('/login');const query=await searchParams;const campaignId=/^\d+$/.test(query.campaign||'')?Number(query.campaign):null;const search=(query.q||'').trim();const results=!campaignId&&search?await findCampaigns(search):[];let data:Awaited<ReturnType<typeof getSmartlinkInsight>>|null=null,error='';if(campaignId)try{data=await getSmartlinkInsight(campaignId,query.refresh==='1')}catch(e){error=e instanceof Error?e.message:'Smartlink konnte nicht geladen werden'}
 const primary=data?[...data.recommendations].sort((a,b)=>({critical:0,warning:1,positive:2,neutral:3}[a.severity]-{critical:0,warning:1,positive:2,neutral:3}[b.severity]))[0]:null;const maxClicks=Math.max(1,...(data?.hourly24.map(x=>x.clicks)||[1]));const rotationLabel=data?.rotationStartEpoch?`Aktuelle Rotation seit ${new Date(data.rotationStartEpoch*1000).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})}`:'Aktuelle Rotation: Teststart unbekannt · max. 14 Tage';
 return <main className="dashboard smartMonitor"><header className="topbar"><div><div className="eyebrow">ME MEDIA · BUSINESS INTELLIGENCE</div><h1>Smartlink Intelligence <span>Beta</span></h1><p>Smartlink suchen, stündlich analysieren und datenbasierte Maßnahmen ableiten.</p></div><div className="topActions"><Link className="logout" href="/affiliates">Affiliate Optimizer</Link><Link className="logout" href="/automation">Auto-Rotation</Link><Link className="logout" href="/">Account Monitor</Link><form action="/api/auth/logout" method="post"><button className="logout">Abmelden</button></form></div></header>
 <section className="smartSearch"><form method="get" action="/smartlinks"><label htmlFor="q">Campaign-ID oder Smartlink-Name</label><div><input id="q" name="q" defaultValue={search} placeholder="z. B. 146 oder Traffic Company"/><button>Suchen</button></div></form>{data&&<a className="refreshBtn" href={`/smartlinks?campaign=${data.identity.campaignId}&refresh=1&ts=${Date.now()}`}>Jetzt aktualisieren</a>}</section>
 <SmartlinkWatchlist current={data?{id:data.identity.campaignId,name:data.identity.name}:undefined}/>
 {!campaignId&&search&&<section className="searchResults"><div className="sectionHead"><div><span>Suchergebnisse</span><h2>{results.length} Smartlinks gefunden</h2></div></div>{results.length?results.map(c=><Link key={c.network_campaign_id} href={`/smartlinks?campaign=${c.network_campaign_id}`}><b>#{c.network_campaign_id}</b><span>{c.campaign_name}</span><em>{c.campaign_status}</em></Link>):<p>Keine passende Campaign gefunden.</p>}</section>}
 {!campaignId&&!search&&<section className="smartEmpty"><b>Startpunkt</b><h2>Welchen Smartlink soll ich beobachten?</h2><p>Suche oben nach der Everflow-Campaign-ID oder dem Namen. Gespeicherte Smartlinks bleiben in diesem Browser in deiner Beobachtungsliste.</p><div><Link href="/smartlinks?campaign=2">TrafficPartner · #2</Link><Link href="/smartlinks?campaign=146">Traffic Company · #146</Link></div></section>}
 {error&&<section className="fatal"><div className="eyebrow">ABRUF FEHLGESCHLAGEN</div><h1>{error}</h1><Link href="/smartlinks">Zur Suche</Link></section>}
 {data&&<><section className="smartIdentity"><div><span>CAMPAIGN #{data.identity.campaignId}</span><h2>{data.identity.name}</h2><p>{data.identity.affiliate} · Affiliate #{data.identity.affiliateId} · Offer {data.identity.offerIds.map(x=>`#${x}`).join(', ')}</p></div><div><b className={data.identity.status==='active'?'up':'down'}>{data.identity.status}</b><small>Campaign-Filter verifiziert</small></div></section>
 {primary&&<section className={`decisionBanner ${primary.severity}`}><div><span>AKTUELLE BI-EMPFEHLUNG · READ ONLY</span><h2>{primary.title}</h2><p>{primary.detail}</p></div><div><b>{primary.action.toUpperCase()}</b><small>Nächste Bewertung beim Refresh</small></div></section>}
 <section className="windowNote"><b>Getrennte Messfenster:</b><span>24h Traffic</span><span>72h Monetarisierung</span><span>14d Entscheidungsreife</span></section>
 <section className="kpis smartKpis"><article className="kpi hero"><span>Profit · 72h</span><strong className={data.money72.profit>=0?'up':'down'}>{euro(data.money72.profit)}</strong><small>Run-rate 24h: {euro(data.money72.profit/3)} · keine Garantie</small></article><article className="kpi"><span>Smartlink-CVR · 24h</span><strong>{pct(data.traffic24.cvr)}</strong><small>{num(data.traffic24.sois)} SOIs / {num(data.traffic24.clicks)} Klicks</small></article><article className="kpi"><span>Monetarisierung · 72h</span><strong>{data.money72.firstSales} / {data.money72.rebills}</strong><small>First-Sales / Rebills · {data.money72.coinSpend} Coin Spend</small></article><article className="kpi"><span>Umsatz / Payout · 72h</span><strong>{euro(data.money72.revenue)}</strong><small>{euro(data.money72.payout)} Payout</small></article><article className="kpi"><span>Profit-EPC · 72h</span><strong className={data.money72.profitEpc>=0?'up':'down'}>{euro(data.money72.profitEpc)}</strong><small>Campaign inkl. Legacy-Umsatz</small></article></section>
 <section className="sectionHead"><div><span>AKTUELLE LIVE-ROTATION</span><h2>{data.currentSlots.length} aktive Landingpages</h2></div><div className="scope">{rotationLabel} · 24h Traffic</div></section><section className="intelligenceSlots">{data.currentSlots.map(slot=>{const r=data.recommendations.find(x=>x.slotId===slot.id)!;return <article key={slot.id} className={`intelSlot ${r.severity}`}><header><div><span>LP #{slot.id} · {slot.weight} %</span><h3>{slot.name}</h3></div><b>{r.action}</b></header><div className="slotDecision"><strong>{r.title}</strong><p>{r.detail}</p></div><div className="metricGrid"><div><b>{num(slot.metrics24.clicks)}</b><span>Klicks · 24h</span></div><div><b>{num(slot.metrics24.sois)}</b><span>SOIs · 24h</span></div><div><b>{pct(slot.metrics24.cvr)}</b><span>CVR · 24h</span></div><div><b>{slot.hoursTo50Sois===null?'–':`${slot.hoursTo50Sois}h`}</b><span>bis 50 SOIs · Run-rate</span></div></div><div className="evidenceGrid"><div><span>SOIs · Rotation</span><b>{slot.metrics14.sois}</b></div><div><span>First-Sales · Rotation</span><b>{slot.metrics14.firstSales}</b></div><div><span>First-Sale-Rate</span><b>{pct(slot.metrics14.firstSaleRate)}</b></div><div><span>Rebills</span><b>{slot.metrics14.rebills}</b></div><div><span>Profit · Rotation</span><b className={slot.metrics14.profit>=0?'up':'down'}>{euro(slot.metrics14.profit)}</b></div><div><span>Profit-EPC · Rotation</span><b>{euro(slot.metrics14.profitEpc)}</b></div></div></article>})}</section>
 <section className="sectionHead"><div><span>STUNDENBASIS · LETZTE 24H</span><h2>Traffic- und SOI-Verlauf</h2></div><div className="scope">Europe/Berlin</div></section><section className="hourlyChart">{data.hourly24.map(point=><div className="hourRow" key={point.epoch}><span>{time(point.epoch)}</span><div className="barTrack"><i style={{width:`${Math.max(point.clicks?2:0,100*point.clicks/maxClicks)}%`}}/></div><b>{point.clicks}</b><em>{point.sois} SOI · {pct(point.cvr)}</em></div>)}</section>
 <section className="auditStrip"><div><span>14d Gesamtprofit</span><b className={data.mature14.profit>=0?'up':'down'}>{euro(data.mature14.profit)}</b></div><div><span>14d First-Sales / Rebills</span><b>{data.mature14.firstSales} / {data.mature14.rebills}</b></div><div><span>Legacy-Beitrag · 14d</span><b>{euro(data.legacy14.profit)}</b></div><div><span>Stand</span><b>{new Date(data.generatedAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})}</b></div></section>
 <footer><div><b>BI-Modus: Read only</b><span>Empfehlungen ändern Everflow nicht automatisch. First-Sales = ausschließlich Event „Sale“; Coin Spend separat.</span></div><div>Manueller Refresh umgeht den 60-Sekunden-Cache.</div></footer></>}
 </main>}
