import {NextResponse} from 'next/server';
import {revalidateTag} from 'next/cache';
import {audit,requestEvidence,securityStore} from '@/lib/access-store';
import {readEverflowCampaignStatus,setEverflowCampaignStatus,type CampaignStatus} from '@/lib/everflow-campaign-status';
import {getCampaignAffiliateMappings} from '@/lib/smartlink-service';
import {patchCampaignSnapshotStatus} from '@/lib/campaign-snapshots';
import {can} from '@/lib/rbac';
import {requirePermission} from '@/lib/session';
import {canonicalOrigin,checkCsrf,parseBoundedJson,securityHeaders,withSecurityLock} from '@/lib/security';
export const dynamic='force-dynamic';
const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{...securityHeaders,'Cache-Control':'private, no-store'}});
const mayManage=(access:Parameters<typeof can>[0])=>access.role!=='partner'&&can(access,'campaigns.edit')&&can(access,'api.manage');
const day=(date:Date)=>date.toISOString().slice(0,10);
async function assertVisibleCampaign(campaignId:number,affiliateId:string,access:Parameters<typeof can>[0]){if(!/^\d+$/.test(affiliateId))throw new Error('Affiliate-ID ungültig');const to=new Date(),from=new Date(to.getTime()-366*86_400_000),rows=await getCampaignAffiliateMappings({from:day(from),to:day(to)},access),visible=rows.some(row=>row.campaignId===campaignId&&row.affiliateId===affiliateId);if(!visible)throw new Error('Die Campaign-/Affiliate-Kombination ist im freigegebenen Scope nicht vorhanden. Keine Änderung durchgeführt.');}
export async function POST(request:Request){const auth=await requirePermission('api.manage');if(!auth.ok)return json({error:auth.status===401?'Nicht angemeldet':'Keine Berechtigung'},auth.status);if(!mayManage(auth.user.access))return json({error:'Keine Berechtigung'},403);let origin:string;try{origin=canonicalOrigin(process.env.APP_ORIGIN,process.env.NODE_ENV,request.url)}catch{return json({error:'Serverkonfiguration ungültig'},500)}if(!checkCsrf(request,origin))return json({error:'Anfrage abgelehnt'},403);let input:Record<string,unknown>;try{input=await parseBoundedJson(request)}catch{return json({error:'Ungültige Anfrage'},400)}const campaignId=Number(input.campaignId),affiliateId=String(input.affiliateId||''),status=input.status as CampaignStatus;if(!Number.isSafeInteger(campaignId)||campaignId<=0||!['active','paused'].includes(status))return json({error:'Campaign-ID oder Zielstatus ungültig'},400);try{const apiKey=process.env.EVERFLOW_API_KEY||'',campaign=await withSecurityLock(securityStore(),`campaign-status:${campaignId}`,async()=>{await assertVisibleCampaign(campaignId,affiliateId,auth.user.access);const before=await readEverflowCampaignStatus(campaignId,apiKey),after=await setEverflowCampaignStatus(campaignId,status,apiKey);try{await audit({actorId:auth.user.actorId,action:status==='paused'?'campaign.pause':'campaign.resume',targetId:String(campaignId),before,after,...requestEvidence(request)})}catch(auditError){try{const rollback=await setEverflowCampaignStatus(campaignId,before.status as CampaignStatus,apiKey);console.error('CAMPAIGN_AUDIT_FAILED_ROLLED_BACK',{campaignId,requestId:request.headers.get('x-request-id')||null,restoredStatus:rollback.status})}catch(rollbackError){console.error('CAMPAIGN_STATUS_UNCLEAR_MANUAL_INTERVENTION',{campaignId,requestId:request.headers.get('x-request-id')||null,auditError,rollbackError});throw new Error('Status unklar: Audit und verifizierter Rollback fehlgeschlagen. Manuelle Prüfung erforderlich.')}throw new Error('Audit fehlgeschlagen; Campaign-Änderung wurde zurückgerollt und verifiziert.')}try{await patchCampaignSnapshotStatus(campaignId,after.status)}catch(patchError){console.error('CAMPAIGN_SNAPSHOT_PATCH_FAILED',{campaignId,requestId:request.headers.get('x-request-id')||null,patchError})}return after});revalidateTag('campaign-directory',{expire:0});revalidateTag('campaign-affiliate-directory',{expire:0});revalidateTag(`smartlink-${campaignId}`,{expire:0});revalidateTag(`affiliate-smartlinks-${affiliateId}`,{expire:0});return json({ok:true,campaign})}catch(error){console.error('Campaign status mutation failed',error);return json({error:error instanceof Error?error.message:'Campaign-Status fehlgeschlagen'},500)}}
