'use client';
import{useEffect,useState}from'react';
type InstallPrompt=Event&{prompt():Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
const decode=(value:string)=>{const padding='='.repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,char=>char.charCodeAt(0))};
export default function AppInstallation(){const[supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[devices,setDevices]=useState(0),[publicKey,setPublicKey]=useState(''),[oneSignal,setOneSignal]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null),[standalone,setStandalone]=useState(false);
 const request=async(action:string,extra:Record<string,unknown>={})=>{const response=await fetch('/api/push',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Aktion fehlgeschlagen');return data};
 useEffect(()=>{const hasSupport='serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;setSupported(hasSupport);setStandalone(window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));const handler=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPrompt)};window.addEventListener('beforeinstallprompt',handler);(async()=>{try{const response=await fetch('/api/push',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Push nicht verfügbar');setPublicKey(data.publicKey);setDevices(data.devices||0);setOneSignal(Boolean(data.oneSignalConfigured));if(hasSupport){const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription){const status=await request('status',{endpoint:subscription.endpoint});setEnabled(Boolean(status.enabled));setDevices(status.devices||0)}}}catch(error){setMessage(error instanceof Error?error.message:'Push-Status nicht erreichbar')}})();return()=>window.removeEventListener('beforeinstallprompt',handler)},[]);
 const enable=async()=>{setBusy(true);setMessage('');try{if(!supported||!publicKey)throw new Error('Push wird auf diesem Gerät nicht unterstützt');if(await Notification.requestPermission()!=='granted')throw new Error('Benachrichtigungen wurden nicht erlaubt');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(publicKey)});const data=await request('subscribe',{subscription:subscription.toJSON()});setEnabled(true);setDevices(data.devices||devices);setMessage('Benachrichtigungen sind auf diesem Gerät aktiv.')}catch(error){setMessage(error instanceof Error?error.message:'Aktivierung fehlgeschlagen')}finally{setBusy(false)}};
 const disable=async()=>{setBusy(true);setMessage('');try{const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription){const data=await request('unsubscribe',{endpoint:subscription.endpoint});await subscription.unsubscribe();setDevices(data.devices||0)}setEnabled(false);setMessage('Dieses Gerät wurde abgemeldet.')}catch(error){setMessage(error instanceof Error?error.message:'Abmeldung fehlgeschlagen')}finally{setBusy(false)}};
 const test=async()=>{setBusy(true);setMessage('');try{const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(!subscription)throw new Error('Dieses Gerät ist nicht registriert');await request('test',{endpoint:subscription.endpoint});setMessage('Testbenachrichtigung wurde an dieses Gerät gesendet.')}catch(error){setMessage(error instanceof Error?error.message:'Test fehlgeschlagen')}finally{setBusy(false)}};
 const testOneSignal=async()=>{setBusy(true);setMessage('');try{await request('onesignal-test');setMessage('OneSignal-Test wurde an deine verbundene external_id gesendet.')}catch(error){setMessage(error instanceof Error?error.message:'OneSignal-Test fehlgeschlagen')}finally{setBusy(false)}};
 const install=async()=>{if(installPrompt){await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==='accepted')setStandalone(true);setInstallPrompt(null)}else setMessage('iPhone/iPad: Teilen → „Zum Home-Bildschirm“. Desktop/Android: Installieren im Browsermenü wählen.')};
 return <section className="appInstallGrid"><article className="appInstallCard"><span className="appInstallEyebrow">App installieren</span><h2>Desktop- oder Mobile-App</h2><p>Installiert das Dashboard direkt aus dem Browser – ohne App Store. Es öffnet sich danach in einem eigenen App-Fenster.</p><button type="button" onClick={install} disabled={standalone}>{standalone?'Bereits als App installiert':'App installieren'}</button><small>Unter iOS über Teilen → Zum Home-Bildschirm.</small></article><article className="appInstallCard"><span className="appInstallEyebrow">Benachrichtigungen</span><h2>Push auf diesem Gerät</h2><p>Erhalte auch bei geschlossenem Dashboard Hinweise. Jede Browser-/Geräteinstallation wird separat freigegeben.</p><div className="appInstallActions">{enabled?<><button type="button" onClick={test} disabled={busy}>Test an dieses Gerät</button><button type="button" className="secondary" onClick={disable} disabled={busy}>Gerät abmelden</button></>:<button type="button" onClick={enable} disabled={busy||!supported}>Benachrichtigungen aktivieren</button>}</div><small>{supported?enabled?`Dieses Gerät ist registriert (${devices} insgesamt).`:`Dieses Gerät ist nicht registriert (${devices} insgesamt).`:'Dieser Browser unterstützt Web Push nicht.'}</small></article><article className="appInstallCard"><span className="appInstallEyebrow">OneSignal API</span><h2>Externer Push-Kanal</h2><p>Der sichere Serveradapter ist vorbereitet. Später wird dein OneSignal-Gerät über die interne Benutzer-ID als external_id verbunden.</p>{oneSignal?<button type="button" onClick={testOneSignal} disabled={busy}>OneSignal-Verbindung testen</button>:<button type="button" disabled>Umgebungsvariablen fehlen</button>}<small>{oneSignal?'OneSignal API ist serverseitig konfiguriert.':'Benötigt ONESIGNAL_APP_ID und ONESIGNAL_REST_API_KEY.'}</small></article>{message&&<p className="appInstallMessage" role="status">{message}</p>}</section>}
