import{NextResponse}from'next/server';
import{audit,requestEvidence}from'@/lib/access-store';
import{listPushSubscriptions,ownsPushEndpoint,publicVapidKey,rateLimitPushMutation,rateLimitPushTest,reconcilePushSubscription,removePushSubscription,savePushSubscription,sendPushToEndpoint}from'@/lib/push-notifications';
import{oneSignalConfigured,sendOneSignalPush}from'@/lib/onesignal';
import{canonicalOrigin,checkCsrf,parseBoundedJson,securityHeaders}from'@/lib/security';
import{currentUser,resolveCurrentUserUncached}from'@/lib/session';
export const dynamic='force-dynamic';
const MAX_BODY_BYTES=16*1024;
const response=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{...securityHeaders,'Cache-Control':'private, no-store'}});
const sameOrigin=(request:Request)=>{try{return checkCsrf(request,canonicalOrigin(process.env.APP_ORIGIN,process.env.NODE_ENV,request.url))}catch{return false}};
async function actor(){const user=await currentUser();return user&&!user.impersonating?user:null}
async function body(request:Request){return await parseBoundedJson(request,MAX_BODY_BYTES)as{action?:unknown;subscription?:unknown;endpoint?:unknown}}
function endpoint(value:unknown){if(typeof value!=='string'||value.length>2048)throw new Error('Ungültiger Push-Endpunkt');return value}
export async function GET(){const user=await actor();if(!user)return response({error:'Nicht autorisiert'},401);try{let publicKey='',webPushConfigured=true;try{publicKey=publicVapidKey()}catch{webPushConfigured=false}return response({publicKey,webPushConfigured,devices:(await listPushSubscriptions(user.id)).length,oneSignalConfigured:oneSignalConfigured()})}catch(error){return response({error:error instanceof Error?error.message:'Push nicht verfügbar'},503)}}
export async function POST(request:Request){if(!sameOrigin(request))return response({error:'Ungültiger Ursprung'},403);const user=await actor();if(!user)return response({error:'Nicht autorisiert'},401);let input:Awaited<ReturnType<typeof body>>;try{input=await body(request)}catch(error){return response({error:error instanceof Error?error.message:'Ungültige Anfrage'},400)}try{if(input.action==='status'){const target=endpoint(input.endpoint);return response({enabled:await ownsPushEndpoint(user.id,target),devices:(await listPushSubscriptions(user.id)).length})}if(input.action==='reconcile'){
 await rateLimitPushMutation(user.id,'reconcile');
 const fresh=async()=>{const value=await resolveCurrentUserUncached();return Boolean(value&&!value.impersonating&&value.id===user.id&&value.actorId===user.actorId)};
 const saved=await reconcilePushSubscription(user.id,input.subscription,request.headers.get('user-agent')||'',undefined,fresh);
 await audit({actorId:user.actorId,action:'push.subscription_reconciled',targetId:user.id,after:{createdAt:saved.createdAt},...requestEvidence(request)});
 return response({ok:true,enabled:true,devices:(await listPushSubscriptions(user.id)).length})
}if(input.action==='subscribe'){await rateLimitPushMutation(user.id,'subscribe');const saved=await savePushSubscription(user.id,input.subscription,request.headers.get('user-agent')||'',undefined,async()=>{const fresh=await resolveCurrentUserUncached();return Boolean(fresh&&!fresh.impersonating&&fresh.id===user.id&&fresh.actorId===user.actorId)});await audit({actorId:user.actorId,action:'push.subscription_created',targetId:user.id,after:{createdAt:saved.createdAt},...requestEvidence(request)});return response({ok:true,devices:(await listPushSubscriptions(user.id)).length})}if(input.action==='unsubscribe'){await rateLimitPushMutation(user.id,'unsubscribe');const target=endpoint(input.endpoint),removed=await removePushSubscription(user.id,target);if(removed)await audit({actorId:user.actorId,action:'push.subscription_removed',targetId:user.id,...requestEvidence(request)});return response({ok:true,removed,devices:(await listPushSubscriptions(user.id)).length})}if(input.action==='onesignal-test'){if(!oneSignalConfigured())return response({error:'OneSignal ist noch nicht konfiguriert'},503);await rateLimitPushTest(user.id,'onesignal');const result=await sendOneSignalPush({userId:user.id,title:'ME Media Intelligence',body:'OneSignal-Testbenachrichtigung erfolgreich empfangen.',path:'/settings/app'});if(result.ok)try{await audit({actorId:user.actorId,action:'push.onesignal_test',targetId:user.id,...requestEvidence(request)})}catch{};return response({ok:result.ok},result.ok?200:502)}if(input.action==='test'){const target=endpoint(input.endpoint);if(!await ownsPushEndpoint(user.id,target))return response({error:'Dieses Gerät ist nicht registriert'},404);await rateLimitPushTest(user.id);const result=await sendPushToEndpoint(user.id,target,{title:'ME Media Intelligence',body:'Testbenachrichtigung erfolgreich empfangen.',path:'/settings/app',tag:'push-test'});return response({ok:result.ok},result.ok?200:502)}return response({error:'Unbekannte Aktion'},400)}catch(error){const message=error instanceof Error?error.message:'Aktion fehlgeschlagen',status=/Minute|kurz/.test(message)?429:/Maximal/.test(message)?409:/Sicherheitsstatus|kritische Änderung|Push-Status/.test(message)?503:/nicht mehr autorisiert/.test(message)?401:400;return response({error:message},status)}}
