"use client";
import {useRouter} from 'next/navigation';
import {FormEvent,useState} from 'react';

export default function FraudStopForm(){
 const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[scope,setScope]=useState<'all_offers'|'offer'>('all_offers'),[mode,setMode]=useState<'tracked'|'api'>('api'),[trackedSubDimension,setTrackedSubDimension]=useState<'sub1'|'sub2'|'sub3'|'sub4'|'sub5'>('sub1');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget),requested=String(form.get('requestedAt')||'');try{const response=await fetch('/api/fraud/stops',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({affiliateId:form.get('affiliateId'),source:form.get('source'),subSource:form.get('subSource'),sourceDimension:mode==='api'?'adv1':'source_id',subSourceDimension:mode==='api'?'adv2':trackedSubDimension,offerId:form.get('offerId'),scope,requestedAt:new Date(requested).toISOString(),graceHours:24,channel:'telegram',reference:form.get('reference'),note:form.get('note')})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Stop konnte nicht gespeichert werden');setMessage('Abbestellung gespeichert. Die 24-Stunden-Kontrolle läuft read-only.');event.currentTarget.reset();router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'Stop konnte nicht gespeichert werden')}finally{setBusy(false)}}
 return <form className="fraudStopForm" onSubmit={submit}><div className="fraudFormGrid"><label>Affiliate-ID<input name="affiliateId" inputMode="numeric" pattern="[0-9]+" required placeholder="z. B. 30"/></label><label>Trafficpfad<select value={mode} onChange={event=>setMode(event.target.value as 'tracked'|'api')}><option value="api">Clickless API · ADV1/ADV2</option><option value="tracked">Tracked · Source/Sub1–Sub5</option></select></label>{mode==='tracked'&&<label>Sub-Dimension<select value={trackedSubDimension} onChange={event=>setTrackedSubDimension(event.target.value as typeof trackedSubDimension)}><option value="sub1">Sub1</option><option value="sub2">Sub2</option><option value="sub3">Sub3</option><option value="sub4">Sub4</option><option value="sub5">Sub5</option></select></label>}<label>{mode==='api'?'ADV1':'Source'} <small>optional</small><input name="source" autoComplete="off" placeholder={mode==='api'?'z. B. Publisher':'Source-ID'}/></label><label>{mode==='api'?'ADV2':'Sub-Source'} <small>optional</small><input name="subSource" autoComplete="off" placeholder={mode==='api'?'z. B. P-3591625022':'Sub1'}/></label><label>Scope<select name="scope" value={scope} onChange={event=>setScope(event.target.value as 'all_offers'|'offer')}><option value="all_offers">Alle Offers</option><option value="offer">Nur ein Offer</option></select></label><label>Offer-ID {scope==='all_offers'&&<small>nicht benötigt</small>}<input name="offerId" inputMode="numeric" pattern="[0-9]+" required={scope==='offer'} disabled={scope==='all_offers'} placeholder="Offer-ID"/></label><label>Telegram-Abbestellung<input name="requestedAt" type="datetime-local" required/></label><label>Nachrichtenreferenz <small>optional</small><input name="reference" autoComplete="off" placeholder="Telegram-Link oder interne Referenz"/></label></div><label className="fraudStopNote">Notiz <small>optional</small><textarea name="note" maxLength={500} placeholder="Sachlicher Kontext, keine personenbezogenen Rohdaten"/></label><div className="fraudFormActions"><button type="submit" disabled={busy}>{busy?'Speichert …':'Abbestellung dokumentieren'}</button><span role="status">{message}</span></div></form>;
}
