import {redirect} from 'next/navigation';
import {currentUser} from '@/lib/session';
import {can} from '@/lib/rbac';
import {getFraudDashboard} from '@/lib/fraud-service';
import DashboardPageHeader from '../components/DashboardPageHeader';
import AccessDeniedHint from '../components/AccessDeniedHint';
import FraudStopForm from './FraudStopForm';
import FraudStopDeactivateButton from './FraudStopDeactivateButton';
import FraudStopRowButton from './FraudStopRowButton';
import PeriodControls from '../components/PeriodControls';
import {reportingRange} from '@/lib/supabase-reporting';
import {resolveGlobalPeriod,todayPartialNote} from '@/lib/period-controls';
import {getDataStatus} from '@/lib/data-status';
export const dynamic='force-dynamic';

const euro=(value:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(value),integer=(value:number)=>new Intl.NumberFormat('de-DE').format(value),percent=(value:number|null)=>value===null?'unbekannt':new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:1}).format(value),dateTime=(value:string|null)=>value?new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Berlin'}).format(new Date(value)):'–';
/** Fraud-Service erlaubt höchstens 93 Tage: 12 Monate/365 Tage und längere freie Bereiche fallen mit Hinweis auf 30 Tage zurück. */
const FRAUD_MAX_DAYS=93,FRAUD_PRESETS=['today','7d','30d','90d'] as const,dayCount=(from:string,to:string)=>Math.round((Date.parse(`${to}T12:00:00Z`)-Date.parse(`${from}T12:00:00Z`))/86_400_000)+1;
const modeLabel={tracked_smartlink:'Smartlink',tracked_direct:'Direct',clickless_api:'Clickless API',unknown:'Unbekannt'} as const,riskLabel={unauffällig:'Unauffällig',beobachten:'Beobachten',verdächtig:'Verdächtig',hohes_risiko:'Hohes Risiko',unbekannt:'Unbekannt'} as const;

type Params={period?:string;from?:string;to?:string;risk?:string;mode?:string;q?:string};
export default async function FraudPage({searchParams}:{searchParams:Promise<Params>}){
 const user=await currentUser();if(!user)redirect('/login');if(user.access.role==='partner'||user.access.role!=='super_admin'||Object.values(user.access.scopes).some(values=>values.length>0)||!can(user.access,'statistics.view')||!can(user.access,'finance.view'))return <main className="fatal"><h1>403 · Keine Berechtigung</h1><AccessDeniedHint permission="statistics.view und finance.view als super_admin ohne Scopes"/></main>;
 const filters=await searchParams;let period=resolveGlobalPeriod(filters.period),periodError:string|null=null,resolved;try{resolved=reportingRange(period,new Date(),{from:filters.from,to:filters.to})}catch{periodError='Bitte ein gültiges Von- und Bis-Datum auswählen.';period='30d';resolved=reportingRange(period)}if(!resolved.from||dayCount(resolved.from,resolved.to)>FRAUD_MAX_DAYS){periodError=`Fraud Detection wertet höchstens ${FRAUD_MAX_DAYS} Tage aus – Zeitraum auf 30 Tage zurückgesetzt.`;period='30d';resolved=reportingRange(period)}
 const range={from:resolved.from!,to:resolved.to},dataStatus=await getDataStatus();let data;try{data=await getFraudDashboard(range,user.access)}catch(error){console.error('Fraud dashboard failed',error);return <main className="fatal"><h1>Fraud Detection konnte nicht geladen werden</h1><p>Migration, Backfill und Supabase-Verbindung prüfen.</p></main>}
 const query=(filters.q||'').trim().toLowerCase(),rows=data.evaluations.filter(row=>(!filters.risk||filters.risk==='all'||row.riskLevel===filters.risk)&&(!filters.mode||filters.mode==='all'||row.trafficMode===filters.mode)&&(!query||[row.affiliateName,row.affiliateId,row.offerName,row.offerId,row.source,row.subSource,row.campaignName,row.offerUrlName].some(value=>value.toLowerCase().includes(query)))).slice(0,250),compliance=new Map(data.stopCompliance.map(row=>[row.id,row])),canManageStops=can(user.access,'api.manage');
 return <main className="dashboard fraudPage"><DashboardPageHeader kicker="Accountweite Traffic-Kontrolle" title="Fraud Detection" status="Shadow Mode" tone="protected" icon="security" description="Alle Affiliates, Offers, Smartlinks, Direct-Pfade und clickless API-Quellen getrennt nach Qualität, Fraud-Risiko und Stop-Compliance."/>
  <PeriodControls dimension="global" period={period} from={period==='custom'?range.from:undefined} to={period==='custom'?range.to:undefined} rangeLabel={resolved.label} maxDate={reportingRange('today').to} presets={FRAUD_PRESETS} error={periodError} todayNote={todayPartialNote(dataStatus)}/>
  <section className="fraudSafety"><strong>Read-only gegenüber Everflow</strong><span>Automatische Maßnahmen deaktiviert · Writes ausgeführt: {data.writesPerformed} · Scores lösen keine Payout-, Postback- oder Source-Änderung aus.</span></section>
  {!data.coverage.cutoverReady&&<section className="fraudWarning"><strong>Conversion-Cutover noch nicht bereit</strong><span>Der versionierte Conversion-Backfill inklusive Typ-Paritätsprüfung läuft. Coin-Kohorten und Stop-Verstöße bleiben bis zum vollständigen Cutover unbekannt.</span></section>}
  {!data.coverage.sourceComplete&&<section className="fraudWarning"><strong>Source-Historie unvollständig</strong><span>{data.coverage.sourceDaysAvailable} von {data.coverage.sourceDaysExpected} Tagen verfügbar. Fehlende Tage werden nicht als null oder unauffällig bewertet.</span></section>}
  <section className="fraudKpis"><article><small>Affiliates</small><strong>{integer(data.totals.affiliates)}</strong><span>beobachtet</span></article><article><small>Offers</small><strong>{integer(data.totals.offers)}</strong><span>dynamisch entdeckt</span></article><article><small>Tiefste Quellen</small><strong>{integer(data.totals.sources)}</strong><span>alle Trafficpfade</span></article><article><small>Verdächtig</small><strong>{data.totals.suspicious===null?'–':integer(data.totals.suspicious)}</strong><span>manuell prüfen</span></article><article><small>Hohes Risiko</small><strong>{data.totals.highRisk===null?'–':integer(data.totals.highRisk)}</strong><span>keine Auto-Sperre</span></article><article><small>Stop-Verstöße</small><strong>{data.totals.stopViolations===null?'–':integer(data.totals.stopViolations)}</strong><span>{data.coverage.cutoverReady?'nach Grace Period':'Backfill läuft'}</span></article></section>
  <section className="fraudPanel"><div className="fraudSectionHead"><div><small>Partnersteuerung</small><h2>Telegram-Abbestellungen</h2><p>Abbestellungszeitpunkt dokumentieren; nach exakt 24 Stunden werden weitere approved, nicht gescrubbte SOIs kontrolliert.</p></div></div>{canManageStops?<FraudStopForm/>:<p className="fraudReadOnly">Nur Benutzer mit API-Verwaltungsrecht dürfen Stops erfassen.</p>}
   {data.activeStops.length>0&&<div className="tableWrap"><table className="performanceTable fraudStopTable"><caption className="srOnly">Aktive Traffic-Abbestellungen</caption><thead><tr><th>Affiliate</th><th>Quelle</th><th>Scope</th><th>Deadline</th><th>Ergebnis</th><th>Aktion</th></tr></thead><tbody>{data.activeStops.map(stop=>{const status=compliance.get(stop.id);return <tr key={stop.id}><td data-label="Affiliate">#{stop.affiliateId}</td><td data-label="Quelle"><b>{stop.source||'alle Hauptquellen'}</b><small>{stop.subSource||'keine Unterquelle'}</small></td><td data-label="Scope">{stop.offerId?`Offer #${stop.offerId}`:'Alle Offers'}</td><td data-label="Deadline">{status?dateTime(status.deadline):'Backfill läuft'}</td><td data-label="Ergebnis">{status?<span className={`fraudBadge ${status.status==='verstoß'?'critical':status.status==='ausstehend'?'unknown':'ok'}`}>{status.status==='verstoß'?`${integer(status.leadsAfterDeadline)} Leads · ${euro(status.payoutAfterDeadline)}`:status.status==='ausstehend'?'Grace Period läuft':'Eingehalten'}</span>:<span className="fraudBadge unknown">Unbekannt</span>}</td><td data-label="Aktion">{canManageStops?<FraudStopDeactivateButton id={stop.id}/>:<span>Nur lesen</span>}</td></tr>})}</tbody></table></div>}
  </section>
  <section className="fraudPanel"><div className="fraudSectionHead"><div><small>Accountweiter Monitor</small><h2>Quellenbewertung</h2><p>Qualität, technische Anomalien, Kohortenreife und Kundenkonzentration bleiben getrennt sichtbar.</p></div><form className="fraudFilters"><input type="hidden" name="period" value={period}/>{period==='custom'&&<><input type="hidden" name="from" value={range.from}/><input type="hidden" name="to" value={range.to}/></>}<label>Risiko<select name="risk" defaultValue={filters.risk||'all'}><option value="all">Alle</option><option value="hohes_risiko">Hohes Risiko</option><option value="verdächtig">Verdächtig</option><option value="beobachten">Beobachten</option><option value="unauffällig">Unauffällig</option><option value="unbekannt">Unbekannt</option></select></label><label>Trafficpfad<select name="mode" defaultValue={filters.mode||'all'}><option value="all">Alle</option><option value="tracked_smartlink">Smartlink</option><option value="tracked_direct">Direct</option><option value="clickless_api">Clickless API</option><option value="unknown">Unbekannt</option></select></label><label>Suche<input name="q" defaultValue={filters.q||''} placeholder="Affiliate, Offer, Source …"/></label><button>Filtern</button></form></div>
   <div className="fraudCoverage"><span>Source-Tage <b>{data.coverage.sourceDaysAvailable}/{data.coverage.sourceDaysExpected}</b></span>{data.coverage.conversionJoin&&Object.entries(data.coverage.conversionJoin).map(([type,item])=><span key={type}>{type.replace('_',' ')} Join <b>{percent(item.rate)}</b> <small>({item.joined}/{item.events})</small></span>)}</div>
   <div className="tableWrap"><table className="performanceTable fraudTable"><caption className="srOnly">Accountweite Fraud- und Qualitätsbewertung nach tiefster Quelle</caption><thead><tr><th>Affiliate / Offer</th><th>Pfad / Quelle</th><th>Traffic</th><th>Coin-Kohorte</th><th>Rebill-Konzentration</th><th>Profit</th><th>Scores</th><th>Begründung</th></tr></thead><tbody>{rows.map(row=><tr key={row.key}><td data-label="Affiliate / Offer"><b>{row.affiliateName} · #{row.affiliateId}</b><small>{row.offerName} · #{row.offerId}</small></td><td data-label="Pfad / Quelle"><b>{modeLabel[row.trafficMode]} · {row.source}</b><small>{row.subSource} · {row.campaignId!=='0'?row.campaignName:row.offerUrlName}</small></td><td data-label="Traffic"><b>{integer(row.metrics.sois)} SOIs</b><small>{integer(row.metrics.firstSales)} Sales · {integer(row.metrics.rebills)} Rebills · {integer(row.metrics.coinEvents)} Coin-Events</small></td><td data-label="Coin-Kohorte">{row.cohort.mode==='user_joined'?<><b>{integer(row.cohort.coinUsers)} Coin-Nutzer</b><small>{integer(row.cohort.saleUsers)} Zahler · P(0) {percent(row.coinZeroSaleProbability)}</small></>:<><b>{row.cohort.mode==='aggregate_only'?'Nur aggregiert':'Nicht verfügbar'}</b><small>{row.dataWarnings.join(' · ')||'keine nutzerbasierte Aussage'}</small></>}</td><td data-label="Rebill-Konzentration">{row.rebillConcentration.status==='available'?<><b>{integer(row.rebillConcentration.customers||0)} Kunden</b><small>Top 1 {percent(row.rebillConcentration.top1Share)} · Top 2 {percent(row.rebillConcentration.top2Share)}</small></>:<><b>Unbekannt</b><small>keine verlässliche Kundenidentität</small></>}</td><td data-label="Profit" className={row.metrics.profit<0?'negative':'positive'}><b>{euro(row.metrics.profit)}</b><small>{euro(row.metrics.revenue)} Umsatz · {euro(row.metrics.payout)} Payout</small></td><td data-label="Scores">{canManageStops&&<FraudStopRowButton affiliateId={row.affiliateId} offerId={row.offerId} source={row.source} subSource={row.subSource} sourceDimension={row.sourceDimension} subSourceDimension={row.subSourceDimension}/>}<span className={`fraudBadge risk-${row.riskLevel}`}>{riskLabel[row.riskLevel]} · {row.fraudScore}</span><small>Qualität {row.qualityScore}</small></td><td data-label="Begründung"><b>{row.reasons[0]||'Kein belastbares Fraud-Signal'}</b><small>{row.dataWarnings.join(' · ')||'Datenmodus ausgewertet'}</small></td></tr>)}</tbody></table></div>
   {!rows.length&&<div className="smartEmpty"><h3>Keine Quellen für diesen Filter</h3><p>Filter ändern oder Source-Snapshot-Coverage prüfen.</p></div>}{data.evaluations.length>250&&<p className="fraudTableLimit">Maximal 250 Zeilen sichtbar. Filter nach Risiko, Pfad oder Quelle.</p>}
  </section>
 </main>;
}
