import InstantLink from'./InstantLink';
import LazyDetails from'./LazyDetails';
import{KpiValue,LandingpageSourceBreakdown,RecommendationBanner,SmartlinkRotationCards,StatusBadge,TimeWindowSection}from'../components/SmartlinkPresentation';
import{buildMonetizationAttribution,hasRecentMonetization,type MonetizationSlice}from'@/lib/smartlink-attribution';
import{reconcileSelectedRangeHeadline}from'@/lib/smartlink-transparency';
import type{CampaignAffiliateMapping}from'@/lib/affiliate-smartlinks';
import type{getAffiliateSmartlinks}from'@/lib/smartlink-service';
import type{RebillConcentration}from'@/lib/rebill-concentration';
import{affiliateCampaignHref,automationCampaignHref,primarySmartlinkRecommendation}from'@/lib/optimization-workflow';
import RebillConcentrationPanel from'../components/RebillConcentrationPanel';
import CampaignStatusButton from'./CampaignStatusButton';

type Insight=Awaited<ReturnType<typeof getAffiliateSmartlinks>>[number];
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const num=(n:number)=>new Intl.NumberFormat('de-DE').format(n);
const pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`;
const time=(epoch:number)=>new Date(epoch*1000).toLocaleTimeString('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit'});

function eventText(m:MonetizationSlice){return`${num(m.firstSales)} First-Sales · ${num(m.rebills)} Rebills · ${num(m.coinSpend)} Coin-Spend-Events`}
function AttributionRow({label,detail,metric,total=false}:{label:string;detail:string;metric:MonetizationSlice;total?:boolean}){return <article className={total?'total':''}><div><b>{label}</b><small>{detail}</small></div><span>{eventText(metric)}</span><span><b>{euro(metric.revenue)}</b><small>Umsatz</small></span><span><b>{euro(metric.payout)}</b><small>SOI-Vergütung</small></span><strong className={metric.profit>=0?'up':'down'}>{euro(metric.profit)}<small>Profit</small></strong></article>}

export default function AffiliateSmartlinks({affiliateId,returnTo,mappings,insights,rangeLabel,rebillAnalyses,selectedCampaignId,canManageSources=false,canManageCampaigns=false}:{affiliateId:string;returnTo:string;mappings:CampaignAffiliateMapping[];insights:Insight[];rangeLabel:string;rebillAnalyses:Record<number,RebillConcentration>;selectedCampaignId?:number;canManageSources?:boolean;canManageCampaigns?:boolean}){
 const selectionMismatch=Boolean(selectedCampaignId&&!mappings.some(mapping=>mapping.campaignId===selectedCampaignId));
 const visibleMappings=selectedCampaignId&&!selectionMismatch?mappings.filter(mapping=>mapping.campaignId===selectedCampaignId):selectedCampaignId?[]:mappings;
 const byId=new Map(insights.map(x=>[x.identity.campaignId,x]));
 const total30=mappings.reduce((sum,m)=>({revenue:sum.revenue+m.revenue30,payout:sum.payout+m.payout30,profit:sum.profit+m.profit30,sois:sum.sois+m.sois30}),{revenue:0,payout:0,profit:0,sois:0});
 return <section className="affiliateSmartlinks"><header className="smartPartnerIntro"><div><span>SMARTLINK-MODUS · GETRENNT VON DIREKTLINKS</span><h2>{mappings.length} beobachtete Campaign{mappings.length===1?'':'s'}</h2><p>Campaign-Bilanz, aktuelle Rotation und Kalendertagsdaten werden getrennt dargestellt. Kein Tageswert wird als rollierende Stundenpräzision ausgegeben.</p></div><div className="smartScopePills"><b>{rangeLabel} · Campaign-Bilanz</b><b>Kalendertagsdaten</b><b>Aktuelle Rotation</b></div></header>
 {mappings.length>0&&<section className="smartlinkThirtyDayBridge"><div><span>SMARTLINK-BILANZ · {rangeLabel}</span><h3>{euro(total30.profit)} Profit aus {mappings.length} Campaign{mappings.length===1?'':'s'}</h3><p>{euro(total30.revenue)} Umsatz – {euro(total30.payout)} SOI-Vergütung = <b>{euro(total30.profit)} Profit</b></p></div><div><KpiValue label={`Umsatz · ${rangeLabel}`} value={euro(total30.revenue)} detail="Summe aller beobachteten Campaigns"/><KpiValue label={`SOI-Vergütung · ${rangeLabel}`} value={euro(total30.payout)} detail={`${num(total30.sois)} vergütete SOIs`}/><KpiValue label={`Profit · ${rangeLabel}`} value={euro(total30.profit)} detail="Umsatz minus SOI-Vergütung" tone={total30.profit>=0?'positive':'negative'}/></div><small>Alle Geldbeträge sind Euro-Beträge. Der Zeitraum steht separat und ist kein Teil des Profitwertes.</small></section>}
 {selectionMismatch&&<div className="emptyDetail"><b>CAMPAIGN PASST NICHT ZUM AFFILIATE</b><p>Campaign #{selectedCampaignId} ist Affiliate #{affiliateId} im gewählten Zeitraum nicht eindeutig zugeordnet. Bitte Campaign oder Affiliate neu auswählen.</p></div>}
 {!selectionMismatch&&(mappings.length===0?<div className="emptyDetail"><b>KEIN SMARTLINK-TRAFFIC</b><p>Für diesen Partner wurde im Zeitraum {rangeLabel} keine Campaign-ID ungleich 0 beobachtet.</p></div>:<div className="affiliateCampaignList">{visibleMappings.map(mapping=>{
  const data=byId.get(mapping.campaignId);
  if(!data)return <article className="affiliateCampaign unavailable" key={mapping.campaignId}><b>Campaign #{mapping.campaignId} · {mapping.campaign}</b><p>Detaildaten konnten nicht geladen werden.</p></article>;
  const primary=primarySmartlinkRecommendation(data.recommendations);
  const rotation=data.rotationStartEpoch?`Campaign zuletzt gespeichert am ${new Date(data.rotationStartEpoch*1000).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})} · als Rotationsreferenz verwendet`:'Campaign-Speicherzeitpunkt unbekannt · Reifefenster maximal 14 Tage';
  const recentAttribution=buildMonetizationAttribution(data.money72,data.currentSlots,data.legacySlots);
  const selected=data.selectedRange?.attribution?reconcileSelectedRangeHeadline(data.selectedRange.attribution,{sois:mapping.sois30,revenue:mapping.revenue30,payout:mapping.payout30,profit:mapping.profit30}):null;
  const recentLegacy=data.legacySlots.filter(x=>hasRecentMonetization(x.metrics72||x.metrics14));
  const legacyOnly=hasRecentMonetization(recentAttribution.legacy)&&!hasRecentMonetization(recentAttribution.current);
  const legacySorted=[...data.legacySlots].sort((a,b)=>Number(hasRecentMonetization(b.metrics72||b.metrics14))-Number(hasRecentMonetization(a.metrics72||a.metrics14))||((b.metrics72||b.metrics14).revenue-(a.metrics72||a.metrics14).revenue)||b.metrics14.profit-a.metrics14.profit),maxClicks=Math.max(1,...data.hourly24.map(point=>point.clicks));
  return <LazyDetails id={`campaign-${mapping.campaignId}`} defaultOpen={selectedCampaignId===mapping.campaignId} className={`affiliateCampaign${selectedCampaignId===mapping.campaignId?' selectedCampaign':''}`} key={mapping.campaignId} summary={<><div><span>CAMPAIGN #{mapping.campaignId} · {data.identity.status}</span><h3>{data.identity.name}</h3><small>{data.currentSlots.length} aktive LPs · {data.legacySlots.length} frühere LPs · Offer {data.identity.offerIds.map(x=>`#${x}`).join(', ')||'n/a'}</small></div><KpiValue label={`CVR · ${data.windows.traffic}`} value={pct(data.traffic24.cvr)} detail={`${num(data.traffic24.sois)} SOIs aus ${num(data.traffic24.clicks)} Klicks`} size="s"/><KpiValue label="Campaign-Profit im ausgewählten Zeitraum" value={euro(mapping.profit30)} detail={`${euro(mapping.revenue30)} Umsatz – ${euro(mapping.payout30)} Payout`} scope={rangeLabel} size="s" tone={mapping.profit30>=0?'positive':'negative'}/><StatusBadge recommendation={primary||undefined}/></>}><div className="campaignBody">{primary&&<RecommendationBanner recommendation={primary} scope={`Campaign-Empfehlung · ${rangeLabel}`}/>}<div className="campaignScope"><span>Campaign #{mapping.campaignId} · {rotation}</span><div className="campaignScopeActions"><InstantLink href={affiliateCampaignHref({campaignId:mapping.campaignId,affiliateId,currentHref:returnTo})}>Campaign in diesem Optimizer öffnen</InstantLink>{primary?.action==='rotate'&&<InstantLink href={automationCampaignHref({campaignId:mapping.campaignId,affiliateId,slotId:primary.slotId})}>Austausch sicher vorbereiten</InstantLink>}<CampaignStatusButton campaignId={mapping.campaignId} campaignName={data.identity.name} affiliateId={String(data.identity.affiliateId)} initialStatus={data.identity.status} canManage={canManageCampaigns}/></div></div>
  <section className="campaignKpiWindows intelligenceKpiWindows"><TimeWindowSection title="Letzte 24 Stunden" subtitle="Traffic · Campaign gesamt"><KpiValue label="CVR" value={pct(data.traffic24.cvr)} detail={`${num(data.traffic24.sois)} SOIs aus ${num(data.traffic24.clicks)} Klicks`} size="l" tone={data.traffic24.cvr>=1?'positive':data.traffic24.clicks?'negative':'neutral'}/><KpiValue label="SOIs" value={num(data.traffic24.sois)}/><KpiValue label="Klicks" value={num(data.traffic24.clicks)}/></TimeWindowSection><TimeWindowSection title="Letzte 72 Stunden" subtitle="Monetarisierung · inklusive früherer LPs"><KpiValue label="Profit" value={euro(data.money72.profit)} size="l" tone={data.money72.profit>=0?'positive':'negative'}/><KpiValue label="First-Sales" value={num(data.money72.firstSales)}/><KpiValue label="Rebills" value={num(data.money72.rebills)}/><KpiValue label="Umsatz" value={euro(data.money72.revenue)}/><KpiValue label="Payout" value={euro(data.money72.payout)}/><KpiValue label="Profit-EPC" value={euro(data.money72.profitEpc)} tone={data.money72.profitEpc>=0?'positive':'negative'}/></TimeWindowSection><TimeWindowSection title="Letzte 14 Tage" subtitle="Entscheidungsreife · Campaign gesamt"><KpiValue label="Profit" value={euro(data.mature14.profit)} tone={data.mature14.profit>=0?'positive':'negative'}/><KpiValue label="First-Sales" value={num(data.mature14.firstSales)}/><KpiValue label="Rebills" value={num(data.mature14.rebills)}/><KpiValue label="Legacy-Profit" value={euro(data.legacy14.profit)} tone={data.legacy14.profit>=0?'positive':'negative'}/></TimeWindowSection></section>
  <section className="sectionHead"><div><span>STUNDENBASIS · LETZTE 24H</span><h4>Traffic- und SOI-Verlauf</h4></div><div className="scope">Europe/Berlin</div></section><section className="hourlyChart">{data.hourly24.map(point=><div className="hourRow" key={point.epoch}><span>{time(point.epoch)}</span><div className="barTrack"><i style={{width:`${Math.max(point.clicks?2:0,100*point.clicks/maxClicks)}%`}}/></div><b>{point.clicks}</b><em>{point.sois} SOIs · {pct(point.cvr)} CVR</em></div>)}</section><section className="auditStrip compactAudit"><div><span>Datenstand</span><b>{new Date(data.generatedAt).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})}</b></div><div><span>Scope</span><b>Affiliate #{affiliateId} · Campaign #{mapping.campaignId}</b></div></section>
  <section className={`profitExplanation ${mapping.profit30<0?'negative':'positive'}`}><div><span>{rangeLabel.toUpperCase()} · CAMPAIGN-BILANZ</span><h4>{mapping.profit30<0?'Warum ist der Profit negativ?':'Warum ist der Profit positiv?'}</h4><p>Die Campaign hat in diesem Zeitraum <b>{euro(mapping.payout30)}</b> für SOIs gekostet und <b>{euro(mapping.revenue30)}</b> Umsatz erzeugt. Deshalb beträgt der Profit <b>{euro(mapping.profit30)}</b>.</p></div><strong>{euro(mapping.revenue30)} – {euro(mapping.payout30)} = {euro(mapping.profit30)}</strong></section>
  {rebillAnalyses[data.identity.campaignId]&&<RebillConcentrationPanel analysis={rebillAnalyses[data.identity.campaignId]} scope={`Campaign #${data.identity.campaignId} · ${rangeLabel}`}/>}
  {selected&&<details className="selectedProfitOrigin compactDisclosure"><summary><span><b>Woher kommen Umsatz und Profit?</b><small>{rangeLabel} · vollständige Kontrollrechnung</small></span><strong className={selected.reconciled?'up':'down'}>{selected.reconciled?'Rechnerisch abgestimmt':'Prüfung erforderlich'}</strong><i aria-hidden="true">›</i></summary><p>Der Campaign-Speichertag bleibt wegen täglicher Datenauflösung separat. Der Speicherzeitpunkt beweist nicht minutengenau, wann die LP-Rotation geändert wurde.</p><div className="attributionRows"><AttributionRow label="Vor der Rotationsreferenz" detail={selected.rotationDay?`Alle Tageswerte vor ${selected.rotationDay}`:'Campaign-Speicherzeitpunkt nicht bekannt'} metric={selected.beforeRotation}/><AttributionRow label="Aktuelle Landingpages nach Rotationsreferenz" detail="Ab dem ersten vollständigen Kalendertag nach dem Campaign-Speichertag" metric={selected.current}/><AttributionRow label="Frühere Landingpages nach Rotationsreferenz" detail="Nachlaufende Werte inzwischen entfernter LPs" metric={selected.legacy}/><AttributionRow label="Campaign-Speichertag" detail={selected.rotationDay?`${selected.rotationDay} · tägliche Daten nicht minutengenau teilbar`:'Kein Referenztag bestimmbar'} metric={selected.transitionDay}/><AttributionRow label="Nicht eindeutig zugeordnet" detail="Fehlende LP-ID oder Differenz zwischen Kopfwert und Detailzeilen" metric={selected.unassigned}/><AttributionRow label="Campaign gesamt" detail={`Kontrollsumme · ${rangeLabel}`} metric={selected.total} total/></div></details>}
  <details className={`campaignComparison compactDisclosure${legacyOnly?' legacyOnly':''}`}><summary><span><b>Kurzfristige Entwicklung anzeigen</b><small>{data.windows.economics} · nicht zum Campaign-Profit addieren</small></span><strong className={data.money72.profit>=0?'up':'down'}>{euro(data.money72.profit)}</strong><i aria-hidden="true">›</i></summary><div className="campaignComparisonBody"><p><b>Nicht direkt vergleichbar:</b> Dieser Kurztrend ist eine Teilmenge des ausgewählten Kampagnenzeitraums. {legacyOnly?'Die Monetarisierung stammt ausschließlich von früheren Landingpages.':recentLegacy.length?`${recentLegacy.length} frühere Landingpage${recentLegacy.length===1?'':'s'} erzeugen nachlaufenden Umsatz.`:'Kein nachlaufender Umsatz früherer Landingpages.'}</p><div className="comparisonKpis"><KpiValue label="Umsatz · Kurztrend" value={euro(data.money72.revenue)} scope={data.windows.economics}/><KpiValue label="Payout · Kurztrend" value={euro(data.money72.payout)} scope={data.windows.economics}/><KpiValue label="Profit · Kurztrend" value={euro(data.money72.profit)} scope={data.windows.economics} tone={data.money72.profit>=0?'positive':'negative'}/></div><div className="attributionRows"><AttributionRow label={`Aktuelle ${data.currentSlots.length} LPs`} detail="Beitrag im Kurztrend" metric={recentAttribution.current}/><AttributionRow label={`Frühere ${data.legacySlots.length} LPs`} detail="Nachlaufende Monetarisierung" metric={recentAttribution.legacy}/>{!recentAttribution.fullyAssigned&&<AttributionRow label="Nicht eindeutig zugeordnet" detail="Ohne verwertbare LP-ID" metric={recentAttribution.unassigned}/>}<AttributionRow label="Kurztrend gesamt" detail={data.windows.economics} metric={recentAttribution.total} total/></div></div></details>
  <SmartlinkRotationCards slots={data.currentSlots} recommendations={data.recommendations} rotationLabel={rotation} windows={data.windows} affiliateId={String(data.identity.affiliateId)} affiliateName={data.identity.affiliate} campaignId={String(mapping.campaignId)} canManage={canManageSources}/><div className="campaignSubhead legacy"><div><span>FRÜHERE LANDINGPAGES · NICHT MEHR AKTIV</span><h4>{data.legacySlots.length} Landingpages · nach aktuellem Beitrag sortiert</h4></div><small>{data.windows.economics} zeigt aktuelle Nachläufer; die Historie nutzt das Reifefenster.</small></div>{legacySorted.length?<div className="legacySlots attributionLegacy">{legacySorted.map(slot=>{const recentMetric=slot.metrics72||slot.metrics14,recentWindow=slot.metrics72?data.windows.economics:data.windows.maturity,recent=hasRecentMonetization(recentMetric);return <article className={recent?'recent':''} key={slot.id}><div><span>LP #{slot.id} · Offer #{slot.offerId}</span><b>{slot.name}</b>{recent&&<em>NACHLAUFENDER UMSATZ</em>}</div><span><b>{recentWindow}</b><small>{recentMetric.firstSales} First-Sales · {recentMetric.rebills} Rebills · {recentMetric.coinSpend} Coin-Spend-Events</small></span><span><b>{euro(recentMetric.revenue)} Umsatz</b><small>{euro(recentMetric.payout)} SOI-Vergütung</small></span><strong className={recentMetric.profit>=0?'up':'down'}>{euro(recentMetric.profit)}<small>Profit</small></strong><span className="legacyHistory"><b>{data.windows.maturity}</b><small>{num(slot.metrics14.sois)} SOIs · {slot.metrics14.firstSales} First-Sales · {slot.metrics14.rebills} Rebills · {slot.metrics14.coinSpend} Coin-Spend-Events · {euro(slot.metrics14.profit)} Profit</small></span><LandingpageSourceBreakdown rows={slot.sourceBreakdown||[]} scope={data.windows.sourceLegacy||data.windows.source||data.windows.maturity} totalSois={slot.metrics14.sois} landingpageId={slot.id} affiliateId={String(data.identity.affiliateId)} affiliateName={data.identity.affiliate} offerId={slot.offerId} offerName={`Offer #${slot.offerId}`} campaignId={String(mapping.campaignId)} canManage={canManageSources}/></article>})}</div>:<p className="emptyInline">Keine frühere Landingpage mit Traffic oder Events im Reifefenster.</p>}</div></LazyDetails>
 })}</div>)}</section>
}
