
import{redirect}from'next/navigation';
import{currentUser}from'@/lib/session';
import{getAffiliateOptimizations,getAffiliateLeadLatency,getAffiliateSourceBreakdown}from'@/lib/affiliate-optimizer-service';
import{groupAffiliateOffers,type AffiliateVariant}from'@/lib/affiliate-optimizer';
import type{SourceBreakdownRow}from'@/lib/source-breakdown';
import type{LeadLatencyAnalysis,UrlLeadMaturity}from'@/lib/lead-latency';
import{getCampaignAffiliateMappings,getAffiliateSmartlinks}from'@/lib/smartlink-service';
import{mergeAffiliateWorkspaces}from'@/lib/affiliate-smartlinks';
import{AFFILIATE_PERIODS,resolveAffiliatePeriod}from'@/lib/affiliate-period';
import AffiliateSmartlinks from'./AffiliateSmartlinks';
import InstantLink from'./InstantLink';
import LazyDetails from'./LazyDetails';
import SourceBreakdown from'./SourceBreakdown';
import TrafficActionLists from'./TrafficActionLists';
export const dynamic='force-dynamic';
const eur=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const num=(n:number)=>new Intl.NumberFormat('de-DE').format(n);
const pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`;
const cr=(m:{clicks:number;sois:number;cvr:number},api=false)=>api?'n/a – clickless':m.clicks?pct(m.cvr):'nicht berechenbar';
function ProfitPeriod({label,m}:{label:string;m:AffiliateVariant['today']}){return <article className="profitPeriod"><span>{label}</span><b className={m.profit>=0?'up':'down'}>{eur(m.profit)} Profit</b><small>{eur(m.revenue)} Umsatz – {eur(m.payout)} SOI-Vergütung = {eur(m.profit)} Profit</small><small>{num(m.firstSales)} First-Sales · {num(m.rebills)} Rebills{m.coinSpend?` · ${num(m.coinSpend)} Coin-Spend-Events`:''}</small><small>{m.clicks?`${cr(m)} CVR · ${num(m.sois)} SOIs aus ${num(m.clicks)} Klicks`:`Keine Klicks · ${num(m.sois)} SOIs`}</small></article>}
const recClass=(v:AffiliateVariant)=>v.recommendation.severity;
const duration=(hours:number|null)=>hours===null?'–':hours<48?`${hours.toFixed(1).replace('.',',')} Std.`:`${(hours/24).toFixed(1).replace('.',',')} Tage`;
function UrlLeadMaturityPanel({data,benchmark}:{data?:UrlLeadMaturity;benchmark:LeadLatencyAnalysis}){if(!data?.pending)return <div className="urlMaturity clear"><div><span>LEAD-REIFE · LETZTE {benchmark.pendingWindowDays} TAGE</span><b>Keine aktuell offenen Leads</b></div><small>Kein unverkaufter SOI in diesem Fenster.</small></div>;return <div className={`urlMaturity ${data.overdue?'late':''}`}><div><span>LEAD-REIFE · LETZTE {benchmark.pendingWindowDays} TAGE</span><b>{data.pending} offene Leads · Ø Alter {duration(data.averageAgeHours)}</b><small>Partner-Ø bis First-Sale: {duration(benchmark.averageHours)} · 75 % bis {duration(benchmark.p75Hours)}</small></div><div><article><b>{data.youngerThanAverage}</b><small>jünger als Ø</small></article><article><b>{data.betweenAverageAndP75}</b><small>über Ø, noch im 75%-Fenster</small></article><article className={data.overdue?'danger':''}><b>{data.overdue}</b><small>älter als 75%-Grenze</small></article></div></div>}
export default async function AffiliateOptimizerPage({searchParams}:{searchParams:Promise<{affiliate?:string;q?:string;offer?:string;mode?:string;period?:string;from?:string;to?:string}>}){
 if(!await currentUser())redirect('/login');const query=await searchParams,period=resolveAffiliatePeriod(query),rangeParams=new URLSearchParams({period:period.period,...(period.period==='custom'?{from:period.from,to:period.to}:{})}).toString(),periodHref=(id:string)=>{const p=new URLSearchParams({period:id});if(query.affiliate)p.set('affiliate',query.affiliate);if(query.offer)p.set('offer',query.offer);if(query.mode)p.set('mode',query.mode);return`/affiliates?${p}`};let analyses,mappings;
 try{[analyses,mappings]=await Promise.all([getAffiliateOptimizations(period.servicePeriod,period.custom),getCampaignAffiliateMappings({from:period.from,to:period.to})])}catch(e){console.error(e);return <main className="fatal"><div className="eyebrow">EVERFLOW NICHT ERREICHBAR</div><h1>Affiliate Optimizer konnte nicht geladen werden</h1><InstantLink href={`/affiliates?${rangeParams}`}>Erneut versuchen</InstantLink></main>}
 const workspaces=mergeAffiliateWorkspaces(analyses,mappings),q=(query.q||'').trim().toLowerCase(),matches=q?workspaces.filter(x=>x.affiliateId===q||x.affiliate.toLowerCase().includes(q)):workspaces,selectedWorkspace=(query.affiliate?workspaces.find(x=>x.affiliateId===query.affiliate):null)||null,selected=selectedWorkspace?.direct||null,mode:'direct'|'smartlinks'=selectedWorkspace&&!selectedWorkspace.direct?'smartlinks':query.mode==='smartlinks'?'smartlinks':'direct';let sourceRows:SourceBreakdownRow[]=[],leadLatency:LeadLatencyAnalysis|null=null,smartlinkInsights:Awaited<ReturnType<typeof getAffiliateSmartlinks>>=[];if(selected&&mode==='direct'){const[sourceResult,latencyResult]=await Promise.allSettled([getAffiliateSourceBreakdown(selected.affiliateId,{from:period.from,to:period.to}),getAffiliateLeadLatency(selected.affiliateId)]);if(sourceResult.status==='fulfilled')sourceRows=sourceResult.value;else console.error('Source breakdown failed',sourceResult.reason);if(latencyResult.status==='fulfilled')leadLatency=latencyResult.value;else console.error('Lead latency failed',latencyResult.reason)}if(selectedWorkspace&&mode==='smartlinks')try{smartlinkInsights=await getAffiliateSmartlinks(selectedWorkspace.affiliateId,selectedWorkspace.campaigns.map(x=>x.campaignId))}catch(e){console.error('Affiliate smartlinks failed',e)}const sourceRowsByUrl=new Map<string,SourceBreakdownRow[]>();for(const row of sourceRows){const key=`${row.offerId}|${row.offerUrlId}`,bucket=sourceRowsByUrl.get(key);if(bucket)bucket.push(row);else sourceRowsByUrl.set(key,[row])}const maturityByUrl=new Map((leadLatency?.byUrl||[]).map(x=>[x.offerUrlId,x])),offers=selected?groupAffiliateOffers(selected):[],activeOffer=offers.find(x=>x.offerId===query.offer)||offers[0],stopVariants=selected?selected.variants.filter(x=>x.recommendation.action==='AUSSCHALTEN').sort((a,b)=>a.days30.profit-b.days30.profit):[],scaleVariants=selected?selected.variants.filter(x=>x.recommendation.action==='SKALIEREN').sort((a,b)=>b.days30.profit-a.days30.profit):[],saving=offers.reduce((s,x)=>s+x.immediateSaving,0),best=selected?[...selected.variants].sort((a,b)=>b.days30.profit-a.days30.profit)[0]:null;
 return <main className="dashboard affiliateOptimizer affiliateDecisionDesk"><header className="topbar"><div><div className="eyebrow">ME MEDIA · AFFILIATE TRAFFIC INTELLIGENCE</div><h1>Affiliate Optimizer <span>Live</span></h1><p>Direktlinks und Smartlinks pro Partner – getrennte KPIs, vollständige Landingpage-Sicht.</p></div><div className="topActions"><InstantLink className="logout active" href="/affiliates" aria-current="page">Affiliate Optimizer</InstantLink><InstantLink className="logout" href="/automation">Auto-Rotation</InstantLink><InstantLink className="logout" href="/smartlinks">Smartlinks</InstantLink><InstantLink className="logout" href="/">Account Monitor</InstantLink><form action="/api/auth/logout" method="post"><button className="logout">Abmelden</button></form></div></header>
 <section className="smartSearch affiliateSearch"><form action="/affiliates"><label htmlFor="q">Affiliate-ID oder Name</label><div><input type="hidden" name="period" value={period.period}/>{period.period==='custom'&&<><input type="hidden" name="from" value={period.from}/><input type="hidden" name="to" value={period.to}/></>}<input id="q" name="q" defaultValue={query.q||''} placeholder="z. B. 376 oder Horny Honey"/><button>Suchen</button></div></form><div className="directScope"><b>{workspaces.length}</b><span>Partner · {mappings.length} beobachtete Smartlink-Zuordnungen</span></div></section>
 <section className="affiliatePeriod"><header><div><span>AUSWERTUNGSZEITRAUM</span><b>{period.label} · Europe/Berlin</b><small>Datumsgrenzen inklusive{period.includesToday?' · heute wird mitgerechnet':''}</small></div>{period.error&&<p role="alert">{period.error}</p>}</header><nav>{AFFILIATE_PERIODS.map(([id,label])=><InstantLink key={id} className={period.period===id?'active':''} href={periodHref(id)}>{label}</InstantLink>)}</nav><form action="/affiliates"><input type="hidden" name="period" value="custom"/>{query.affiliate&&<input type="hidden" name="affiliate" value={query.affiliate}/>} {query.offer&&<input type="hidden" name="offer" value={query.offer}/>} {query.mode&&<input type="hidden" name="mode" value={query.mode}/>}<label>Von<input type="date" name="from" required max={period.to} defaultValue={period.from}/></label><label>Bis<input type="date" name="to" required max={period.to} defaultValue={period.to}/></label><button>Zeitraum anwenden</button></form></section>
 {selectedWorkspace&&mode==='smartlinks'?<><section className="partnerHero smartPartnerHero"><div><InstantLink href={`/affiliates?${rangeParams}`}>← Alle Partner</InstantLink><span>AFFILIATE #{selectedWorkspace.affiliateId}</span><h2>{selectedWorkspace.affiliate}</h2><p>{selectedWorkspace.campaigns.length} Smartlinks · {selectedWorkspace.direct?.variants.length||0} direkte Landingpages · strikt getrennte Modi</p></div><div><small>Smartlink-Profit · {period.label}</small><strong className={selectedWorkspace.campaigns.reduce((s,c)=>s+c.profit30,0)>=0?'up':'down'}>{eur(selectedWorkspace.campaigns.reduce((s,c)=>s+c.profit30,0))}</strong><span>{num(selectedWorkspace.campaigns.reduce((s,c)=>s+c.sois30,0))} SOIs · Campaign-Traffic</span></div></section><nav className="trafficModeTabs">{selectedWorkspace.direct?<InstantLink href={`/affiliates?affiliate=${selectedWorkspace.affiliateId}&mode=direct&${rangeParams}`}>Direktlinks <small>{selectedWorkspace.direct.variants.length} LPs</small></InstantLink>:<span className="disabled">Direktlinks <small>kein Multi-LP-Direkttraffic</small></span>}<InstantLink className="active" href={`/affiliates?affiliate=${selectedWorkspace.affiliateId}&mode=smartlinks&${rangeParams}`}>Smartlinks <small>{selectedWorkspace.campaigns.length} Campaigns</small></InstantLink></nav><AffiliateSmartlinks mappings={selectedWorkspace.campaigns} insights={smartlinkInsights}/></>:selected&&activeOffer?<><section className="partnerHero"><div><InstantLink href={`/affiliates?${rangeParams}`}>← Alle Partner</InstantLink><span>AFFILIATE #{selected.affiliateId}</span><h2>{selected.affiliate}</h2><p>{offers.length} Offers · {selected.variants.length} Pfade · {period.label}</p></div><div><small>Direktlink-Profit · {period.label}</small><strong className={selected.totals30.profit>=0?'up':'down'}>{eur(selected.totals30.profit)}</strong><span>{num(selected.totals30.sois)} SOIs · {selected.totals30.firstSales} First-Sales</span></div></section><nav className="trafficModeTabs"><InstantLink className="active" href={`/affiliates?affiliate=${selected.affiliateId}&mode=direct&${rangeParams}`}>Direktlinks <small>{selected.variants.length} LPs</small></InstantLink>{selectedWorkspace?.campaigns.length?<InstantLink href={`/affiliates?affiliate=${selected.affiliateId}&mode=smartlinks&${rangeParams}`}>Smartlinks <small>{selectedWorkspace.campaigns.length} Campaigns</small></InstantLink>:<span className="disabled">Smartlinks <small>kein 30d-Traffic</small></span>}</nav>
 <section className="profitCommand"><article className="danger"><span>Direkt handeln</span><strong>{stopVariants.length}</strong><small>Landingpages zum Ausschalten</small></article><article><span>Erkennbares Sparpotenzial</span><strong className="up">{eur(saving)}</strong><small>negativer Profit im gewählten Zeitraum</small></article><article><span>Skalierungskandidaten</span><strong>{scaleVariants.length}</strong><small>mit belastbarer Sales-Evidenz</small></article><article><span>Beste Landingpage</span><strong className={best&&best.days30.profit>=0?'up':'down'}>{best?eur(best.days30.profit):'–'}</strong><small>{best?.offerUrl||'Keine Daten'}</small></article></section>
 {(stopVariants.length>0||scaleVariants.length>0)&&<section className="nextActions"><header><div><span>PROFIT-PRIORITÄT</span><h2>Was jetzt zuerst zu tun ist</h2></div><small>größter wirtschaftlicher Hebel zuerst</small></header><div>{[...stopVariants,...scaleVariants].slice(0,4).map(v=><InstantLink key={v.key} href={`/affiliates?affiliate=${selected.affiliateId}&offer=${v.offerId}&${rangeParams}#url-${v.offerUrlId}`} className={recClass(v)}><b>{v.recommendation.action}</b><span><strong>{v.offerUrl}</strong><small>Offer #{v.offerId} · URL #{v.offerUrlId}</small></span><em className={v.days30.profit>=0?'up':'down'}>{eur(v.days30.profit)}</em></InstantLink>)}</div></section>}
 {leadLatency&&<section className="leadLatencyPanel"><header><div><span>HISTORISCHE ZAHLERGESCHWINDIGKEIT</span><h2>Wie lange braucht ein Lead bis zum First-Sale?</h2><p>90-Tage-Historie · nur SOI → erster Event „Sale“ · 14 Tage gereifte Kohorten</p></div><em>Datengüte: {leadLatency.confidence} · {leadLatency.sampleSize} Zahler</em></header>{leadLatency.averageHours!==null?<><div className="latencyBenchmarks"><article><span>Ø SOI → Zahler</span><strong>{duration(leadLatency.averageHours)}</strong><small>arithmetischer Partnerdurchschnitt</small></article><article><span>Median</span><strong>{duration(leadLatency.medianHours)}</strong><small>50 % zahlen bis dahin</small></article><article><span>75%-Grenze</span><strong>{duration(leadLatency.p75Hours)}</strong><small>danach ist ein Lead überfällig</small></article><article><span>90%-Grenze</span><strong>{duration(leadLatency.p90Hours)}</strong><small>lange Nachläufer berücksichtigt</small></article></div><div className="leadCohortStatus"><div><b>{leadLatency.current.pending} offene Leads</b><small>aus den letzten {leadLatency.pendingWindowDays} Tagen · Ø Alter {duration(leadLatency.current.averageAgeHours)}</small></div><article><strong>{leadLatency.current.youngerThanAverage}</strong><span>Noch jünger als Partner-Ø</span><small>Noch nicht vorschnell abschalten</small></article><article><strong>{leadLatency.current.betweenAverageAndP75}</strong><span>Über Ø, aber im 75%-Fenster</span><small>eng beobachten</small></article><article className={leadLatency.current.overdue?'danger':''}><strong>{leadLatency.current.overdue}</strong><span>Älter als 75%-Grenze</span><small>überfällige Leads prüfen</small></article></div></>:<div className="latencyEmpty">Noch zu wenige zuordenbare First-Sales für einen belastbaren Partner-Benchmark.</div>}</section>}
 <section className="offerPicker"><header><div><span>1 · OFFER AUSWÄHLEN</span><h2>{offers.length} Offers dieses Partners</h2></div><small>Offer anklicken – nur ihre Landingpages werden darunter angezeigt</small></header><nav>{offers.map(o=><InstantLink key={o.offerId} className={o.offerId===activeOffer.offerId?'active':''} href={`/affiliates?affiliate=${selected.affiliateId}&offer=${o.offerId}&${rangeParams}`}><span>OFFER #{o.offerId}</span><strong>{o.offer}</strong><em>{o.variants.some(v=>v.trafficMode==='api')?'API · CLICKLESS':'DIREKTLINK · TRACKING'}</em><div><b className={o.totals30.profit>=0?'up':'down'}>{eur(o.totals30.profit)}</b><small>{period.label} · {o.totals30.sois} SOIs · {o.totals30.firstSales} First-Sales · {o.totals30.rebills} Rebills</small><small>{o.variants.length} Pfade · {o.stopCount?`${o.stopCount} stoppen`:o.scaleCount?`${o.scaleCount} skalieren`:'beobachten'}</small></div></InstantLink>)}</nav></section>
 <section className="offerWorkspace"><header><div><span>2 · LANDINGPAGES VERGLEICHEN · OFFER #{activeOffer.offerId}</span><h2>{activeOffer.offer}</h2><p>{activeOffer.variants.length} Offer-URLs – wichtigste Entscheidung steht oben</p></div><div><small>Profit dieser Offer · {period.label}</small><strong className={activeOffer.totals30.profit>=0?'up':'down'}>{eur(activeOffer.totals30.profit)}</strong><span>{eur(activeOffer.totals30.revenue)} Umsatz – {eur(activeOffer.totals30.payout)} SOI-Vergütung = Profit</span><span>{activeOffer.totals30.sois} SOIs · {activeOffer.totals30.firstSales} First-Sales · {activeOffer.totals30.rebills} Rebills</span></div></header><div className="urlTableHead"><span>Entscheidung / Landingpage</span><span>CR · SOIs / Klicks</span><span>Profit · Zeitraum</span><span>First-Sales</span><span>Trend</span></div><div className="urlDecisionTable">{activeOffer.variants.map(v=><LazyDetails id={`url-${v.offerUrlId}`} key={v.key} className={recClass(v)} summary={<><span className="urlMain"><b>{v.recommendation.action}</b><strong>{v.offerUrl}</strong><small>Landingpage · URL #{v.offerUrlId}</small></span><span className="crAbsolute">{cr(v.days30,v.trafficMode==='api')}<small>{v.trafficMode==='api'?`${num(v.days30.sois)} SOIs · ADV1 / ADV2`:`${num(v.days30.sois)} SOIs aus ${num(v.days30.clicks)} Klicks`}</small></span><span className={v.days30.profit>=0?'up':'down'}>{eur(v.days30.profit)}</span><span>{v.days30.firstSales} <small>First-Sales</small></span><span>{v.trend}<i>Details</i></span></>}><div className="urlDetails"><div className="periodCompare"><ProfitPeriod label={period.label} m={v.days30}/><article className="profitPeriod efficiency"><span>{v.efficiency.label==='Profit je Klick'?'PROFIT JE KLICK':'PROFIT JE SOI'}</span><b>{v.days30.clicks||v.days30.sois?eur(v.efficiency.days30):'nicht berechenbar'}</b><small>{v.efficiency.label==='Profit je Klick'?`${num(v.days30.clicks)} Klicks als Basis`:`${num(v.days30.sois)} SOIs als Basis`}</small><small>Diese Kennzahl erklärt nicht den Umsatz; sie misst nur die Effizienz.</small></article></div><div className="decisionReason"><b>{v.recommendation.action}: {v.recommendation.reason}</b><p>{v.recommendation.evidence.join(' · ')}</p></div>{leadLatency&&<UrlLeadMaturityPanel data={maturityByUrl.get(v.offerUrlId)} benchmark={leadLatency}/>}<SourceBreakdown rows={sourceRowsByUrl.get(`${v.offerId}|${v.offerUrlId}`)||[]} apiMode={v.trafficMode==='api'} rangeLabel={period.label}/></div></LazyDetails>)}</div>{!activeOffer.variants.some(v=>v.trafficMode==='api')&&<TrafficActionLists rows={sourceRows.filter(row=>row.offerId===activeOffer.offerId)} urls={Object.fromEntries(activeOffer.variants.map(v=>[v.offerUrlId,v.offerUrl]))}/>}</section></>:
 <><section className="sectionHead"><div><span>PARTNER-ÜBERSICHT</span><h2>{matches.length} Affiliates</h2></div><div className="scope">Profitabelste Partner zuerst</div></section><section className="affiliateList">{matches.map(a=><InstantLink key={a.affiliateId} href={`/affiliates?affiliate=${a.affiliateId}&mode=${a.direct?'direct':'smartlinks'}&${rangeParams}`}><div><span>AFFILIATE #{a.affiliateId}</span><h3>{a.affiliate}</h3><p>{a.direct?`${a.direct.variants.length} direkte Landingpages`: 'Kein Multi-LP-Direkttraffic'} · {a.campaigns.length} Smartlink{a.campaigns.length===1?'':'s'}</p></div><div className="partnerTrafficTotals">{a.direct&&<span><b className={a.direct.totals30.profit>=0?'up':'down'}>{eur(a.direct.totals30.profit)}</b><small>Direkt · 30d</small></span>}{a.campaigns.length>0&&<span><b className={a.campaigns.reduce((s,c)=>s+c.profit30,0)>=0?'up':'down'}>{eur(a.campaigns.reduce((s,c)=>s+c.profit30,0))}</b><small>Smartlinks · 30d</small></span>}</div><strong>Partner öffnen →</strong></InstantLink>)}</section>{!matches.length&&<section className="smartEmpty"><h2>Kein Affiliate gefunden</h2><p>Suche nach einer anderen ID oder einem anderen Namen.</p></section>}</>}
 </main>}
