import Link from'next/link';
import{redirect}from'next/navigation';
import{currentUser}from'@/lib/session';
import{getAffiliateOptimizations,getAffiliateLeadLatency,getAffiliateSourceBreakdown}from'@/lib/affiliate-optimizer-service';
import{groupAffiliateOffers,type AffiliateVariant}from'@/lib/affiliate-optimizer';
import type{SourceBreakdownRow}from'@/lib/source-breakdown';
import type{LeadLatencyAnalysis,UrlLeadMaturity}from'@/lib/lead-latency';
import SourceBreakdown from'./SourceBreakdown';
export const dynamic='force-dynamic';
const eur=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const num=(n:number)=>new Intl.NumberFormat('de-DE').format(n);
const pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`;
const cr=(m:{clicks:number;sois:number;cvr:number})=>m.clicks?`${pct(m.cvr)} (${num(m.sois)} / ${num(m.clicks)})`:`n/a (${num(m.sois)} / 0)`;
const recClass=(v:AffiliateVariant)=>v.recommendation.severity;
const duration=(hours:number|null)=>hours===null?'–':hours<48?`${hours.toFixed(1).replace('.',',')} Std.`:`${(hours/24).toFixed(1).replace('.',',')} Tage`;
function UrlLeadMaturityPanel({data,benchmark}:{data?:UrlLeadMaturity;benchmark:LeadLatencyAnalysis}){if(!data?.pending)return <div className="urlMaturity clear"><div><span>LEAD-REIFE · LETZTE {benchmark.pendingWindowDays} TAGE</span><b>Keine aktuell offenen Leads</b></div><small>Kein unverkaufter SOI in diesem Fenster.</small></div>;return <div className={`urlMaturity ${data.overdue?'late':''}`}><div><span>LEAD-REIFE · LETZTE {benchmark.pendingWindowDays} TAGE</span><b>{data.pending} offene Leads · Ø Alter {duration(data.averageAgeHours)}</b><small>Partner-Ø bis First-Sale: {duration(benchmark.averageHours)} · 75 % bis {duration(benchmark.p75Hours)}</small></div><div><article><b>{data.youngerThanAverage}</b><small>jünger als Ø</small></article><article><b>{data.betweenAverageAndP75}</b><small>über Ø, noch im 75%-Fenster</small></article><article className={data.overdue?'danger':''}><b>{data.overdue}</b><small>älter als 75%-Grenze</small></article></div></div>}
export default async function AffiliateOptimizerPage({searchParams}:{searchParams:Promise<{affiliate?:string;q?:string;offer?:string}>}){
 if(!await currentUser())redirect('/login');const query=await searchParams;let analyses;
 try{analyses=await getAffiliateOptimizations()}catch(e){console.error(e);return <main className="fatal"><div className="eyebrow">EVERFLOW NICHT ERREICHBAR</div><h1>Affiliate Optimizer konnte nicht geladen werden</h1><Link href="/affiliates">Erneut versuchen</Link></main>}
 const q=(query.q||'').trim().toLowerCase(),matches=q?analyses.filter(x=>x.affiliateId===q||x.affiliate.toLowerCase().includes(q)):analyses,selected=(query.affiliate?analyses.find(x=>x.affiliateId===query.affiliate):null)||null;let sourceRows:SourceBreakdownRow[]=[],leadLatency:LeadLatencyAnalysis|null=null;if(selected){const[sourceResult,latencyResult]=await Promise.allSettled([getAffiliateSourceBreakdown(selected.affiliateId),getAffiliateLeadLatency(selected.affiliateId)]);if(sourceResult.status==='fulfilled')sourceRows=sourceResult.value;else console.error('Source breakdown failed',sourceResult.reason);if(latencyResult.status==='fulfilled')leadLatency=latencyResult.value;else console.error('Lead latency failed',latencyResult.reason)}const maturityByUrl=new Map((leadLatency?.byUrl||[]).map(x=>[x.offerUrlId,x])),offers=selected?groupAffiliateOffers(selected):[],activeOffer=offers.find(x=>x.offerId===query.offer)||offers[0],stopVariants=selected?selected.variants.filter(x=>x.recommendation.action==='AUSSCHALTEN').sort((a,b)=>a.days30.profit-b.days30.profit):[],scaleVariants=selected?selected.variants.filter(x=>x.recommendation.action==='SKALIEREN').sort((a,b)=>b.days30.profit-a.days30.profit):[],saving=offers.reduce((s,x)=>s+x.immediateSaving,0),best=selected?[...selected.variants].sort((a,b)=>b.days30.profit-a.days30.profit)[0]:null;
 return <main className="dashboard affiliateOptimizer affiliateDecisionDesk"><header className="topbar"><div><div className="eyebrow">ME MEDIA · DIRECT TRAFFIC INTELLIGENCE</div><h1>Affiliate Optimizer <span>Live</span></h1><p>Vom Partner zur Offer zur Landingpage – Entscheidungen nach Profit priorisiert.</p></div><div className="topActions"><Link className="logout" href="/automation">Auto-Rotation</Link><Link className="logout" href="/smartlinks">Smartlinks</Link><Link className="logout" href="/">Account Monitor</Link><form action="/api/auth/logout" method="post"><button className="logout">Abmelden</button></form></div></header>
 <section className="smartSearch affiliateSearch"><form action="/affiliates"><label htmlFor="q">Affiliate-ID oder Name</label><div><input id="q" name="q" defaultValue={query.q||''} placeholder="z. B. 376 oder Horny Honey"/><button>Suchen</button></div></form><div className="directScope"><b>{analyses.length}</b><span>Multi-Offer-Partner · direkte Links</span></div></section>
 {selected&&activeOffer?<><section className="partnerHero"><div><Link href="/affiliates">← Alle Partner</Link><span>AFFILIATE #{selected.affiliateId}</span><h2>{selected.affiliate}</h2><p>{offers.length} Offers · {selected.variants.length} Landingpages · letzte 30 Tage</p></div><div><small>Gesamtprofit</small><strong className={selected.totals30.profit>=0?'up':'down'}>{eur(selected.totals30.profit)}</strong><span>{num(selected.totals30.sois)} SOIs · {selected.totals30.firstSales} First-Sales</span></div></section>
 <section className="profitCommand"><article className="danger"><span>Direkt handeln</span><strong>{stopVariants.length}</strong><small>Landingpages zum Ausschalten</small></article><article><span>Erkennbares Sparpotenzial</span><strong className="up">{eur(saving)}</strong><small>negativer 30d-Profit der Stop-Kandidaten</small></article><article><span>Skalierungskandidaten</span><strong>{scaleVariants.length}</strong><small>mit belastbarer Sales-Evidenz</small></article><article><span>Beste Landingpage</span><strong className={best&&best.days30.profit>=0?'up':'down'}>{best?eur(best.days30.profit):'–'}</strong><small>{best?.offerUrl||'Keine Daten'}</small></article></section>
 {leadLatency&&<section className="leadLatencyPanel"><header><div><span>HISTORISCHE ZAHLERGESCHWINDIGKEIT</span><h2>Wie lange braucht ein Lead bis zum First-Sale?</h2><p>90-Tage-Historie · nur SOI → erster Event „Sale“ · 14 Tage gereifte Kohorten</p></div><em>Datengüte: {leadLatency.confidence} · {leadLatency.sampleSize} Zahler</em></header>{leadLatency.averageHours!==null?<><div className="latencyBenchmarks"><article><span>Ø SOI → Zahler</span><strong>{duration(leadLatency.averageHours)}</strong><small>arithmetischer Partnerdurchschnitt</small></article><article><span>Median</span><strong>{duration(leadLatency.medianHours)}</strong><small>50 % zahlen bis dahin</small></article><article><span>75%-Grenze</span><strong>{duration(leadLatency.p75Hours)}</strong><small>danach ist ein Lead überfällig</small></article><article><span>90%-Grenze</span><strong>{duration(leadLatency.p90Hours)}</strong><small>lange Nachläufer berücksichtigt</small></article></div><div className="leadCohortStatus"><div><b>{leadLatency.current.pending} offene Leads</b><small>aus den letzten {leadLatency.pendingWindowDays} Tagen · Ø Alter {duration(leadLatency.current.averageAgeHours)}</small></div><article><strong>{leadLatency.current.youngerThanAverage}</strong><span>Noch jünger als Partner-Ø</span><small>Noch nicht vorschnell abschalten</small></article><article><strong>{leadLatency.current.betweenAverageAndP75}</strong><span>Über Ø, aber im 75%-Fenster</span><small>eng beobachten</small></article><article className={leadLatency.current.overdue?'danger':''}><strong>{leadLatency.current.overdue}</strong><span>Älter als 75%-Grenze</span><small>überfällige Leads prüfen</small></article></div></>:<div className="latencyEmpty">Noch zu wenige zuordenbare First-Sales für einen belastbaren Partner-Benchmark.</div>}</section>}
 {(stopVariants.length>0||scaleVariants.length>0)&&<section className="nextActions"><header><div><span>PROFIT-PRIORITÄT</span><h2>Was jetzt zuerst zu tun ist</h2></div><small>größter wirtschaftlicher Hebel zuerst</small></header><div>{[...stopVariants,...scaleVariants].slice(0,4).map(v=><Link key={v.key} href={`/affiliates?affiliate=${selected.affiliateId}&offer=${v.offerId}#url-${v.offerUrlId}`} className={recClass(v)}><b>{v.recommendation.action}</b><span><strong>{v.offerUrl}</strong><small>Offer #{v.offerId} · URL #{v.offerUrlId}</small></span><em className={v.days30.profit>=0?'up':'down'}>{eur(v.days30.profit)}</em></Link>)}</div></section>}
 <section className="offerPicker"><header><div><span>1 · OFFER AUSWÄHLEN</span><h2>{offers.length} Offers dieses Partners</h2></div><small>Offer anklicken – nur ihre Landingpages werden darunter angezeigt</small></header><nav>{offers.map(o=><Link key={o.offerId} className={o.offerId===activeOffer.offerId?'active':''} href={`/affiliates?affiliate=${selected.affiliateId}&offer=${o.offerId}`}><span>OFFER #{o.offerId}</span><strong>{o.offer}</strong><div><b className={o.totals30.profit>=0?'up':'down'}>{eur(o.totals30.profit)}</b><small>{o.variants.length} LPs · {o.stopCount?`${o.stopCount} stoppen`:o.scaleCount?`${o.scaleCount} skalieren`:'beobachten'}</small></div></Link>)}</nav></section>
 <section className="offerWorkspace"><header><div><span>2 · LANDINGPAGES VERGLEICHEN · OFFER #{activeOffer.offerId}</span><h2>{activeOffer.offer}</h2><p>{activeOffer.variants.length} Offer-URLs – wichtigste Entscheidung steht oben</p></div><div><small>30-Tage-Offer-Profit</small><strong className={activeOffer.totals30.profit>=0?'up':'down'}>{eur(activeOffer.totals30.profit)}</strong><span>{activeOffer.totals30.sois} SOIs · {activeOffer.totals30.firstSales} Sales</span></div></header><div className="urlTableHead"><span>Entscheidung / Landingpage</span><span>CR · SOIs / Klicks</span><span>30d Profit</span><span>First-Sales</span><span>Trend</span></div><div className="urlDecisionTable">{activeOffer.variants.map(v=><details id={`url-${v.offerUrlId}`} key={v.key} className={recClass(v)}><summary><span className="urlMain"><b>{v.recommendation.action}</b><strong>{v.offerUrl}</strong><small>Landingpage · URL #{v.offerUrlId}</small></span><span className="crAbsolute">{cr(v.days30)}<small>SOIs / Klicks</small></span><span className={v.days30.profit>=0?'up':'down'}>{eur(v.days30.profit)}</span><span>{v.days30.firstSales} <small>First-Sales</small></span><span>{v.trend}<i>Details ›</i></span></summary><div className="urlDetails"><div className="periodCompare"><article><span>HEUTE</span><b className={v.today.profit>=0?'up':'down'}>{eur(v.today.profit)}</b><small>CR {cr(v.today)} · {v.today.firstSales} Sales</small></article><article><span>7 TAGE</span><b className={v.days7.profit>=0?'up':'down'}>{eur(v.days7.profit)}</b><small>CR {cr(v.days7)} · {v.days7.firstSales} Sales</small></article><article><span>30 TAGE</span><b className={v.days30.profit>=0?'up':'down'}>{eur(v.days30.profit)}</b><small>CR {cr(v.days30)} · {v.days30.firstSales} Sales</small></article><article><span>{v.efficiency.label.toUpperCase()}</span><b>{eur(v.efficiency.days30)}</b><small>{v.days30.rebills} Rebills · {eur(v.days30.revenue)} Umsatz</small></article></div><div className="decisionReason"><b>{v.recommendation.action}: {v.recommendation.reason}</b><p>{v.recommendation.evidence.join(' · ')}</p></div>{leadLatency&&<UrlLeadMaturityPanel data={maturityByUrl.get(v.offerUrlId)} benchmark={leadLatency}/>}<SourceBreakdown rows={sourceRows.filter(row=>row.offerId===v.offerId&&row.offerUrlId===v.offerUrlId)}/></div></details>)}</div></section></>:
 <><section className="sectionHead"><div><span>PARTNER-ÜBERSICHT</span><h2>{matches.length} Affiliates</h2></div><div className="scope">Profitabelste Partner zuerst</div></section><section className="affiliateList">{matches.map(a=><Link key={a.affiliateId} href={`/affiliates?affiliate=${a.affiliateId}`}><div><span>AFFILIATE #{a.affiliateId}</span><h3>{a.affiliate}</h3><p>{a.summary}</p></div><div><b className={a.totals30.profit>=0?'up':'down'}>{eur(a.totals30.profit)}</b><span>30-Tage-Profit</span></div><strong>Partner öffnen →</strong></Link>)}</section>{!matches.length&&<section className="smartEmpty"><h2>Kein Affiliate gefunden</h2><p>Suche nach einer anderen ID oder einem anderen Namen.</p></section>}</>}
 </main>}
