'use client';
import{useRef,useState,useTransition,type FormEvent}from'react';
import{usePathname,useRouter,useSearchParams}from'next/navigation';
import{buildCalendarSourceRange,buildSourcePeriodQuery,type ResolvedSourcePeriod,type SourcePeriod}from'../../lib/source-period';
const presets:[SourcePeriod,string][]=[['today','Heute'],['7d','7 Tage'],['30d','30 Tage'],['90d','90 Tage']];
const months=[['01','Januar'],['02','Februar'],['03','März'],['04','April'],['05','Mai'],['06','Juni'],['07','Juli'],['08','August'],['09','September'],['10','Oktober'],['11','November'],['12','Dezember']] as const;
export const collectOpenSourceDetails=(node:HTMLElement|null)=>{const outer=node?.closest<HTMLDetailsElement>('details[id]');if(!outer)return{ids:[] as string[],anchorId:''};const details=[outer,...outer.querySelectorAll<HTMLDetailsElement>('details[open][id]')],ids=[...new Set(details.filter(item=>item.open).map(item=>item.id))];return{ids,anchorId:outer.id}};
export default function SourcePeriodControls({period}:{period:ResolvedSourcePeriod}){
 const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams(),root=useRef<HTMLDivElement>(null),[pending,startTransition]=useTransition();
 const maxYear=Number(period.maxDate.slice(0,4)),maxMonth=period.maxDate.slice(5,7),initialYear=period.period==='calendar'?period.from.slice(0,4):String(maxYear),initialMonth=period.period==='calendar'&&period.from.slice(0,7)===period.to.slice(0,7)?period.from.slice(5,7):'all';
 const [panel,setPanel]=useState<'calendar'|'custom'|null>(period.period==='calendar'?'calendar':period.period==='custom'||Boolean(period.error)?'custom':null),[year,setYear]=useState(initialYear),[month,setMonth]=useState(initialMonth);
 const years=Array.from({length:11},(_,index)=>String(maxYear-index)),visibleMonths=months.filter(([id])=>year!==String(maxYear)||id<=maxMonth);
 const navigate=(next:SourcePeriod,from?:string,to?:string)=>{const query=new URLSearchParams(buildSourcePeriodQuery(searchParams,next,from,to)),{ids,anchorId}=collectOpenSourceDetails(root.current);if(ids.length)query.set('sourceOpen',ids.join(','));else query.delete('sourceOpen');startTransition(()=>router.push(`${pathname}?${query}${anchorId?`#${encodeURIComponent(anchorId)}`:''}`,{scroll:false}))};
 const submitCustom=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);navigate('custom',String(data.get('sourceFrom')||''),String(data.get('sourceTo')||''))};
 const submitCalendar=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const range=buildCalendarSourceRange(year,month,period.maxDate);if(range)navigate('calendar',range.from,range.to)};
 const chooseYear=(next:string)=>{setYear(next);if(next===String(maxYear)&&month!=='all'&&month>maxMonth)setMonth('all')};
 return <div ref={root} className="sourcePeriodControls" aria-busy={pending}>
  <div className="sourcePeriodPresets" role="group" aria-label="Zeitraum der Quellenauswertung"><small>Zeitraum</small>{presets.map(([id,label])=><button type="button" key={id} className={period.period===id?'active':''} aria-pressed={period.period===id} onClick={()=>navigate(id)}>{label}</button>)}<button type="button" className={period.period==='calendar'||panel==='calendar'?'active':''} aria-expanded={panel==='calendar'} onClick={()=>setPanel(value=>value==='calendar'?null:'calendar')}>Jahr / Monat</button><button type="button" className={period.period==='custom'||panel==='custom'?'active':''} aria-expanded={panel==='custom'} onClick={()=>setPanel(value=>value==='custom'?null:'custom')}>Individuell</button></div>
  {panel==='calendar'&&<form className="sourceCalendarPeriod" onSubmit={submitCalendar}><label>Jahr auswählen<select name="sourceYear" value={year} onChange={event=>chooseYear(event.target.value)}>{years.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>Monat auswählen<select name="sourceMonth" value={month} onChange={event=>setMonth(event.target.value)}><option value="all">Ganzes Jahr</option>{visibleMonths.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><button type="submit">Anwenden</button><small>{month==='all'?`01.01.${year} bis ${year===String(maxYear)?period.maxDate.split('-').reverse().join('.'): `31.12.${year}`}`:`Kalendermonat ${months.find(([id])=>id===month)?.[1]} ${year}`}</small></form>}
  {panel==='custom'&&<form className="sourceCustomPeriod" onSubmit={submitCustom}><label>Von<input type="date" name="sourceFrom" required max={period.maxDate} defaultValue={period.from}/></label><label>Bis<input type="date" name="sourceTo" required max={period.maxDate} defaultValue={period.to}/></label><button type="submit">Anwenden</button></form>}
  {period.error&&<p role="alert">{period.error}</p>}{pending&&<span className="sourcePeriodPending" role="status"><i/>Lädt …</span>}
 </div>
}
