'use client';
import{useMemo,useState,type ReactNode}from'react';
import{sortSmartlinkSlots,type SmartlinkSort}from'@/lib/smartlink-presentation';
import type{SlotRecommendation,SmartSlot}from'@/lib/smartlink';
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n),num=(n:number)=>new Intl.NumberFormat('de-DE').format(n),pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`,actionLabel:{[K in SlotRecommendation['action']]:string}={stop:'STOPPEN',rotate:'ROTIEREN',scale:'SKALIEREN',protect:'SCHÜTZEN',hold:'HALTEN'};
export function KpiValue({label,value,detail,scope,size='m',tone='neutral'}:{label:string;value:string;detail?:string;scope?:string;size?:'l'|'m'|'s';tone?:'positive'|'negative'|'neutral'}){return <div className={`sharedKpi size-${size} tone-${tone}`}><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}{scope&&<em>{scope}</em>}</div>}
export function TimeWindowSection({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:ReactNode;className?:string}){return <section className={`timeWindowSection ${className}`.trim()}><header><b>{title}</b>{subtitle&&<span>{subtitle}</span>}</header><div>{children}</div></section>}
export function RecommendationBanner({recommendation,scope='Aktuelle BI-Empfehlung · Read only'}:{recommendation:SlotRecommendation;scope?:string}){return <section className={`sharedRecommendation ${recommendation.severity}`}><div><span>{scope}</span><h3>{recommendation.title}</h3><p>{recommendation.detail}</p></div><b>{actionLabel[recommendation.action]}</b></section>}
export function StatusBadge({recommendation}:{recommendation?:SlotRecommendation}){const rec=recommendation||{action:'hold',severity:'neutral',title:'Beobachten',detail:'Noch keine belastbare Empfehlung.'}as SlotRecommendation,tip=`${rec.title}: ${rec.detail}`;return <button type="button" className={`sharedStatusBadge ${rec.severity}`} data-tooltip={tip} aria-label={`${actionLabel[rec.action]}. ${tip}`}>{actionLabel[rec.action]}</button>}
export function SmartlinkRotationCards({slots,recommendations,rotationLabel}:{slots:SmartSlot[];recommendations:SlotRecommendation[];rotationLabel:string}){const[sort,setSort]=useState<SmartlinkSort>('rotation'),sorted=useMemo(()=>sortSmartlinkSlots(slots,sort),[slots,sort]),byId=useMemo(()=>new Map(recommendations.map(x=>[x.slotId,x])),[recommendations]);return <section className="sharedRotation"><div className="rotationToolbar"><div><span>AKTUELLE ROTATION</span><b>{slots.length} aktive Landingpages</b><small>{rotationLabel}</small></div><div className="rotationSort" role="group" aria-label="Landingpages sortieren"><small>Sortierung</small>{([['rotation','Rotation'],['profit','Profit'],['cvr','CVR'],['sois','SOIs']]as const).map(([id,label])=><button type="button" key={id} className={sort===id?'active':''} aria-pressed={sort===id} onClick={()=>setSort(id)}>{label}</button>)}</div></div><div className="sharedLpGrid">{sorted.map(slot=>{const rec=byId.get(slot.id);return <article className={`sharedLpCard ${rec?.severity||'neutral'}`} key={slot.id}><header><div><span>LP #{slot.id} · Offer #{slot.offerId}</span><h3>{slot.name}</h3><small>{slot.weight} % Gewicht · {slot.status}</small></div><StatusBadge recommendation={rec}/></header><div className="primaryKpis"><KpiValue label="Profit" value={euro(slot.metrics14.profit)} scope="Aktuelle Rotation" size="l" tone={slot.metrics14.profit>=0?'positive':'negative'}/><KpiValue label="CVR" value={pct(slot.metrics24.cvr)} detail={`${num(slot.metrics24.sois)} SOIs aus ${num(slot.metrics24.clicks)} Klicks`} scope="Letzte 24 Stunden" size="l" tone={slot.metrics24.cvr>=1?'positive':slot.metrics24.clicks?'negative':'neutral'}/></div><TimeWindowSection title="Aktuelle Rotation" subtitle="Sales- und Reife-Evidenz"><KpiValue label="SOIs" value={num(slot.metrics14.sois)}/><KpiValue label="First-Sales" value={num(slot.metrics14.firstSales)}/><KpiValue label="First-Sale-Rate" value={pct(slot.metrics14.firstSaleRate)} detail={`${num(slot.metrics14.firstSales)} First-Sales aus ${num(slot.metrics14.sois)} SOIs`}/><KpiValue label="Rebills" value={num(slot.metrics14.rebills)}/></TimeWindowSection><TimeWindowSection title="Weitere Wirtschaftlichkeit" subtitle="Nachrangige Diagnose" className="tertiaryWindow"><KpiValue label="Profit-EPC" value={euro(slot.metrics14.profitEpc)} size="s" tone={slot.metrics14.profitEpc>=0?'positive':'negative'}/><KpiValue label="Umsatz" value={euro(slot.metrics72.revenue)} size="s"/><KpiValue label="Payout" value={euro(slot.metrics72.payout)} size="s"/><KpiValue label="Bis 50 SOIs" value={slot.hoursTo50Sois===null?'Keine Prognose':`${slot.hoursTo50Sois} Std.`} size="s"/></TimeWindowSection></article>})}</div></section>}
