import InstantLink from './affiliates/InstantLink';
import { redirect } from 'next/navigation';
import { currentUser } from '@/lib/session';
import { getDashboard } from '@/lib/dashboard-service';
import {reportingRange,type ReportingPeriod} from '@/lib/supabase-reporting';
import type { EntityRow,PathRow } from '@/lib/portfolio';
import DashboardPageHeader from './components/DashboardPageHeader';
import DataStatusBar from './components/DataStatusBar';
import AccessDeniedHint from './components/AccessDeniedHint';
import {getDataStatus,headerStatus,partnerHeaderStatus} from '@/lib/data-status';
import PortfolioCopyButton from './components/PortfolioCopyButton';
import {buildPortfolioCopyReport} from '@/lib/portfolio-copy-report';
import {companyResultState,filterCompanies} from '@/lib/portfolio-company-search';
import {can} from '@/lib/rbac';
import DashboardPeriodControls from './components/DashboardPeriodControls';
import LeitstandSection from './components/LeitstandSection';
export const dynamic='force-dynamic';
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const num=(n:number)=>new Intl.NumberFormat('de-DE').format(n);
const pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`;
type View='offers'|'affiliates'|'paths';
export default async function DashboardPage({searchParams}:{searchParams:Promise<{period?:string;view?:string;from?:string;to?:string;company?:string}>}){
 const user=await currentUser();if(!user)redirect('/login');if(!can(user.access,'dashboard.view'))return <main className="fatal"><h1>403 · Keine Berechtigung</h1><p>Fehlende Berechtigung: dashboard.view</p></main>;const finance=can(user.access,'finance.view'),query=await searchParams;const allowed:ReportingPeriod[]=['today','7d','30d','90d','12m','all','custom'];const period:ReportingPeriod=allowed.includes(query.period as ReportingPeriod)?query.period as ReportingPeriod:'7d';const view:View=query.view==='affiliates'||query.view==='paths'?query.view:'offers';
 let data;try{data=await getDashboard(period,{from:query.from,to:query.to},user.access)}catch(error){console.error(error);if(error instanceof Error&&error.message.includes('403'))return <main className="fatal"><h1>403 · Scope nicht sicher auswertbar</h1><AccessDeniedHint/></main>;return <main className="fatal"><div className="eyebrow">DATENQUELLE NICHT ERREICHBAR</div><h1>Dashboard konnte nicht geladen werden</h1><p>Der Supabase-Historiencache ist noch nicht eingerichtet oder vorübergehend nicht verfügbar.</p><InstantLink href="/">Erneut versuchen</InstantLink></main>}
 const rows:(EntityRow|PathRow)[]=view==='offers'?data.offers:view==='affiliates'?data.affiliates:data.paths;const visibleRows=rows.filter(x=>x.clicks>0||x.sois>0||x.firstSales>0||x.rebills>0||(finance&&(x.revenue!==0||x.payout!==0))),activeRows=finance?visibleRows:[...visibleRows].sort((a,b)=>b.sois-a.sois),company=query.company?.trim()??'',displayedRows=view==='affiliates'?filterCompanies(activeRows as EntityRow[],company):activeRows,companyState=view==='affiliates'?companyResultState(displayedRows.length,company):null,copyInput={rangeLabel:data.range.label,totals:data.totals,paths:data.paths},periodQuery=`period=${period}${period==='custom'?`&from=${encodeURIComponent(data.range.from??'')}&to=${encodeURIComponent(data.range.to)}`:''}`;
 const dataStatus=await getDataStatus(),header=user.access.role==='partner'?partnerHeaderStatus(dataStatus):headerStatus(dataStatus);
 return <main className="dashboard"><DashboardPageHeader kicker="ME Media · Everflow Monitor" title={user.access.role==='partner'?'Freigegebene Partnerdaten':'Gesamter Account'} status={header.label} tone={header.tone} icon="monitor" description={user.access.role==='partner'?'Ausschließlich Ihr zugeordneter Datenscope':'Alle Offers, Affiliates, Smartlinks und Direkt-Traffic auf einen Blick.'}/>
 <DataStatusBar status={dataStatus} audience={user.access.role==='partner'?'partner':'internal'}/>
 {user.access.role!=='partner'&&<LeitstandSection access={user.access}/>}
 <DashboardPeriodControls period={period} rangeLabel={data.range.label} maxDate={reportingRange('today').to} from={data.range.from??undefined} to={data.range.to}/>
 <section className="kpis">{finance&&<><article className="kpi hero"><span>Account-Profit</span><strong className={data.totals.profit>=0?'up':'down'}>{euro(data.totals.profit)}</strong><small>Profit-EPC {euro(data.totals.profitEpc)}</small></article><article className="kpi"><span>Umsatz</span><strong>{euro(data.totals.revenue)}</strong><small>{euro(data.totals.payout)} Payout</small></article></>}<article className="kpi"><span>Traffic</span><strong>{num(data.totals.clicks)}</strong><small>Klicks</small></article><article className="kpi"><span>SOIs</span><strong>{num(data.totals.sois)}</strong><small>CVR {pct(data.totals.cvr)}</small></article><article className="kpi"><span>Monetarisierung</span><strong>{data.totals.firstSales} / {data.totals.rebills}</strong><small>First-Sales / Rebills</small></article></section>
 {finance&&<section className="portfolioCopyBar"><div><span>PARTNERFERTIGE ÜBERSICHTEN</span><b>Nur Leads und gebuchte Payouts weitergeben</b><small>Umsatz und Profit werden nie kopiert. Es erscheinen nur Firmen und Brands mit Leads.</small></div><PortfolioCopyButton text={buildPortfolioCopyReport(copyInput,{scope:'total'})} label="Gesamtübersicht kopieren"/></section>}
 <section className="portfolioScope"><div><b>{data.offers.length}</b><span>Offers</span></div><div><b>{data.affiliates.length}</b><span>Affiliates</span></div><div><b>{data.paths.length}</b><span>Traffic-Pfade / LPs</span></div><div><b>{data.paths.filter(x=>x.trafficType==='Smartlink').length}</b><span>Smartlink-Pfade</span></div><div><b>{data.paths.filter(x=>x.trafficType==='Direkt').length}</b><span>Direkte Pfade</span></div></section>
 <div className="viewTabs">{([['offers','Brands / Offers'],['affiliates','Firmen / Affiliates'],['paths','Landingpages & Pfade']] as const).map(([value,label])=><InstantLink key={value} className={view===value?'active':''} href={`/?${periodQuery}&view=${value}`}>{label}</InstantLink>)}</div>
 <section className="sectionHead"><div><span>{user.access.role==='partner'?'Freigegebene Auswertung':'Accountweite Auswertung'}</span><h2>{view==='offers'?'Brands / Offers':view==='affiliates'?'Firmen / Affiliates':'Landingpages und Traffic-Pfade'}</h2></div><div className="scope">{displayedRows.length}{company&&view==='affiliates'?` von ${activeRows.length}`:''} aktive Zeilen · {finance?'nach Profit':'nach SOIs'} sortiert</div></section>
 {view==='affiliates'&&<form className="companySearch" method="get" role="search"><input type="hidden" name="period" value={period}/><input type="hidden" name="view" value="affiliates"/>{period==='custom'&&<><input type="hidden" name="from" value={query.from}/><input type="hidden" name="to" value={query.to}/></>}<label htmlFor="company-search">Firmen suchen</label><div><input id="company-search" name="company" type="search" defaultValue={company} placeholder="Firma oder Affiliate-ID"/><button type="submit">Suchen</button>{company&&<InstantLink className="companySearchClear" href={`/?period=${period}&view=affiliates${period==='custom'?`&from=${encodeURIComponent(query.from??'')}&to=${encodeURIComponent(query.to??'')}`:''}`}>Zurücksetzen</InstantLink>}</div></form>}
 {companyState==='search-empty'?<div className="companySearchEmpty"><b>Keine Firma gefunden</b><span>Suchbegriff oder Affiliate-ID prüfen.</span></div>:companyState==='portfolio-empty'?<div className="companySearchEmpty"><b>Keine aktiven Firmen</b><span>Für diesen Zeitraum liegen keine aktiven Firmen vor.</span></div>:<div className="tableWrap"><table className="performanceTable"><thead><tr><th>#</th><th>{view==='offers'?'Brand / Offer':view==='affiliates'?'Firma / Affiliate':'Landingpage / Pfad'}</th><th>Klicks</th><th>SOIs / CVR</th><th>First-Sales / Rate</th><th>Rebills</th>{finance&&<><th>Umsatz</th><th>Payout</th><th>Profit</th><th>Profit-EPC</th></>}</tr></thead><tbody>{displayedRows.map((row,index)=>{const isPath='key'in row;const path=row as PathRow;const entity=row as EntityRow;const name=isPath?path.offerUrl:entity.name;const id=isPath?path.offerUrlId:entity.id;const copyText=finance&&!isPath?buildPortfolioCopyReport(copyInput,view==='affiliates'?{scope:'affiliate',id}:{scope:'offer',id}):'';return <tr key={isPath?path.key:`${view}-${entity.id}`}><td data-label="#">{index+1}</td><td data-label="Einheit"><b>{name}</b><small>#{id}{isPath?` · ${path.offer} · ${path.affiliate} · ${path.trafficType}${path.campaignId!=='0'?` #${path.campaignId}`:''}`:` · ${entity.pathCount} Pfade`}</small>{copyText&&<PortfolioCopyButton text={copyText} label={view==='affiliates'?'Partnerbericht kopieren':'Brand / Offer kopieren'}/>}</td><td data-label="Klicks">{num(row.clicks)}</td><td data-label="SOIs / CVR"><b>{num(row.sois)}</b><small>{pct(row.cvr)}</small></td><td data-label="First-Sales / Rate"><b>{row.firstSales}</b><small>{pct(row.firstSaleRate)}</small></td><td data-label="Rebills">{row.rebills}</td>{finance&&<><td data-label="Umsatz">{euro(row.revenue)}</td><td data-label="Payout">{euro(row.payout)}</td><td data-label="Profit"><b className={row.profit>=0?'up':'down'}>{euro(row.profit)}</b></td><td data-label="Profit-EPC">{euro(row.profitEpc)}</td></>}</tr>})}</tbody></table></div>}
 <footer><div><b>Persistenter Supabase-Cache</b><span>Gebuchte Payouts inklusive Custom Payouts · First-Sales ausschließlich Event „Sale“.</span></div></footer></main>
}
