import Link from 'next/link';
import { redirect } from 'next/navigation';
import { currentUser } from '@/lib/session';
import { getDashboard } from '@/lib/dashboard-service';
import type { Period } from '@/lib/dashboard';
import type { EntityRow,PathRow } from '@/lib/portfolio';
export const dynamic='force-dynamic';
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const num=(n:number)=>new Intl.NumberFormat('de-DE').format(n);
const pct=(n:number)=>`${n.toFixed(2).replace('.',',')} %`;
type View='offers'|'affiliates'|'paths';
export default async function DashboardPage({searchParams}:{searchParams:Promise<{period?:string;view?:string}>}){
 const user=await currentUser();if(!user)redirect('/login');const query=await searchParams;const period:Period=query.period==='today'||query.period==='30d'?query.period:'7d';const view:View=query.view==='affiliates'||query.view==='paths'?query.view:'offers';
 let data;try{data=await getDashboard(period)}catch(error){console.error(error);return <main className="fatal"><div className="eyebrow">DATENQUELLE NICHT ERREICHBAR</div><h1>Dashboard konnte nicht geladen werden</h1><p>Die Everflow-Daten sind vorübergehend nicht verfügbar.</p><Link href="/">Erneut versuchen</Link></main>}
 const rows:(EntityRow|PathRow)[]=view==='offers'?data.offers:view==='affiliates'?data.affiliates:data.paths;const activeRows=rows.filter(x=>x.clicks>0||x.sois>0||x.revenue!==0||x.payout!==0);
 return <main className="dashboard"><header className="topbar"><div><div className="eyebrow">ME MEDIA · EVERFLOW ACCOUNT MONITOR</div><h1>Gesamter Account <span>Live</span></h1><p>Alle Offers · alle Affiliates · Smartlinks und Direkt-Traffic</p></div><div className="topActions"><Link className="logout" href="/automation">Auto-Rotation</Link><Link className="logout" href="/smartlinks">Smartlink Intelligence</Link><div className="live"><span/>Read only</div><form action="/api/auth/logout" method="post"><button className="logout">Abmelden</button></form></div></header>
 <nav className="periods" aria-label="Zeitraum">{([['today','Heute'],['7d','7 Tage'],['30d','30 Tage']] as const).map(([value,label])=><Link key={value} className={period===value?'active':''} href={`/?period=${value}&view=${view}`}>{label}</Link>)}<span className="range">{data.range.label} · Berlin</span></nav>
 <section className="kpis"><article className="kpi hero"><span>Account-Profit</span><strong className={data.totals.profit>=0?'up':'down'}>{euro(data.totals.profit)}</strong><small>Profit-EPC {euro(data.totals.profitEpc)}</small></article><article className="kpi"><span>Umsatz</span><strong>{euro(data.totals.revenue)}</strong><small>{euro(data.totals.payout)} Payout</small></article><article className="kpi"><span>Traffic</span><strong>{num(data.totals.clicks)}</strong><small>Klicks</small></article><article className="kpi"><span>SOIs</span><strong>{num(data.totals.sois)}</strong><small>CVR {pct(data.totals.cvr)}</small></article><article className="kpi"><span>Monetarisierung</span><strong>{data.totals.firstSales} / {data.totals.rebills}</strong><small>First-Sales / Rebills</small></article></section>
 <section className="portfolioScope"><div><b>{data.offers.length}</b><span>Offers</span></div><div><b>{data.affiliates.length}</b><span>Affiliates</span></div><div><b>{data.paths.length}</b><span>Traffic-Pfade / LPs</span></div><div><b>{data.paths.filter(x=>x.trafficType==='Smartlink').length}</b><span>Smartlink-Pfade</span></div><div><b>{data.paths.filter(x=>x.trafficType==='Direkt').length}</b><span>Direkte Pfade</span></div></section>
 <div className="viewTabs">{([['offers','Offers'],['affiliates','Affiliates'],['paths','Landingpages & Pfade']] as const).map(([value,label])=><Link key={value} className={view===value?'active':''} href={`/?period=${period}&view=${value}`}>{label}</Link>)}</div>
 <section className="sectionHead"><div><span>Accountweite Auswertung</span><h2>{view==='offers'?'Alle Offers':view==='affiliates'?'Alle Affiliates':'Alle Landingpages und Traffic-Pfade'}</h2></div><div className="scope">{activeRows.length} aktive Zeilen · nach Profit sortiert</div></section>
 <div className="tableWrap"><table className="performanceTable"><thead><tr><th>#</th><th>{view==='offers'?'Offer':view==='affiliates'?'Affiliate':'Landingpage / Pfad'}</th><th>Klicks</th><th>SOIs / CVR</th><th>First-Sales / Rate</th><th>Rebills</th><th>Umsatz</th><th>Payout</th><th>Profit</th><th>Profit-EPC</th></tr></thead><tbody>{activeRows.map((row,index)=>{const isPath='key'in row;const path=row as PathRow;const entity=row as EntityRow;const name=isPath?path.offerUrl:entity.name;const id=isPath?path.offerUrlId:entity.id;return <tr key={isPath?path.key:`${view}-${entity.id}`}><td data-label="#">{index+1}</td><td data-label="Einheit"><b>{name}</b><small>#{id}{isPath?` · ${path.offer} · ${path.affiliate} · ${path.trafficType}${path.campaignId!=='0'?` #${path.campaignId}`:''}`:` · ${entity.pathCount} Pfade`}</small></td><td data-label="Klicks">{num(row.clicks)}</td><td data-label="SOIs / CVR"><b>{num(row.sois)}</b><small>{pct(row.cvr)}</small></td><td data-label="First-Sales / Rate"><b>{row.firstSales}</b><small>{pct(row.firstSaleRate)}</small></td><td data-label="Rebills">{row.rebills}</td><td data-label="Umsatz">{euro(row.revenue)}</td><td data-label="Payout">{euro(row.payout)}</td><td data-label="Profit"><b className={row.profit>=0?'up':'down'}>{euro(row.profit)}</b></td><td data-label="Profit-EPC">{euro(row.profitEpc)}</td></tr>})}</tbody></table></div>
 <footer><div><b>Vollständiger Account-Scope</b><span>Gebuchte Payouts inklusive Custom Payouts · First-Sales ausschließlich Event „Sale“.</span></div><div>Vercel Data Cache: 60 Sekunden · {new Date(data.generatedAt).toLocaleTimeString('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit'})}</div></footer></main>
}
