import {beforeEach,describe,expect,it,vi} from 'vitest';
import {parseAccessMetadata} from '@/lib/rbac';
const requirePermission=vi.fn(),listAutomationConfigurations=vi.fn();
vi.mock('@/lib/session',()=>({requirePermission,resolveCurrentUserUncached:vi.fn()}));
vi.mock('@/lib/access-store',()=>({securityStore:()=>({}),audit:vi.fn(),requestEvidence:()=>({})}));
vi.mock('@/lib/automation-store',()=>({listAutomationConfigurations,createAutomationConfiguration:vi.fn(),getAutomationConfiguration:vi.fn(),transitionAutomation:vi.fn(),updateAutomationConfiguration:vi.fn()}));
vi.mock('@/data/automation-journal',()=>({default:{generatedAt:'2026-07-30T00:00:00Z',campaigns:[{campaignId:'c-1',revenue:100,decision:'keep'}]}}));
const user=(role:'employee'|'partner',grants:string[]=[])=>({id:'u-1',email:'user@example.test',actorId:'u-1',impersonating:false,access:parseAccessMetadata({role,status:'active',grants,version:1})});
describe('GET /api/automation',()=>{beforeEach(()=>{requirePermission.mockReset();listAutomationConfigurations.mockReset().mockResolvedValue([])});it('preserves the authentication boundary status from campaigns.edit',async()=>{requirePermission.mockResolvedValue({ok:false,status:401,user:null});const{GET}=await import('./route');const response=await GET();expect(response.status).toBe(401);expect(await response.json()).toEqual({error:'Unauthorized'})});it('returns 403 when finance.view is missing instead of returning redacted automation data',async()=>{requirePermission.mockResolvedValue({ok:true,status:200,user:user('employee',['campaigns.edit'])});const{GET}=await import('./route');const response=await GET();expect(response.status).toBe(403);expect(await response.json()).toEqual({error:'Forbidden'})});it('explicitly denies partners even when both permissions are granted',async()=>{requirePermission.mockResolvedValue({ok:true,status:200,user:user('partner',['campaigns.edit','finance.view'])});const{GET}=await import('./route');expect((await GET()).status).toBe(403)});it('returns the source journal and an empty control-plane view to a legacy non-partner',async()=>{requirePermission.mockResolvedValue({ok:true,status:200,user:user('employee',['campaigns.edit','finance.view'])});const{GET}=await import('./route');const response=await GET();expect(response.status).toBe(200);expect(await response.json()).toEqual({generatedAt:'2026-07-30T00:00:00Z',campaigns:[{campaignId:'c-1',revenue:100,decision:'keep'}],configurations:[],canRunLive:false});expect(listAutomationConfigurations).not.toHaveBeenCalled()})});
