import {NextResponse} from 'next/server';
import {revalidateTag} from 'next/cache';
import {audit,requestEvidence,securityStore} from '@/lib/access-store';
import {activateEverflowSourceBlock,deactivateEverflowSourceBlock} from '@/lib/everflow-source-blocks';
import {activateSourceBlock,activateSourceBlocksAtomically,deactivateSourceBlock,listSourceBlocks,SourceBlockStateUncertainError} from '@/lib/source-block-service';
import {normalizeSourceBlockInput,sourceBlockIdentityKey,sourceBlockOfferSummariesFromSnapshotRows,sourceBlockOffersFromSnapshotRows,sourceBlockRequiredConfirmation,sourceBlockStoreKey,sourceBlockVisibleInSnapshotRows,type SourceBlockInput,type SourceBlockRecord} from '@/lib/source-blocks';
import {isSourceBlockReasonCategory,listSourceBlockHistory,recordSourceBlockHistory,SOURCE_BLOCK_REASON_CATEGORIES,type SourceBlockReasonCategory} from '@/lib/source-block-history';
import {BLOCK_EFFECTS_CACHE_TAG,loadBlockEffects,loadBlockIndex} from '@/lib/block-effects';
import {getAffiliateSourceScopeRows} from '@/lib/affiliate-optimizer-service';
import {resolveSourcePeriod} from '@/lib/source-period';
import {requirePermission,resolveCurrentUserUncached} from '@/lib/session';
import {can} from '@/lib/rbac';
import {canonicalOrigin,checkCsrf,parseBoundedJson,securityHeaders} from '@/lib/security';
export const dynamic='force-dynamic';
/** Phase B schaltet die Pflicht scharf: bis dahin gilt ein fehlendes Feld als 'sonstiges', ein ungültiges wird immer abgelehnt. */
const REASON_CATEGORY_REQUIRED=false;
const REASON_CATEGORY_ERROR=`Grundkategorie fehlt oder ist ungültig (erlaubt: ${SOURCE_BLOCK_REASON_CATEGORIES.join(', ')})`;
const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{...securityHeaders,'Cache-Control':'private, no-store'}});
const mayManage=(access:Parameters<typeof can>[0])=>access.role!=='partner'&&can(access,'landingpages.manage')&&can(access,'api.manage');
const isDay=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value);
const expireBlockCaches=()=>{try{revalidateTag(BLOCK_EFFECTS_CACHE_TAG,{expire:0})}catch(error){console.error('Source block cache could not be expired',error)}};
class SourceBlockAuthorizationError extends Error{}
class SourceBlockRequestError extends Error{}
function resolveReasonInput(input:Record<string,unknown>,required:boolean):{reasonCategory?:SourceBlockReasonCategory;reason?:string}{
 const raw=input.reasonCategory,missing=raw===undefined||raw===null||raw==='';
 if(!missing&&!isSourceBlockReasonCategory(raw))throw new SourceBlockRequestError(REASON_CATEGORY_ERROR);
 if(missing&&required&&REASON_CATEGORY_REQUIRED)throw new SourceBlockRequestError(REASON_CATEGORY_ERROR);
 if(input.reason!==undefined&&input.reason!==null&&typeof input.reason!=='string')throw new SourceBlockRequestError('Begründung ist ungültig');
 const reason=typeof input.reason==='string'?input.reason.trim():'';
 if(reason.length>500)throw new SourceBlockRequestError('Begründung ist zu lang (max. 500 Zeichen)');
 return{reasonCategory:missing?(required?'sonstiges':undefined):raw as SourceBlockReasonCategory,...(reason?{reason}:{})};
}
async function sourceScopeRows(block:ReturnType<typeof normalizeSourceBlockInput>,access:Parameters<typeof can>[0]){const period=resolveSourcePeriod({sourcePeriod:'12m'});return getAffiliateSourceScopeRows(String(block.affiliateId),{from:period.from,to:period.to},access)}
async function assertVisibleSource(input:SourceBlockInput,access:Parameters<typeof can>[0]){const block=normalizeSourceBlockInput(input),rows=await sourceScopeRows(block,access);if(!sourceBlockVisibleInSnapshotRows(rows,block))throw new Error('Die Campaign-/Affiliate-/Offer-/Quellenkombination ist serverseitig nicht vorhanden. Keine Änderung durchgeführt.');}
const NO_OFFER_ERROR='Diese Quelle wurde serverseitig in keinem Offer gefunden. Keine Änderung durchgeführt.';
async function resolveProductWideInputs(input:SourceBlockInput,access:Parameters<typeof can>[0]){const block=normalizeSourceBlockInput(input),rows=await sourceScopeRows(block,access),offers=sourceBlockOffersFromSnapshotRows(rows,block);if(!offers.length)throw new Error(NO_OFFER_ERROR);return offers.map(({offerId,offerName})=>({...input,offerId,offerName,campaignId:undefined}));}
/** Vorschau: dieselbe Offer-Ermittlung wie resolveProductWideInputs, zusätzlich Reporting-Summen je Offer aus denselben Snapshot-Zeilen. */
async function resolveProductWideOffers(input:SourceBlockInput,access:Parameters<typeof can>[0]){const block=normalizeSourceBlockInput(input),rows=await sourceScopeRows(block,access),offers=sourceBlockOfferSummariesFromSnapshotRows(rows,block);if(!offers.length)throw new Error(NO_OFFER_ERROR);return{block,offers}}
/** Ordnet einen fehlgeschlagenen Versuch dem bestehenden Record zu (Incident-Record des Service), sonst der Identität. */
async function resolveFailedBlock(input:Record<string,unknown>,fallback:string,store:ReturnType<typeof securityStore>){
 try{
  if(input.action==='deactivate'){const id=String(input.id||'').slice(0,100),match=(await listSourceBlocks(store)).find(record=>record.id===id);return{blockId:id||fallback,identityKey:match?sourceBlockIdentityKey(match):fallback}}
  const block=normalizeSourceBlockInput(input as unknown as SourceBlockInput),identityKey=sourceBlockIdentityKey(block),existing=await store.get(sourceBlockStoreKey(block)) as Partial<SourceBlockRecord>|null;
  return{blockId:typeof existing?.id==='string'?existing.id:identityKey,identityKey};
 }catch{return{blockId:fallback,identityKey:fallback}}
}
export async function GET(request:Request){const auth=await requirePermission('api.manage');if(!auth.ok)return json({error:auth.status===401?'Nicht angemeldet':'Keine Berechtigung'},auth.status);if(!mayManage(auth.user.access))return json({error:'Keine Berechtigung'},403);try{const url=new URL(request.url),action=url.searchParams.get('action'),store=securityStore();
 if(action==='preview_across_offers'){const input=Object.fromEntries(url.searchParams) as unknown as SourceBlockInput,{block,offers}=await resolveProductWideOffers(input,auth.user.access),index=await loadBlockIndex(store);return json({offers:offers.map(offer=>({...offer,blocked:index.get(sourceBlockIdentityKey({...block,offerId:Number(offer.offerId)}))?.status==='active'})),requiredConfirmation:sourceBlockRequiredConfirmation(block)});}
 if(action==='history'){const id=String(url.searchParams.get('id')||'').trim().slice(0,100);if(!id)return json({error:'Sperr-ID fehlt'},400);return json({events:await listSourceBlockHistory(id,store)})}
 if(url.searchParams.get('effects')==='1'){const from=String(url.searchParams.get('from')||''),to=String(url.searchParams.get('to')||''),affiliateId=String(url.searchParams.get('affiliateId')||'').trim();if(!isDay(from)||!isDay(to)||from>to)return json({error:'Zeitraum fehlt oder ist ungültig (from/to als JJJJ-MM-TT)'},400);if(affiliateId&&!/^\d+$/.test(affiliateId))return json({error:'Affiliate-ID ist ungültig'},400);const[blocks,effects]=await Promise.all([listSourceBlocks(store),loadBlockEffects({from,to},affiliateId||undefined)]);return json({blocks,effects})}
 return json({blocks:await listSourceBlocks(store)})}catch(error){return json({error:error instanceof Error?error.message:'Quellen-Sperren konnten nicht geladen werden'},400)}}
export async function POST(request:Request){const auth=await requirePermission('api.manage');if(!auth.ok)return json({error:auth.status===401?'Nicht angemeldet':'Keine Berechtigung'},auth.status);if(!mayManage(auth.user.access))return json({error:'Keine Berechtigung'},403);let origin:string;try{origin=canonicalOrigin(process.env.APP_ORIGIN,process.env.NODE_ENV,request.url)}catch{return json({error:'Serverkonfiguration ungültig'},500)}if(!checkCsrf(request,origin))return json({error:'Anfrage abgelehnt'},403);let input:Record<string,unknown>;try{input=await parseBoundedJson(request)}catch{return json({error:'Ungültige Anfrage'},400)}const apiKey=process.env.EVERFLOW_API_KEY||'',store=securityStore(),evidence=requestEvidence(request),actorId=auth.user.actorId,writer={actorId,activate:(block:Parameters<typeof activateEverflowSourceBlock>[0],id:string)=>activateEverflowSourceBlock(block,id,apiKey),deactivate:(id:number,block:Parameters<typeof deactivateEverflowSourceBlock>[1])=>deactivateEverflowSourceBlock(id,block,apiKey)},authorizeWriter=(scopeCheck:(access:Parameters<typeof can>[0],record?:Awaited<ReturnType<typeof listSourceBlocks>>[number])=>Promise<void>)=>({...writer,authorize:async (record?:Awaited<ReturnType<typeof listSourceBlocks>>[number])=>{const fresh=await resolveCurrentUserUncached();if(!fresh||fresh.id!==auth.user.id||fresh.actorId!==auth.user.actorId||!mayManage(fresh.access))throw new SourceBlockAuthorizationError('Keine Berechtigung');try{await scopeCheck(fresh.access,record)}catch{throw new SourceBlockAuthorizationError('Keine Berechtigung')}}});
 let reasonInput:ReturnType<typeof resolveReasonInput>={};
 try{
  if(input.action==='activate'||input.action==='activate_across_offers'||input.action==='deactivate'){try{reasonInput=resolveReasonInput(input,input.action!=='deactivate')}catch(error){if(error instanceof SourceBlockRequestError)return json({error:error.message},400);throw error}}
  const{reasonCategory,reason}=reasonInput,history=(action:'activate'|'activate_across_offers'|'deactivate',after:SourceBlockRecord,before?:SourceBlockRecord|null)=>before===after?Promise.resolve():recordSourceBlockHistory({blockId:after.id,identityKey:sourceBlockIdentityKey(after),actorId,action,reasonCategory,reason,before:before??null,after},store);
  if(input.action==='activate'){const requested={...input,reasonCategory,reason} as unknown as SourceBlockInput;await assertVisibleSource(requested,auth.user.access);const record=await activateSourceBlock(store,requested,authorizeWriter(access=>assertVisibleSource(requested,access)),async (after,before)=>audit({actorId:auth.user.actorId,action:'source_block.activate',targetId:after.id,before,after,...evidence}).then(()=>history('activate',after,before)));expireBlockCaches();return json({ok:true,block:record},201)}
  if(input.action==='activate_across_offers'){const requested={...input,reasonCategory,reason} as unknown as SourceBlockInput,block=normalizeSourceBlockInput(requested),required=sourceBlockRequiredConfirmation(block);if(String(input.confirmation??'')!==required)return json({error:'Quellenwert wurde nicht exakt bestätigt'},400);const items=await resolveProductWideInputs(requested,auth.user.access),records=await activateSourceBlocksAtomically(store,items,authorizeWriter(async access=>{const freshItems=await resolveProductWideInputs(requested,access),expected=items.map(item=>String(item.offerId)).join(','),actual=freshItems.map(item=>String(item.offerId)).join(',');if(actual!==expected)throw new SourceBlockAuthorizationError('Keine Berechtigung')}),async (after,before)=>audit({actorId:auth.user.actorId,action:'source_block.activate_across_offers',targetId:`${block.affiliateId}:${required}`,before:{blocks:before},after:{offers:after.map(record=>record.offerId),blocks:after},...evidence}).then(async()=>{for(const[index,record]of after.entries())await history('activate_across_offers',record,before?.[index]??null)}));expireBlockCaches();return json({ok:true,blocks:records},201)}
  if(input.action==='deactivate'){const id=String(input.id||'').slice(0,100);if(!id)return json({error:'Sperr-ID fehlt'},400);const record=await deactivateSourceBlock(store,id,authorizeWriter((access,fresh)=>fresh?assertVisibleSource({...fresh,affiliateId:String(fresh.affiliateId),offerId:String(fresh.offerId)},access):Promise.reject(new SourceBlockAuthorizationError('Keine Berechtigung'))),async (after,before)=>audit({actorId:auth.user.actorId,action:'source_block.deactivate',targetId:after.id,before,after,...evidence}).then(()=>history('deactivate',after,before)));expireBlockCaches();return json({ok:true,block:record})}
  return json({error:'Unbekannte Aktion'},400)
 }catch(error){console.error('Source block mutation failed',error);const message=error instanceof Error?error.message:'Quellen-Sperre fehlgeschlagen',failedTargetId=input.action==='deactivate'?String(input.id||'').slice(0,100):[input.affiliateId,input.offerId,input.trafficMode,input.level,input.mainValue||'',input.subValue||''].map(value=>String(value??'').slice(0,100)).join(':');await audit({actorId:auth.user.actorId,action:input.action==='deactivate'?'source_block.deactivate_failed':'source_block.activate_failed',targetId:failedTargetId,after:{error:message},...evidence}).catch(()=>{});const failed=await resolveFailedBlock(input,failedTargetId,store);await recordSourceBlockHistory({...failed,actorId,action:input.action==='deactivate'?'deactivate_failed':'activate_failed',reasonCategory:reasonInput.reasonCategory,reason:reasonInput.reason,error:message},store);expireBlockCaches();const status=error instanceof SourceBlockAuthorizationError?403:error instanceof SourceBlockStateUncertainError?503:error instanceof Error&&/widersprüchliche|zwischenzeitlich/.test(error.message)?409:502;return json({error:error instanceof Error?error.message:'Quellen-Sperre fehlgeschlagen'},status)}}
