import{NextResponse}from'next/server';
import{audit,requestEvidence,securityStore}from'@/lib/access-store';
import{activateEverflowSourceBlock,deactivateEverflowSourceBlock}from'@/lib/everflow-source-blocks';
import{activateSourceBlock,deactivateSourceBlock,listSourceBlocks}from'@/lib/source-block-service';
import{normalizeSourceBlockInput,type SourceBlockInput}from'@/lib/source-blocks';
import{getAffiliateSourceBreakdown}from'@/lib/affiliate-optimizer-service';
import{resolveSourcePeriod}from'@/lib/source-period';
import{requirePermission}from'@/lib/session';
import{can}from'@/lib/rbac';
import{canonicalOrigin,checkCsrf,parseBoundedJson,securityHeaders}from'@/lib/security';
export const dynamic='force-dynamic';
const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{...securityHeaders,'Cache-Control':'private, no-store'}});
const mayManage=(access:Parameters<typeof can>[0])=>access.role!=='partner'&&can(access,'landingpages.manage')&&can(access,'api.manage');
async function assertVisibleSource(input:SourceBlockInput,access:Parameters<typeof can>[0]){const block=normalizeSourceBlockInput(input),period=resolveSourcePeriod({sourcePeriod:'12m'}),rows=await getAffiliateSourceBreakdown(String(block.affiliateId),{from:period.from,to:period.to},access),match=rows.some(row=>row.affiliateId===String(block.affiliateId)&&row.offerId===String(block.offerId)&&row.trafficMode===block.trafficMode&&row.mainValue===block.mainValue&&(block.level==='main_source'||row.subValue===block.subValue));if(!match)throw new Error('Die gewählte Affiliate-/Offer-/Quellenkombination ist serverseitig nicht vorhanden. Keine Änderung durchgeführt.');}
export async function GET(){const auth=await requirePermission('api.manage');if(!auth.ok)return json({error:auth.status===401?'Nicht angemeldet':'Keine Berechtigung'},auth.status);if(!mayManage(auth.user.access))return json({error:'Keine Berechtigung'},403);try{return json({blocks:await listSourceBlocks(securityStore())})}catch{return json({error:'Quellen-Sperren konnten nicht geladen werden'},500)}}
export async function POST(request:Request){const auth=await requirePermission('api.manage');if(!auth.ok)return json({error:auth.status===401?'Nicht angemeldet':'Keine Berechtigung'},auth.status);if(!mayManage(auth.user.access))return json({error:'Keine Berechtigung'},403);let origin:string;try{origin=canonicalOrigin(process.env.APP_ORIGIN,process.env.NODE_ENV,request.url)}catch{return json({error:'Serverkonfiguration ungültig'},500)}if(!checkCsrf(request,origin))return json({error:'Anfrage abgelehnt'},403);let input:Record<string,unknown>;try{input=await parseBoundedJson(request)}catch{return json({error:'Ungültige Anfrage'},400)}const apiKey=process.env.EVERFLOW_API_KEY||'',store=securityStore(),writer={actorId:auth.user.actorId,activate:(block:Parameters<typeof activateEverflowSourceBlock>[0],id:string)=>activateEverflowSourceBlock(block,id,apiKey),deactivate:(id:number)=>deactivateEverflowSourceBlock(id,apiKey)};try{if(input.action==='activate'){await assertVisibleSource(input as unknown as SourceBlockInput,auth.user.access);const before=await listSourceBlocks(store),record=await activateSourceBlock(store,input as unknown as SourceBlockInput,writer);await audit({actorId:auth.user.actorId,action:'source_block.activate',targetId:record.id,before:before.find(item=>item.id===record.id),after:record,...requestEvidence(request)});return json({ok:true,block:record},201)}if(input.action==='deactivate'){const id=String(input.id||'').slice(0,100);if(!id)return json({error:'Sperr-ID fehlt'},400);const before=(await listSourceBlocks(store)).find(item=>item.id===id),record=await deactivateSourceBlock(store,id,writer);await audit({actorId:auth.user.actorId,action:'source_block.deactivate',targetId:record.id,before,after:record,...requestEvidence(request)});return json({ok:true,block:record})}return json({error:'Unbekannte Aktion'},400)}catch(error){console.error('Source block mutation failed',error);return json({error:error instanceof Error?error.message:'Quellen-Sperre fehlgeschlagen'},error instanceof Error&&/widersprüchliche|zwischenzeitlich/.test(error.message)?409:502)}}
