// Generated by scripts/sync-automation-journal.mjs
const journal={
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T07:46:24.053723+00:00",
  "scope": "server-side tracked live Smartlinks",
  "campaigns": [
    {
      "campaignId": 2,
      "name": "Trafficpartner - POP - ALL",
      "affiliateId": 6,
      "affiliate": "TrafficPartner",
      "mode": "live",
      "schedule": "alle 120 Minuten",
      "enabled": true,
      "lastRunAt": "2026-08-02T07:46:24.053723+00:00",
      "nextRunAt": "2026-08-02T09:46:24.053723+00:00",
      "lastStatus": "ok",
      "policy": "50/25/25 Champion/Challenger · Profit-first · ca. 1 % Smartlink-CVR schützen",
      "currentRotation": [
        {
          "id": 2749,
          "weight": 25
        },
        {
          "id": 2756,
          "weight": 25
        },
        {
          "id": 2762,
          "weight": 50
        }
      ],
      "latest": {
        "campaignId": 2,
        "evaluatedAt": "2026-08-02T07:46:23.542Z",
        "action": "none",
        "writes": 0,
        "verified": true,
        "summary": "cvr_protection_no_safe_action · state_verified",
        "metrics": {
          "blendCvr": 0.009389248860091192,
          "cvrFloor": 0.01,
          "regime": "protection"
        }
      }
    },
    {
      "campaignId": 146,
      "name": "Global - TrafficCompany",
      "affiliateId": 436,
      "affiliate": "Traffic Company",
      "mode": "live",
      "schedule": "alle 120 Minuten",
      "enabled": false,
      "lastRunAt": "2026-07-30T17:17:37.538476+00:00",
      "nextRunAt": "2026-07-30T19:17:37.538476+00:00",
      "lastStatus": "ok",
      "policy": "Sale-first · 3 Slots gleich · 50 SOIs Testquote · robuste Sales vor Scale",
      "currentRotation": [
        {
          "id": 2749,
          "name": "Single69_Everflow_Verlangen fsk18",
          "startedAt": "2026-07-28T14:19:57.540Z",
          "weight": 33.3
        },
        {
          "id": 2758,
          "name": "Single69_Everflow_LUV2 mainstream",
          "startedAt": "2026-07-30T07:12:25.004Z",
          "weight": 33.3
        },
        {
          "id": 2769,
          "name": "Single69_Everflow_SeniorSexDates fsk18",
          "startedAt": "2026-07-30T07:12:25.989Z",
          "weight": 33.3
        }
      ],
      "latest": {
        "campaignId": 146,
        "evaluatedAt": "2026-07-30T17:17:37.000Z",
        "action": "review",
        "writes": 0,
        "verified": true,
        "summary": "**Live-Lauf Affiliate 436 · Campaign 146 · Offer 57**\n\n- **Ergebnis:** `action: \"none\"`\n- **Writes:** `0`\n- **Status:** Erfolgreicher Hold/No-op, keine Rotation und kein Everflow-PUT.\n- **Gewichte:** alle drei LPs gleich gewichtet (`1 / 1 / 1`)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 25 | 1 | 1 | 50,96 h | 50 SOIs; noch **25 SOIs**. Schutz erst ab mindestens 3 unabhängigen First-Sales. |\n| **2758** | Single69_Everflow_LUV2 mainstream | 2 | 0 | 0 | 10,08 h | Früh-Gate bei 30 SOIs und ≥24 h; noch **28 SOIs** und rund **13,92 h** Mindestalter. |\n| **2769** | Single69_Everflow_SeniorSexDates fsk18 | 5 | 0 | 0 | 10,08 h | Früh-Gate bei 30 SOIs und ≥24 h; noch **25 SOIs** und rund **13,92 h** Mindestalter. |\n\nFirst-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat ausgewiesen. Es gab keinen ausgehenden/eingehenden LP-Wechsel, daher auch keinen Backup-, PUT→GET- oder Tracking-HTTP-Nachweis."
      }
    }
  ],
  "rotations": [
    {
      "campaignId": 146,
      "time": "2026-07-30T07:12:25.989Z",
      "type": "slot_replacement",
      "from": {
        "id": 2765,
        "name": "LP 2765"
      },
      "to": {
        "id": 2769,
        "name": "Single69_Everflow_SeniorSexDates fsk18"
      },
      "after": [
        {
          "id": 2749,
          "weight": 1
        },
        {
          "id": 2758,
          "weight": 1
        },
        {
          "id": 2769,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-30T07:12:25.004Z",
      "type": "slot_replacement",
      "from": {
        "id": 2759,
        "name": "LP 2759"
      },
      "to": {
        "id": 2758,
        "name": "Single69_Everflow_LUV2 mainstream"
      },
      "after": [
        {
          "id": 2749,
          "weight": 1
        },
        {
          "id": 2758,
          "weight": 1
        },
        {
          "id": 2765,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-28T20:23:58.464Z",
      "type": "slot_replacement",
      "from": {
        "id": 2748,
        "name": "LP 2748"
      },
      "to": {
        "id": 2765,
        "name": "Single69_Everflow_DirektFlirten fsk18"
      },
      "after": [
        {
          "id": 2749,
          "weight": 1
        },
        {
          "id": 2759,
          "weight": 1
        },
        {
          "id": 2765,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-28T14:19:57.540Z",
      "type": "slot_replacement",
      "from": {
        "id": 2789,
        "name": "LP 2789"
      },
      "to": {
        "id": 2749,
        "name": "Single69_Everflow_Verlangen fsk18"
      },
      "after": [
        {
          "id": 2748,
          "weight": 1
        },
        {
          "id": 2749,
          "weight": 1
        },
        {
          "id": 2759,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-27T18:09:44.702Z",
      "type": "slot_replacement",
      "from": {
        "id": 2746,
        "name": "LP 2746"
      },
      "to": {
        "id": 2759,
        "name": "Single69_Everflow_DatingSex fsk18"
      },
      "after": [
        {
          "id": 2748,
          "weight": 1
        },
        {
          "id": 2759,
          "weight": 1
        },
        {
          "id": 2789,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-27T08:04:40.194Z",
      "type": "slot_replacement",
      "from": {
        "id": 2816,
        "name": "LP 2816"
      },
      "to": {
        "id": 2748,
        "name": "Single69_Everflow_Onlyxnude fsk18"
      },
      "after": [
        {
          "id": 2746,
          "weight": 1
        },
        {
          "id": 2748,
          "weight": 1
        },
        {
          "id": 2789,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-27T08:04:39.182Z",
      "type": "slot_replacement",
      "from": {
        "id": 2756,
        "name": "LP 2756"
      },
      "to": {
        "id": 2789,
        "name": "Single69_Everflow mainstream"
      },
      "after": [
        {
          "id": 2746,
          "weight": 1
        },
        {
          "id": 2789,
          "weight": 1
        },
        {
          "id": 2816,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-26T07:51:04.351Z",
      "type": "slot_replacement",
      "from": {
        "id": 2768,
        "name": "LP 2768"
      },
      "to": {
        "id": 2816,
        "name": "Single69_Everflow_TikPorn fsk18"
      },
      "after": [
        {
          "id": 2746,
          "weight": 1
        },
        {
          "id": 2756,
          "weight": 1
        },
        {
          "id": 2816,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-26T07:51:02.201Z",
      "type": "slot_replacement",
      "from": {
        "id": 2774,
        "name": "LP 2774"
      },
      "to": {
        "id": 2746,
        "name": "Single69_Everflow_zusammende mainstream"
      },
      "after": [
        {
          "id": 2746,
          "weight": 1
        },
        {
          "id": 2756,
          "weight": 1
        },
        {
          "id": 2768,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-26T07:51:01.746Z",
      "type": "slot_replacement",
      "from": {
        "id": 2751,
        "name": "LP 2751"
      },
      "to": {
        "id": 2756,
        "name": "Sibgle69_Everflow_LUV mainstream"
      },
      "after": [
        {
          "id": 2756,
          "weight": 1
        },
        {
          "id": 2768,
          "weight": 1
        },
        {
          "id": 2774,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 2,
      "time": "2026-07-24T10:19:37.848Z",
      "type": "champion_and_slot_update",
      "before": [
        {
          "id": 2750,
          "name": "Single69_Everflow_Tabuu fsk18",
          "weight": 50
        },
        {
          "id": 2816,
          "name": "Single69_Everflow_TikPorn fsk18",
          "weight": 25
        },
        {
          "id": 2762,
          "name": "Single69_Everflow_MilfsFicken fsk18",
          "weight": 25
        }
      ],
      "after": [
        {
          "id": 2749,
          "weight": 25
        },
        {
          "id": 2756,
          "weight": 25
        },
        {
          "id": 2762,
          "weight": 50
        }
      ],
      "verified": true,
      "source": "writer-backup + accepted Everflow state"
    },
    {
      "campaignId": 146,
      "time": "2026-07-24T08:28:48.197Z",
      "type": "slot_replacement",
      "from": {
        "id": 2762,
        "name": "LP 2762"
      },
      "to": {
        "id": 2751,
        "name": "Single69_Everflow_Heutenochdate fsk18"
      },
      "after": [
        {
          "id": 2751,
          "weight": 1
        },
        {
          "id": 2768,
          "weight": 1
        },
        {
          "id": 2774,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-24T02:18:11.149Z",
      "type": "slot_replacement",
      "from": {
        "id": 2747,
        "name": "LP 2747"
      },
      "to": {
        "id": 2768,
        "name": "Single69_Everflow_NachbarsMatch mainstream"
      },
      "after": [
        {
          "id": 2762,
          "weight": 1
        },
        {
          "id": 2768,
          "weight": 1
        },
        {
          "id": 2774,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-23T12:10:20.006Z",
      "type": "slot_replacement",
      "from": {
        "id": 2753,
        "name": "LP 2753"
      },
      "to": {
        "id": 2774,
        "name": "Single69_Everflow_SecretCasual fsk18"
      },
      "after": [
        {
          "id": 2747,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        },
        {
          "id": 2774,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-21T11:27:57.284Z",
      "type": "slot_replacement",
      "from": {
        "id": 2780,
        "name": "Single69_Everflow_TelefonSex fsk18"
      },
      "to": {
        "id": 2747,
        "name": "Single69_Everflow_Striptie fsk18"
      },
      "after": [
        {
          "id": 2747,
          "weight": 1
        },
        {
          "id": 2753,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-21T11:27:56.829Z",
      "type": "slot_replacement",
      "from": {
        "id": 2754,
        "name": "Single69_Everflow_Fraueninmeinernaehe mainstream"
      },
      "to": {
        "id": 2753,
        "name": "Single69_Everflow_Datelifede fsk18"
      },
      "after": [
        {
          "id": 2753,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        },
        {
          "id": 2780,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-21T11:27:56.369Z",
      "type": "slot_replacement",
      "from": {
        "id": 2750,
        "name": "Single69_Everflow_Tabuu fsk18"
      },
      "to": {
        "id": 2762,
        "name": "Single69_Everflow_MilfsFicken fsk18"
      },
      "after": [
        {
          "id": 2754,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        },
        {
          "id": 2780,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    }
  ],
  "evaluations": [
    {
      "campaignId": 2,
      "evaluatedAt": "2026-08-02T07:46:23.542Z",
      "action": "none",
      "writes": 0,
      "verified": true,
      "summary": "cvr_protection_no_safe_action · state_verified",
      "metrics": {
        "blendCvr": 0.009389248860091192,
        "cvrFloor": 0.01,
        "regime": "protection"
      }
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T17:17:37.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf Affiliate 436 · Campaign 146 · Offer 57**\n\n- **Ergebnis:** `action: \"none\"`\n- **Writes:** `0`\n- **Status:** Erfolgreicher Hold/No-op, keine Rotation und kein Everflow-PUT.\n- **Gewichte:** alle drei LPs gleich gewichtet (`1 / 1 / 1`)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 25 | 1 | 1 | 50,96 h | 50 SOIs; noch **25 SOIs**. Schutz erst ab mindestens 3 unabhängigen First-Sales. |\n| **2758** | Single69_Everflow_LUV2 mainstream | 2 | 0 | 0 | 10,08 h | Früh-Gate bei 30 SOIs und ≥24 h; noch **28 SOIs** und rund **13,92 h** Mindestalter. |\n| **2769** | Single69_Everflow_SeniorSexDates fsk18 | 5 | 0 | 0 | 10,08 h | Früh-Gate bei 30 SOIs und ≥24 h; noch **25 SOIs** und rund **13,92 h** Mindestalter. |\n\nFirst-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat ausgewiesen. Es gab keinen ausgehenden/eingehenden LP-Wechsel, daher auch keinen Backup-, PUT→GET- oder Tracking-HTTP-Nachweis."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T15:16:49.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · **0 Writes** · Exitcode 0  \nDie Rotation bleibt unverändert bei gleichen Gewichten **1:1:1**.\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 25 | 1 | 1 | 48,94 h | Noch **25 SOIs bis 50**; Schutz nur bei mindestens 3 unabhängigen First-Sales |\n| **2758** | Single69_Everflow_LUV2 mainstream | 1 | 0 | 0 | 8,07 h | Früh-Gate bei **30 SOIs und ≥24 h**: noch 29 SOIs und ca. 15,93 h |\n| **2769** | Single69_Everflow_SeniorSexDates fsk18 | 5 | 0 | 0 | 8,07 h | Früh-Gate bei **30 SOIs und ≥24 h**: noch 25 SOIs und ca. 15,93 h |\n\nAlle drei LPs haben derzeit **0 reife SOIs** im 336-Stunden-Fenster. Da kein Write erfolgte, gab es keinen Backup-, PUT→GET- oder Tracking-HTTP-Schritt."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T13:15:44.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow Sale-first-Lauf – Affiliate 436 / Campaign 146 / Offer 57**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0` – kein Everflow-PUT, daher kein Backup-/GET-/Tracking-Test erforderlich\n- **Gewichtung:** alle drei LPs gleich gewichtet (`1/1/1`, je ca. 33,3 %)\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 24 | 1 | 1 | 46,93 h | Weiter bis 50 SOIs; noch **26 SOIs**. Dann Rotation, sofern weniger als 3 unabhängige First-Sales |\n| **2758** | Single69_Everflow_LUV2 mainstream | 1 | 0 | 0 | 6,05 h | Null-Sale-Gate bei 30 SOIs und ≥24 h; noch **29 SOIs**, Altersgrenze in ca. **17,95 h** |\n| **2769** | Single69_Everflow_SeniorSexDates fsk18 | 4 | 0 | 0 | 6,05 h | Null-Sale-Gate bei 30 SOIs und ≥24 h; noch **26 SOIs**, Altersgrenze in ca. **17,95 h** |\n\n**Fazit:** Alle Schutzregeln greifen korrekt; aktuell ist keine LP rotationsreif. First-Sales wurden ausschließlich aus dem Event **Sale** gezählt, Rebills separat. Die 336-Stunden-Reifekohorten enthalten derzeit noch keine reifen SOIs."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T11:14:35.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf erfolgreich:** `action: none`, `writesPerformed: 0`, Exitcode 0. Keine Rotation und kein Everflow-Writeschritt.\n\n**Campaign 146 · Affiliate 436 · Offer 57 — gleiche Gewichte (je 1 / ca. 33,3 %)**\n\n- **LP 2749 — Single69_Everflow_Verlangen fsk18**\n  - 24 SOIs · **1 First-Sale** · 0 Rebills\n  - Alter: **44,91 Std.**\n  - Nächstes Gate: **50 SOIs**; noch **26 SOIs**. Dann Rotation, sofern nicht mindestens 3 unabhängige First-Sales erreicht sind.\n\n- **LP 2758 — Single69_Everflow_LUV2 mainstream**\n  - 1 SOI · **0 First-Sales** · 0 Rebills\n  - Alter: **4,03 Std.**\n  - Nächstes Gate: **30 SOIs und mindestens 24 Std.**; noch **29 SOIs**, außerdem Mindestalter noch nicht erreicht.\n\n- **LP 2769 — Single69_Everflow_SeniorSexDates fsk18**\n  - 3 SOIs · **0 First-Sales** · 0 Rebills\n  - Alter: **4,03 Std.**\n  - Nächstes Gate: **30 SOIs und mindestens 24 Std.**; noch **27 SOIs**, außerdem Mindestalter noch nicht erreicht.\n\nKeine LP ist derzeit rotationsreif oder vorläufig geschützt. Da kein Write stattfand, gab es keinen Backup-/PUT→GET-/Tracking-HTTP-Vorgang."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T09:13:32.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf Affiliate 436 · Campaign 146 · Offer 57**\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exitcode 0  \nKeine Rotation und kein Everflow-Write; daher kein Backup, PUT→GET oder Tracking-HTTP-Test erforderlich.\n\nAktuelle Rotation: **gleich gewichtet (1/1/1, je 33,33 %)**\n\n- **LP 2749 – Single69_Everflow_Verlangen fsk18**  \n  23 SOIs · **1 First-Sale** · 0 Rebills · Alter **42,89 h**  \n  **Nächstes Gate:** 50 SOIs; noch **27 SOIs**. Danach Rotation, sofern nicht mindestens 3 unabhängige First-Sales erreicht sind.\n\n- **LP 2758 – Single69_Everflow_LUV2 mainstream**  \n  1 SOI · **0 First-Sales** · 0 Rebills · Alter **2,02 h**  \n  **Nächstes Gate:** mindestens 30 SOIs und 24 h; noch **29 SOIs** und rund **21,98 h**.\n\n- **LP 2769 – Single69_Everflow_SeniorSexDates fsk18**  \n  3 SOIs · **0 First-Sales** · 0 Rebills · Alter **2,02 h**  \n  **Nächstes Gate:** mindestens 30 SOIs und 24 h; noch **27 SOIs** und rund **21,98 h**.\n\nReife Kohorte derzeit bei allen LPs: **0 reife SOIs / 0 reife First-Sales**. Nachlaufende Rebills und Wirtschaftlichkeit bleiben gemäß Policy **336 Stunden** in Beobachtung."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T07:13:00.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf: Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `replace_slot` — **2 LPs rotiert**, Exitcode 0  \n**Zeitpunkt:** 30.07.2026, ca. 07:12 UTC  \n**Writes:** 2 · beide **PUT→GET-verifiziert**  \n**Tracking-Test:** HTTP **302** — Weiterleitung funktioniert.\n\n### Aktuelle Rotation — gleich gewichtet 1:1:1\n\n| LP | Gewicht | SOIs | First-Sales | Rebills | Testalter | Nächstes Gate |\n|---|---:|---:|---:|---:|---:|---|\n| **2749 – Single69_Everflow_Verlangen fsk18** | 1 | 22 | 1 | 0 | 40,9 h | Noch **28 SOIs** bis 50; Rotation, falls dann weniger als 3 unabhängige First-Sales |\n| **2758 – Single69_Everflow_LUV2 mainstream** | 1 | neu gestartet | 0 | 0 | ~0 h | Frühestens bei **30 SOIs + 24 h**, sofern weiterhin 0 First-Sales |\n| **2769 – Single69_Everflow_SeniorSexDates fsk18** | 1 | neu gestartet | 0 | 0 | ~0 h | Frühestens bei **30 SOIs + 24 h**, sofern weiterhin 0 First-Sales |\n\n### Durchgeführte Wechsel\n\n1. **2759 – DatingSex fsk18** entfernt  \n   → **2758 – LUV2 mainstream** eingesetzt  \n   Grund: **53 SOIs, 1 First-Sale, 0 Rebills, 61,0 h** — 50er-Gate erreicht, aber weniger als 3 unabhängige First-Sales.  \n   Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-30T07-12-24-667Z.json`\n\n2. **2765 – DirektFlirten fsk18** entfernt  \n   → **2769 – SeniorSexDates fsk18** eingesetzt  \n   Grund: **35 SOIs, 0 First-Sales, 0 Rebills, 34,8 h** — Frühstopp-Gate von 30 SOIs und 24 Stunden überschritten.  \n   Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-30T07-12-25-674Z.json`\n\nDie entfernten Kohorten bleibe"
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T05:11:28.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "**Live-Lauf fehlgeschlagen / Sicherheitsstopp**\n\n- **Affiliate:** 436 · **Campaign:** 146 · **Offer:** 57\n- **Exit-Code:** `1`\n- **Exakter Fehler:** `everflow_api_key_missing`\n- **Fehlerstelle:** `run-live-sale-first.js:71`\n- **JSON-Ergebnis:** keines – das Skript brach vor der API-Abfrage ab.\n- **Writes:** `0`; kein Everflow-PUT, kein manueller Eingriff.\n- **LPs, Gewichte, KPIs und nächste Gates:** wegen fehlendem API-Key nicht abrufbar.\n\nDie Schutzmechanismen wurden nicht umgangen und der Lauf nicht wiederholt."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T03:10:20.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf fehlgeschlagen — keine Änderungen durchgeführt.**\n\n- **Affiliate:** 436\n- **Campaign:** 146\n- **Offer:** 57\n- **Exitcode:** `1`\n- **Exakter Fehler:** `everflow_api_key_missing`\n- **Fehlerstelle:** `/home/hermes/everflow-ops/trafficcompany-436/run-live-sale-first.js:71`\n- **Writes:** `0`\n- **Backup / PUT→GET-Verifikation / Tracking-HTTP-Test:** nicht ausgeführt\n- **JSON-Ergebnis:** keines; das Skript brach vor der Datenerhebung ab.\n\nDie aktuellen LPs, Gewichte, SOIs, First-Sales, Rebills, Testalter und nächsten Gates konnten deshalb nicht ermittelt werden. Die Sicherheitsmechanismen wurden nicht umgangen und der Lauf wurde nicht wiederholt."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-30T01:09:20.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf fehlgeschlagen (Exitcode 1).**\n\n- Exakter Fehler: `everflow_api_key_missing`\n- Das Skript brach beim Laden des API-Schlüssels ab und lieferte daher **kein JSON-Ergebnis**.\n- **Keine Everflow-Schreiboperation**, kein LP-Tausch und kein PUT→GET wurden ausgeführt.\n- Aktuelle LPs, Gewichte, SOIs, First-Sales, Rebills, Alter und nächste Gates konnten nicht abgerufen werden.\n- Die Schutzmechanismen wurden nicht umgangen; das Skript wurde wie angefordert nur einmal ausgeführt."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T23:08:26.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "**Live-Lauf fehlgeschlagen (Exit-Code 1).**\n\n- **Exakter Fehler:** `everflow_api_key_missing`\n- **Ursprung:** `run-live-sale-first.js:71`\n- **Ergebnis:** Das Skript brach vor API-Abfrage und JSON-Ausgabe ab.\n- **Writes:** 0 — kein Everflow-PUT, kein LP-Tausch.\n- **LP-KPIs/Gates:** Nicht abrufbar, da der API-Key fehlte.\n- **Safeguards:** Nicht umgangen; kein separater oder manueller Everflow-Schreibzugriff ausgeführt."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T21:07:46.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "**Live-Lauf fehlgeschlagen / Safeguard nicht umgangen**\n\n- **Exitcode:** `1`\n- **Exakter Fehler:** `everflow_api_key_missing`\n- **JSON-Ergebnis:** keines – das Skript brach vor der Auswertung ab.\n- **Writes:** `0`; kein Everflow-PUT und keine manuelle Änderung.\n- **LP-KPIs / nächste Gates:** konnten wegen des fehlenden API-Keys nicht geladen werden.\n\nFehlerstelle: `/home/hermes/everflow-ops/trafficcompany-436/run-live-sale-first.js:71`"
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T14:40:29.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow Sale-first-Lauf – Affiliate 436 / Campaign 146 / Offer 57**\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · erfolgreicher Exit.  \nDie Rotation bleibt unverändert und gleich gewichtet (`1 / 1 / 1`).\n\n- **LP 2749 – Single69_Everflow_Verlangen fsk18**  \n  11 SOIs · 0 First-Sales · 0 Rebills · Alter 24,34 h  \n  **Nächstes Gate:** noch 19 SOIs bis zum 30-SOI-Zero-Sale-Gate.\n\n- **LP 2759 – Single69_Everflow_DatingSex fsk18**  \n  35 SOIs · 1 First-Sale · 0 Rebills · Alter 44,51 h  \n  **Nächstes Gate:** noch 15 SOIs bis 50. Dann Rotation, sofern nicht mindestens 3 unabhängige First-Sales erreicht sind.\n\n- **LP 2765 – Single69_Everflow_DirektFlirten fsk18**  \n  21 SOIs · 0 First-Sales · 0 Rebills · Alter 18,27 h  \n  **Nächstes Gate:** 30 SOIs und mindestens 24 Stunden Testalter; aktuell fehlen 9 SOIs, das Alterskriterium ist noch nicht erfüllt.\n\nKein PUT, daher keine LP ausgetauscht und keine Backup-, PUT→GET- oder Tracking-HTTP-Verifikation erforderlich."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T10:36:51.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` — **kein LP-Wechsel**, `writesPerformed: 0`.  \nDer Lauf endete erfolgreich (Exitcode 0); alle Schutzregeln blieben aktiv.\n\n**Aktuelle Rotation:** drei gleich gewichtete LPs (je Gewicht `1`, entsprechend gleichverteilt)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 8 | 0 | 0 | 20,28 h | 30 SOIs **und** ≥24 h; noch 22 SOIs |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 32 | 1 | 0 | 40,45 h | 50 SOIs; noch 18. Danach Rotation, sofern nicht mindestens 3 unabhängige First-Sales erreicht sind |\n| **2765** | Single69_Everflow_DirektFlirten fsk18 | 16 | 0 | 0 | 14,21 h | 30 SOIs **und** ≥24 h; noch 14 SOIs |\n\n**Reife Kohorten:** derzeit bei allen drei LPs `0` reife SOIs und `0` reife First-Sales im 336-Stunden-Fenster. First-Sales wurden ausschließlich aus dem **Sale-Event** gezählt; Rebills sind separat ausgewiesen. Da kein Write stattfand, gab es keinen Backup-, PUT→GET- oder Tracking-HTTP-Vorgang."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T08:31:06.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow Sale-first Lauf – Affiliate 436 / Campaign 146 / Offer 57**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0`\n- **Status:** Erfolgreicher Hold, keine Rotation erforderlich\n- **Gewichtung:** alle drei LPs gleich (`1:1:1`)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 7 | 0 | 0 | 18,18 h | Noch 23 SOIs bis 30; Rotation frühestens zusätzlich nach 24 h |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 30 | 1 | 0 | 38,35 h | Noch 20 SOIs bis 50; dann Rotation, sofern nicht mindestens 3 unabhängige First-Sales erreicht sind |\n| **2765** | Single69_Everflow_DirektFlirten fsk18 | 10 | 0 | 0 | 12,11 h | Noch 20 SOIs bis 30; Rotation frühestens zusätzlich nach 24 h |\n\nRebills bleiben separat; entfernte und aktuelle Kohorten werden laut Policy bis **336 Stunden** nachverfolgt. Da kein Write erfolgte, gab es keinen Backup-, PUT→GET- oder Tracking-HTTP-Vorgang."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T06:29:12.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf Affiliate 436 · Campaign 146 · Offer 57**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0`\n- **Status:** Erfolgreicher Hold; keine Rotation erforderlich, keine Safeguards umgangen.\n- **Gewichtung:** alle drei LPs gleich gewichtet (`1 / 1 / 1`)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 6 | 0 | 0 | 16,15 h | 30 SOIs **und** mindestens 24 h; noch 24 SOIs |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 27 | 1 | 0 | 36,32 h | Wegen 1 Sale weiter bis 50 SOIs; noch 23 SOIs. Schutz erst ab ≥3 unabhängigen First-Sales |\n| **2765** | Single69_Everflow_DirektFlirten fsk18 | 8 | 0 | 0 | 10,08 h | 30 SOIs **und** mindestens 24 h; noch 22 SOIs |\n\nEs wurden keine Everflow-Writes ausgeführt; daher gab es keinen LP-Austausch, kein Backup, keinen PUT→GET-Verifikationslauf und keinen Tracking-HTTP-Test. Die 336-Stunden-Reifekohorten enthalten aktuell noch keine reifen SOIs."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T04:28:04.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Everflow Sale-first-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exitcode `0`  \nKeine Rotation und kein Everflow-PUT erforderlich. Die Schutzmechanismen wurden nicht umgangen.\n\n**Aktuelle Rotation:** gleiche Gewichte `1:1:1`\n\n- **LP 2749 – Single69_Everflow_Verlangen fsk18**\n  - 5 SOIs · 0 First-Sales · 0 Rebills\n  - Alter: 14,13 Stunden\n  - Nächstes Gate: mindestens **30 SOIs und 24 Stunden** bei weiterhin 0 First-Sales\n  - Noch 25 SOIs bis zum SOI-Gate\n\n- **LP 2759 – Single69_Everflow_DatingSex fsk18**\n  - 26 SOIs · 1 First-Sale · 0 Rebills\n  - Alter: 34,30 Stunden\n  - Nächstes Gate: **50 SOIs**\n  - Noch 24 SOIs; bei 50 SOIs Rotation, sofern dann nicht mindestens 3 unabhängige First-Sales vorliegen\n\n- **LP 2765 – Single69_Everflow_DirektFlirten fsk18**\n  - 4 SOIs · 0 First-Sales · 0 Rebills\n  - Alter: 8,06 Stunden\n  - Nächstes Gate: mindestens **30 SOIs und 24 Stunden** bei weiterhin 0 First-Sales\n  - Noch 26 SOIs bis zum SOI-Gate\n\nDa kein Write stattfand, gab es keinen LP-Austausch, kein Backup, keine PUT→GET-Verifikation und keinen Tracking-HTTP-Test."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T02:27:05.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Everflow Sale-first-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · erfolgreicher Exit  \nKeine Rotation, kein Everflow-PUT und folglich keine Backup-/PUT→GET-/Tracking-Prüfung erforderlich.\n\n**Aktuelle Rotation:** drei gleich gewichtete LPs (`1 / 1 / 1`)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes relevantes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 5 | 0 | 0 | 12,11 h | Frührotation erst bei **30 SOIs und ≥24 h**; noch 25 SOIs |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 25 | 1 | 0 | 32,28 h | Wegen 1 First-Sale Weiterlauf bis **50 SOIs**; noch 25 SOIs. Schutz erst ab ≥3 unabhängigen First-Sales |\n| **2765** | Single69_Everflow_DirektFlirten fsk18 | 2 | 0 | 0 | 6,05 h | Frührotation erst bei **30 SOIs und ≥24 h**; noch 28 SOIs |\n\nNoch keine reifen 336-Stunden-Kohorten (`matureSois: 0` bei allen LPs). First-Sales wurden ausschließlich aus dem Event **Sale** gewertet; Rebills sind separat ausgewiesen."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-29T00:26:03.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf erfolgreich beendet** — Exitcode `0`.\n\n- **Aktion:** `none`\n- **Writes:** `0`\n- **Campaign:** 146 · Offer 57 · Affiliate 436\n- **Rotation:** gleich gewichtet `1:1:1`\n- Kein Backup, PUT→GET oder Tracking-HTTP-Test erforderlich, da kein Write erfolgte.\n\n| LP | Gewicht | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---:|---:|---:|---:|---:|---|\n| **2749** — Single69_Everflow_Verlangen fsk18 | 1 | 5 | 0 | 0 | 10,10 h | Noch 25 SOIs bis 30; Rotation erst bei ≥24 h und weiterhin 0 First-Sales |\n| **2759** — Single69_Everflow_DatingSex fsk18 | 1 | 23 | 1 | 0 | 30,27 h | Weiter bis 50 SOIs; noch 27. Dann Rotation, falls nicht mindestens 3 unabhängige First-Sales erreicht sind |\n| **2765** — Single69_Everflow_DirektFlirten fsk18 | 1 | 2 | 0 | 0 | 4,03 h | Noch 28 SOIs bis 30; Rotation erst bei ≥24 h und weiterhin 0 First-Sales |\n\n**Ergebnis:** Alle drei LPs bleiben unverändert aktiv. First-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat ausgewiesen. Die 336-Stunden-Reifephase ist noch nicht erreicht (`matureSois: 0` bei allen LPs)."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T22:25:11.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Everflow Sale-first Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exit-Code `0`  \nDie drei LPs laufen weiterhin **gleich gewichtet (1/1/1, je ca. 33,3 %)**. Kein Backup, PUT→GET oder Tracking-HTTP-Test erforderlich, da kein Write erfolgte.\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2749** | Single69_Everflow_Verlangen fsk18 | 5 | 0 | 0 | 8,08 h | Noch **25 SOIs** und mindestens **15,92 h** bis zum 30-SOI/24h-Gate |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 20 | 1 | 0 | 28,25 h | Wegen 1 First-Sale weiter bis **50 SOIs**; noch **30 SOIs** |\n| **2765** | Single69_Everflow_DirektFlirten fsk18 | 2 | 0 | 0 | 2,02 h | Noch **28 SOIs** und mindestens **21,98 h** bis zum 30-SOI/24h-Gate |\n\n**Fazit:** Kein Slot hat aktuell sein Rotations- oder Schutz-Gate erreicht. First-Sales wurden ausschließlich aus dem Event **Sale** gewertet; Rebills bleiben separat."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T20:24:36.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf: LP-Austausch durchgeführt\n\n**Affiliate 436 · Campaign 146 · Offer 57**  \n**Aktion:** `replace_slot` · **Writes:** 1 · Exitcode 0\n\n### Austausch\n- **Entfernt:** LP **2748** — `Single69_Everflow_Onlyxnude fsk18`\n  - 32 SOIs · **0 First-Sales** · 0 Rebills\n  - Testalter: **36,32 h**\n  - Grund: Gate erfüllt — mindestens 30 SOIs, mindestens 24 Stunden und keine First-Sales\n- **Neu:** LP **2765** — `Single69_Everflow_DirektFlirten fsk18`\n  - Neuer Teststart: **28.07.2026, 20:23:58 UTC**\n  - Der Lauf liefert noch keine Post-Swap-Kennzahlen.\n  - 120-Tage-Vorhistorie, nicht aktueller Test: 42 Regs, 1 First-Sale, 0 Rebills, −123,34 € Profit\n\n### Aktuelle Rotation — gleiche Gewichte\n| LP | Name | Gewicht | Stand beim Lauf | Nächstes Gate |\n|---|---|---:|---|---|\n| **2749** | Verlangen fsk18 | 1 (~33,3 %) | 3 SOIs, 0 First-Sales, 0 Rebills, 6,07 h | Noch 27 SOIs und mindestens 17,93 h bis zum frühen 30-SOI-/24h-Gate |\n| **2759** | DatingSex fsk18 | 1 (~33,3 %) | 16 SOIs, 1 First-Sale, 0 Rebills, 26,24 h | Noch 34 SOIs bis 50; Schutz erst ab mindestens 3 unabhängigen First-Sales |\n| **2765** | DirektFlirten fsk18 | 1 (~33,3 %) | Frisch aktiviert; keine Post-Swap-Metriken ausgegeben | Zunächst 30 SOIs + 24 h bei 0 First-Sales; bei 1–2 Sales weiter bis 50 SOIs |\n\n### Write-Verifikation\n- Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-28T20-23-58-100Z.json`\n- **PUT → GET verifiziert:** ja\n- **Tracking-Link:** HTTP **302**\n- Die entfernte LP-Kohorte bleibt gemäß Policy **336 Stunden** für Rebills und nachhaltige Wirtschaftlichkeit im Trackin"
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T18:23:06.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Everflow Sale-first-Lauf — Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · **0 Writes** · Exitcode 0  \nAktuelle Rotation unverändert, **gleich gewichtet 1/1/1**.\n\n- **LP 2748 — Single69_Everflow_Onlyxnude fsk18**  \n  25 SOIs · 0 First-Sales · 0 Rebills · Alter 34,30 h  \n  **Nächstes Gate:** noch 5 SOIs bis zum 30-SOI-Rotationsgate.\n\n- **LP 2749 — Single69_Everflow_Verlangen fsk18**  \n  2 SOIs · 0 First-Sales · 0 Rebills · Alter 4,05 h  \n  **Nächstes Gate:** noch 28 SOIs; zusätzlich mindestens 24 h Testalter erforderlich.\n\n- **LP 2759 — Single69_Everflow_DatingSex fsk18**  \n  16 SOIs · 1 First-Sale · 0 Rebills · Alter 24,22 h  \n  **Nächstes Gate:** noch 34 SOIs bis 50. Dann Rotation, sofern nicht mindestens 3 unabhängige First-Sales erreicht sind.\n\nKeine LP wurde ausgetauscht; daher kein Backup, PUT→GET oder Tracking-HTTP-Test erforderlich."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T16:22:14.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "**Everflow Sale-first Lauf — Campaign 146 / Affiliate 436 / Offer 57**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0`\n- **Gewichtung:** alle drei LPs gleich gewichtet (`1 / 1 / 1`)\n- **Safeguards:** kein PUT erforderlich, keine Schutzmaßnahme umgangen\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 25 | 0 | 0 | 32,29 h | Noch **5 SOIs** bis zum 30-SOI-Rotationsgate |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 16 | 0 | 0 | 22,20 h | Noch **14 SOIs** und mindestens 24 h Testalter |\n| **2749** | Single69_Everflow_Verlangen fsk18 | 2 | 0 | 0 | 2,03 h | Noch **28 SOIs** und mindestens 24 h Testalter |\n\nEs gab keine First-Sales aus dem Event **Sale** und keine Rebills. Keine LP hat derzeit das zweistufige Rotationsgate vollständig erreicht; daher wurde korrekt **nicht geschrieben**."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T14:20:49.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf: Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `replace_slot` — **1 verifizierter Write**, Exitcode `0`.\n\n### Austausch\n- **Entfernt:** LP **2789** – `Single69_Everflow mainstream`\n  - 30 SOIs\n  - 0 First-Sales\n  - 0 Rebills\n  - Alter: 30,253 Stunden\n- **Neu:** LP **2749** – `Single69_Everflow_Verlangen fsk18`\n- **Grund:** Früh-Gate erreicht: mindestens 30 SOIs, mindestens 24 Stunden alt und kein First-Sale.\n- Der Nachlauf der entfernten Kohorte bleibt gemäß Policy **336 Stunden** für Rebills und Wirtschaftlichkeit erfasst.\n\n### Aktuelle Rotation – gleiche Gewichte `1 / 1 / 1`\n| LP | Aktuelle Kohorte beim Lauf | Nächstes Gate |\n|---|---:|---|\n| **2749** – Verlangen fsk18 | Neu gestartet; im Ergebnis noch keine neuen Kohorten-KPIs ausgewiesen | Bei 0 Sales: 30 SOIs und ≥24h; bei 1–2 Sales: 50 SOIs |\n| **2759** – DatingSex fsk18 | 12 SOIs, 0 First-Sales, 0 Rebills, 20,168h | Noch 18 SOIs; zusätzlich mindestens 24h |\n| **2748** – Onlyxnude fsk18 | 23 SOIs, 0 First-Sales, 0 Rebills, 30,253h | Noch 7 SOIs bis zum Früh-Gate |\n\nAb 50 SOIs erfolgt Schutz nur bei **mindestens 3 unabhängigen First-Sales**. First-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat.\n\n### Write-Verifikation\n- Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-28T14-19-57-189Z.json`\n- PUT→GET verifiziert: **ja**\n- Aktive LPs nach GET: **2748, 2749, 2759**\n- Tracking-Link-Test: **HTTP 302**"
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T12:19:04.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "## Live-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exitcode `0`  \nDie drei LPs laufen weiterhin **gleich gewichtet mit jeweils Gewicht 1 (1:1:1)**.\n\n| LP | Name | SOIs | First-Sales | Rebills | Testalter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2789** | Single69_Everflow mainstream | 27 | 0 | 0 | 28,24 h | Noch **3 SOIs** bis zum 30-SOI-Rotationsgate |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 10 | 0 | 0 | 18,15 h | Noch **20 SOIs** und mindestens **5,85 h** |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 21 | 0 | 0 | 28,24 h | Noch **9 SOIs** bis zum 30-SOI-Rotationsgate |\n\nEs liegen keine First-Sales aus dem Event **Sale** und keine Rebills vor. Keine LP hat derzeit das zweistufige Rotations- oder Schutzgate erreicht. Daher erfolgten **kein PUT, kein LP-Austausch und keine weiteren Everflow-Schreibzugriffe**."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T10:18:08.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "## Sale-first-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exitcode `0`  \nDie drei LPs laufen weiterhin **gleich gewichtet (1:1:1)**. Kein Everflow-PUT und damit kein LP-Austausch, Backup oder Tracking-Link-Test erforderlich.\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2789** | Single69_Everflow mainstream | 25 | 0 | 0 | 26,2189 h | Noch **5 SOIs** bis zum 30-SOI-Zero-Sale-Gate |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 7 | 0 | 0 | 16,1340 h | Noch **23 SOIs** und Mindestalter **24 h** |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 18 | 0 | 0 | 26,2186 h | Noch **12 SOIs** bis zum 30-SOI-Zero-Sale-Gate |\n\n**Kurzurteil:** Hold ohne Eingriff. LP **2789** erreicht als Nächstes das relevante Austausch-Gate, sofern sie bei **30 SOIs weiterhin 0 First-Sales** hat. First-Sales wurden ausschließlich als `Sale` gewertet; Rebills bleiben separat."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T08:17:06.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf: Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exitcode `0`  \nKeine LP wurde rotiert; alle Schutzregeln wurden eingehalten.\n\n**Aktuelle Rotation – gleiche Gewichte (`1 / 1 / 1`):**\n\n- **LP 2789 – Single69_Everflow mainstream**  \n  23 SOIs · 0 First-Sales · 0 Rebills · Alter: 24,2035 h  \n  **Nächstes Gate:** weitere 7 SOIs bis zum 30-SOI-Zero-Sale-Gate.\n\n- **LP 2759 – Single69_Everflow_DatingSex fsk18**  \n  6 SOIs · 0 First-Sales · 0 Rebills · Alter: 14,1187 h  \n  **Nächstes Gate:** 30 SOIs und mindestens 24 Stunden Testalter; noch 24 SOIs erforderlich.\n\n- **LP 2748 – Single69_Everflow_Onlyxnude fsk18**  \n  17 SOIs · 0 First-Sales · 0 Rebills · Alter: 24,2033 h  \n  **Nächstes Gate:** weitere 13 SOIs bis zum 30-SOI-Zero-Sale-Gate.\n\nNoch keine reifen SOIs oder First-Sales. Da kein Write erfolgte, gab es keinen Backup-, PUT→GET- oder Tracking-HTTP-Vorgang."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T06:15:59.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "## Live-Lauf: Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `action: none` · `writesPerformed: 0` · Exitcode `0`  \nDie Rotation bleibt unverändert. **Gleichgewichtung: 1 / 1 / 1.**\n\n| LP | Gewicht | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---:|---:|---:|---:|---:|---|\n| **2789 – Single69_Everflow mainstream** | 1 | 21 | 0 | 0 | 22,19 h | Frührotation bei **30 SOIs und ≥24 h**; noch 9 SOIs |\n| **2759 – Single69_Everflow_DatingSex fsk18** | 1 | 6 | 0 | 0 | 12,10 h | Frührotation bei **30 SOIs und ≥24 h**; noch 24 SOIs |\n| **2748 – Single69_Everflow_Onlyxnude fsk18** | 1 | 15 | 0 | 0 | 22,18 h | Frührotation bei **30 SOIs und ≥24 h**; noch 15 SOIs |\n\n**Bewertung:** Keine LP erfüllt derzeit beide Voraussetzungen der ersten Rotationsstufe. First-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat ausgewiesen. Es erfolgte kein PUT und somit kein LP-Austausch."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T04:14:54.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow Sale-first Lauf – Affiliate 436 / Campaign 146 / Offer 57**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0`\n- **Gewichtung:** alle drei LPs gleich gewichtet (`1/1/1`, je rund ein Drittel)\n- **Status:** Noch keine LP erfüllt gleichzeitig die erste Rotationsschwelle von **30 SOIs, mindestens 24 Stunden Testalter und 0 First-Sales**.\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2789** | Single69_Everflow mainstream | 21 | 0 | 0 | 20,17 h | Noch 9 SOIs; außerdem mindestens 24 h Alter |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 15 | 0 | 0 | 20,17 h | Noch 15 SOIs; außerdem mindestens 24 h Alter |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 5 | 0 | 0 | 10,08 h | Noch 25 SOIs; außerdem mindestens 24 h Alter |\n\nEs erfolgte **kein LP-Austausch und kein Everflow-PUT**; daher gibt es keinen Backup-, PUT→GET- oder Tracking-HTTP-Nachweis zu melden."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T02:13:58.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf: Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `action: none` · **0 Writes** · Exitcode 0.  \nKeine Rotation erforderlich; alle Schutzmechanismen blieben aktiv.\n\n**Aktuelle Rotation – gleich gewichtet (je 1/3):**\n\n- **LP 2789 — Single69_Everflow mainstream:** 21 SOIs · 0 First-Sales · 0 Rebills · Alter 18,15 h  \n  **Nächstes Gate:** noch 9 SOIs und mindestens 24 h Testalter.\n- **LP 2748 — Single69_Everflow_Onlyxnude fsk18:** 15 SOIs · 0 First-Sales · 0 Rebills · Alter 18,15 h  \n  **Nächstes Gate:** noch 15 SOIs und mindestens 24 h Testalter.\n- **LP 2759 — Single69_Everflow_DatingSex fsk18:** 4 SOIs · 0 First-Sales · 0 Rebills · Alter 8,07 h  \n  **Nächstes Gate:** noch 26 SOIs und mindestens 24 h Testalter.\n\n**Nächste relevante Entscheidung:** voraussichtlich LP **2789**, sobald gleichzeitig mindestens **30 SOIs**, mindestens **24 Stunden Alter** und weiterhin **0 First-Sales** erreicht sind. Da kein Write stattfand, gab es keinen Backup-, PUT→GET- oder Tracking-HTTP-Vorgang."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-28T00:12:55.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "**Live-Lauf erfolgreich – keine Rotation**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0`\n- **Campaign:** 146 · **Affiliate:** 436 · **Offer:** 57\n- **Gewichtung:** gleichmäßig **1:1:1**\n- Keine PUTs, Backups oder Tracking-Link-Prüfungen erforderlich.\n\n| LP | Gewicht | SOIs | First-Sales | Rebills | Testalter | Nächstes Gate |\n|---|---:|---:|---:|---:|---:|---|\n| **2789 – Single69_Everflow mainstream** | 1 | 21 | 0 | 0 | 16,13 h | Noch 9 SOIs und mindestens 24 h Testalter |\n| **2748 – Single69_Everflow_Onlyxnude fsk18** | 1 | 15 | 0 | 0 | 16,13 h | Noch 15 SOIs und mindestens 24 h Testalter |\n| **2759 – Single69_Everflow_DatingSex fsk18** | 1 | 4 | 0 | 0 | 6,05 h | Noch 26 SOIs und mindestens 24 h Testalter |\n\n**Urteil:** Alle drei LPs bleiben aktiv. Noch keine Seite erfüllt das Rotationsgate von mindestens 30 SOIs, mindestens 24 Stunden Alter und null First-Sales. First-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat ausgewiesen."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T22:11:52.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "## Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `action: none` — **Hold ohne Fehler**, `writesPerformed: 0`.  \nKeine Rotation und kein Everflow-Write. Alle drei LPs laufen gleich gewichtet (**1/1/1**, je ca. 33,3 %).\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2789** | Single69_Everflow mainstream | 21 | 0 | 0 | 14,12 h | Noch **9 SOIs** und mindestens **24 h** Testalter |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 15 | 0 | 0 | 14,12 h | Noch **15 SOIs** und mindestens **24 h** Testalter |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 3 | 0 | 0 | 4,03 h | Noch **27 SOIs** und mindestens **24 h** Testalter |\n\n**Urteil:** Noch keine LP erfüllt das erste Rotationsgate von mindestens 30 SOIs, mindestens 24 Stunden Alter und null First-Sales. Der nächste relevante Kandidat ist **LP 2789**. Die Kohortenreife beträgt **336 Stunden**."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T20:10:56.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf erfolgreich – keine Rotation**\n\n- **Ergebnis:** `action: none`\n- **Writes:** `0`\n- **Campaign:** 146 · **Offer:** 57 · **Affiliate:** 436\n- **Gewichtung:** alle drei LPs gleich gewichtet (`1/1/1`)\n- **Policy:** Rotation frühestens bei **30 SOIs + 24 Stunden Testalter + 0 First-Sales**\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2789** | Single69_Everflow mainstream | 19 | 0 | 0 | 12,10 h | Noch 11 SOIs; zusätzlich mindestens 24 h Alter |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 12 | 0 | 0 | 12,10 h | Noch 18 SOIs; zusätzlich mindestens 24 h Alter |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 2 | 0 | 0 | 2,02 h | Noch 28 SOIs; zusätzlich mindestens 24 h Alter |\n\n**Fazit:** Keine LP erfüllt derzeit das erste Rotations-Gate. Es gab keinen Everflow-PUT, daher auch keinen LP-Austausch, kein Write-Backup und keine PUT→GET-/Tracking-Verifikation."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T18:10:15.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf erfolgreich – LP ausgetauscht\n\n**Affiliate 436 · Campaign 146 · Offer 57**  \n**Aktion:** `replace_slot` · **Writes:** 1 · **Zeitpunkt:** 27.07.2026, 18:09:44 UTC\n\n### Austausch\n- **Entfernt:** LP **2746** – `Single69_Everflow_zusammende mainstream`\n  - 30 SOIs · **0 First-Sales** · 0 Rebills · Alter 34,31 h\n  - Grund: Früh-Gate erreicht: ≥30 SOIs, ≥24 h und keine Sale-Events\n- **Neu:** LP **2759** – `Single69_Everflow_DatingSex fsk18`\n  - Neue Testkohorte: 0 SOIs · 0 First-Sales · 0 Rebills · Alter ≈0 h\n  - Nächstes Gate: 30 SOIs **und** 24 h bei weiterhin 0 First-Sales; bei 1–2 First-Sales Fortsetzung bis 50 SOIs\n\n### Aktuelle Rotation – gleich gewichtet\n| LP | Name | Gewicht | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---:|---|\n| **2789** | Single69_Everflow mainstream | 1 (≈33,3 %) | 16 | 0 | 0 | 10,08 h | noch 14 SOIs und mindestens 24 h |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 1 (≈33,3 %) | 10 | 0 | 0 | 10,08 h | noch 20 SOIs und mindestens 24 h |\n| **2759** | Single69_Everflow_DatingSex fsk18 | 1 (≈33,3 %) | 0 | 0 | 0 | ≈0 h | 30 SOIs und mindestens 24 h |\n\nBei 1–2 First-Sales läuft eine LP bis 50 SOIs weiter; Schutz gibt es erst ab **3 unabhängigen First-Sales**. Rebills bleiben separat. Die entfernte Kohorte wird gemäß Policy bis 336 Stunden weiterverfolgt.\n\n### Schreib- und Sicherheitsnachweis\n- Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-27T18-09-44-395Z.json`\n- **PUT→GET verifiziert:** ja\n- Finale Gewichte: `2748=1`, `2759=1`, `2789=1`\n- Tracking-Test: **HTTP 3"
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T16:08:55.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf erfolgreich — keine Rotation, keine Writes.**\n\n- **Action:** `none`\n- **Writes:** `0`\n- **Campaign:** 146 · Affiliate 436 · Offer 57\n- **Gewichte:** gleichmäßig `1 / 1 / 1`\n\n| LP | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---:|---:|---:|---:|---|\n| **2746** — Single69_Everflow_zusammende mainstream | 29 | 0 | 0 | 32.2941 h | Noch **1 SOI** bis zur 30-SOI-Rotation; 24-h-Mindestalter bereits erreicht |\n| **2789** — Single69_Everflow mainstream | 14 | 0 | 0 | 8.0672 h | Noch **16 SOIs** und mindestens 24 h Testalter |\n| **2748** — Single69_Everflow_Onlyxnude fsk18 | 9 | 0 | 0 | 8.0669 h | Noch **21 SOIs** und mindestens 24 h Testalter |\n\nEs gab keinen PUT; daher waren kein Backup, keine PUT→GET-Verifikation und kein Tracking-HTTP-Test erforderlich. Script-Endstatus: **Exit 0**."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T14:08:04.000Z",
      "action": "review",
      "writes": 0,
      "verified": false,
      "summary": "**Live-Lauf erfolgreich – keine Rotation**\n\n- **Ergebnis:** `action: \"none\"`\n- **Writes:** `0`\n- **Campaign:** 146 · **Offer:** 57 · **Affiliate:** 436\n- **Gewichtung:** alle drei LPs gleich (`1/1/1`, entsprechend je einem Drittel)\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Testalter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2746** | Single69_Everflow_zusammende mainstream | 28 | 0 | 0 | 30,28 h | Noch **2 SOIs** bis zum 30-SOI-Gate; 24-h-Alter bereits erfüllt |\n| **2789** | Single69_Everflow mainstream | 10 | 0 | 0 | 6,05 h | Noch **20 SOIs** und mindestens 24 h Testalter |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 6 | 0 | 0 | 6,05 h | Noch **24 SOIs** und mindestens 24 h Testalter |\n\nEs gab keine First-Sales aus dem Event **Sale** und keine Rebills. Da noch keine LP alle Voraussetzungen für eine Rotation erfüllt, erfolgten **kein PUT, kein LP-Austausch und keine Everflow-Schreiboperation**."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T12:07:01.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Live-Lauf Affiliate 436 · Campaign 146 · Offer 57**\n\n**Ergebnis:** `action: none` — keine Rotation, `writesPerformed: 0`. Alle LPs laufen gleich gewichtet **1:1:1**.\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2746** | Single69_Everflow_zusammende mainstream | 23 | 0 | 0 | 28,26 h | Noch **7 SOIs** bis zum 30-SOI-Zero-Sale-Gate; Mindestalter bereits erreicht |\n| **2789** | Single69_Everflow mainstream | 7 | 0 | 0 | 4,03 h | Noch **23 SOIs** und Mindestalter von 24 h erreichen |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 3 | 0 | 0 | 4,03 h | Noch **27 SOIs** und Mindestalter von 24 h erreichen |\n\nFirst-Sales wurden ausschließlich über das Event **Sale** gezählt; Rebills separat. Keine LP hat aktuell das Rotationsgate erreicht, daher gab es weder Backup noch PUT/GET-Verifikation oder Tracking-Link-Test."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T10:06:08.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "### Sale-first-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: none` · **keine Änderung** · `writesPerformed: 0`  \nDie drei LPs laufen weiterhin **gleich gewichtet (1/1/1)**.\n\n| LP | Landingpage | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---|---|---:|---:|---:|---:|---|\n| **2746** | Single69_Everflow_zusammende mainstream | 19 | 0 | 0 | 26,24 h | Noch **11 SOIs** bis zum 30-SOI-Zero-Sale-Gate |\n| **2789** | Single69_Everflow mainstream | 4 | 0 | 0 | 2,02 h | Noch **26 SOIs** und mindestens 24 h Testalter |\n| **2748** | Single69_Everflow_Onlyxnude fsk18 | 2 | 0 | 0 | 2,02 h | Noch **28 SOIs** und mindestens 24 h Testalter |\n\n**Bewertung:** Hold ohne Write. LP 2746 hat die Altersgrenze bereits erreicht, aber noch nicht die erforderlichen 30 SOIs. Es gab keine First-Sales aus dem Event **Sale** und keine Rebills. Daher kein Backup, Campaign-PUT, GET-Write-Check oder Tracking-HTTP-Test erforderlich."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T08:05:11.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf: Affiliate 436 · Campaign 146 · Offer 57\n\n**Ergebnis:** `replace_slot` — **2 LPs rotiert**, `writesPerformed: 2`, Exitcode 0.\n\n### Aktuelle Rotation — gleich gewichtet (`1 / 1 / 1`)\n\n| LP | Aktuelle Testkohorte | SOIs | First-Sales | Rebills | Alter / nächstes Gate |\n|---|---:|---:|---:|---:|---|\n| **2746 – Single69_Everflow_zusammende mainstream** | laufend | 18 | 0 | 0 | 24,23 h; noch **12 SOIs** bis zum 30-SOI-Gate |\n| **2789 – Single69_Everflow mainstream** | neu ab 08:04:39 UTC | 0 zum Start | 0 | 0 | Neu; mindestens **30 SOIs und 24 h** |\n| **2748 – Single69_Everflow_Onlyxnude fsk18** | neu ab 08:04:40 UTC | 0 zum Start | 0 | 0 | Neu; mindestens **30 SOIs und 24 h** |\n\n### Durchgeführte Wechsel\n\n1. **LP 2756 – Sibgle69_Everflow_LUV mainstream** entfernt  \n   → **LP 2789 – Single69_Everflow mainstream** eingesetzt  \n   Grund: **44 SOIs, 0 First-Sales, 0 Rebills, 24,23 h**  \n   Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-27T08-04-38-880Z.json`  \n   **PUT→GET verifiziert:** ja\n\n2. **LP 2816 – Single69_Everflow_TikPorn fsk18** entfernt  \n   → **LP 2748 – Single69_Everflow_Onlyxnude fsk18** eingesetzt  \n   Grund: **40 SOIs, 0 First-Sales, 0 Rebills, 24,23 h**  \n   Backup: `/home/hermes/everflow-ops/trafficcompany-436/backups/campaign-146-2026-07-27T08-04-39-867Z.json`  \n   **PUT→GET verifiziert:** ja\n\n**Gesamtverifikation:** erfolgreich.  \n**Tracking-Link:** HTTP **302**.  \nDie entfernten Kohorten bleiben gemäß Policy bis **336 Stunden** für Rebills und langfristige Wirtschaftlichkeit in Beobachtung."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-27T06:03:53.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Live-Lauf – Affiliate 436 / Campaign 146 / Offer 57\n\n**Ergebnis:** `action: \"none\"` · `writesPerformed: 0` · Exitcode `0`  \nDie Rotation blieb unverändert. Alle drei LPs laufen **gleich gewichtet (1/1/1, je ca. 33,3 %)**.\n\n| LP | Name | SOIs | First-Sales | Rebills | Alter | Nächstes Gate |\n|---:|---|---:|---:|---:|---:|---|\n| **2756** | Sibgle69_Everflow_LUV mainstream | 42 | 0 | 0 | 22,21 h | 24-h-Mindestalter; noch ca. **1,79 h**, danach Rotation möglich |\n| **2746** | Single69_Everflow_zusammende mainstream | 17 | 0 | 0 | 22,21 h | Noch **13 SOIs** bis zum 30-SOI-Gate; zusätzlich mindestens 24 h |\n| **2816** | Single69_Everflow_TikPorn fsk18 | 36 | 0 | 0 | 22,21 h | 24-h-Mindestalter; noch ca. **1,79 h**, danach Rotation möglich |\n\nFirst-Sales wurden ausschließlich aus dem Event **Sale** gezählt; Rebills sind separat ausgewiesen. Es erfolgte **kein PUT**, daher gibt es für diesen Lauf keinen Backup-, PUT→GET- oder Tracking-HTTP-Nachweis."
    }
  ]
} as const;
export default journal;
