// Generated by scripts/sync-automation-journal.mjs
const journal={
  "schemaVersion": 1,
  "generatedAt": "2026-07-22T08:57:07.543Z",
  "scope": "server-side tracked live Smartlinks",
  "campaigns": [
    {
      "campaignId": 2,
      "name": "Trafficpartner - POP - ALL",
      "affiliateId": 6,
      "affiliate": "TrafficPartner",
      "mode": "live",
      "schedule": "alle 120 Minuten",
      "enabled": true,
      "lastRunAt": "2026-07-22T08:49:12.261136+00:00",
      "nextRunAt": "2026-07-22T10:49:12.261136+00:00",
      "lastStatus": "ok",
      "policy": "50/25/25 Champion/Challenger · Profit-first · ca. 1 % Smartlink-CVR schützen",
      "currentRotation": [
        {
          "id": 2748,
          "weight": 25
        },
        {
          "id": 2762,
          "weight": 50
        },
        {
          "id": 2816,
          "weight": 25
        }
      ],
      "latest": {
        "campaignId": 2,
        "evaluatedAt": "2026-07-22T08:49:11.697Z",
        "action": "none",
        "writes": 0,
        "verified": true,
        "summary": "cvr_protection_no_safe_action · state_verified",
        "metrics": {
          "blendCvr": 0.009106464429685913,
          "cvrFloor": 0.01,
          "regime": "protection"
        }
      }
    },
    {
      "campaignId": 146,
      "name": "Global - TrafficCompany",
      "affiliateId": 436,
      "affiliate": "Traffic Company",
      "mode": "live",
      "schedule": "alle 120 Minuten",
      "enabled": true,
      "lastRunAt": "2026-07-22T07:43:42.855689+00:00",
      "nextRunAt": "2026-07-22T09:43:42.855689+00:00",
      "lastStatus": "ok",
      "policy": "Sale-first · 3 Slots gleich · 50 SOIs Testquote · robuste Sales vor Scale",
      "currentRotation": [
        {
          "id": 2762,
          "name": "Single69_Everflow_MilfsFicken fsk18",
          "startedAt": "2026-07-21T11:27:56.369Z",
          "weight": 33.3
        },
        {
          "id": 2753,
          "name": "Single69_Everflow_Datelifede fsk18",
          "startedAt": "2026-07-21T11:27:56.829Z",
          "weight": 33.3
        },
        {
          "id": 2747,
          "name": "Single69_Everflow_Striptie fsk18",
          "startedAt": "2026-07-21T11:27:57.284Z",
          "weight": 33.3
        }
      ],
      "latest": {
        "campaignId": 146,
        "evaluatedAt": "2026-07-22T07:43:42.000Z",
        "action": "none",
        "writes": 0,
        "verified": true,
        "summary": "**Keine Aktion – 0 Writes**  \nStand: **22.07.2026, 09:43 Uhr Berlin**\n\nCampaign **146**, Affiliate **436**, Offer **57** läuft unverändert mit gleichmäßiger Verteilung (**je Routing-Gewicht 1 ≈ 33,3 %**):\n\n- **LP 2753 – Single69_Everflow_Datelifede fsk18:** 25 SOIs, 0 First-Sales, 0 Rebills → **noch 25 SOIs bis zur Rotation**\n- **LP 2747 – Single69_Everflow_Striptie fsk18:** 18 SOIs, 0 First-Sales, 0 Rebills → **noch 32 SOIs**\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18:** 16 SOIs, 0 First-Sales, 0 Rebills → **noch 34 SOIs**\n\nAlle Slots sind erst rund **20,3 Stunden** aktiv. Daher liegen noch **keine reifen SOIs** für das 336-Stunden-Fenster vor; die reife First-Sale-Rate ist jeweils noch nicht bestimmbar.\n\nCampaign-Zustand stimmt exakt mit `state.json` überein. Kein technischer Fehler und keine LP hat die 50-SOI-Quote erreicht, daher war kein PUT erforderlich. Campaign-Lock wurde ordnungsgemäß freigegeben."
      }
    }
  ],
  "rotations": [
    {
      "campaignId": 146,
      "time": "2026-07-21T11:27:57.284Z",
      "type": "slot_replacement",
      "from": {
        "id": 2780,
        "name": "Single69_Everflow_TelefonSex fsk18"
      },
      "to": {
        "id": 2747,
        "name": "Single69_Everflow_Striptie fsk18"
      },
      "after": [
        {
          "id": 2747,
          "weight": 1
        },
        {
          "id": 2753,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-21T11:27:56.829Z",
      "type": "slot_replacement",
      "from": {
        "id": 2754,
        "name": "Single69_Everflow_Fraueninmeinernaehe mainstream"
      },
      "to": {
        "id": 2753,
        "name": "Single69_Everflow_Datelifede fsk18"
      },
      "after": [
        {
          "id": 2753,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        },
        {
          "id": 2780,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 146,
      "time": "2026-07-21T11:27:56.369Z",
      "type": "slot_replacement",
      "from": {
        "id": 2750,
        "name": "Single69_Everflow_Tabuu fsk18"
      },
      "to": {
        "id": 2762,
        "name": "Single69_Everflow_MilfsFicken fsk18"
      },
      "after": [
        {
          "id": 2754,
          "weight": 1
        },
        {
          "id": 2762,
          "weight": 1
        },
        {
          "id": 2780,
          "weight": 1
        }
      ],
      "verified": true,
      "source": "replacement-history.jsonl"
    },
    {
      "campaignId": 2,
      "time": "2026-07-21T10:28:35.344Z",
      "type": "champion_and_slot_update",
      "before": [
        {
          "id": 2750,
          "name": "Single69_Everflow_Tabuu fsk18",
          "weight": 50
        },
        {
          "id": 2816,
          "name": "Single69_Everflow_TikPorn fsk18",
          "weight": 25
        },
        {
          "id": 2762,
          "name": "Single69_Everflow_MilfsFicken fsk18",
          "weight": 25
        }
      ],
      "after": [
        {
          "id": 2748,
          "weight": 25
        },
        {
          "id": 2762,
          "weight": 50
        },
        {
          "id": 2816,
          "weight": 25
        }
      ],
      "verified": true,
      "source": "writer-backup + accepted Everflow state"
    }
  ],
  "evaluations": [
    {
      "campaignId": 2,
      "evaluatedAt": "2026-07-22T08:49:11.697Z",
      "action": "none",
      "writes": 0,
      "verified": true,
      "summary": "cvr_protection_no_safe_action · state_verified",
      "metrics": {
        "blendCvr": 0.009106464429685913,
        "cvrFloor": 0.01,
        "regime": "protection"
      }
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-22T07:43:42.000Z",
      "action": "none",
      "writes": 0,
      "verified": true,
      "summary": "**Keine Aktion – 0 Writes**  \nStand: **22.07.2026, 09:43 Uhr Berlin**\n\nCampaign **146**, Affiliate **436**, Offer **57** läuft unverändert mit gleichmäßiger Verteilung (**je Routing-Gewicht 1 ≈ 33,3 %**):\n\n- **LP 2753 – Single69_Everflow_Datelifede fsk18:** 25 SOIs, 0 First-Sales, 0 Rebills → **noch 25 SOIs bis zur Rotation**\n- **LP 2747 – Single69_Everflow_Striptie fsk18:** 18 SOIs, 0 First-Sales, 0 Rebills → **noch 32 SOIs**\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18:** 16 SOIs, 0 First-Sales, 0 Rebills → **noch 34 SOIs**\n\nAlle Slots sind erst rund **20,3 Stunden** aktiv. Daher liegen noch **keine reifen SOIs** für das 336-Stunden-Fenster vor; die reife First-Sale-Rate ist jeweils noch nicht bestimmbar.\n\nCampaign-Zustand stimmt exakt mit `state.json` überein. Kein technischer Fehler und keine LP hat die 50-SOI-Quote erreicht, daher war kein PUT erforderlich. Campaign-Lock wurde ordnungsgemäß freigegeben."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-22T05:42:34.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow LP-Test – Campaign 146 · Affiliate 436 · Offer 57**  \n**Stand:** 22.07.2026, 07:42 CEST\n\n**Aktion:** Keine Änderung, **0 Writes**. Der Live-Campaign-GET stimmt exakt mit dem gespeicherten Zustand überein. Kein Slot hat die Rotationquote von 50 SOIs erreicht; daher war kein PUT erforderlich.\n\n| Aktive LP | Gewicht | SOIs | First-Sales | Reife SOIs | Reife First-Sale-Rate | Rebills | Bis Quote |\n|---|---:|---:|---:|---:|---:|---:|---:|\n| **2762** – Single69_Everflow_MilfsFicken fsk18 | 1 (⅓) | 15 | 0 | 0 | n/a | 0 | 35 |\n| **2753** – Single69_Everflow_Datelifede fsk18 | 1 (⅓) | 20 | 0 | 0 | n/a | 0 | 30 |\n| **2747** – Single69_Everflow_Striptie fsk18 | 1 (⅓) | 17 | 0 | 0 | n/a | 0 | 33 |\n\nAlle Slots laufen erst seit rund **18,2 Stunden** und sind noch nicht im **336-Stunden-Reifefenster**. Es gibt aktuell weder einen belastbaren Ausreißer noch einen Grund für 50/25/25; die gleichmäßige **1/1/1-Rotation** bleibt bestehen."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-22T03:41:33.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Keine LP-Rotation – 0 Writes**  \nStand: **22.07.2026, 05:41 CEST**\n\nCampaign **146** entspricht dem gespeicherten Sollzustand; der Campaign-GET bestätigte drei Offer-57-Slots mit gleichen Gewichten:\n\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18:** Gewicht 1, **12/50 SOIs**, 0 First-Sales, 0 Rebills – noch **38 SOIs**\n- **LP 2753 – Single69_Everflow_Datelifede fsk18:** Gewicht 1, **19/50 SOIs**, 0 First-Sales, 0 Rebills – noch **31 SOIs**\n- **LP 2747 – Single69_Everflow_Striptie fsk18:** Gewicht 1, **15/50 SOIs**, 0 First-Sales, 0 Rebills – noch **35 SOIs**\n\nAlle Slots laufen erst seit rund **16,2 Stunden**. Bei **336 Stunden Reifezeit** gibt es noch keine reifen SOIs; die mature First-Sale-Rate ist daher noch nicht bestimmbar. Kein Slot hat die Rotationsquote erreicht und es liegt kein technischer Ausfall vor. Deshalb blieb die gleichgewichtete Rotation unverändert; **kein PUT erforderlich**."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-22T01:40:20.000Z",
      "action": "none",
      "writes": 0,
      "verified": true,
      "summary": "**Keine Aktion – 0 Writes.** Campaign 146 entspricht dem gespeicherten Zustand; der Campaign-GET bestätigte die drei aktiven LPs mit gleicher Gewichtung **1/1/1**. Keine technische Störung, kein State-Konflikt.\n\n| LP | SOIs | First-Sales | Reife SOIs (336 h) | Reife First-Sale-Rate | Rebills | Bis Quote |\n|---|---:|---:|---:|---:|---:|---:|\n| **2762** – Single69_Everflow_MilfsFicken fsk18 | 12 | 0 | 0 | noch nicht bestimmbar | 0 | 38 |\n| **2753** – Single69_Everflow_Datelifede fsk18 | 17 | 0 | 0 | noch nicht bestimmbar | 0 | 33 |\n| **2747** – Single69_Everflow_Striptie fsk18 | 14 | 0 | 0 | noch nicht bestimmbar | 0 | 36 |\n\nDie Slots laufen erst seit rund **14,2 Stunden** und keiner hat die Stage-A-Quote von 50 SOIs erreicht. Daher wurde richtliniengemäß **kein PUT ausgeführt**; eine Post-Write-Verifikation war nicht erforderlich. Nächster möglicher Austausch: sobald ein Slot 50 SOIs erreicht und nicht als robuster Sale-Outlier qualifiziert ist."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T23:39:19.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "## Everflow LP-Testlauf – Campaign 146\n\n**Aktion:** Keine Änderung, **0 Writes**.  \nDer Campaign-GET entspricht exakt dem gespeicherten Zustand. Alle drei Slots bleiben gleich gewichtet (**1/1/1 ≈ 33,3 % je LP**). Kein Slot hat die Stage-A-Quote von 50 SOIs erreicht.\n\n| Aktive LP | SOIs | First-Sales | Reife SOIs / First-Sales | Reife First-Sale-Rate | Rebills | Bis Quote |\n|---|---:|---:|---:|---:|---:|---:|\n| **2762 – MilfsFicken fsk18** | 11 | 0 | 0 / 0 | noch nicht reif | 0 | 39 |\n| **2753 – Datelifede fsk18** | 16 | 0 | 0 / 0 | noch nicht reif | 0 | 34 |\n| **2747 – Striptie fsk18** | 12 | 0 | 0 / 0 | noch nicht reif | 0 | 38 |\n\nDie Slots laufen erst seit rund **12,2 Stunden**; bei einem Reifefenster von **336 Stunden** gibt es noch keine reife Sale-Kohorte. Daher weder Champion-Auswahl noch LP-Austausch.\n\n**Verifikation:** Campaign 146 per GET geprüft; LP-IDs, Offer 57 und Gewichte stimmen mit `state.json` überein. Kein PUT erforderlich."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T21:38:26.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow Sale-first LP-Test – Campaign 146**  \n**Stand:** 21.07.2026, 23:38 CEST\n\n**Aktion:** Keine Änderung, **0 Writes**. Kein Slot hat die Stage-A-Quote von 50 SOIs erreicht. Die aktuelle Everflow-Rotation wurde per GET geprüft und stimmt exakt mit `state.json` überein. Kein Fremdeingriff erkannt.\n\n| LP | Gewicht | SOIs | First-Sales | Reife SOIs | Reife First-Sale-Rate | Rebills | Bis Quote |\n|---|---:|---:|---:|---:|---:|---:|---:|\n| **2762 – MilfsFicken fsk18** | 1 | 9 | 0 | 0 | noch nicht reif | 0 | 41 |\n| **2753 – Datelifede fsk18** | 1 | 16 | 0 | 0 | noch nicht reif | 0 | 34 |\n| **2747 – Striptie fsk18** | 1 | 12 | 0 | 0 | noch nicht reif | 0 | 38 |\n\nDie Slots laufen seit rund **10,2 Stunden**; das Offer-57-Reifefenster beträgt **336 Stunden**. Deshalb ist aktuell noch keine belastbare reife First-Sale-Rate verfügbar. Die gleichmäßige **1/1/1-Rotation** bleibt bestehen.\n\n**Verifikation:** Campaign-GET erfolgreich und semantisch gegen den erwarteten Zustand geprüft. Kein PUT erforderlich; daher keine Post-write-Verifikation oder Tracking-Link-Prüfung ausgelöst."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T19:37:14.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Keine Live-Aktion – Campaign 146 unverändert.**\n\nDer Everflow-GET entspricht exakt dem gespeicherten Zustand; kein `foreign_state_change`. Alle drei Slots laufen gleichgewichtet mit **1/1/1**:\n\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18:** 7 SOIs, 0 First-Sales, 0 Rebills, **43 SOIs bis zur Quote**\n- **LP 2753 – Single69_Everflow_Datelifede fsk18:** 10 SOIs, 0 First-Sales, 0 Rebills, **40 SOIs bis zur Quote**\n- **LP 2747 – Single69_Everflow_Striptie fsk18:** 9 SOIs, 0 First-Sales, 0 Rebills, **41 SOIs bis zur Quote**\n\nTestalter jeweils rund **8,2 Stunden**. Nach dem 336-Stunden-Reifefenster gibt es noch keine reifen SOIs; die **reife First-Sale-Rate ist daher noch nicht bestimmbar**.\n\n**Verifikation:** Campaign-GET erfolgreich und semantisch identisch zum erwarteten Zustand. **Kein PUT, 0 Writes.** Kein Slot hat die Rotationsquote von 50 SOIs erreicht."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T17:36:22.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Keine Live-Aktion erforderlich** — Stand: **21.07.2026, 19:36 CEST**\n\nCampaign **146** entspricht exakt dem gespeicherten Sollzustand; kein Fremdeingriff erkannt. Alle drei LPs liegen unter der Stage-A-Quote von 50 SOIs:\n\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18:** Gewicht 1/3 · **6 SOIs** · 0 First-Sales · 0 Rebills · noch **44 SOIs**\n- **LP 2753 – Single69_Everflow_Datelifede fsk18:** Gewicht 1/3 · **7 SOIs** · 0 First-Sales · 0 Rebills · noch **43 SOIs**\n- **LP 2747 – Single69_Everflow_Striptie fsk18:** Gewicht 1/3 · **6 SOIs** · 0 First-Sales · 0 Rebills · noch **44 SOIs**\n\nDie Kohorten sind erst rund **6,1 Stunden** alt; bei **336 Stunden Reifezeit** gibt es noch keine reifen SOIs. Die mature First-Sale-Rate ist daher für alle LPs **noch nicht bestimmbar**.\n\n**Ergebnis:** 0 PUTs, 0 Änderungen. Campaign-GET und State-Abgleich erfolgreich; Gleichverteilung bleibt bestehen. Campaign-Lock wurde ordnungsgemäß freigegeben."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T15:35:12.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Keine Live-Aktion erforderlich — 0 Writes.**\n\nCampaign **146**, Affiliate **436**, Offer **57** stimmt exakt mit dem gespeicherten Zustand überein. Die Rotation bleibt gleichgewichtet bei **1/1/1**:\n\n- **LP 2762 — Single69_Everflow_MilfsFicken fsk18:** 5/50 SOIs, 0 First-Sales, 0 Rebills, noch **45 SOIs**\n- **LP 2753 — Single69_Everflow_Datelifede fsk18:** 4/50 SOIs, 0 First-Sales, 0 Rebills, noch **46 SOIs**\n- **LP 2747 — Single69_Everflow_Striptie fsk18:** 4/50 SOIs, 0 First-Sales, 0 Rebills, noch **46 SOIs**\n\nDie Slots laufen erst seit etwa **4,1 Stunden**. Daher gibt es noch keine 336 Stunden alten, reifen SOIs; die **reife First-Sale-Rate ist noch nicht bestimmbar**. Kein Slot hat die Stage-A-Quote von 50 SOIs erreicht, daher erfolgte richtliniengemäß **kein PUT und kein LP-Tausch**. Campaign-GET und State-Abgleich waren erfolgreich; der exklusive Lock wurde ordnungsgemäß freigegeben."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T13:34:13.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Everflow Sale-first LP-Test – Kampagne 146**  \n**Stand:** 21.07.2026, 15:34 CEST\n\n**Aktion:** Keine Änderung, **0 Writes**. Der Live-Zustand stimmt mit `state.json` überein; alle drei Offer-57-Slots laufen weiterhin gleichgewichtet mit **1/1/1**.\n\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18**  \n  3/50 SOIs · 0 First-Sales · 0 Rebills · noch **47 SOIs**\n- **LP 2753 – Single69_Everflow_Datelifede fsk18**  \n  2/50 SOIs · 0 First-Sales · 0 Rebills · noch **48 SOIs**\n- **LP 2747 – Single69_Everflow_Striptie fsk18**  \n  1/50 SOIs · 0 First-Sales · 0 Rebills · noch **49 SOIs**\n\nDie Slots laufen erst seit rund **2,1 Stunden**. Es gibt noch keine 336 Stunden alten SOIs; daher ist die **reife First-Sale-Rate noch nicht verfügbar**. Kein Slot hat die Rotationsquote von 50 SOIs erreicht, somit war kein LP-Tausch zulässig oder erforderlich.\n\n**Prüfung:** Campaign 146 wurde live per GET mit Redirects gelesen und erfolgreich gegen den gespeicherten Sollzustand abgeglichen. Kein PUT durchgeführt."
    },
    {
      "campaignId": 146,
      "evaluatedAt": "2026-07-21T11:32:48.000Z",
      "action": "review",
      "writes": 0,
      "verified": true,
      "summary": "**Keine Live-Aktion – Testbatch läuft erst seit ca. 0,1 Stunden.**\n\nCampaign **146**, Affiliate **436**, Offer **57**:\n\n- **LP 2762 – Single69_Everflow_MilfsFicken fsk18:** Gewicht 1 (~33,3 %), **0/50 SOIs**, 0 First-Sales, 0 Rebills, mature First-Sale-Rate: **n/a** (0 reife SOIs)\n- **LP 2753 – Single69_Everflow_Datelifede fsk18:** Gewicht 1 (~33,3 %), **0/50 SOIs**, 0 First-Sales, 0 Rebills, mature First-Sale-Rate: **n/a** (0 reife SOIs)\n- **LP 2747 – Single69_Everflow_Striptie fsk18:** Gewicht 1 (~33,3 %), **0/50 SOIs**, 0 First-Sales, 0 Rebills, mature First-Sale-Rate: **n/a** (0 reife SOIs)\n\n**Ergebnis:** Gleichverteilung **1/1/1** unverändert. Der Live-Campaign-GET entsprach exakt dem gespeicherten Zustand. **0 PUTs / 0 Änderungen**; daher keine Post-Write-Verifikation erforderlich. Nächste Rotation jeweils bei **50 SOIs**. Der Campaign-Lock wurde erfolgreich erworben und anschließend freigegeben."
    }
  ]
} as const;
export default journal;
